/*
* Frappe Gantt v14.62.4
* https://github.com/frappe/gantt?tab=MIT-1-ov-file#readme
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(p){return p.raw=p};$jscomp.createTemplateTagFirstArgWithRaw=function(p,k){p.raw=k;return p};$jscomp.arrayIteratorImpl=function(p){var k=0;return function(){return k<p.length?{done:!1,value:p[k++]}:{done:!0}}};$jscomp.arrayIterator=function(p){return{next:$jscomp.arrayIteratorImpl(p)}};
$jscomp.makeIterator=function(p){var k="undefined"!=typeof Symbol&&Symbol.iterator&&p[Symbol.iterator];if(k)return k.call(p);if("number"==typeof p.length)return $jscomp.arrayIterator(p);throw Error(String(p)+" is not an iterable or ArrayLike");};$jscomp.arrayFromIterator=function(p){for(var k,m=[];!(k=p.next()).done;)m.push(k.value);return m};$jscomp.arrayFromIterable=function(p){return p instanceof Array?p:$jscomp.arrayFromIterator($jscomp.makeIterator(p))};
var Gantt=function(){function p(a,b,c){a+="";b>>=0;c=String("undefined"!==typeof c?c:" ");if(a.length>b)return String(a);b-=a.length;b>c.length&&(c+=c.repeat(b/c.length));return c.slice(0,b)+String(a)}function k(a,b){return"string"===typeof a?(b||document).querySelector(a):a||null}function m(a,b){var c=document.createElementNS("http://www.w3.org/2000/svg",a),d;for(d in b)"append_to"===d?b.append_to.appendChild(c):"innerHTML"===d?c.innerHTML=b.innerHTML:c.setAttribute(d,b[d]);return c}function z(a,
b,c,d){var e=void 0,f=void 0;e=void 0===e?"0.4s":e;f=void 0===f?"0.1s":f;var l=a.querySelector("animate");l?k.attr(l,{attributeName:b,from:c,to:d,dur:e,begin:"click + "+f}):(b=m("animate",{attributeName:b,from:c,to:d,dur:e,begin:f,calcMode:"spline",values:c+";"+d,keyTimes:"0; 1",keySplines:"0 0 .58 1"}),a.appendChild(b));a===a&&(b=document.createEvent("HTMLEvents"),b.initEvent("click",!0,!0),b.eventName="click",a.dispatchEvent(b))}var g={parse:function(a,b,c){if(a instanceof Date)return a;isNaN(Date.parse(a))&&
(a.match(/T/g)?(a=a.replace(/\//g,"-"),a.match(/(\+[0-9]{2}:?[0-9]{2}|Z$)/g)||(a+="Z")):a=a.replace(/-/g,"/"));return new Date(a)},to_string:function(a,b){b=void 0===b?!1:b;if(!(a instanceof Date))throw new TypeError("Invalid argument type");var c=this.get_date_values(a).map(function(e,f){1===f&&(e+=1);return 6===f?p(e+"",3,"0"):p(e+"",2,"0")}),d=c[3]+":"+c[4]+":"+c[5]+"."+c[6];return c[0]+"-"+c[1]+"-"+c[2]+(b?" "+d:"")},format:function(a,b,c){b=void 0===b?"YYYY-MM-DD HH:mm:ss.SSS":b;c=void 0===c?
"en":c;var d=new Intl.DateTimeFormat(c,{month:"long"});c=new Intl.DateTimeFormat(c,{month:"short"});d=d.format(a);c=c.format(a);a=this.get_date_values(a).map(function(q){return p(q,2,0)});var e={YYYY:a[0],MM:p(+a[1]+1,2,0),DD:a[2],HH:a[3],mm:a[4],ss:a[5],SSS:a[6],D:a[2],MMMM:d,MMM:c},f=b,l=[];Object.keys(e).sort(function(q,w){return w.length-q.length}).forEach(function(q){f.includes(q)&&(f=f.replace(q,"$"+l.length),l.push(e[q]))});l.forEach(function(q,w){f=f.replace("$"+w,q)});return f},diff:function(a,
b,c){c=void 0===c?"day":c;a-=b;b=a/1E3;var d=b/60;var e=d/60;var f=e/24;var l=f/30;var q=l/12;c.endsWith("s")||(c+="s");return Math.floor({milliseconds:a,seconds:b,minutes:d,hours:e,days:f,months:l,years:q}[c])},today:function(){var a=this.get_date_values(new Date).slice(0,3);return new Date(a[0],a[1],a[2])},now:function(){return new Date},add:function(a,b,c){b=parseInt(b,10);a=[a.getFullYear()+("year"===c?b:0),a.getMonth()+("month"===c?b:0),a.getDate()+("day"===c?b:0),a.getHours()+("hour"===c?b:
0),a.getMinutes()+("minute"===c?b:0),a.getSeconds()+("second"===c?b:0),a.getMilliseconds()+("millisecond"===c?b:0)];return new Date(a[0],a[1],a[2],a[3],a[4],a[5],a[6])},start_of:function(a,b){function c(f){return e[f]<=e[b]}var d={},e=(d.year=6,d.month=5,d.day=4,d.hour=3,d.minute=2,d.second=1,d.millisecond=0,d);d=[a.getFullYear(),c("year")?0:a.getMonth(),c("month")?1:a.getDate(),c("day")?0:a.getHours(),c("hour")?0:a.getMinutes(),c("minute")?0:a.getSeconds(),c("second")?0:a.getMilliseconds()];return new Date(d[0],
d[1],d[2],d[3],d[4],d[5],d[6])},clone:function(a){a=this.get_date_values(a);return new Date(a[0],a[1],a[2],a[3],a[4],a[5],a[6])},get_date_values:function(a){return[a.getFullYear(),a.getMonth(),a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds(),a.getMilliseconds()]},get_days_in_month:function(a){var b=[31,28,31,30,31,30,31,31,30,31,30,31],c=a.getMonth();if(1!==c)return b[c];a=a.getFullYear();return 0==a%4&&0!=a%100||0==a%400?29:28}};k.on=function(a,b,c,d){d?k.delegate(a,b,c,d):k.bind(a,b,c)};k.off=
function(a,b,c){a.removeEventListener(b,c)};k.bind=function(a,b,c){b.split(/\s+/).forEach(function(d){a.addEventListener(d,c)})};k.delegate=function(a,b,c,d){a.addEventListener(b,function(e){var f=e.target.closest(c);f&&(e.delegatedTarget=f,d.call(this,e,f))})};k.closest=function(a,b){return b?b.matches(a)?b:k.closest(a,b.parentNode):null};k.attr=function(a,b,c){if(!c&&"string"===typeof b)return a.getAttribute(b);if("object"===typeof b)for(var d in b)k.attr(a,d,b[d]);else a.setAttribute(b,c)};var n=
function(a,b){this.set_defaults(a,b);this.prepare();this.draw();this.bind()};n.prototype.set_defaults=function(a,b){this.action_completed=!1;this.gantt=a;this.task=b};n.prototype.prepare=function(){this.prepare_values();this.prepare_helpers()};n.prototype.prepare_values=function(){this.invalid=this.task.invalid;this.height=this.gantt.options.bar_height;this.x=this.compute_x();this.y=this.compute_y();this.corner_radius=this.gantt.options.bar_corner_radius;this.duration=g.diff(this.task._end,this.task._start,
"hour")/this.gantt.options.step;this.width=this.gantt.options.column_width*this.duration;this.progress_width=null==this.task.progress?this.gantt.options.column_width*this.duration:this.task.progress/100*this.duration*this.gantt.options.column_width||0;this.group=m("g",{"class":"bar-wrapper "+(this.task.custom_class||""),"data-id":this.task.id});this.bar_group=m("g",{"class":"bar-group",append_to:this.group});this.handle_group=m("g",{"class":"handle-group",append_to:this.group})};n.prototype.prepare_helpers=
function(){SVGElement.prototype.getX=function(){return+this.getAttribute("x")};SVGElement.prototype.getY=function(){return+this.getAttribute("y")};SVGElement.prototype.getWidth=function(){return+this.getAttribute("width")};SVGElement.prototype.getHeight=function(){return+this.getAttribute("height")};SVGElement.prototype.getEndX=function(){return this.getX()+this.getWidth()}};n.prototype.draw=function(){this.draw_bar();this.draw_progress_bar();this.draw_label();this.draw_resize_handles()};n.prototype.draw_bar=
function(){this.$bar=m("rect",{x:this.x,y:this.y,width:this.width,height:this.height,rx:this.corner_radius,ry:this.corner_radius,"class":"bar",append_to:this.bar_group});z(this.$bar,"width",0,this.width);this.invalid&&this.$bar.classList.add("bar-invalid")};n.prototype.draw_progress_bar=function(){this.invalid||(this.$bar_progress=this.task.colors.back?m("rect",{x:this.x,y:this.y,width:this.progress_width,height:this.height,rx:this.corner_radius,ry:this.corner_radius,"class":"bar-progress",append_to:this.bar_group,
style:"fill: "+this.task.colors.back}):m("rect",{x:this.x,y:this.y,width:this.progress_width,height:this.height,rx:this.corner_radius,ry:this.corner_radius,"class":"bar-progress default",append_to:this.bar_group}),z(this.$bar_progress,"width",0,this.progress_width))};n.prototype.draw_label=function(){var a=this;this.task.colors.fore?m("text",{x:this.x+this.width/2,y:this.y+this.height/2,innerHTML:this.task.name,"class":"bar-label",append_to:this.bar_group,style:"fill: "+this.task.colors.fore}):m("text",
{x:this.x+this.width/2,y:this.y+this.height/2,innerHTML:this.task.name,"class":"bar-label",append_to:this.bar_group});requestAnimationFrame(function(){return a.update_label_position()})};n.prototype.draw_resize_handles=function(){if(!this.invalid){var a=this.$bar;this.task.resizable.right&&m("rect",{x:a.getX()+a.getWidth()-9,y:a.getY()+1,width:8,height:this.height-2,rx:this.corner_radius,ry:this.corner_radius,"class":"handle right",append_to:this.handle_group});this.task.resizable.left&&m("rect",
{x:a.getX()+1,y:a.getY()+1,width:8,height:this.height-2,rx:this.corner_radius,ry:this.corner_radius,"class":"handle left",append_to:this.handle_group});this.task.progress&&100>this.task.progress&&(this.$handle_progress=m("polygon",{points:this.get_progress_polygon_points().join(","),"class":"handle progress",append_to:this.handle_group}))}};n.prototype.get_progress_polygon_points=function(){var a=this.$bar_progress;return[a.getEndX()-5,a.getY()+a.getHeight(),a.getEndX()+5,a.getY()+a.getHeight(),a.getEndX(),
a.getY()+a.getHeight()-8.66]};n.prototype.bind=function(){this.invalid||this.setup_click_event()};n.prototype.setup_click_event=function(){var a=this;k.on(this.group,"focus "+this.gantt.options.popup_trigger,function(b){a.action_completed||(a.show_popup(),a.gantt.unselect_all(),a.group.classList.add("active"))});k.on(this.group,"dblclick",function(b){a.action_completed||a.gantt.trigger_event("click",[a.task])})};n.prototype.show_popup=function(){if(!this.gantt.bar_being_dragged){var a=g.format(this.task._start,
"MMM D",this.gantt.options.language),b=g.format(g.add(this.task._end,-1,"second"),"MMM D",this.gantt.options.language);this.gantt.show_popup({border:this.task.colors.back,progress:this.task.progress,target_element:this.$bar,title:this.task.name,subtitle:a+" - "+b,task:this.task})}};n.prototype.update_popup_progress=function(){var a=this.compute_progress();this.gantt.update_popup({progress:"Prog. "+a.toString()+"%"})};n.prototype.update_bar_position=function(a){var b=this,c=void 0===a.x?null:a.x;a=
void 0===a.width?null:a.width;var d=this.$bar;if(c){if(!this.task.dependencies.map(function(e){return b.gantt.get_bar(e).$bar.getX()}).reduce(function(e,f){return c>=f},c)){a=null;return}this.update_attr(d,"x",c)}a&&a>=this.gantt.options.column_width&&this.update_attr(d,"width",a);this.update_label_position();this.update_handle_position();this.update_progressbar_position();this.update_arrow_position()};n.prototype.date_changed=function(){var a=!1,b=this.compute_start_end_date(),c=b.new_start_date;
b=b.new_end_date;Number(this.task._start)!==Number(c)&&(a=!0,this.task._start=c);Number(this.task._end)!==Number(b)&&(a=!0,this.task._end=b);return a};n.prototype.progress_changed=function(){var a=this.compute_progress();this.task.progress=a;this.gantt.trigger_event("progress_change",[this.task,a])};n.prototype.set_action_completed=function(){var a=this;this.action_completed=!0;setTimeout(function(){return a.action_completed=!1},1E3)};n.prototype.compute_start_end_date=function(){var a=this.$bar,
b=a.getX()/this.gantt.options.column_width;b=g.add(this.gantt.gantt_start,b*this.gantt.options.step,"hour");a=a.getWidth()/this.gantt.options.column_width;a=g.add(b,a*this.gantt.options.step,"hour");return{new_start_date:b,new_end_date:a}};n.prototype.compute_progress=function(){var a=this.$bar_progress.getWidth()/this.$bar.getWidth()*100;return parseInt(a,10)};n.prototype.compute_x=function(){var a=this.gantt.options,b=a.step;a=a.column_width;var c=this.task._start,d=this.gantt.gantt_start;b=g.diff(c,
d,"hour")/b*a;this.gantt.view_is("Month")&&(b=g.diff(c,d,"day")*a/30);return b};n.prototype.compute_y=function(){return this.gantt.options.header_height+this.gantt.options.padding+this.task._index*(this.height+this.gantt.options.padding)};n.prototype.get_snap_position=function(a){if(this.gantt.view_is("Week")){var b=a%(this.gantt.options.column_width/7);a=a-b+(b<this.gantt.options.column_width/14?0:this.gantt.options.column_width/7)}else this.gantt.view_is("Month")?(b=a%(this.gantt.options.column_width/
30),a=a-b+(b<this.gantt.options.column_width/60?0:this.gantt.options.column_width/30)):(b=a%this.gantt.options.column_width,a=a-b+(b<this.gantt.options.column_width/2?0:this.gantt.options.column_width));return a};n.prototype.update_attr=function(a,b,c){c=+c;isNaN(c)||a.setAttribute(b,c);return a};n.prototype.update_progressbar_position=function(){this.invalid||(this.$bar_progress.setAttribute("x",this.$bar.getX()),null==this.task.progress?this.$bar_progress.setAttribute("width",this.$bar.getWidth()):
this.$bar_progress.setAttribute("width",this.$bar.getWidth()*(this.task.progress/100)))};n.prototype.update_label_position=function(){var a=this.$bar,b=this.group.querySelector(".bar-label");b.getBBox().width>a.getWidth()?(b.classList.add("big"),b.setAttribute("x",a.getX()+a.getWidth()+5)):(b.classList.remove("big"),b.setAttribute("x",a.getX()+a.getWidth()/2))};n.prototype.update_handle_position=function(){if(!this.invalid){var a=this.$bar;this.task.resizable.left&&this.handle_group.querySelector(".handle.left").setAttribute("x",
a.getX()+1);this.task.resizable.right&&this.handle_group.querySelector(".handle.right").setAttribute("x",a.getEndX()-9);(a=this.group.querySelector(".handle.progress"))&&a.setAttribute("points",this.get_progress_polygon_points())}};n.prototype.update_arrow_position=function(){this.arrows=this.arrows||[];for(var a=$jscomp.makeIterator(this.arrows),b=a.next();!b.done;b=a.next())b.value.update()};var y=function(a,b,c){this.gantt=a;this.from_task=b;this.to_task=c;this.calculate_path();this.draw()};y.prototype.calculate_path=
function(){for(var a=this.from_task.$bar.getX()+this.from_task.$bar.getWidth()/2;this.to_task.$bar.getX()<a+this.gantt.options.padding&&a>this.from_task.$bar.getX()+this.gantt.options.padding;)a-=10;var b=this.gantt.options.header_height+this.gantt.options.bar_height+(this.gantt.options.padding+this.gantt.options.bar_height)*this.from_task.task._index+this.gantt.options.padding,c=this.to_task.$bar.getX()-this.gantt.options.padding/2,d=this.gantt.options.header_height+this.gantt.options.bar_height/
2+(this.gantt.options.padding+this.gantt.options.bar_height)*this.to_task.task._index+this.gantt.options.padding,e=this.from_task.task._index>this.to_task.task._index,f=this.gantt.options.arrow_curve,l=e?1:0,q=e?-f:f;this.path="\n            M "+a+" "+b+"\n            V "+(e?d+this.gantt.options.arrow_curve:d-this.gantt.options.arrow_curve)+"\n            a "+f+" "+f+" 0 0 "+l+" "+f+" "+q+"\n            L "+c+" "+d+"\n            m -5 -5\n            l 5 5\n            l -5 5";if(this.to_task.$bar.getX()<
this.from_task.$bar.getX()+this.gantt.options.padding){e=this.gantt.options.padding/2-f;var w=this.to_task.$bar.getY()+this.to_task.$bar.getHeight()/2-q,v=this.to_task.$bar.getX()-this.gantt.options.padding;this.path="\n                M "+a+" "+b+"\n                v "+e+"\n                a "+f+" "+f+" 0 0 1 -"+f+" "+f+"\n                H "+v+"\n                a "+f+" "+f+" 0 0 "+l+" -"+f+" "+q+"\n                V "+w+"\n                a "+f+" "+f+" 0 0 "+l+" "+f+" "+q+"\n                L "+
c+" "+d+"\n                m -5 -5\n                l 5 5\n                l -5 5"}};y.prototype.draw=function(){this.element=m("path",{d:this.path,"data-from":this.from_task.task.id,"data-to":this.to_task.task.id})};y.prototype.update=function(){this.calculate_path();this.element.setAttribute("d",this.path)};var x=function(a,b){this.parent=a;this.custom_html=b;this.make()};x.prototype.make=function(){this.parent.innerHTML='\n            <div class="title"></div>\n            <div class="subtitle"></div>\n            <div class="progress"></div>\n            <div class="pointer"></div>\n        ';
this.hide();this.title=this.parent.querySelector(".title");this.subtitle=this.parent.querySelector(".subtitle");this.progress=this.parent.querySelector(".progress");this.pointer=this.parent.querySelector(".pointer")};x.prototype.show=function(a){if(!a.target_element)throw Error("target_element is required to show popup");a.position||(a.position="left");var b=a.target_element;this.title.style.borderBottom=a.border?"3px solid "+a.border:"";if(this.custom_html){var c=this.custom_html(a.task);this.parent.innerHTML=
c+'<div class="pointer"></div>';this.pointer=this.parent.querySelector(".pointer")}else this.title.innerHTML=a.title,this.subtitle.innerHTML=a.subtitle,this.parent.style.width=this.parent.clientWidth+"px",null!=a.progress?(this.progress.innerHTML="Prog. "+a.progress+"%",this.progress.style.display="block"):this.progress.style.display="none";var d;b instanceof HTMLElement?d=b.getBoundingClientRect():b instanceof SVGElement&&(d=a.target_element.getBBox());"left"===a.position&&(this.parent.style.left=
d.x+(d.width+10)+"px",this.parent.style.top=d.y+"px",this.pointer.style.transform="rotateZ(90deg)",this.pointer.style.left="-7px",this.pointer.style.top="2px");this.parent.style.opacity=1};x.prototype.update=function(a){var b=this;Object.keys(a).forEach(function(c){b[c].innerHTML=a[c]})};x.prototype.hide=function(){this.parent.style.opacity=0;this.parent.style.left=0};var t={QUARTER_DAY:"Quarter Day",HALF_DAY:"Half Day",DAY:"Day",WEEK:"Week",MONTH:"Month",YEAR:"Year"},h=function(a,b,c){this.setup_wrapper(a);
this.setup_options(c);this.setup_tasks(b);this.change_view_mode();this.bind_events()};h.prototype.setup_wrapper=function(a){"string"===typeof a&&(a=document.querySelector(a));if(a instanceof HTMLElement){var b=a;a=a.querySelector("svg")}else if(!(a instanceof SVGElement))throw new TypeError("Frapp\u00e9 Gantt only supports usage of a string CSS selector, HTML DOM element or SVG DOM element for the 'element' parameter");a?(this.$svg=a,this.$svg.classList.add("gantt")):this.$svg=m("svg",{append_to:b,
"class":"gantt"});this.$container=document.createElement("div");this.$container.classList.add("gantt-container");this.$svg.parentElement.appendChild(this.$container);this.$container.appendChild(this.$svg);this.popup_wrapper=document.createElement("div");this.popup_wrapper.classList.add("popup-wrapper");this.$container.appendChild(this.popup_wrapper)};h.prototype.setup_options=function(a){var b={header_height:50,column_width:30,step:24,view_modes:[].concat($jscomp.arrayFromIterable(Object.values(t))),
bar_height:20,bar_corner_radius:3,arrow_curve:5,padding:18,view_mode:"Day",date_format:"YYYY-MM-DD",popup_trigger:"click",custom_popup_html:null,language:"en"};this.options=Object.assign({},b,a)};h.prototype.setup_tasks=function(a){this.tasks=a.map(function(b,c){b._start=g.parse(b.start);b._end=g.parse(b.end);10<g.diff(b._end,b._start,"year")&&(b.end=null);b._index=c;if(!b.start&&!b.end){var d=g.today();b._start=d;b._end=g.add(d,2,"day")}!b.start&&b.end&&(b._start=g.add(b._end,-2,"day"));b.start&&
!b.end&&(b._end=g.add(b._start,2,"day"));g.get_date_values(b._end).slice(3).every(function(e){return 0===e})&&(b._end=g.add(b._end,24,"hour"));b.start&&b.end||(b.invalid=!0);"string"!==typeof b.dependencies&&b.dependencies||(d=[],b.dependencies&&(d=b.dependencies.split(",").map(function(e){return e.trim()}).filter(function(e){return e})),b.dependencies=d);b.id||(b.id=b.name+"_"+Math.random().toString(36).slice(2,12));"group"in b||(b.group="");"colors"in b||(b.colors={back:"",fore:""});"resizable"in
b||(b.colors={left:!0,right:!0});return b});this.setup_dependencies()};h.prototype.setup_dependencies=function(){this.dependency_map={};for(var a=$jscomp.makeIterator(this.tasks),b=a.next();!b.done;b=a.next()){b=b.value;for(var c=$jscomp.makeIterator(b.dependencies),d=c.next();!d.done;d=c.next())d=d.value,this.dependency_map[d]=this.dependency_map[d]||[],this.dependency_map[d].push(b.id)}};h.prototype.refresh=function(a){this.setup_tasks(a);this.change_view_mode()};h.prototype.change_view_mode=function(a){a=
void 0===a?this.options.view_mode:a;this.update_view_scale(a);this.setup_dates();this.render();this.trigger_event("view_change",[a])};h.prototype.update_view_scale=function(a){this.options.view_mode=a;a===t.DAY?(this.options.step=24,this.options.column_width=38):a===t.HALF_DAY?(this.options.step=12,this.options.column_width=38):a===t.QUARTER_DAY?(this.options.step=6,this.options.column_width=38):a===t.WEEK?(this.options.step=168,this.options.column_width=140):a===t.MONTH?(this.options.step=720,this.options.column_width=
120):a===t.YEAR&&(this.options.step=8760,this.options.column_width=120)};h.prototype.setup_dates=function(){this.setup_gantt_dates();this.setup_date_values()};h.prototype.setup_gantt_dates=function(){if(0!=this.tasks.length){this.gantt_start=this.gantt_end=null;for(var a=$jscomp.makeIterator(this.tasks),b=a.next();!b.done;b=a.next()){b=b.value;if(!this.gantt_start||b._start<this.gantt_start)this.gantt_start=b._start;if(!this.gantt_end||b._end>this.gantt_end)this.gantt_end=b._end}}else this.gantt_start=
new Date(this.options.start),this.gantt_end=new Date(this.options.end);this.gantt_start=g.start_of(this.gantt_start,"day");this.gantt_end=g.start_of(this.gantt_end,"day");this.view_is(t.QUARTER_DAY)?(this.gantt_start=g.add(this.gantt_start,-7,"day"),this.gantt_end=g.add(this.gantt_end,7,"day")):this.view_is(t.HALF_DAY)?(this.gantt_start=g.add(this.gantt_start,-14,"day"),this.gantt_end=g.add(this.gantt_end,14,"day")):this.view_is(t.WEEK)?(this.gantt_start=g.add(this.gantt_start,-2,"month"),this.gantt_end=
g.add(this.gantt_end,2,"month")):this.view_is(t.MONTH)?(this.gantt_start=g.start_of(this.gantt_start,"year"),this.gantt_end=g.add(this.gantt_end,1,"year")):this.view_is(t.YEAR)?(this.gantt_start=g.add(this.gantt_start,-2,"year"),this.gantt_end=g.add(this.gantt_end,2,"year")):(this.gantt_start=g.add(this.gantt_start,-1,"month"),this.gantt_end=g.add(this.gantt_end,1,"month"))};h.prototype.setup_date_values=function(){this.dates=[];for(var a=null;null===a||a<this.gantt_end;)a=a?this.view_is(t.YEAR)?
g.add(a,1,"year"):this.view_is(t.MONTH)?g.add(a,1,"month"):g.add(a,this.options.step,"hour"):g.clone(this.gantt_start),this.dates.push(a)};h.prototype.bind_events=function(){this.bind_grid_click();this.bind_bar_events()};h.prototype.render=function(){this.clear();this.setup_layers();this.make_grid();this.make_dates();this.make_bars();this.make_arrows();this.map_arrows_on_bars();this.set_width();this.set_scroll_position()};h.prototype.setup_layers=function(){this.layers={};for(var a=$jscomp.makeIterator("grid date arrow progress bar details".split(" ")),
b=a.next();!b.done;b=a.next())b=b.value,this.layers[b]=m("g",{"class":b,append_to:this.$svg})};h.prototype.make_grid=function(){this.make_grid_background();this.make_grid_rows();this.make_grid_header();this.make_grid_ticks();this.make_grid_highlights()};h.prototype.make_grid_background=function(){var a=this.options.header_height+this.options.padding+(this.options.bar_height+this.options.padding)*this.tasks.length;m("rect",{x:0,y:0,width:this.dates.length*this.options.column_width,height:a,"class":"grid-background",
append_to:this.layers.grid});k.attr(this.$svg,{height:a+this.options.padding+100,width:"100%"})};h.prototype.make_grid_rows=function(){var a=m("g",{append_to:this.layers.grid}),b=m("g",{append_to:this.layers.grid}),c=this.dates.length*this.options.column_width,d=this.options.bar_height+this.options.padding,e=this.options.header_height+this.options.padding/2;if(0!=this.tasks.length)for(var f=$jscomp.makeIterator(this.tasks),l=f.next();!l.done;l=f.next())m("rect",{x:0,y:e,width:c,height:d,"class":"grid-row",
append_to:a}),m("line",{x1:0,y1:e+d,x2:c,y2:e+d,"class":"row-line",append_to:b}),e+=this.options.bar_height+this.options.padding;else m("rect",{x:0,y:e,width:c,height:d,"class":"grid-row",append_to:a})};h.prototype.make_grid_header=function(){m("rect",{x:0,y:0,width:this.dates.length*this.options.column_width,height:this.options.header_height+10,"class":"grid-header",append_to:this.layers.grid})};h.prototype.make_grid_ticks=function(){for(var a=0,b=this.options.header_height+this.options.padding/
2,c=(this.options.bar_height+this.options.padding)*this.tasks.length,d=$jscomp.makeIterator(this.dates),e=d.next();!e.done;e=d.next()){e=e.value;var f="tick";this.view_is(t.DAY)&&1===e.getDate()&&(f+=" thick");this.view_is(t.WEEK)&&1<=e.getDate()&&8>e.getDate()&&(f+=" thick");this.view_is(t.MONTH)&&0===e.getMonth()%3&&(f+=" thick");m("path",{d:"M "+a+" "+b+" v "+c,"class":f,append_to:this.layers.grid});a=this.view_is(t.MONTH)?a+g.get_days_in_month(e)*this.options.column_width/30:a+this.options.column_width}};
h.prototype.make_grid_highlights=function(){if(this.view_is(t.DAY)){var a=g.diff(g.today(),this.gantt_start,"hour")/this.options.step*this.options.column_width;m("rect",{x:a,y:0,width:this.options.column_width,height:(this.options.bar_height+this.options.padding)*this.tasks.length+this.options.header_height+this.options.padding/2,"class":"today-highlight",append_to:this.layers.grid})}};h.prototype.make_dates=function(){for(var a=$jscomp.makeIterator(this.get_dates_to_draw()),b=a.next();!b.done;b=
a.next())b=b.value,m("text",{x:b.lower_x,y:b.lower_y,innerHTML:b.lower_text,"class":"lower-text",append_to:this.layers.date}),b.upper_text&&(b=m("text",{x:b.upper_x,y:b.upper_y,innerHTML:b.upper_text,"class":"upper-text",append_to:this.layers.date}),b.getBBox().x2>this.layers.grid.getBBox().width&&b.remove())};h.prototype.get_dates_to_draw=function(){var a=this,b=null;return this.dates.map(function(c,d){var e=a.get_date_info(c,b,d);b=c;return e})};h.prototype.get_date_info=function(a,b,c){b||(b=g.add(a,
1,"year"));a={"Quarter Day_lower":0==c?"":g.format(a,"HH",this.options.language),"Half Day_lower":0==c?"":g.format(a,"HH",this.options.language),Day_lower:a.getDate()!==b.getDate()?g.format(a,"D",this.options.language):"",Week_lower:a.getMonth()!==b.getMonth()?0==c?"":g.format(a,"D MMM",this.options.language):0==c?"":g.format(a,"D",this.options.language),Month_lower:g.format(a,"MMMM",this.options.language),Year_lower:g.format(a,"YYYY",this.options.language),"Quarter Day_upper":a.getDate()!==b.getDate()?
g.format(a,"D MMM",this.options.language):"","Half Day_upper":a.getDate()!==b.getDate()?a.getMonth()!==b.getMonth()?g.format(a,"D MMM",this.options.language):g.format(a,"D",this.options.language):"",Day_upper:a.getMonth()!==b.getMonth()?g.format(a,"MMMM",this.options.language):"",Week_upper:a.getMonth()!==b.getMonth()?g.format(a,"MMMM",this.options.language):"",Month_upper:a.getFullYear()!==b.getFullYear()?g.format(a,"YYYY",this.options.language):"",Year_upper:a.getFullYear()!==b.getFullYear()?g.format(a,
"YYYY",this.options.language):""};c*=this.options.column_width;b={"Quarter Day_lower":0,"Quarter Day_upper":4*this.options.column_width/2,"Half Day_lower":0,"Half Day_upper":2*this.options.column_width/2,Day_lower:this.options.column_width/2,Day_upper:30*this.options.column_width/2,Week_lower:0,Week_upper:4*this.options.column_width/2,Month_lower:this.options.column_width/2,Month_upper:12*this.options.column_width/2,Year_lower:this.options.column_width/2,Year_upper:30*this.options.column_width/2};
return{upper_text:a[this.options.view_mode+"_upper"],lower_text:a[this.options.view_mode+"_lower"],upper_x:c+b[this.options.view_mode+"_upper"],upper_y:this.options.header_height-25,lower_x:c+b[this.options.view_mode+"_lower"],lower_y:this.options.header_height}};h.prototype.make_bars=function(){var a=this;this.bars=this.tasks.map(function(b){b=new n(a,b);a.layers.bar.appendChild(b.group);return b})};h.prototype.make_arrows=function(){var a=this;this.arrows=[];for(var b=$jscomp.makeIterator(this.tasks),
c=b.next(),d={};!c.done;d={task$jscomp$6:d.task$jscomp$6},c=b.next())d.task$jscomp$6=c.value,c=[],c=d.task$jscomp$6.dependencies.map(function(e){return function(f){if(f=a.get_task(f))return f=new y(a,a.bars[f._index],a.bars[e.task$jscomp$6._index]),a.layers.arrow.appendChild(f.element),f}}(d)).filter(Boolean),this.arrows=this.arrows.concat(c)};h.prototype.map_arrows_on_bars=function(){for(var a=$jscomp.makeIterator(this.bars),b=a.next(),c={};!b.done;c={bar$jscomp$6:c.bar$jscomp$6},b=a.next())c.bar$jscomp$6=
b.value,c.bar$jscomp$6.arrows=this.arrows.filter(function(d){return function(e){return e.from_task.task.id===d.bar$jscomp$6.task.id||e.to_task.task.id===d.bar$jscomp$6.task.id}}(c))};h.prototype.set_width=function(){var a=this.$svg.getBoundingClientRect().width,b=this.$svg.querySelector(".grid .grid-row").getAttribute("width");a<b&&this.$svg.setAttribute("width",b)};h.prototype.set_scroll_position=function(){var a=this.$svg.parentElement;if(a){var b=g.diff(this.get_oldest_starting_date(),this.gantt_start,
"hour")/this.options.step*this.options.column_width-this.options.column_width;a.scrollLeft=b}};h.prototype.bind_grid_click=function(){var a=this;k.on(this.$svg,this.options.popup_trigger,".grid-row, .grid-header",function(){a.unselect_all();a.hide_popup()})};h.prototype.bind_bar_events=function(){var a=this,b=!1,c=0,d=!1,e=!1,f=null,l=null,q=[];this.bar_being_dragged=null;k.on(this.$svg,"mousedown",".bar-wrapper, .handle",function(w,v){var u=k.closest(".bar-wrapper",v);v.classList.contains("left")?
d=!0:v.classList.contains("right")?e=!0:v.classList.contains("bar-wrapper")&&(b=!0);u.classList.add("active");c=w.offsetX;f=u.getAttribute("data-id");l=a.tasks.filter(function(r){return r.id==f}).first();b&&!l.resizable.left&&(b=!1);q=[f].concat($jscomp.arrayFromIterable(a.get_all_dependent_tasks(f))).map(function(r){return a.get_bar(r)});v.classList.contains("progress")?(a.bar_being_dragged=null,a.get_bar(f).show_popup()):a.bar_being_dragged=f;q.forEach(function(r){r=r.$bar;r.ox=r.getX();r.oy=r.getY();
r.owidth=r.getWidth();r.finaldx=0})});k.on(this.$svg,"mousemove",function(w){if(b||d||e){var v=w.offsetX-c;q.forEach(function(u){var r=u.$bar;r.finaldx=a.get_snap_position(v);a.hide_popup();d?f===u.task.id?u.update_bar_position({x:r.ox+r.finaldx,width:r.owidth-r.finaldx}):u.update_bar_position({x:r.ox+r.finaldx}):e?f===u.task.id&&u.update_bar_position({width:r.owidth+r.finaldx}):b&&u.update_bar_position({x:r.ox+r.finaldx})})}});document.addEventListener("mouseup",function(w){(b||d||e)&&q.forEach(function(v){return v.group.classList.remove("active")});
e=d=b=!1});k.on(this.$svg,"mouseup",function(w){var v=!1;a.bar_being_dragged=null;q.forEach(function(u){u.$bar.finaldx&&(u.date_changed()&&(v=!0),u.set_action_completed())});v&&a.trigger_event("date_change",[a.tasks.filter(function(u){return u.group==l.group})])});this.bind_bar_progress()};h.prototype.bind_bar_progress=function(){var a=this,b=0,c=null,d=null,e=null,f=null;k.on(this.$svg,"mousedown",".handle.progress",function(l,q){c=!0;b=l.offsetX;var w=k.closest(".bar-wrapper",q).getAttribute("data-id");
d=a.get_bar(w);e=d.$bar_progress;f=d.$bar;e.finaldx=0;e.owidth=e.getWidth();e.min_dx=-e.getWidth();e.max_dx=f.getWidth()-e.getWidth()});k.on(this.$svg,"mousemove",function(l){if(c){l=l.offsetX-b;l>e.max_dx&&(l=e.max_dx);l<e.min_dx&&(l=e.min_dx);var q=d.$handle_progress;k.attr(e,"width",e.owidth+l);k.attr(q,"points",d.get_progress_polygon_points());e.finaldx=l;d.update_popup_progress()}});k.on(this.$svg,"mouseup",function(){c=!1;e&&e.finaldx&&(d.progress_changed(),d.set_action_completed())})};h.prototype.get_all_dependent_tasks=
function(a){for(var b=this,c=[],d=[a];d.length;)a=d.reduce(function(e,f){return e=e.concat(b.dependency_map[f])},[]),c=c.concat(a),d=a.filter(function(e){return!d.includes(e)});return c.filter(Boolean)};h.prototype.get_snap_position=function(a){if(this.view_is(t.WEEK)){var b=a%(this.options.column_width/7);a=a-b+(b<this.options.column_width/14?0:this.options.column_width/7)}else this.view_is(t.MONTH)?(b=a%(this.options.column_width/30),a=a-b+(b<this.options.column_width/60?0:this.options.column_width/
30)):(b=a%this.options.column_width,a=a-b+(b<this.options.column_width/2?0:this.options.column_width));return a};h.prototype.unselect_all=function(){[].concat($jscomp.arrayFromIterable(this.$svg.querySelectorAll(".bar-wrapper"))).forEach(function(a){a.classList.remove("active")})};h.prototype.view_is=function(a){var b=this;return"string"===typeof a?this.options.view_mode===a:Array.isArray(a)?a.some(function(c){return b.options.view_mode===c}):!1};h.prototype.get_task=function(a){return this.tasks.find(function(b){return b.id===
a})};h.prototype.get_bar=function(a){return this.bars.find(function(b){return b.task.id===a})};h.prototype.show_popup=function(a){this.popup||(this.popup=new x(this.popup_wrapper,this.options.custom_popup_html));this.popup.show(a)};h.prototype.update_popup=function(a){this.popup.update(a)};h.prototype.hide_popup=function(){this.popup&&this.popup.hide()};h.prototype.trigger_event=function(a,b){this.options["on_"+a]&&this.options["on_"+a].apply(null,b)};h.prototype.get_oldest_starting_date=function(){return 0!=
this.tasks.length?this.tasks.map(function(a){return a._start}).reduce(function(a,b){return b<=a?b:a}):this.gantt_start};h.prototype.clear=function(){this.$svg.innerHTML=""};h.VIEW_MODE=t;return h}();