/*
* FileName "plugins.action.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(K=>{var b={handlers:{}},M=(g,n,F,L)=>new Promise((J,v)=>{var C=JSON.stringify(kb.record.simplify({fields:b.fieldInfos.origin},n)),D=(p,d)=>{var e=()=>{p++;p<g.length?D(p,d):d()};(a=>{var f=kb.filter.scan(b.app,n,a.condition.value);f?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(x=>{if(x){var E={clear:z=>{try{a.clear.value.map(c=>c.value).each((c,y)=>{c.table.value in b.fieldInfos.tables&&(n[c.table.value].value=n[c.table.value].value.filter(u=>!f[c.table.value].value.includes(u)),
f[c.table.value].value=[])}),z()}catch(c){kb.alert(kb.error.parse(c)),v()}},fill:z=>{try{a.fill.value.map(c=>c.value).each((c,y)=>{c.table.value in b.fieldInfos.tables&&(u=>{u=kb.isNumeric(u)?parseInt(u)-f[c.table.value].value.length:0;0<u&&Array(u).fill().map(()=>kb.record.create(b.fieldInfos.origin[c.table.value],!1)).each((A,q)=>{n[c.table.value]==f[c.table.value]?n[c.table.value].value.push({value:A}):(n[c.table.value].value.push({value:A}),f[c.table.value].value.push({value:A}))})})(kb.formula.calculate({field:{value:Object.values(b.fieldInfos.parallelize).first().code},
formula:c.range},f,f,n,b.fieldInfos.parallelize))}),z()}catch(c){kb.alert(kb.error.parse(c)),v()}},formula:z=>{try{a.formula.value.map(c=>c.value).each((c,y)=>{c.field.value in b.fieldInfos.parallelize&&(u=>{u.tableCode?f[u.tableCode].value.each((A,q)=>{A.value[u.code].value=kb.formula.calculate(c,A.value,f,n,b.fieldInfos.parallelize);u.lookup&&(A.value[u.code].lookup=!0)}):(f[u.code].value=kb.formula.calculate(c,f,f,n,b.fieldInfos.parallelize),u.lookup&&(f[u.code].lookup=!0))})(b.fieldInfos.parallelize[c.field.value])}),
z()}catch(c){kb.alert(kb.error.parse(c)),v()}},lookup:z=>{try{a.lookupApp.value?kb.field.load(a.lookupApp.value).then(c=>{(y=>{var u=[],A=[],q=(r,t)=>{var l=(k,m)=>k.lookup?kb.extend({lookup:!0,type:k.type},m):kb.extend({type:k.type},m);kb.view.records.get(a.lookupApp.value,t.query,t.sort).then(k=>{0!=k.length?(m=>{a.lookupLimited.value.includes("limited")||1==k.length?m(k.first()):(kb.popups.loader.cover.css({zIndex:"999997"}),b.picker.show({app:a.lookupApp.value,query:t.query,sort:t.sort,picker:u.reduce((w,
h)=>{w[h.external.code]=h.external;return w},{})},w=>{kb.popups.loader.cover.css({zIndex:"999999"});m(w)}))})(m=>{u.each((w,h)=>{if(a.lookupOverwrite.value.includes("overwrite")||kb.field.isEmpty(t.record[w.internal.code].value))t.record[w.internal.code]=l(w.internal,m[w.external.code])});r++;r<A.length?q(r,A[r]):(F.latest.action[a.sIndex.value].lookup=B(),z())}):(a.lookupReset.value.includes("reset")&&u.each((m,w)=>{t.record[m.internal.code]=l(m.internal,kb.record.create({fields:{empty:m.internal}}).empty)}),
r++,r<A.length?q(r,A[r]):(F.latest.action[a.sIndex.value].lookup=B(),z()))}).catch(k=>{kb.alert(kb.error.parse(k));v()})},B=()=>(r=>JSON.stringify(A.reduce((t,l)=>{t.push(l.query);t.push(kb.record.simplify({fields:r},l.record));return t},[])))(u.reduce((r,t)=>{r[t.internal.code]=t.internal;return r},{}));a.lookupCriteria.value.some(r=>!(r.value.external.value in y.external&&r.value.internal.value in y.internal))?(kb.alert("No field to lookup was found"),v()):a.lookupMapping.value.some(r=>!(r.value.external.value in
y.external&&r.value.internal.value in y.internal))?(kb.alert("No field to lookup was found"),v()):(u=a.lookupMapping.value.map(r=>({external:y.external[r.value.external.value],internal:y.internal[r.value.internal.value]})),A=(r=>r.map(t=>({query:a.lookupCriteria.value.reduce((l,k)=>{var m=y.external[k.value.external.value],w=k.value.operator.value;k=y.internal[k.value.internal.value];var h=k.tableCode?t.value:n;a.lookupIgnore.value.includes("ignore")&&kb.field.isEmpty(h[k.code].value)||l.push(kb.filter.query.create(m,
w,h[k.code]));return l},kb.filter.query.parse.expand({id:a.lookupApp.value,fields:c.origin},a.lookupFilter.value).map(l=>l.field+" "+l.operator+" "+l.value)).join(" and "),sort:(0!=a.lookupSort.value.length?a.lookupSort.value.map(l=>l.value.field.value+" "+l.value.order.value):["$id asc"]).join(","),record:t.value})))((r=>r?f[r].value:[{value:n}])(Array.from(new Set(u.map(r=>r.internal.tableCode))).first())),0!=A.length?F.latest.action[a.sIndex.value].lookup&&F.latest.action[a.sIndex.value].lookup==
B()?z():q(0,A.first()):z())})({external:c.origin,internal:b.fieldInfos.parallelize})}).catch(c=>{kb.alert(kb.error.parse(c));v()}):z()}catch(c){kb.alert(kb.error.parse(c)),v()}},user:z=>{try{a.userSource.value?(c=>{0==kb.roleSet.user.length?kb.roleSet.load().then(()=>c()):c()})(()=>{var c=[],y=[],u=(q,B)=>{(t=>{c.each((l,k)=>{if(l.isCustom)switch(l.field.type){case "USER_SELECT":l.value=t.reduce((m,w)=>{"customItemValues"in w&&(h=>{0!=h.length&&(G=>{(H=>{0!=H.length&&(m.some(I=>I.code==H.first().info.code)||
m.push({code:H.first().info.code,name:H.first().info.name}))})(kb.roleSet.user.filter(H=>H.info.id==G))})(h.first().value)})(w.customItemValues.filter(h=>h.code==l.item));return Array.from(new Set(m)).filter(h=>h)},[]);break;default:l.value=t.reduce((m,w)=>{"customItemValues"in w&&(h=>{0!=h.length&&m.push(h.first().value)})(w.customItemValues.filter(h=>h.code==l.item));return Array.from(new Set(m)).filter(h=>h)},[]).join(",")}else switch(l.item){case "groups":case "organizations":l.value=t.map(m=>
m.code);break;case "primaryOrganization":l.value=t.reduce((m,w)=>{l.item in w&&(h=>{0!=h.length&&(m.some(G=>G.code==h.first().info.code)||m.push({code:h.first().info.code,name:h.first().info.name}))})(kb.roleSet.organization.filter(h=>h.info.id==w[l.item]));return m},[]);break;default:l.value=t.reduce((m,w)=>{l.item in w&&m.push(w[l.item]);return Array.from(new Set(m)).filter(h=>h)},[]).join(",")}})})(B[a.userSource.value].value.reduce((t,l)=>{(k=>{0!=k.length&&t.push(k.first().info)})(kb.roleSet.user.filter(k=>
k.info.code==l.code));return t},[]));var r=(t,l)=>{((k,m)=>{var w=(h,G,H)=>{switch(k.item){case "groups":kintone.api(kintone.api.url("/v1/user/groups",!0),"GET",{code:k.value[h]}).then(I=>{I.groups&&(G=G.concat(I.groups.map(N=>({code:N.code,name:N.name}))),h++,h<k.value.length?w(h,G,H):H(G))}).catch(I=>{kb.alert(kb.error.parse(I));v()});break;case "organizations":kintone.api(kintone.api.url("/v1/user/organizations",!0),"GET",{code:k.value[h]}).then(I=>{I.organizationTitles&&(G=G.concat(I.organizationTitles.map(N=>
({code:N.organization.code,name:N.organization.name}))),h++,h<k.value.length?w(h,G,H):H(G))}).catch(I=>{kb.alert(kb.error.parse(I));v()})}};a.userOverwrite.value.includes("overwrite")||kb.field.isEmpty(B[k.field.code].value)||m();switch(k.item){case "groups":case "organizations":0!=k.value.length?w(0,[],h=>{B[k.field.code].value=h;m()}):(B[k.field.code].value=k.value,m());break;default:B[k.field.code].value=k.value,m()}})(c[t],()=>{t++;t<c.length?r(t,l):l()})};r(0,()=>{q++;q<y.length?u(q,y[q]):(F.latest.action[a.sIndex.value].user=
A(),z())})},A=()=>(q=>JSON.stringify(y.map(B=>kb.record.simplify({fields:q},B))))(c.reduce((q,B)=>{q[B.field.code]=B.field;return q},(q=>{var B={};B[q]=b.fieldInfos.parallelize[q];return B})(a.userSource.value)));a.userCustomItem.value.some(q=>!(q.value.field.value in b.fieldInfos.parallelize))?(kb.alert("No field to user informations was found"),v()):a.userMapping.value.some(q=>!(q.value.field.value in b.fieldInfos.parallelize))?(kb.alert("No field to user informations was found"),v()):(a.userCustomItem.value.each((q,
B)=>{c.push({isCustom:!0,item:q.value.item.value,field:b.fieldInfos.parallelize[q.value.field.value],value:[]})}),a.userMapping.value.each((q,B)=>{c.push({isCustom:!1,item:q.value.item.value,field:b.fieldInfos.parallelize[q.value.field.value],value:[]})}),a.userPrimaryOrganization.value&&a.userPrimaryOrganization.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"primaryOrganization",field:b.fieldInfos.parallelize[a.userPrimaryOrganization.value],value:[]}),a.userOrganization.value&&a.userOrganization.value in
b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"organizations",field:b.fieldInfos.parallelize[a.userOrganization.value],value:[]}),a.userGroup.value&&a.userGroup.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"groups",field:b.fieldInfos.parallelize[a.userGroup.value],value:[]}),y=(q=>q?f[q].value:[{value:n}])(b.fieldInfos.parallelize[a.userSource.value].tableCode).map(q=>q.value),0!=y.length?F.latest.action[a.sIndex.value].user&&F.latest.action[a.sIndex.value].user==A()?z():0!=c.length?
u(0,y.first()):z():z())}):z()}catch(c){kb.alert(kb.error.parse(c)),v()}}};E.clear(()=>{E.fill(()=>{E.formula(()=>{E.lookup(()=>{E.user(()=>{e()})})})})})}else e()}).catch(x=>{kb.alert(kb.error.parse(x));v()}):e()})((a=>{F.latest?F.latest.action||(F.latest.action={}):F.latest={action:{}};a.sIndex.value in F.latest.action||(F.latest.action[a.sIndex.value]={lookup:"[]",user:"[]"});return a})(g[p]))};D(0,()=>{J({record:n,performed:C!=JSON.stringify(kb.record.simplify({fields:b.fieldInfos.origin},n))})})});
kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.index.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show mobile.app.record.index.show".split(" "),g=>new Promise((n,F)=>{((L,J)=>{b.mobile=L;b.type=J;for(var v in b.handlers)b.handlers[v].each((C,D)=>{kintone.events.off(v,C)});kb.config[K].config.get().then(C=>{0!=Object.keys(C).length?kb.field.load(kb.config[K].app,!0).then(D=>{b.app={id:kb.config[K].app,fields:D.origin};
b.fieldInfos=D;b.picker=new KintoneBoosterRecordPicker("record");try{["create","edit","reuse"].includes(b.type)&&(p=>{if(0!=p.length)b.latest={record:"",time:null},((d,e)=>{kintone.events.on(d,e);d.each((a,f)=>{a in b.handlers||(b.handlers[a]=[]);b.handlers[a].push(e)})})(D.changes.reduce((d,e)=>{d.push("app.record.create.change."+e);d.push("app.record.edit.change."+e);d.push("mobile.app.record.create.change."+e);d.push("mobile.app.record.edit.change."+e);return d},[]),d=>{var e=p.filter(a=>(f=>!f.first()||
f.includes(d.type.split(".").last()))(a.triggers.value.map(f=>f.value.field.value)));if((()=>{var a=!0;["DATETIME","TIME"].includes(d.changes.field.type)&&(f=>{f&&(Array.isArray(f)?f:[f]).each((x,E)=>{x.elm(".control-errors-content-gaia")&&(a=!1)})})(kb.field.get(D.parallelize[d.type.split(".").last()],b.mobile,b.type));return a})())return(()=>{var a=!0;b.latest.record&&(a=!1,b.latest.record==JSON.stringify(kb.record.simplify({fields:D.origin},d.record))?b.latest={record:"",time:null}:b.latest.time<
(new Date).getTime()-1E3&&(b.latest={record:"",time:null},a=!0));return a})()&&kb.event.call("kb.lookup.identifier.call",{record:d.record,tableCode:d.type.split(".").last()}).then(a=>{0!=e.length?M(e,a.record,kb.elm("body"),"record").then(f=>{kb.event.call("kb.style.call",{container:kb.elm("body"),record:a.record,mobile:b.mobile,pattern:"reuse"==b.type?"create":b.type,workplace:"record"}).then(x=>{kb.event.call("kb.cascade.call",x).then(E=>{if(f.performed||E.performed)b.latest=f.performed?{record:JSON.stringify(kb.record.simplify({fields:D.origin},
E.record)),time:(new Date).getTime()}:{record:"",time:null},(b.mobile?kintone.mobile.app.record:kintone.app.record).set(d)}).catch(()=>{})}).catch(()=>{})}).catch(()=>{}):kb.event.call("kb.style.call",{container:kb.elm("body"),record:a.record,mobile:b.mobile,pattern:"reuse"==b.type?"create":b.type,workplace:"record"}).then(f=>{kb.event.call("kb.cascade.call",f).then(x=>{x.performed&&(b.latest={record:"",time:null},(b.mobile?kintone.mobile.app.record:kintone.app.record).set(d))}).catch(()=>{})}).catch(()=>
{})}).catch(()=>{}),d}),kb.event.on("kb.action.installed.change",d=>({installed:!0}));else kb.event.on("kb.action.installed.change",d=>({installed:!1}))})(JSON.parse(C.tab).map((p,d)=>kb.extend({sIndex:{value:d.toString()}},p.setting)).reduce((p,d)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(d.device.value)&&d.event.value.includes("change")&&p.push(d);return p},[])),["detail"].includes(b.type)&&kintone.app.record.getPermissions().then(p=>{p.editRecord&&(d=>{0!=d.length&&((e,
a)=>{kintone.events.on(e,a);e.each((f,x)=>{f in b.handlers||(b.handlers[f]=[]);b.handlers[f].push(a)})})(["app.record.detail.process.proceed","mobile.app.record.detail.process.proceed"],e=>new Promise((a,f)=>{try{(x=>{0!=x.length?M(x,e.record,kb.elm("body"),"record").then(E=>a(e)).catch(()=>{}):a(e)})(d.filter(x=>x.action.value==e.action.value+":"+e.status.value+":"+e.nextStatus.value))}catch(x){kb.alert(kb.error.parse(x)),a(e)}}))})(JSON.parse(C.tab).map((d,e)=>kb.extend({sIndex:{value:e.toString()}},
d.setting)).reduce((d,e)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(e.device.value)&&e.event.value.includes("process")&&d.push(e);return d},[]))}).catch(()=>{}),(p=>{if(0!=p.length)switch(b.type){case "create":case "edit":case "reuse":M(p,g.record,kb.elm("body"),"record").then(e=>{kb.event.call("kb.style.call",{container:kb.elm("body"),record:g.record,mobile:b.mobile,pattern:"reuse"==b.type?"create":b.type,workplace:"record"}).then(a=>{kb.event.call("kb.cascade.call",a).then(f=>
n(g)).catch(()=>{})}).catch(()=>{})}).catch(()=>{});kb.event.on("kb.action.installed.show",e=>({installed:!0}));break;case "detail":var d=e=>{(a=>{kb.filter.scan(b.app,g.record,a.condition.value)?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(f=>{f&&kb.button.create(b.mobile,b.type,"kb-action-button"+e.toString(),a.label.value,a.message.value,()=>{M([a],g.record,kb.elm("body"),"record").then(x=>{kb.view.records.set(b.app.id,{put:[kb.view.records.transform(x.record)]}).then(E=>
kb.alert("Done!",()=>window.location.reload(!0))).catch(E=>kb.alert(kb.error.parse(E)))}).catch(()=>{})});e++;e<p.length&&d(e)}).catch(f=>{e++;e<p.length&&d(e)}):(e++,e<p.length&&d(e))})(p[e])};d(0);n(g);break;case "index":d=e=>{(a=>{kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(f=>{f&&(a.view.value&&a.view.value!=g.viewId.toString()||kb.button.create(b.mobile,b.type,"kb-action-button"+e.toString(),a.label.value,a.message.value,()=>{kb.view.records.get(b.app.id,(b.mobile?kintone.mobile.app:
kintone.app).getQueryCondition()).then(x=>{var E=[];let z=(c,y)=>{M([a],x[c],kb.create("div"),"record").then(u=>{u.performed&&E.push(kb.view.records.transform(u.record));kb.progressUpdate();c++;c<x.length?z(c,y):y()}).catch(()=>{})};0!=x.length?(kb.progressStart(x.length),z(0,()=>{kb.view.records.set(b.app.id,{put:E}).then(c=>kb.alert("Done!",()=>window.location.reload(!0))).catch(c=>kb.alert(kb.error.parse(c)))})):kb.alert("There are no records.")}).catch(x=>kb.alert(kb.error.parse(x)))}));e++;e<
p.length&&d(e)}).catch(f=>{e++;e<p.length&&d(e)})})(p[e])},d(0),n(g)}else n(g)})(JSON.parse(C.tab).map((p,d)=>kb.extend({sIndex:{value:d.toString()}},p.setting)).reduce((p,d)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(d.device.value)&&d.event.value.includes(b.type)&&p.push(d);return p},[]))}catch(p){kb.alert(kb.error.parse(p)),n(g)}}).catch(D=>n(g)):n(g)}).catch(C=>n(g))})("mobile"==g.type.split(".").first(),g.reuse?"reuse":g.type.split(".").slice(-2).first())}));kb.event.on("kb.action.call",
g=>new Promise((n,F)=>{kb.config[K].config.get().then(L=>{0!=Object.keys(L).length?kb.field.load(kb.config[K].app,!0).then(J=>{b.app={id:kb.config[K].app,fields:J.origin};b.fieldInfos=J;b.mobile="mobile"in b?b.mobile:g.mobile;b.picker=new KintoneBoosterRecordPicker("record");try{(v=>{if(0!=v.length){var C=(()=>{var D=v;"change"==g.pattern&&(D=v.filter(p=>(d=>"fields"in g?!d.first()||g.fields.some(e=>d.includes(e)):!d.first()||d.includes(g.field))(p.triggers.value.map(d=>d.value.field.value))));return D})();
0!=C.length?M(C,g.record,g.container,g.workplace?g.workplace:"record").then(D=>{g.stopPropagation&&(b.latest={record:JSON.stringify(kb.record.simplify({fields:J.origin},g.record)),time:(new Date).getTime()});g.performed=D.performed;n(g)}).catch(()=>n(g)):n(g)}else n(g)})(JSON.parse(L.tab).map((v,C)=>kb.extend({sIndex:{value:C.toString()}},v.setting)).reduce((v,C)=>{(g.mobile?["all","both","mobile"]:["all","both","pc"]).includes(C.device.value)&&C.event.value.includes(g.pattern)&&v.push(C);return v},
[]))}catch(v){kb.alert(kb.error.parse(v)),n(g)}}).catch(J=>n(g)):n(g)}).catch(L=>n(g))}))})(kintone.$PLUGIN_ID);
