/*
* FileName "plugins.decoder.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(A=>{var a={guideMargin:.15,lastCode:null,matchCount:0,reader:null,video:null,observers:[]},D=d=>{var h=a.video.getBoundingClientRect(),k=a.video.video.getBoundingClientRect();if(!k.width||!k.height)return null;var b=a.video.video.videoWidth,l=a.video.video.videoHeight;if(!b||!l)return null;var c=Math.min(k.width/b,k.height/l),m=b*c;c*=l;var f="qrcode"==d?Math.min(m,c)*(1-2*a.guideMargin):m*(1-2*a.guideMargin);d="qrcode"==d?f:Math.max(100,.25*c);var q=(m-f)/2,x=(c-d)/2;a.video.guide.css({height:d+
"px",left:k.left-h.left+(k.width-m)/2+q+"px",top:k.top-h.top+(k.height-c)/2+x+"px",width:f+"px"});return{sx:q/m*b,sy:x/c*l,sw:f/m*b,sh:d/c*l}},B=(d,h,k)=>{a.video.video.autoplay&&setTimeout(()=>{a.video.video.autoplay&&a.video.video.srcObject&&((b,l)=>{var c=D(d)||{sx:0,sy:0,sw:a.video.video.videoWidth,sh:a.video.video.videoHeight},m=f=>{try{return(new TextDecoder("utf-8",{fatal:!0})).decode(f)}catch(q){return(new TextDecoder("shift_jis")).decode(f)}};b.width=c.sw;b.height=c.sh;b.width&&b.height&&
(b.getContext("2d").drawImage(a.video.video,c.sx,c.sy,c.sw,c.sh,0,0,c.sw,c.sh),"qrcode"==d?(b=jsQR(b.getContext("2d").getImageData(0,0,b.width,b.height).data,b.width,b.height))?l(b.binaryData?m(new Uint8Array(b.binaryData)):b.data):l(null):Quagga.decodeSingle({locator:{patchSize:"medium",halfSample:!1},decoder:{readers:[h.readers]},numOfWorkers:0,locate:!1,src:b.toDataURL("image/png")},f=>l(f&&f.codeResult?f.codeResult.code:null)))})(bst.create("canvas"),b=>{if(b&&b==a.lastCode){if(a.matchCount++,
1<a.matchCount){k(b);return}}else a.lastCode=b,a.matchCount=b?1:0;B(d,h,k)})},250)},E=(d,h,k)=>{(b=>{b.observe(bst.elm(".subtable-"+d.id+(a.mobile?"":" tbody")),{childList:!0,subtree:!1});(l=>{bst.elms(l).length==h[d.code].value.length&&k.each((c,m)=>c({record:h}))})(".subtable-"+d.id+(a.mobile?" .subtable-row-gaia":" tbody tr"));a.observers.push(b)})(new MutationObserver(()=>{k.each((b,l)=>b({record:h}))}))},y=()=>{a.video.video.srcObject&&a.video.video.srcObject.getTracks().each((d,h)=>d.stop());
a.video.video.autoplay=!1;a.video.video.srcObject=null};kintone.events.on(["app.record.create.show","app.record.edit.show","mobile.app.record.create.show","mobile.app.record.edit.show"],d=>new Promise((h,k)=>{((b,l)=>{a.mobile=b;a.type=l;a.video=(c=>{c.guide=bst.create("div").css({boxSizing:"border-box",border:"1px solid #ffc107",pointerEvents:"none",position:"absolute"});c.video=bst.create("video").attr("muted","muted").attr("playsinline","playsinline").css({boxSizing:"border-box",height:"100%",
objectFit:"contain",width:"100%"});return c.append(c.video).append(c.guide)})(bst.create("div").css({boxSizing:"border-box",height:"100%",position:"relative",width:"100%"}));a.reader=a.video.popup("full","full",[],y);a.observers.each((c,m)=>c.disconnect());a.observers=[];bst.config[A].config.get().then(c=>{0!=Object.keys(c).length?bst.field.load(bst.config[A].app,!0).then(m=>{a.app={id:bst.config[A].app,fields:m.origin};a.fieldInfos=m;try{(f=>{var q={};f=[...f.barcode.value.map(e=>{e.value.type={value:"barcode"};
return e.value}),...f.qrcode.value.map(e=>{e.value.type={value:"qrcode"};return e.value})].reduce((e,t)=>{t.field.value in a.fieldInfos.parallelize&&(e[t.field.value]={fieldInfo:a.fieldInfos.parallelize[t.field.value],format:"format"in t?t.format.value:"",type:t.type.value});return e},{});bst.event.off("bst.decoder.call");Object.values(f).each((e,t)=>{(z=>{if(e.fieldInfo.tableCode){var p=a.fieldInfos.tables[e.fieldInfo.tableCode];p.code in q||(q[p.code]=[]);q[p.code].push(z);a.mobile&&z({record:d.record})}else z({record:d.record})})(z=>
{((p,v)=>{p&&(Array.isArray(p)?p:[p]).each((g,F)=>{g.value.parentNode.elm(".bst-decoder-operation")||(v(g,g.value,a.mobile?g.value:g.value.elm("input[type=text]")),e.fieldInfo.lookup&&(g.nextSibling&&g.nextSibling.tagName.toLowerCase().startsWith("kuc")&&(n=>{n&&v(g,a.mobile?n:n.parentNode,n)})(g.nextSibling.elm("input[type=text]")),bst.event.on("bst.decoder.call",n=>{if(n.field==g&&g.nextSibling&&g.nextSibling.tagName.toLowerCase().startsWith("kuc")&&!g.nextSibling.elm(".bst-decoder-operation")){var u=
g.nextSibling.elm("input[type=text]");v(g,a.mobile?u:u.parentNode,u)}return n})))})})(bst.field.get(e.fieldInfo,a.mobile,a.type),(p,v,g)=>{v.parentNode.css(a.mobile?{alignItems:"center"}:{alignItems:"center",display:"flex"}).insertBefore(bst.create("button").addClass("bst-icon bst-icon-camera bst-decoder-operation"+(a.mobile?" bst-mobile":"")).on("click",F=>{a.video.video.autoplay=!0;a.video.video.muted=!0;navigator.mediaDevices.getUserMedia({audio:!1,video:{facingMode:{ideal:"environment"}}}).then(n=>
{a.video.video.srcObject=n;a.video.video.play().then(()=>{a.lastCode="";a.matchCount=0;a.reader.show();B(e.type,{readers:e.format},u=>{a.reader.hide();y();((G,C)=>{bst.event.call("bst.action.call",{container:bst.elm("body"),record:(r=>{var w={};e.fieldInfo.tableCode?(w[e.fieldInfo.tableCode]=r[e.fieldInfo.tableCode],w[e.fieldInfo.tableCode].value[G.indexOf(p)].value[e.fieldInfo.code]=C):w[e.fieldInfo.code]=C;return w})((a.mobile?kintone.mobile.app.record:kintone.app.record).get().record),mobile:a.mobile,
pattern:"change",fields:[e.fieldInfo.lookup?e.fieldInfo.lookup.triggerField:e.fieldInfo.code],stopPropagation:!0,workplace:"record"}).then(r=>{bst.event.call("bst.style.call",{container:r.container,record:r.record,mobile:r.mobile,pattern:"$id"in r.record?r.record.$id.value?"edit":"create":"create",workplace:r.workplace}).then(w=>{bst.event.call("bst.cascade.call",w).then(H=>{(a.mobile?kintone.mobile.app.record:kintone.app.record).set({record:H.record})}).catch(()=>{})}).catch(()=>{})}).catch(()=>
{})})(bst.field.get(e.fieldInfo,a.mobile,a.type),bst.extend({type:e.fieldInfo.type,value:u},e.fieldInfo.lookup?{lookup:"UPDATE"}:{}))})}).catch(u=>{a.reader.hide();y();bst.alert(bst.error.parse(u))})}).catch(n=>{a.reader.hide();y();bst.alert(bst.error.parse(n))})}),v.nextSibling);a.mobile&&g.addClass("bst-decoder-operation-input bst-mobile")})})});for(var x in q)E(a.fieldInfos.tables[x],d.record,q[x])})(JSON.parse(c.flat)),h(d)}catch(f){bst.alert(bst.error.parse(f)),h(d)}}).catch(m=>h(d)):h(d)}).catch(c=>
h(d))})("mobile"==d.type.split(".").first(),d.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
