/*
* FileName "plugins.gantt.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(u=>{var e={},w=(m,c)=>{(b=>{var p=null,q=a=>{var k=[],f=[];b.subTask&&a[b.subTask].value.each((d,g)=>{d.value[c.subtaskStart.value].value&&d.value[c.subtaskEnd.value].value&&f.push({id:"task_"+a.$id.value.toString()+"_"+g.toString(),name:bst.field.stringify(e.fieldInfos.parallelize[c.subtaskTitle.value],d.value[c.subtaskTitle.value].value," / "),start:(l=>b.time.subTask.start?l:(new Date(l)).calc(bst.timezoneOffset()+" hour").toISOString())(d.value[c.subtaskStart.value].value),end:(l=>b.time.subTask.end?
l:(new Date(l)).calc(bst.timezoneOffset()+" hour").toISOString())(d.value[c.subtaskEnd.value].value),progress:c.subtaskProgress.value?d.value[c.subtaskProgress.value].value:null,dependencies:"task_"+a.$id.value.toString()+(0<g?"_"+(g-1).toString():""),group:"task_"+a.$id.value.toString(),colors:{back:d.value[c.subtaskTitle.value].backcolor,fore:d.value[c.subtaskTitle.value].forecolor},resizable:{left:b.editable.subTask.start,right:b.editable.subTask.end}})});k.push({id:"task_"+a.$id.value.toString(),
name:bst.field.stringify(e.fieldInfos.parallelize[c.taskTitle.value],a[c.taskTitle.value].value," / "),start:(d=>b.time.task.start?d:(new Date(d)).calc(bst.timezoneOffset()+" hour").toISOString())(a[c.taskStart.value].value),end:(d=>b.time.task.end?d:(new Date(d)).calc(bst.timezoneOffset()+" hour").toISOString())(a[c.taskEnd.value].value),progress:c.taskProgress.value?a[c.taskProgress.value].value:null,dependencies:"",group:"task_"+a.$id.value.toString(),colors:{back:a[c.taskTitle.value].backcolor,
fore:a[c.taskTitle.value].forecolor},resizable:{left:b.editable.task.start,right:b.editable.task.end}});k=k.concat(f);e.records[a.$id.value]=a;return k},n=(a,k)=>{bst.view.records.get(e.app.id,(f=>{var d=[],g=h=>h.calc(bst.timezoneOffset()+" hour"),l=(h,t,v)=>b.timeStamp[t][v]?(h.getTime()/1E3).toString():b.time[t][v]?h.toISOString():h.format("Y-m-d");d.push((()=>{var h=[];h.push(c.taskStart.value+'!=""');h.push(c.taskStart.value+'>"'+l(b.time.task.start?g((new Date(a.start)).calc("-1 second")):(new Date(a.start)).calc("-1 day"),
"task","start")+'"');h.push(c.taskStart.value+'<"'+l(b.time.task.start?g((new Date(a.end)).calc("1 day")):(new Date(a.end)).calc("1 day"),"task","start")+'"');return"("+h.join(" and ")+")"})());d.push((()=>{var h=[];h.push(c.taskEnd.value+'!=""');h.push(c.taskEnd.value+'>"'+l(b.time.task.end?g((new Date(a.start)).calc("-1 second")):(new Date(a.start)).calc("-1 day"),"task","end")+'"');h.push(c.taskEnd.value+'<"'+l(b.time.task.end?g((new Date(a.end)).calc("1 day")):(new Date(a.end)).calc("1 day"),
"task","end")+'"');return"("+h.join(" and ")+")"})());d.push((()=>{var h=[];h.push(c.taskStart.value+'!=""');h.push(c.taskEnd.value+'!=""');h.push(c.taskStart.value+'<="'+l(b.time.task.start?g((new Date(a.start)).calc("-1 second")):(new Date(a.start)).calc("-1 day"),"task","start")+'"');h.push(c.taskEnd.value+'>="'+l(b.time.task.end?g((new Date(a.end)).calc("1 day")):(new Date(a.end)).calc("1 day"),"task","end")+'"');return"("+h.join(" and ")+")"})());b.subTask&&(d.push((()=>{var h=[];h.push(c.subtaskStart.value+
' not in ("")');h.push(c.subtaskStart.value+'>"'+l(b.time.subTask.start?g((new Date(a.start)).calc("-1 second")):(new Date(a.start)).calc("-1 day"),"subTask","start")+'"');h.push(c.subtaskStart.value+'<"'+l(b.time.subTask.start?g((new Date(a.end)).calc("1 day")):(new Date(a.end)).calc("1 day"),"subTask","start")+'"');return"("+h.join(" and ")+")"})()),d.push((()=>{var h=[];h.push(c.subtaskEnd.value+' not in ("")');h.push(c.subtaskEnd.value+'>"'+l(b.time.subTask.end?g((new Date(a.start)).calc("-1 second")):
(new Date(a.start)).calc("-1 day"),"subTask","end")+'"');h.push(c.subtaskEnd.value+'<"'+l(b.time.subTask.end?g((new Date(a.end)).calc("1 day")):(new Date(a.end)).calc("1 day"),"subTask","end")+'"');return"("+h.join(" and ")+")"})()),d.push((()=>{var h=[];h.push(c.subtaskStart.value+' not in ("")');h.push(c.subtaskEnd.value+' not in ("")');h.push(c.subtaskStart.value+'<="'+l(b.time.subTask.start?g((new Date(a.start)).calc("-1 second")):(new Date(a.start)).calc("-1 day"),"subTask","start")+'"');h.push(c.subtaskEnd.value+
'>="'+l(b.time.subTask.end?g((new Date(a.end)).calc("1 day")):(new Date(a.end)).calc("1 day"),"subTask","end")+'"');return"("+h.join(" and ")+")"})()));return(f?"("+f+") and ":"")+"("+d.join(" or ")+")"})((e.mobile?kintone.mobile.app:kintone.app).getQueryCondition()),(f=>{f=f.match(/order by/g)?f.replace(/^.*order by/g,""):"";return(f=f.replace(/limit [0-9]+/g,"").replace(/ offset [0-9]+/g,"").replace(/^[ ]+/g,"").replace(/[ ]+$/g,""))?f:"$id asc"})((e.mobile?kintone.mobile.app:kintone.app).getQuery())).then(f=>
{var d=(g,l)=>{bst.event.call("bst.style.call",{container:bst.elm("body"),record:f[g],mobile:e.mobile,pattern:"detail",workplace:"view"}).then(h=>{g++;g<f.length?d(g,l):l()}).catch(h=>{g++;g<f.length?d(g,l):l()})};e.records={};e.tasks=[];0!=f.length?d(0,()=>{f.each((g,l)=>{e.tasks=e.tasks.concat(q(g))});k()}):k()}).catch(f=>bst.alert(bst.error.parse(f)))},r=a=>{0!=Object.keys(a.record).length&&bst.view.records.set(e.app.id,{put:[a]},!0).then(k=>{var f=JSON.stringify(e.records[a.id]);bst.event.call("bst.style.call",
{container:bst.elm("body"),record:e.records[a.id],mobile:e.mobile,pattern:"detail",workplace:"view"}).then(d=>{f!=JSON.stringify(d.record)&&(g=>{e.tasks=e.tasks.filter(l=>l.group!="task_"+d.record.$id.value.toString());Array.prototype.splice.apply(e.tasks,[g,0].concat(q(d.record)));p.refresh(e.tasks)})(e.tasks.findIndex(g=>g.id=="task_"+d.record.$id.value.toString()))}).catch(d=>finish())}).catch(k=>bst.alert(bst.error.parse(k)))};m.empty().append((a=>{var k={Day:{en:"Day",ja:"\u65e5",zh:"\u65e5",
"zh-TW":"\u65e5"},Week:{en:"Week",ja:"\u9031",zh:"\u5468","zh-TW":"\u9031"},Month:{en:"Month",ja:"\u6708",zh:"\u6708","zh-TW":"\u6708"},"Half Day":{en:"Half Day",ja:"12\u6642\u9593\u6bce",zh:"\u6bcf12\u5c0f\u65f6","zh-TW":"\u6bcf12\u5c0f\u6642"},"Quarter Day":{en:"Quarter Day",ja:"6\u6642\u9593\u6bce",zh:"\u6bcf6\u5c0f\u65f6","zh-TW":"\u6bcf6\u5c0f\u6642"}};a.append(bst.create("div").addClass("kb-gantt-header-filter").append(bst.create("span").addClass("kb-gantt-guide").html("From:")).append(bst.create("button").addClass("kb-gantt-button kb-gantt-pickup-button").on("click",
f=>{(d=>{bst.pickupDate(b.session.start,g=>{b.session.start=g;d.html(b.session.start)})})(f.currentTarget.nextElementSibling)})).append(bst.create("span").addClass("kb-gantt-guide").html(b.session.start)).append(bst.create("span").addClass("kb-gantt-guide").html("&nbsp;&nbsp;To:")).append(bst.create("button").addClass("kb-gantt-button kb-gantt-pickup-button").on("click",f=>{(d=>{bst.pickupDate(b.session.end,g=>{b.session.end=g;d.html(b.session.end)})})(f.currentTarget.nextElementSibling)})).append(bst.create("span").addClass("kb-gantt-guide").html(b.session.end)).append(bst.create("button").addClass("kb-gantt-button kb-gantt-search-button").on("click",
f=>{n(b.session,()=>p.refresh(e.tasks));sessionStorage.setItem("kb-gantt-"+c.view.value,JSON.stringify({start:b.session.start,end:b.session.end,initial:p.options.view_mode}))}))).append(bst.create("div").addClass("kb-gantt-header-mode"));(f=>{for(var d in k)(g=>{f.append((l=>{k[g].button=l;return l.on("click",()=>{p.change_view_mode(g);for(var h in k){var t=h;k[t].button==l?k[t].button.addClass("kb-gantt-button-active"):k[t].button.removeClass("kb-gantt-button-active")}})})(bst.create("button").addClass("kb-gantt-button"+
(b.session.initial==g?" kb-gantt-button-active":"")).html(k[g][bst.operator.language])))})(d)})(a.elm(".kb-gantt-header-mode"));return a})(bst.create("div").attr("id","kb-gantt-header"))).append(bst.create("div").attr("id","kb-gantt-main"));n(b.session,()=>{p=new Gantt("#kb-gantt-main",e.tasks,{start:b.session.start,end:b.session.end,header_height:50,column_width:30,view_modes:["Quarter Day","Half Day","Day","Week","Month"],bar_height:20,bar_corner_radius:3,arrow_curve:5,padding:18,view_mode:b.session.initial,
language:"en",custom_popup_html:null,on_click:a=>{bst.confirm(bst.constants.gantt.message.confirm.edit[bst.operator.language],()=>{var k=(c.page||{value:[]}).value.includes("detail"),f=bst.config[u].app,d=a.id.replace(/task_/g,"").split("_").first();k||sessionStorage.setItem("kb-gantt-edit",JSON.stringify({href:window.location.href}));window.location.href=k?bst.record.page.detail(e.mobile,f,d):bst.record.page.edit(e.mobile,f,d)})},on_date_change:a=>{(k=>{var f={id:k.first(),record:{}};a.each((d,g)=>
{if(0==g)b.editable.task.start&&(f.record[c.taskStart.value]=e.records[k.first()][c.taskStart.value],f.record[c.taskStart.value].value=b.time.task.start?d._start.toISOString():d._start.format("Y-m-d")),b.editable.task.end&&(f.record[c.taskEnd.value]=e.records[k.first()][c.taskEnd.value],f.record[c.taskEnd.value].value=b.time.task.end?d._end.toISOString():d._end.calc("-1 day").format("Y-m-d"));else if(b.editable.subTask.start||b.editable.subTask.end)f.record[b.subTask]=e.records[k.first()][b.subTask],
b.editable.subTask.start&&(f.record[b.subTask].value[g-1].value[c.subtaskStart.value].value=b.time.subTask.start?d._start.toISOString():d._start.format("Y-m-d")),b.editable.subTask.end&&(f.record[b.subTask].value[g-1].value[c.subtaskEnd.value].value=b.time.subTask.end?d._end.toISOString():d._end.calc("-1 day").format("Y-m-d"))});r(f)})(a.first().id.replace(/task_/g,"").split("_"))},on_progress_change:(a,k)=>{var f=a.id.replace(/task_/g,"").split("_");a=a.id==a.group;var d={id:f.first(),record:{}};
a?c.taskProgress.value&&(d.record[c.taskProgress.value]=e.records[f.first()][c.taskProgress.value],d.record[c.taskProgress.value].value=k):c.subtaskProgress.value&&(d.record[b.subTask]=e.records[f.first()][b.subTask],d.record[b.subTask].value[f.last()].value[c.subtaskProgress.value].value=k);r(d)},on_view_change:a=>{}})})})((b=>{var p=b(e.fieldInfos.parallelize[c.taskStart.value]),q=b(e.fieldInfos.parallelize[c.taskEnd.value]),n=b(c.subtaskStart.value?e.fieldInfos.parallelize[c.subtaskStart.value]:
{type:""});b=b(c.subtaskEnd.value?e.fieldInfos.parallelize[c.subtaskEnd.value]:{type:""});var r={task:{start:p.isEditable,end:q.isEditable},subTask:{start:n.isEditable,end:b.isEditable}};var a=(a=sessionStorage.getItem("kb-gantt-"+c.view.value))?JSON.parse(a):{start:(new Date).format("Y-m-d"),end:(new Date).calc("1 month,-1 day").format("Y-m-d"),initial:c.initial.value};return{editable:r,session:a,subTask:c.subtaskTitle.value?e.fieldInfos.parallelize[c.subtaskTitle.value].tableCode:"",time:{task:{start:p.isDateTime,
end:q.isDateTime},subTask:{start:n.isDateTime,end:b.isDateTime}},timeStamp:{task:{start:p.isTimeStamp,end:q.isTimeStamp},subTask:{start:n.isTimeStamp,end:b.isTimeStamp}}}})(b=>{switch(b.type){case "CALC":switch(b.format){case "DATE":b.isDateTime=!1;b.isEditable=!1;break;case "DATETIME":b.isDateTime=!0,b.isEditable=!1}b.isTimeStamp=!0;break;case "CREATED_TIME":case "UPDATED_TIME":b.isDateTime=!0;b.isEditable=!1;b.isTimeStamp=!1;break;case "DATE":b.isDateTime=!1;b.isEditable=!0;b.isTimeStamp=!1;break;
case "DATETIME":b.isDateTime=!0;b.isEditable=!0;b.isTimeStamp=!1;break;default:b.isDateTime=!1,b.isEditable=!0,b.isTimeStamp=!1}return b}))};kintone.events.on(["app.record.index.show","mobile.app.record.index.show"],m=>new Promise((c,b)=>{((p,q)=>{e.mobile=p;e.type=q;bst.config[u].config.get().then(n=>{0!=Object.keys(n).length?bst.field.load(bst.config[u].app,!0).then(r=>{e.app={id:bst.config[u].app,fields:r.origin};e.fieldInfos=r;e.records={};e.tasks=[];try{(a=>{if(a){a.taskTitle.value&&(a.taskTitle.value in
e.fieldInfos.parallelize||c(m));a.taskStart.value&&(a.taskStart.value in e.fieldInfos.parallelize||c(m));a.taskEnd.value&&(a.taskEnd.value in e.fieldInfos.parallelize||c(m));a.taskProgress.value&&(a.taskProgress.value in e.fieldInfos.parallelize||c(m));a.subtaskTitle.value&&(a.subtaskTitle.value in e.fieldInfos.parallelize||c(m));a.subtaskStart.value&&(a.subtaskStart.value in e.fieldInfos.parallelize||c(m));a.subtaskEnd.value&&(a.subtaskEnd.value in e.fieldInfos.parallelize||c(m));a.subtaskProgress.value&&
(a.subtaskProgress.value in e.fieldInfos.parallelize||c(m));var k=bst.elm("#bst-gantt, #kb-gantt");k&&w(k,a)}c(m)})(JSON.parse(n.tab).map((a,k)=>bst.extend({sIndex:{value:k.toString()}},a.setting)).reduce((a,k)=>{k.view.value==m.viewId.toString()&&(a=k);return a},null))}catch(a){bst.alert(bst.error.parse(a)),c(m)}}).catch(r=>c(m)):c(m)}).catch(n=>c(m))})("mobile"==m.type.split(".").first(),m.type.split(".").slice(-2).first())}));kintone.events.on(["app.record.edit.show","mobile.app.record.edit.show"],
m=>new Promise((c,b)=>{(p=>{p&&((q=>{(n=>{n.parentNode.insertBefore(n.clone().removeAttr("disabled").on("click",r=>{window.location.href=q.href}),n.hide().nextElementSibling)})(bst.elm("mobile"==m.type.split(".").first()?".gaia-mobile-v2-app-record-edittoolbar-cancel":".gaia-ui-actionmenu-cancel"));kintone.events.on(["app.record.edit.submit.success","mobile.app.record.edit.submit.success"],n=>new Promise((r,a)=>{n.url=q.href;r(n)}))})(JSON.parse(p)),sessionStorage.removeItem("kb-gantt-edit"));c(m)})(sessionStorage.getItem("kb-gantt-edit"))}))})(kintone.$PLUGIN_ID);
bst.constants=bst.extend({gantt:{message:{confirm:{edit:{en:"Do you want to open the record?",ja:"\u30ec\u30b3\u30fc\u30c9\u3092\u958b\u304d\u307e\u3059\u304b\uff1f",zh:"\u60a8\u8981\u6253\u5f00\u8bb0\u5f55\u5417\uff1f","zh-TW":"\u60a8\u8981\u6253\u958b\u8a18\u9304\u55ce\uff1f"}}}}},bst.constants);
