/*
* FileName "plugins.upsert.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(I=>{var m={handlers:{}},L=(h,u,J=!1)=>new Promise((B,y)=>{var x=(v,F)=>{var n=()=>{v++;v<h.length?x(v,F):F()};(d=>{var a=kb.filter.scan(m.app,u,d.condition.value);a?kb.filter.auth(d.user.value,d.organization.value,d.group.value).then(k=>{k?kb.field.load(d.app.value).then(w=>{var q={id:d.app.value,fields:w.origin};(t=>{var C=[],K=[],M=[],G={},D={table:"",index:g=>D.table&&D.table==g.tableCode?r.progress.record:r.progress.row},r={record:1,row:1,progress:{record:0,row:0}},N=()=>{var g=[],p={field:(e,
c)=>{c=e.tableCode?a[e.tableCode].value.length>c?a[e.tableCode].value[c].value[e.code]:kb.record.create({fields:{empty:e}}).empty:a[e.code];return kb.extend({type:e.type},c)},record:e=>{r.row.each(c=>{var A=(b=>{var l=kb.filter.scan(q,e,b.query);if(!l&&"upsert"==d.pattern.value){for(var f in b.rows)0==kb.filter.result[f].value.length&&(e[f].value.push({value:kb.extend({},b.rows[f])}),kb.filter.result[f]={value:[e[f].value.last()]});l=kb.filter.result}return l})((()=>{var b={rows:{},query:[]};r.progress.row=
c;C.each((l,f)=>{l.external.tableCode&&(l.external.tableCode in b.rows||(b.rows[l.external.tableCode]=kb.record.create(q.fields[l.external.tableCode],!1)),f=p.field(l.internal,D.index(l.internal)),["=","in"].includes(l.operator.trim())&&(b.rows[l.external.tableCode][l.external.code]=z(l.external,f)),b.query.push(kb.filter.query.create(l.external,l.operator,f)))});K.each((l,f)=>{l.field.tableCode&&b.query.push(l.field.code+" "+l.operator+" "+l.value)});b.query=b.query.join(" and ");return b})());A&&
M.each((b,l)=>{b.external.tableCode?b.external.tableCode in G?(e[b.external.tableCode]={value:G[b.external.tableCode]},G[b.external.tableCode].each((f,H)=>{f.value[b.external.code]=z(b.external,p.field(b.internal,H));"FILE"==b.external.type&&f.value[b.external.code].value&&Array.prototype.push.apply(g,f.value[b.external.code].value)})):A[b.external.tableCode].value.each((f,H)=>{f.value[b.external.code]=z(b.external,p.field(b.internal,D.index(b.internal)));"FILE"==b.external.type&&f.value[b.external.code].value&&
Array.prototype.push.apply(g,f.value[b.external.code].value)}):(e[b.external.code]=z(b.external,p.field(b.internal,r.progress.record)),"FILE"==b.external.type&&e[b.external.code].value&&Array.prototype.push.apply(g,e[b.external.code].value))})});return e}},z=(e,c)=>{switch(e.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":Array.isArray(c.value)||(c.value=[c.value])}c.type=e.type;return e.lookup?kb.extend({lookup:!0},c):c},E=
e=>{e.each((c,A)=>{d.formula.value.each((b,l)=>{b.value.field.value in t.external&&(f=>{f.tableCode?c[f.tableCode].value.each((H,O)=>{H.value[f.code].value=kb.formula.calculate(b.value,H.value,c,c,t.external);f.lookup&&(H.value[f.code].lookup=!0)}):(c[f.code].value=kb.formula.calculate(b.value,c,c,c,t.external),f.lookup&&(c[f.code].lookup=!0))})(t.external[b.value.field.value])})});return e};"insert"==d.pattern.value?(e=>{kb.file.clone(g,!0).then(()=>{kb.view.records.set(d.app.value,{post:e},J).then(c=>
{r.progress.record++;r.progress.record<r.record?N():n()}).catch(c=>{kb.alert(kb.error.parse(c));y()})})})(E([p.record(kb.record.create(q))])):kb.view.records.get(d.app.value,(()=>{var e=[];C.each((c,A)=>{c.external.tableCode||e.push(kb.filter.query.create(c.external,c.operator,p.field(c.internal,r.progress.record)))});K.each((c,A)=>{c.field.tableCode||e.push(c.field.code+" "+c.operator+" "+c.value)});return e.join(" and ")})()).then(e=>{e=(c=>{var A=[];0!=c.length?A=c.map(b=>p.record(b)):"upsert"==
d.pattern.value&&(b=>{A.push(p.record((()=>{var l=kb.record.create(q);b.each((f,H)=>{f.external.tableCode?l[f.external.tableCode]={value:[]}:["=","in"].includes(f.operator.trim())&&(l[f.external.code]=z(f.external,p.field(f.internal,r.progress.record)))});return l})()))})(C.filter(b=>!kb.field.reserved.includes(b.external.type)));return E(A)})(e);kb.file.clone(g,!0).then(()=>{kb.view.records.set(d.app.value,{post:e.filter(c=>!c.$id.value),put:e.reduce((c,A)=>{A.$id.value&&c.push(kb.view.records.transform(A));
return c},[])},J).then(c=>{r.progress.record++;r.progress.record<r.record?N():n()}).catch(c=>{kb.alert(kb.error.parse(c));y()})})}).catch(e=>{kb.alert(kb.error.parse(e));y()})};d.mapping.value.some(g=>!(g.value.external.value in t.external&&g.value.internal.value in t.internal))?(kb.alert("No field to transfer was found"),y()):d.criteria.value.some(g=>!(g.value.external.value in t.external&&g.value.internal.value in t.internal))?(kb.alert("No field to transfer was found"),y()):([...d.mapping.value,
...d.criteria.value].each((g,p)=>{p=t.internal[g.value.internal.value];!t.external[g.value.external.value].tableCode&&p.tableCode&&(D.table=p.tableCode,r.record=0==a[p.tableCode].value.length?0:a[p.tableCode].value.length)}),d.mapping.value.each((g,p)=>{((z,E)=>{z.tableCode&&(D.table&&D.table==E.tableCode||(G[z.tableCode]=(e=>{e=e?e.length:1;E.tableCode&&(e=e<a[E.tableCode].value.length?a[E.tableCode].value.length:e);return Array(e).fill().map(()=>({value:kb.record.create(q.fields[z.tableCode],!1)}))})(G[z.tableCode])));
M.push({external:z,internal:E})})(t.external[g.value.external.value],t.internal[g.value.internal.value])}),d.criteria.value.each((g,p)=>{p=t.external[g.value.external.value];var z=g.value.operator.value;g=t.internal[g.value.internal.value];p.tableCode&&(p.tableCode in G&&delete G[p.tableCode],!D.table&&g.tableCode&&(r.row=r.row<a[g.tableCode].value.length?a[g.tableCode].value.length:r.row));C.push({external:p,operator:z,internal:g})}),kb.filter.query.parse.expand({id:d.app.value,fields:w.origin},
d.filter.value).each((g,p)=>{K.push({field:t.external[g.field],operator:g.operator,value:g.value})}),0!=r.record?(r.progress.record=0,r.progress.row=0,N()):n())})({external:w.parallelize,internal:m.fieldInfos.parallelize})}).catch(w=>{kb.alert(kb.error.parse(w));y()}):n()}).catch(k=>{kb.alert(kb.error.parse(k));y()}):n()})(h[v])};J||kb.loadStart();x(0,()=>{J||kb.loadEnd();B()})});kintone.events.on("app.record.create.submit.success app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),
h=>new Promise((u,J)=>{((B,y)=>{m.mobile=B;m.type=y;for(var x in m.handlers)m.handlers[x].each((v,F)=>{kintone.events.off(x,v)});kb.config[I].config.get().then(v=>{0!=Object.keys(v).length?kb.field.load(kb.config[I].app,!0).then(F=>{m.app={id:kb.config[I].app,fields:F.origin};m.fieldInfos=F;try{["detail"].includes(m.type)&&kintone.app.record.getPermissions().then(n=>{n.editRecord&&(d=>{0!=d.length&&((a,k)=>{kintone.events.on(a,k);a.each((w,q)=>{w in m.handlers||(m.handlers[w]=[]);m.handlers[w].push(k)})})(["app.record.detail.process.proceed",
"mobile.app.record.detail.process.proceed"],a=>new Promise((k,w)=>{try{(q=>{0!=q.length?L(q,a.record).then(t=>k(a)).catch(()=>{}):k(a)})(d.filter(q=>q.action.value==a.action.value+":"+a.status.value+":"+a.nextStatus.value))}catch(q){kb.alert(kb.error.parse(q)),k(a)}}))})(JSON.parse(v.tab).map((d,a)=>kb.extend({sIndex:{value:a.toString()}},d.setting)).reduce((d,a)=>{(m.mobile?["all","both","mobile"]:["all","both","pc"]).includes(a.device.value)&&a.event.value.includes("process")&&d.push(a);return d},
[]))}).catch(()=>{}),(n=>{if(0!=n.length)switch(m.type){case "create":case "edit":L(n,h.record).then(a=>u(h)).catch(()=>{});break;case "detail":var d=a=>{(k=>{kb.filter.scan(m.app,h.record,k.condition.value)?kb.filter.auth(k.user.value,k.organization.value,k.group.value).then(w=>{w&&kb.button.create(m.mobile,m.type,"kb-upsert-button"+a.toString(),k.label.value,k.message.value,()=>L([k],h.record).then(q=>kb.alert("Done!")).catch(()=>{}));a++;a<n.length&&d(a)}).catch(w=>{a++;a<n.length&&d(a)}):(a++,
a<n.length&&d(a))})(n[a])};d(0);u(h);break;case "index":d=a=>{(k=>{kb.filter.auth(k.user.value,k.organization.value,k.group.value).then(w=>{w&&(k.view.value&&k.view.value!=h.viewId.toString()||kb.button.create(m.mobile,m.type,"kb-upsert-button"+a.toString(),k.label.value,k.message.value,()=>{kb.view.records.get(m.app.id,(m.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(q=>{let t=(C,K)=>{L([k],q[C],!0).then(M=>{kb.progressUpdate();C++;C<q.length?t(C,K):K()}).catch(()=>{})};0!=q.length?
(kb.progressStart(q.length),t(0,()=>kb.alert("Done!"))):kb.alert("There are no records.")}).catch(q=>kb.alert(kb.error.parse(q)))}));a++;a<n.length&&d(a)}).catch(w=>{a++;a<n.length&&d(a)})})(n[a])},d(0),u(h)}else u(h)})(JSON.parse(v.tab).map((n,d)=>kb.extend({sIndex:{value:d.toString()}},n.setting)).reduce((n,d)=>{(m.mobile?["all","both","mobile"]:["all","both","pc"]).includes(d.device.value)&&d.event.value.includes(m.type)&&n.push(d);return n},[]))}catch(n){kb.alert(kb.error.parse(n)),u(h)}}).catch(F=>
u(h)):u(h)}).catch(v=>u(h))})("mobile"==h.type.split(".").first(),(B=>{switch(B){case "submit":B=h.type.split(".").slice(-3).first()}return B})(h.type.split(".").slice(-2).first()))}));kb.event.on("kb.upsert.call",h=>new Promise((u,J)=>{kb.config[I].config.get().then(B=>{0!=Object.keys(B).length?kb.field.load(kb.config[I].app,!0).then(y=>{m.app={id:kb.config[I].app,fields:y.origin};m.fieldInfos=y;try{(x=>{0!=x.length?L(x,h.record,!0).then(v=>u(h)).catch(()=>u(h)):u(h)})(JSON.parse(B.tab).map((x,v)=>
kb.extend({sIndex:{value:v.toString()}},x.setting)).reduce((x,v)=>{(h.mobile?["all","both","mobile"]:["all","both","pc"]).includes(v.device.value)&&v.event.value.includes(h.pattern)&&x.push(v);return x},[]))}catch(x){kb.alert(kb.error.parse(x)),u(h)}}).catch(y=>u(h)):u(h)}).catch(B=>u(h))}))})(kintone.$PLUGIN_ID);
