/*
* FileName "plugins.mail.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(z=>{var c={handlers:{}},C=(e,n,D=!1)=>new Promise((x,v)=>{var u="",r=(w,g)=>{var m=()=>{w++;w<e.length?r(w,g):g()};(a=>{var b=kb.filter.scan(c.app,n,a.condition.value);b?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(d=>{if(d){var q=(k,t,f)=>{"HTML"==a.format.value&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var h in t){var l=t[h].value;h in c.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[h].type&&(l=l.replace(/\r/g,"").replace(/\n/g,
"<br>")),k=k.replace(new RegExp("%"+h+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[h],l," / ",!0)))}for(h in f)l=f[h].value,h in c.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[h].type&&(l=l.replace(/\r/g,"").replace(/\n/g,"<br>")),k=k.replace(new RegExp("%"+h+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[h],l," / ",!0)));return k};(k=>{var t=(f,h)=>{(l=>{var B=(p,y)=>{if(0!=l.attachment.length){var E=!1;window.hasOwnProperty("kb_report_temp")&&
l.attachment[p].fileKey in window.kb_report_temp&&(E=!0);E?(l.attachment[p].data=window.kb_report_temp[l.attachment[p].fileKey],p++,p<l.attachment.length?B(p,y):y()):kb.file.download(l.attachment[p],!0).then(A=>{kb.field.blobToBase64(A,G=>{l.attachment[p].data=G;p++;p<l.attachment.length?B(p,y):y()})}).catch(A=>{kb.alert(kb.error.parse(A));v()})}else y()};B(0,()=>{kb.encrypt(JSON.stringify(l.data),u).then(p=>{var y=fetch,E="https://api.kintone-booster.com/mail/"+kb.operator.language,A=JSON,G=A.stringify;
l.data=p.data;l.iv=p.iv;l.tag=p.tag;y(E,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:G.call(A,l)}).then(F=>{F.json().then(H=>{switch(F.status){case 200:f++;f<k.length?t(f,h):h();break;default:kb.alert(kb.error.parse(H)),v()}})}).catch(F=>{kb.alert(kb.error.parse(F));v()})}).catch(p=>{v()})})})(k[f])};0!=k.length?t(0,()=>{try{a.formula.value.map(f=>f.value).each((f,h)=>{f.field.value in c.fieldInfos.parallelize&&(h=c.fieldInfos.parallelize[f.field.value],h.tableCode||(b[h.code].value=
kb.formula.calculate(f,b,b,n,c.fieldInfos.parallelize),h.lookup&&(b[h.code].lookup=!0),f=b.$id.value,f in c.formulaRecords||(c.formulaRecords[f]={$id:{value:f}}),c.formulaRecords[f][h.code]=b[h.code]))}),m()}catch(f){kb.alert(kb.error.parse(f)),v()}}):m()})((()=>{var k=[];(c.fieldInfos.parallelize[a.to.value].tableCode?b[c.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:b}]).each((t,f)=>{if(t.value[a.to.value].value){f=k.push;var h={mail:a.mail.value,sender:a.sender.value,host:a.host.value,
port:a.port.value,author:a.author.value,pwd:a.pwd.value,secure:a.secure.value,to:t.value[a.to.value].value,cc:q(a.cc.value,b,c.fieldInfos.parallelize[a.to.value].tableCode?t.value:{}),bcc:q(a.bcc.value,b,c.fieldInfos.parallelize[a.to.value].tableCode?t.value:{}),html:"HTML"==a.format.value},l=q(a.subject.value,b,c.fieldInfos.parallelize[a.to.value].tableCode?t.value:{}),B=q(a.body.value,b,c.fieldInfos.parallelize[a.to.value].tableCode?t.value:{}),p=[];a.attachment.value&&a.attachment.value in c.fieldInfos.parallelize&&
(p=(c.fieldInfos.parallelize[a.attachment.value].tableCode?t.value:b)[a.attachment.value].value);f.call(k,{data:h,subject:l,body:B,attachment:p})}});return k})())}else m()}).catch(d=>{kb.alert(kb.error.parse(d));v()}):m()})(e[w])};fetch("https://api.kintone-booster.com/mail/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(w=>{w.json().then(g=>{switch(w.status){case 200:u=g.passphrase;D||kb.loadStart();r(0,()=>{D||kb.loadEnd();x()});break;default:kb.alert(kb.error.parse(g)),
v()}})}).catch(w=>{kb.alert(kb.error.parse(w));v()})});kintone.events.on("app.record.create.submit.success app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),e=>new Promise((n,D)=>{((x,v)=>{c.mobile=x;c.type=v;for(var u in c.handlers)c.handlers[u].each((r,w)=>{kintone.events.off(u,r)});kb.config[z].config.get().then(r=>{0!=Object.keys(r).length?
kb.field.load(kb.config[z].app,!0).then(w=>{c.app={id:kb.config[z].app,fields:w.origin};c.fieldInfos=w;c.formulaRecords={};try{["detail"].includes(c.type)&&kintone.app.record.getPermissions().then(g=>{g.editRecord&&(m=>{0!=m.length&&((a,b)=>{kintone.events.on(a,b);a.each((d,q)=>{d in c.handlers||(c.handlers[d]=[]);c.handlers[d].push(b)})})(["app.record.detail.process.proceed","mobile.app.record.detail.process.proceed"],a=>new Promise((b,d)=>{try{(q=>{0!=q.length?C(q,a.record).then(k=>b(a)).catch(()=>
{}):b(a)})(m.filter(q=>q.action.value==a.action.value+":"+a.status.value+":"+a.nextStatus.value))}catch(q){kb.alert(kb.error.parse(q)),b(a)}}))})(JSON.parse(r.tab).map((m,a)=>kb.extend({sIndex:{value:a.toString()}},m.setting)).reduce((m,a)=>{(c.mobile?["all","both","mobile"]:["all","both","pc"]).includes(a.device.value)&&a.event.value.includes("process")&&m.push(a);return m},[]))}).catch(()=>{}),(g=>{if(0!=g.length){var m=b=>{0!=Object.keys(c.formulaRecords).length?kb.view.records.set(c.app.id,{put:Object.values(c.formulaRecords).map(d=>
kb.view.records.transform(d))},!1).then(d=>b()).catch(d=>kb.alert(kb.error.parse(d))):b()};"formula"in g.first()||(kb.alert(kb.error.config.update("Boost! Mail")),g=g.map(b=>{b.formula={value:[]};return b}));switch(c.type){case "create":case "edit":C(g,e.record).then(b=>m(()=>n(e))).catch(()=>{});break;case "detail":var a=b=>{(d=>{kb.filter.scan(c.app,e.record,d.condition.value)?kb.filter.auth(d.user.value,d.organization.value,d.group.value).then(q=>{q&&kb.button.create(c.mobile,c.type,"kb-mail-button"+
b.toString(),d.label.value,d.message.value,()=>C([d],e.record).then(k=>m(()=>kb.alert("Done!",()=>window.location.reload(!0)))).catch(()=>{}));b++;b<g.length&&a(b)}).catch(q=>{b++;b<g.length&&a(b)}):(b++,b<g.length&&a(b))})(g[b])};a(0);n(e);break;case "index":a=b=>{(d=>{kb.filter.auth(d.user.value,d.organization.value,d.group.value).then(q=>{q&&(d.view.value&&d.view.value!=e.viewId.toString()||kb.button.create(c.mobile,c.type,"kb-mail-button"+b.toString(),d.label.value,d.message.value,()=>{kb.view.records.get(c.app.id,
(c.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(k=>{let t=(f,h)=>{C([d],k[f],!0).then(l=>{kb.progressUpdate();f++;f<k.length?t(f,h):h()}).catch(()=>{})};0!=k.length?(kb.progressStart(k.length),t(0,()=>m(()=>kb.alert("Done!",()=>window.location.reload(!0))))):kb.alert("There are no records.")}).catch(k=>kb.alert(kb.error.parse(k)))}));b++;b<g.length&&a(b)}).catch(q=>{b++;b<g.length&&a(b)})})(g[b])},a(0),n(e)}}else n(e)})(JSON.parse(r.tab).map((g,m)=>kb.extend({sIndex:{value:m.toString()}},
g.setting)).reduce((g,m)=>{(c.mobile?["all","both","mobile"]:["all","both","pc"]).includes(m.device.value)&&m.event.value.includes(c.type)&&g.push(m);return g},[]))}catch(g){kb.alert(kb.error.parse(g)),n(e)}}).catch(w=>n(e)):n(e)}).catch(r=>n(e))})("mobile"==e.type.split(".").first(),(x=>{switch(x){case "submit":x=e.type.split(".").slice(-3).first()}return x})(e.type.split(".").slice(-2).first()))}));kb.event.on("kb.mail.call",e=>new Promise((n,D)=>{kb.config[z].config.get().then(x=>{0!=Object.keys(x).length?
kb.field.load(kb.config[z].app,!0).then(v=>{c.app={id:kb.config[z].app,fields:v.origin};c.fieldInfos=v;try{(u=>{0!=u.length?C(u,e.record,!0).then(r=>n(e)).catch(()=>n(e)):n(e)})(JSON.parse(x.tab).map((u,r)=>kb.extend({sIndex:{value:r.toString()}},u.setting)).reduce((u,r)=>{(e.mobile?["all","both","mobile"]:["all","both","pc"]).includes(r.device.value)&&r.event.value.includes(e.pattern)&&u.push(r);return u},[]))}catch(u){kb.alert(kb.error.parse(u)),n(e)}}).catch(v=>n(e)):n(e)}).catch(x=>n(e))}))})(kintone.$PLUGIN_ID);
