/*
* FileName "plugins.decoder.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(B=>{var a={guideMargin:.15,lastCode:null,matchCount:0,reader:null,requestId:null,video:null,observers:[]},F=d=>{var k=a.video.getBoundingClientRect(),l=a.video.video.getBoundingClientRect();if(!l.width||!l.height)return null;var c=a.video.video.videoWidth,g=a.video.video.videoHeight;if(!c||!g)return null;var b=Math.min(l.width/c,l.height/g),n=c*b;b*=g;var h="qrcode"==d?Math.min(n,b)*(1-2*a.guideMargin):n*(1-2*a.guideMargin);d="qrcode"==d?h:Math.min(b,Math.max(100,.25*b));var m=(n-h)/2,w=(b-d)/2;
a.video.guide.css({height:d+"px",left:l.left-k.left+(l.width-n)/2+m+"px",top:l.top-k.top+(l.height-b)/2+w+"px",width:h+"px"});return{sx:m/n*c,sy:w/b*g,sw:h/n*c,sh:d/b*g}},D=(d,k,l)=>{a.video.video.autoplay&&setTimeout(()=>{a.video.video.autoplay&&a.video.video.srcObject&&((c,g)=>{try{var b=F(d)||{sx:0,sy:0,sw:a.video.video.videoWidth,sh:a.video.video.videoHeight},n=m=>{try{return(new TextDecoder("utf-8",{fatal:!0})).decode(m)}catch(w){return(new TextDecoder("shift_jis")).decode(m)}};c.width=b.sw;
c.height=b.sh;if(c.width&&c.height)if(c.getContext("2d").drawImage(a.video.video,b.sx,b.sy,b.sw,b.sh,0,0,b.sw,b.sh),"qrcode"==d){var h=jsQR(c.getContext("2d").getImageData(0,0,c.width,c.height).data,c.width,c.height);h?g(h.binaryData?n(new Uint8Array(h.binaryData)):h.data):g(null)}else Quagga.decodeSingle({locator:{patchSize:"medium",halfSample:!1},decoder:{readers:[k.readers]},numOfWorkers:0,locate:!1,src:c.toDataURL("image/png")},m=>g(m&&m.codeResult?m.codeResult.code:null));else g(null)}catch{g(null)}})(bst.create("canvas"),
c=>{if(c&&c==a.lastCode){if(a.matchCount++,1<a.matchCount){l(c);return}}else a.lastCode=c,a.matchCount=c?1:0;D(d,k,l)})},250)},G=(d,k,l)=>{(c=>{c.observe(bst.elm(".subtable-"+d.id+(a.mobile?"":" tbody")),{childList:!0,subtree:!1});(g=>{bst.elms(g).length==k[d.code].value.length&&l.each((b,n)=>b({record:k}))})(".subtable-"+d.id+(a.mobile?" .subtable-row-gaia":" tbody tr"));a.observers.push(c)})(new MutationObserver(()=>{l.each((c,g)=>c({record:k}))}))},z=()=>{a.requestId=null;a.video.video.srcObject&&
a.video.video.srcObject.getTracks().forEach(d=>d.stop());a.video.video.autoplay=!1;a.video.video.srcObject=null};kintone.events.on(["app.record.create.show","app.record.edit.show","mobile.app.record.create.show","mobile.app.record.edit.show"],d=>new Promise((k,l)=>{((c,g)=>{a.mobile=c;a.type=g;a.video=(b=>{b.guide=bst.create("div").css({boxSizing:"border-box",border:"1px solid #ffc107",pointerEvents:"none",position:"absolute"});b.video=bst.create("video").attr("muted","muted").attr("playsinline",
"playsinline").css({boxSizing:"border-box",height:"100%",objectFit:"contain",width:"100%"});return b.append(b.video).append(b.guide)})(bst.create("div").css({boxSizing:"border-box",height:"100%",position:"relative",width:"100%"}));a.reader=a.video.popup("full","full",[],z);a.observers.each((b,n)=>b.disconnect());a.observers=[];bst.config[B].config.get().then(b=>{0!=Object.keys(b).length?bst.field.load(bst.config[B].app,!0).then(n=>{a.app={id:bst.config[B].app,fields:n.origin};a.fieldInfos=n;try{(h=>
{var m={};h=[...h.barcode.value.map(e=>{e.value.type={value:"barcode"};return e.value}),...h.qrcode.value.map(e=>{e.value.type={value:"qrcode"};return e.value})].reduce((e,u)=>{u.field.value in a.fieldInfos.parallelize&&(e[u.field.value]={fieldInfo:a.fieldInfos.parallelize[u.field.value],format:"format"in u?u.format.value:"",type:u.type.value});return e},{});bst.event.off("bst.decoder.call");Object.values(h).each((e,u)=>{(A=>{if(e.fieldInfo.tableCode){var q=a.fieldInfos.tables[e.fieldInfo.tableCode];
q.code in m||(m[q.code]=[]);m[q.code].push(A);a.mobile&&A({record:d.record})}else A({record:d.record})})(A=>{((q,x)=>{q&&(Array.isArray(q)?q:[q]).each((f,H)=>{f.value.parentNode.elm(".bst-decoder-operation")||(x(f,f.value,a.mobile?f.value:f.value.elm("input[type=text]")),e.fieldInfo.lookup&&(f.nextSibling&&f.nextSibling.tagName.toLowerCase().startsWith("kuc")&&(p=>{p&&x(f,a.mobile?p:p.parentNode,p)})(f.nextSibling.elm("input[type=text]")),bst.event.on("bst.decoder.call",p=>{if(p.field==f&&f.nextSibling&&
f.nextSibling.tagName.toLowerCase().startsWith("kuc")&&!f.nextSibling.elm(".bst-decoder-operation")){var r=f.nextSibling.elm("input[type=text]");x(f,a.mobile?r:r.parentNode,r)}return p})))})})(bst.field.get(e.fieldInfo,a.mobile,a.type),(q,x,f)=>{x.parentNode.css(a.mobile?{alignItems:"center"}:{alignItems:"center",display:"flex"}).insertBefore(bst.create("button").addClass("bst-icon bst-icon-camera bst-decoder-operation"+(a.mobile?" bst-mobile":"")).on("click",H=>{const p=Symbol();a.requestId=p;a.video.video.autoplay=
!0;a.video.video.muted=!0;navigator.mediaDevices.getUserMedia({audio:!1,video:{facingMode:{ideal:"environment"}}}).then(r=>{a.requestId!==p?r.getTracks().forEach(v=>v.stop()):(a.video.video.srcObject=r,a.video.video.play().then(()=>{a.requestId!==p?r.getTracks().forEach(v=>v.stop()):(a.lastCode="",a.matchCount=0,a.reader.show(),D(e.type,{readers:e.format},v=>{a.reader.hide();z();((C,E)=>{bst.event.call("bst.action.call",{container:bst.elm("body"),record:(t=>{var y={};e.fieldInfo.tableCode?(y[e.fieldInfo.tableCode]=
t[e.fieldInfo.tableCode],y[e.fieldInfo.tableCode].value[C.indexOf(q)].value[e.fieldInfo.code]=E):y[e.fieldInfo.code]=E;return y})((a.mobile?kintone.mobile.app.record:kintone.app.record).get().record),mobile:a.mobile,pattern:"change",fields:[e.fieldInfo.code],stopPropagation:!0,workplace:"record"}).then(t=>{bst.event.call("bst.style.call",{container:t.container,record:t.record,mobile:t.mobile,pattern:"$id"in t.record?t.record.$id.value?"edit":"create":"create",workplace:t.workplace}).then(y=>{bst.event.call("bst.cascade.call",
y).then(I=>{(a.mobile?kintone.mobile.app.record:kintone.app.record).set({record:I.record})}).catch(()=>{})}).catch(()=>{})}).catch(()=>{})})(bst.field.get(e.fieldInfo,a.mobile,a.type),bst.extend({type:e.fieldInfo.type,value:v},e.fieldInfo.lookup?{lookup:"UPDATE"}:{}))}))}).catch(v=>{r.getTracks().forEach(C=>C.stop());a.requestId===p&&(a.reader.hide(),z(),bst.alert(bst.error.parse(v)))}))}).catch(r=>{a.requestId===p&&(a.reader.hide(),z(),bst.alert(bst.error.parse(r)))})}),x.nextSibling);a.mobile&&
f.addClass("bst-decoder-operation-input bst-mobile")})})});for(var w in m)G(a.fieldInfos.tables[w],d.record,m[w])})(JSON.parse(b.flat)),k(d)}catch(h){bst.alert(bst.error.parse(h)),k(d)}}).catch(n=>k(d)):k(d)}).catch(b=>k(d))})("mobile"==d.type.split(".").first(),d.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
