/*
* FileName "plugins.report.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(E=>{var e={},H=(b,c,G=!1)=>new Promise((x,v)=>{var p=(h,f)=>{var l=()=>{h++;h<b.length?p(h,f):f()};(a=>{bst.filter.scan(e.app,c,a.condition.value)?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(m=>{if(m)if(a.attachment.value in e.fieldInfos.origin){var y=Object.values(e.fieldInfos.tables).reduce((n,B)=>{Object.values(B.fields).each((C,k)=>{n[C.code]={index:-1,limit:c[B.code].value.length,status:0==c[B.code].value.length?"complete":"ready",table:B.code}});return n},{});(n=>
{if(0!=n.sheets.length){var B=(k,t,z)=>{(u=>{var g=!1,A=bst.extend({},u),D;for(D in e.fieldInfos.parallelize)(d=>{u.cells.each((F,K)=>{F.each((q,L)=>{if(q.value.match(new RegExp("%"+d.code+"%")))switch(d.type){case "FILE":(r=>{Array.isArray(r)?(w=>{if(w){q.type="image";var M=u.rows.slice(K,K+parseInt(q.rowSpan||"1")).reduce((I,J)=>I+=J.origin,0),N=u.cols.slice(L,L+parseInt(q.colSpan||"1")).reduce((I,J)=>I+=J.origin,0);t.push({cell:q,fileKey:w.fileKey,size:{height:M,width:N}});g=!0}else q.value=""})(r.find(w=>
w.contentType.match(/image/g))):q.value=""})((()=>{var r=null;if(d.code in y){var w=y[d.code];"complete"!=w.status&&(w.index++,w.status=w.index==w.limit-1?"complete":"processing",r=c[w.table].value[w.index].value[d.code].value)}else r=c[d.code].value;return r})());break;default:d.code in y?(r=>{"complete"!=r.status?(r.index++,r.status=r.index==r.limit-1?"complete":"processing",q.value=q.value.replace(new RegExp("%"+d.code+"%","g"),q.value.match(/^=(TODAY|DATE_FORMAT)/)?JSON.stringify(c[r.table].value[r.index].value[d.code].value):
bst.field.stringify(d,c[r.table].value[r.index].value[d.code].value," / ",!0)),g=!0):q.value=q.value.match(/^=(TODAY|DATE_FORMAT)/)?"":q.value.replace(new RegExp("%"+d.code+"%","g"),"")})(y[d.code]):(q.value=q.value.replace(new RegExp("%"+d.code+"%","g"),q.value.match(/^=(TODAY|DATE_FORMAT)/)?JSON.stringify(c[d.code].value):bst.field.stringify(d,c[d.code].value," / ",!0)),g=!0)}})})})(e.fieldInfos.parallelize[D]);u.cells.each(d=>{d.each(F=>{F.value.match(/^=(TODAY|DATE_FORMAT)/)&&(F.value=eval(F.value.replace(/^=/,
"").replace(/\b(TODAY|DATE_FORMAT)\(/g,"bst.formula.report.$1(")))})});u.repeat&&(Object.values(y).some(d=>"processing"==d.status)?n.sheets.splice(k+1,0,A):g||(n.sheets.splice(k,1),k--));k++;k<n.sheets.length?B(k,t,z):z(t)})(n.sheets[k])},C=(k,t,z)=>{0!=t.length?bst.file.download(t[k],!0).then(u=>{var g=new Image;g.onload=()=>{var A=Math.min(t[k].size.width/g.width,t[k].size.height/g.height),D=Math.round(g.height*A);A=Math.round(g.width*A);var d=bst.create("canvas");d.width=A;d.height=D;d.getContext("2d").drawImage(g,
0,0,A,D);t[k].cell.value=d.toDataURL("image/png");k++;k<t.length?C(k,t,z):z()};g.src=URL.createObjectURL(u)}).catch(u=>bst.alert(bst.error.parse(u),()=>v())):z()};B(0,[],k=>{C(0,k,()=>{(t=>{fetch("https://api.pandafirm.jp/layup/report",{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({lang:bst.operator.language,name:t,datas:n})}).then(z=>{z.json().then(u=>{switch(z.status){case 200:bst.file.upload((g=>{var A=atob(g.binary),D=new Uint8Array(A.length);A.length.each(d=>
D[d]=A.charCodeAt(d));return new File([new Blob([D.buffer],{type:g.contentType})],g.filename,{type:g.contentType})})(u.file),!0).then(g=>{window.hasOwnProperty("bst_report_temp")||(window.bst_report_temp={});window.bst_report_temp[g.fileKey]=u.file.binary;c[a.attachment.value].value.push(g);l()}).catch(g=>{bst.alert(bst.error.parse(g),()=>v())});break;default:bst.alert(bst.error.parse(u),()=>v())}})}).catch(z=>bst.alert(bst.error.parse(z),()=>v()))})((a.name.value in e.fieldInfos.origin?c[a.name.value].value:
"")||"report")})})}else l()})(a.template.value?JSON.parse(a.template.value):{sheets:[]})}else l();else l()}).catch(m=>bst.alert(bst.error.parse(m),()=>v())):l()})(b[h])};G||bst.loadStart();p(0,()=>{bst.view.records.set(e.app.id,{put:[bst.view.records.transform(b.reduce((h,f)=>{f.attachment.value in e.fieldInfos.origin&&(h[f.attachment.value]=c[f.attachment.value]);return h},{$id:c.$id}))]},!0).then(h=>{G||bst.loadEnd();x()}).catch(h=>bst.alert(bst.error.parse(h),()=>v()))})});kintone.events.on("app.record.create.submit.success app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),
b=>new Promise((c,G)=>{((x,v)=>{e.mobile=x;e.type=v;bst.config[E].config.get().then(p=>{0!=Object.keys(p).length?bst.field.load(bst.config[E].app,!0).then(h=>{e.app={id:bst.config[E].app,fields:h.origin};e.fieldInfos=h;try{(f=>{if(0!=f.length)switch(e.type){case "create":case "edit":H(f,b.record).then(a=>c(b)).catch(()=>c(b));break;case "detail":var l=a=>{(m=>{bst.filter.scan(e.app,b.record,m.condition.value)?bst.filter.auth(m.user.value,m.organization.value,m.group.value).then(y=>{y&&bst.button.create(e.mobile,
e.type,"bst-report-button"+a.toString(),m.label.value,m.message.value,()=>H([m],b.record).then(n=>bst.alert("Done!",()=>window.location.reload(!0))).catch(()=>{}));a++;a<f.length&&l(a)}).catch(y=>{a++;a<f.length&&l(a)}):(a++,a<f.length&&l(a))})(f[a])};l(0);c(b);break;case "index":l=a=>{(m=>{bst.filter.auth(m.user.value,m.organization.value,m.group.value).then(y=>{y&&(m.view.value&&m.view.value!=b.viewId.toString()||bst.button.create(e.mobile,e.type,"bst-report-button"+a.toString(),m.label.value,m.message.value,
()=>{bst.view.records.get(e.app.id,(e.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(n=>{let B=(C,k)=>{H([m],n[C],!0).then(t=>{bst.progressUpdate();C++;C<n.length?B(C,k):k()}).catch(()=>{})};0!=n.length?(bst.progressStart(n.length),B(0,()=>bst.alert("Done!",()=>window.location.reload(!0)))):bst.alert("There are no records.")}).catch(n=>bst.alert(bst.error.parse(n)))}));a++;a<f.length&&l(a)}).catch(y=>{a++;a<f.length&&l(a)})})(f[a])},l(0),c(b)}else c(b)})(JSON.parse(p.tab).map((f,
l)=>bst.extend({sIndex:{value:l.toString()}},f.setting)).reduce((f,l)=>{(e.mobile?["all","both","mobile"]:["all","both","pc"]).includes(l.device.value)&&l.event.value.includes(e.type)&&f.push(l);return f},[]))}catch(f){bst.alert(bst.error.parse(f),()=>c(b))}}).catch(h=>c(b)):c(b)}).catch(p=>c(b))})("mobile"==b.type.split(".").first(),(x=>{switch(x){case "submit":x=b.type.split(".").slice(-3).first()}return x})(b.type.split(".").slice(-2).first()))}));bst.event.on("bst.report.call",b=>new Promise((c,
G)=>{bst.config[E].config.get().then(x=>{0!=Object.keys(x).length?bst.field.load(bst.config[E].app,!0).then(v=>{e.app={id:bst.config[E].app,fields:v.origin};e.fieldInfos=v;try{(p=>{0!=p.length?H(p,b.record,!0).then(h=>c(b)).catch(()=>c(b)):c(b)})(JSON.parse(x.tab).map((p,h)=>bst.extend({sIndex:{value:h.toString()}},p.setting)).reduce((p,h)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(h.device.value)&&h.event.value.includes(b.pattern)&&p.push(h);return p},[]))}catch(p){bst.alert(bst.error.parse(p),
()=>c(b))}}).catch(v=>c(b)):c(b)}).catch(x=>c(b))}))})(kintone.$PLUGIN_ID);
