/*
* FileName "plugins.linkage.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(L=>{var d={handlers:{},stats:{}},O=(t,C)=>new Promise((M,J)=>{bst.field.load(t.app.value).then(z=>{(D=>{t.criteria.value.some(p=>!(p.value.external.value in D.external&&p.value.internal.value in D.internal))?(bst.alert("No field to linkage was found"),J()):t.mapping.value.some(p=>!(p.value.external.value in D.external))?(bst.alert("No field to linkage was found"),J()):(p=>{p.api=p.api.join(" and ");p.url=p.url.join(" and ");bst.view.records.get(t.app.value,p.api).then(u=>{0!=u.length?((r,w,E)=>{M((A=>
{A.records.sort((l,f)=>{var m=0;t.sort.value.filter(g=>g.value.field.value in z.parallelize).each((g,b)=>{switch(z.parallelize[g.value.field.value].type){case "CALC":switch(z.parallelize[g.value.field.value].format){case "NUMBER":case "NUMBER_DIGIT":b=l[g.value.field.value].value?parseFloat(l[g.value.field.value].value):0;var k=f[g.value.field.value].value?parseFloat(f[g.value.field.value].value):0;break;default:b=l[g.value.field.value].value,k=f[g.value.field.value].value}break;case "CATEGORY":case "CHECK_BOX":case "CREATOR":case "FILE":case "GROUP_SELECT":case "MODIFIER":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "STATUS_ASSIGNEE":case "USER_SELECT":b=
JSON.stringify(l[g.value.field.value].value);k=JSON.stringify(f[g.value.field.value].value);break;case "NUMBER":b=l[g.value.field.value].value?parseFloat(l[g.value.field.value].value):0;k=f[g.value.field.value].value?parseFloat(f[g.value.field.value].value):0;break;default:b=l[g.value.field.value].value,k=f[g.value.field.value].value}switch(g.value.order.value){case "asc":b>k&&(m=1);b<k&&(m=-1);break;case "desc":b>k&&(m=-1),b<k&&(m=1)}if(m)return BST_BREAK});return m});return A})(r.reduce((A,l)=>
{Array(E?l[E].value.length:1).fill().map(()=>({})).each((f,m)=>{f.$id=l.$id;for(var g in z.parallelize)z.parallelize[g].tableCode?z.parallelize[g].tableCode==E&&(f[g]=l[E].value[m].value[g]):"$rowId"!=g?f[g]=l[g]:f.$rowId=E?{value:l[E].value[m].id}:{value:""};A.records.push(f)});return A},{offset:0,origin:w,query:p.url,records:[]})))})(u.reduce((r,w)=>{(w=bst.filter.scan({fields:z.origin},w,p.api))&&r.push(w);return r},[]),u,Array.from(new Set(t.mapping.value.map(r=>z.parallelize[r.value.external.value].tableCode))).join("")):
M({offset:0,records:[]})}).catch(u=>{bst.alert(bst.error.parse(u));J()})})(t.criteria.value.reduce((p,u)=>{p.api.push(bst.filter.query.create(D.external[u.value.external.value],u.value.operator.value,C[u.value.internal.value]));D.external[u.value.external.value].tableCode||p.url.push(p.api.last());return p},bst.filter.query.parse.expand({id:t.app.value,fields:z.origin},t.filter.value).reduce((p,u)=>{p.api.push(u.field+" "+u.operator+" "+u.value);D.external[u.field].tableCode||p.url.push(p.api.last());
return p},{api:[],url:[]})))})({external:z.parallelize,internal:d.fieldInfos.parallelize})}).catch(z=>{bst.alert(bst.error.parse(z));J()})});kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.index.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show mobile.app.record.index.show".split(" "),t=>new Promise((C,M)=>{((J,z)=>{d.mobile=J;d.type=z;for(var D in d.handlers)d.handlers[D].each((p,u)=>{kintone.events.off(D,
p)});bst.config[L].config.get().then(p=>{0!=Object.keys(p).length?bst.field.load(bst.config[L].app,!0).then(u=>{d.app={id:bst.config[L].app,fields:u.origin};d.fieldInfos=u;d.stats={};try{(r=>{if(0!=r.length){var w=(l,f,m,g)=>{var b=l.mapping.value.reduce((c,e)=>{if(e.value.external.value in f.parallelize)switch(f.parallelize[e.value.external.value].type){case "CALC":switch(f.parallelize[e.value.external.value].format){case "DATE":case "DATETIME":c[e.value.external.value]={max:"",min:""};break;case "NUMBER":case "NUMBER_DIGIT":c[e.value.external.value]=
{count:0,sum:"",avg:"",max:"",min:""}}break;case "CREATED_TIME":case "DATE":case "DATETIME":case "UPDATED_TIME":c[e.value.external.value]={max:"",min:""};break;case "NUMBER":c[e.value.external.value]={count:0,sum:"",avg:"",max:"",min:""}}return c},{});g.each((c,e)=>{for(var a in c)if(a in f.parallelize)switch(f.parallelize[a].type){case "CALC":switch(f.parallelize[a].format){case "DATE":case "DATETIME":if(a in b&&c[a].value){if(!b[a].max||c[a].value>b[a].max)b[a].max=c[a].value;if(!b[a].min||c[a].value<
b[a].min)b[a].min=c[a].value}break;case "NUMBER":case "NUMBER_DIGIT":if(a in b&&bst.isNumeric(c[a].value)){if(!bst.isNumeric(b[a].max)||Number(c[a].value)>b[a].max)b[a].max=Number(c[a].value);if(!bst.isNumeric(b[a].min)||Number(c[a].value)<b[a].min)b[a].min=Number(c[a].value);bst.isNumeric(b[a].sum)||(b[a].sum=0);b[a].sum+=Number(c[a].value);b[a].count++}}break;case "CREATED_TIME":case "DATE":case "DATETIME":case "UPDATED_TIME":if(a in b&&c[a].value){if(!b[a].max||c[a].value>b[a].max)b[a].max=c[a].value;
if(!b[a].min||c[a].value<b[a].min)b[a].min=c[a].value}break;case "NUMBER":if(a in b&&bst.isNumeric(c[a].value)){if(!bst.isNumeric(b[a].max)||Number(c[a].value)>b[a].max)b[a].max=Number(c[a].value);if(!bst.isNumeric(b[a].min)||Number(c[a].value)<b[a].min)b[a].min=Number(c[a].value);bst.isNumeric(b[a].sum)||(b[a].sum=0);b[a].sum+=Number(c[a].value);b[a].count++}}});for(var k in b)b[k].count&&(b[k].avg=b[k].sum/b[k].count),l.mapping.value.each((c,e)=>{if(c.value.external.value==k){c=JSON.parse(c.value.stats.value||
"{}");for(var a in c)e=c[a],e.value in d.fieldInfos.origin&&(m[e.value]={type:d.fieldInfos.origin[e.value].type,value:d.stats[e.value].value=b[k][a]})}});switch(d.type){case "create":case "edit":(c=>{try{c()}catch(a){var e=setInterval(()=>{try{c(),clearInterval(e)}catch(x){}},500)}})(()=>{0!=Object.keys(m).length&&(d.mobile?kintone.mobile.app.record:kintone.app.record).set({record:m})});break;case "detail":for(k in m)(c=>{var e=bst.field.stringify(c,m[k].value," / ");d.mobile?bst.field.get(c,d.mobile,
d.type).value.html(e):bst.field.get(c,d.mobile,d.type).value.elm("span").html(e)})(d.fieldInfos.parallelize[k])}},E=(l,f,m)=>{var g=(b=>Array.from(new Set(b.map(k=>d.fieldInfos.parallelize[k.value.internal.value].tableCode))).reduce((k,c)=>{f[c].value=[];k[c]={fields:b.filter(e=>d.fieldInfos.parallelize[e.value.internal.value].tableCode==c),row:bst.record.create(d.fieldInfos.origin[c],!1)};return k},{}))(l.mapping.value.reduce((b,k)=>{k.value.internal.value in d.fieldInfos.parallelize&&b.push(k);
return b},[]));m.each((b,k)=>{for(var c in g)f[c].value.push((e=>{g[c].fields.each((a,x)=>{a.value.internal.value in d.fieldInfos.parallelize&&(e[a.value.internal.value].value=b[a.value.external.value].value,d.fieldInfos.parallelize[a.value.internal.value].lookup&&(e[a.value.internal.value].lookup=!0))});return{value:e}})(bst.extend({},g[c].row)))});return f};r.each((l,f)=>{l.mapping.value.each((m,g)=>{m=JSON.parse(m.value.stats.value||"{}");for(var b in m)((k,c)=>{c.value in d.fieldInfos.origin&&
(c.value in d.stats||((e,a)=>{kintone.events.on(e,a);e.each((x,G)=>{x in d.handlers||(d.handlers[x]=[]);d.handlers[x].push(a)})})(["app.record.create.change."+c.value,"app.record.edit.change."+c.value,"mobile.app.record.create.change."+c.value,"mobile.app.record.edit.change."+c.value],e=>{e.record[c.value].value!=d.stats[c.value].value&&(e.record[c.value].value=d.stats[c.value].value);return e}),d.stats[c.value]={value:""})})(b,m[b])})});d.mobile&&bst.elm("body").addClass("bst-mobile");switch(d.type){case "create":case "edit":case "detail":var A=
l=>{(f=>{(m=>{m&&bst.field.load(f.app.value).then(g=>{(b=>{((k,c)=>{var e={},a={copy:bst.create("button").addClass("bst-linkage-container-button").html(f.label.value).on("click",n=>{bst.confirm(f.message.value,()=>{bst.event.call("bst.action.call",{container:bst.elm("body"),record:E(f,(d.mobile?kintone.mobile.app.record:kintone.app.record).get().record,e.records),mobile:d.mobile,pattern:"change",fields:(h=>h.reduce((q,v)=>q=q.concat(Object.keys(d.fieldInfos.tables[v].fields)),h))(f.mapping.value.reduce((h,
q)=>{q.value.internal.value in d.fieldInfos.parallelize&&h.push(d.fieldInfos.parallelize[q.value.internal.value].tableCode);return h},[])),stopPropagation:!0,workplace:"record"}).then(h=>{bst.event.call("bst.style.call",{container:h.container,record:h.record,mobile:h.mobile,pattern:"$id"in h.record?h.record.$id.value?"edit":"create":"create",workplace:h.workplace}).then(q=>{bst.event.call("bst.cascade.call",q).then(v=>{(d.mobile?kintone.mobile.app.record:kintone.app.record).set({record:v.record})}).catch(()=>
{})}).catch(()=>{})}).catch(()=>{})})}),edit:bst.create("button").addClass("bst-icon bst-icon-edit").on("click",n=>{[a.total,a.reload,a.open,a.edit,a.prev,a.next,a.copy].each((h,q)=>h.addClass("bst-hidden"));[a.submit,a.cancel].each((h,q)=>h.removeClass("bst-hidden"));k.elms(".bst-field").each((h,q)=>h.removeClass("bst-readonly"));(h=>{h=bst.elm(".bst_spread_style_"+CSS.escape(h));h.parentNode.removeChild(h)})("view_"+b.id+"_"+b.view.id+"_"+location.host.split(".").first());m.parentNode.show()}),
submit:bst.create("button").addClass("bst-linkage-container-button").on("click",n=>{var h=k.tr.reduce((v,y,H)=>{v.error||"unsaved"!=y.elm(".bst-scope").attr("unsaved")||(y=bst.record.get(y.elm(".bst-scope"),b),y.error?v.error=!0:v.records["row"+H.toString()]=y.record);return v},{error:!1,records:{}}),q=(v=!1)=>{[a.total,a.reload,a.open,a.edit,a.prev,a.next,a.copy].each((y,H)=>y.removeClass("bst-hidden"));[a.submit,a.cancel].each((y,H)=>y.addClass("bst-hidden"));v?G((d.mobile?kintone.mobile.app.record:
kintone.app.record).get().record):x()};h.error||0==Object.keys(h.records).length?q():bst.confirm(bst.constants.common.message.confirm.submit[bst.operator.language],v=>{if(v)q();else{var y={},H;for(H in h.records)((I,R)=>{var K=I.$id.value,S=I.$rowId.value,N=JSON.parse(JSON.stringify(e.origin.find(B=>B.$id.value==K)||{}));0!=Object.keys(N)&&(K in y||(y[K]=(B=>{var F={id:K,record:{$id:N.$id}};B&&(F.record[B]=N[B]);return F})(Array.from(new Set(f.mapping.value.map(B=>g.parallelize[B.value.external.value].tableCode))).join(""))),
y[K].record=b.view.fields.reduce((B,F)=>{k.tr[R].elm('[field-id="'+CSS.escape(F)+'"]').hasAttribute("edited")&&(P=>{P?B[P].value.each((Q,T)=>{Q.id==S&&(Q.value[F]=I[F])}):B[F]=I[F]})(b.fields[F].tableCode);return B},y[K].record))})(h.records[H],H.replace(/^row/g,""));bst.view.records.set(b.id,{put:Object.values(y)},!1,!0).then(I=>{q(!0)}).catch(I=>{bst.alert(bst.error.parse(I));q()})}},!0)}).html(bst.constants.common.caption.button.submit[bst.operator.language]).addClass("bst-hidden"),cancel:bst.create("button").addClass("bst-linkage-container-button").on("click",
n=>{[a.total,a.reload,a.open,a.edit,a.prev,a.next,a.copy].each((h,q)=>h.removeClass("bst-hidden"));[a.submit,a.cancel].each((h,q)=>h.addClass("bst-hidden"));x()}).html(bst.constants.common.caption.button.cancel[bst.operator.language]).addClass("bst-hidden"),open:bst.create("button").addClass("bst-icon bst-icon-open").on("click",n=>{window.open(bst.record.page.view(d.mobile,b.id,"20",e.query))}),prev:bst.create("button").addClass("bst-icon bst-icon-arrow bst-icon-arrow-left").on("click",n=>{e.offset-=
c;x()}),next:bst.create("button").addClass("bst-icon bst-icon-arrow bst-icon-arrow-right").on("click",n=>{e.offset+=c;x()}),reload:bst.create("button").addClass("bst-icon bst-icon-reload").on("click",n=>{G((d.mobile?kintone.mobile.app.record:kintone.app.record).get().record)}),total:bst.create("span").addClass("bst-linkage-container-monitor").html("")},x=()=>{var n=e.records.slice(e.offset,e.offset+c);k.clearRows();n.each((h,q)=>{(v=>{bst.record.set(v.elm("[form-id=form_"+b.id+"]"),b,h).then(()=>
{v.elm(".bst-view-row-edit").attr("href",bst.record.page.detail(d.mobile,b.id,h.$id.value)).attr("target","_blank");q==n.length-1&&m.parentNode.show()})})(k.addRow())});switch(bst.operator.language){case "en":a.total.html(e.records.length.toString()+"records in total");break;case "ja":a.total.html("\u7dcf"+e.records.length.toString()+"\u884c");break;case "zh":a.total.html("\u5171"+e.records.length.toString()+"\u6761\u8bb0\u5f55");break;case "zh-TW":a.total.html("\u5171"+e.records.length.toString()+
"\u7b46\u8a18\u9304")}0<e.offset?a.prev.removeAttr("disabled"):a.prev.attr("disabled","disabled");e.offset+(c==n.length?c:n.length)<e.records.length?a.next.removeAttr("disabled"):a.next.attr("disabled","disabled")},G=n=>{O(f,n).then(h=>{e=h;x();w(f,g,{},e.records)}).catch(()=>{e={offset:0,records:[]};x();w(f,g,{},e.records)})};switch(d.type){case "create":case "edit":m.append(bst.create("div").addClass("bst-linkage-container-footer").append(a.total).append(a.reload).append(a.open).append(a.edit).append(a.prev).append(a.next).append(a.copy).append(a.submit).append(a.cancel));
break;case "detail":m.append(bst.create("div").addClass("bst-linkage-container-footer").append(a.total).append(a.reload).append(a.open).append(a.edit).append(a.prev).append(a.next).append(a.submit).append(a.cancel))}f.editable.value.includes("editable")||a.edit.addClass("bst-hidden");((n,h)=>{kintone.events.on(n,h);n.each((q,v)=>{q in d.handlers||(d.handlers[q]=[]);d.handlers[q].push(h)})})(f.criteria.value.reduce((n,h)=>{n.push("app.record.create.change."+h.value.internal.value);n.push("app.record.edit.change."+
h.value.internal.value);n.push("mobile.app.record.create.change."+h.value.internal.value);n.push("mobile.app.record.edit.change."+h.value.internal.value);return n},[]),n=>{G(n.record);return n});b.view.fields.each((n,h)=>{bst.event.on("bst.change."+n,q=>{q.container.elm('[field-id="'+CSS.escape(n)+'"]').attr("edited","edited");return q})});G(t.record)})(bst.view.create(m.addClass("bst-linkage-container"),b,b.view.id,d.mobile).elm(".bst-view"),parseInt(f.limit.value))})({id:f.app.value,disables:[],
fields:(b=>{b.$rowId={code:"$rowId",type:"SINGLE_LINE_TEXT",label:"",required:!1,noLabel:!0,placeholder:""};return b})(g.parallelize),view:{id:"linkage_"+f.app.value+"_"+f.container.value,buttons:["delete"],fields:f.mapping.value.map(b=>b.value.external.value),mode:"viewer"}})}).catch(()=>{})})((d.mobile?kintone.mobile.app.record:kintone.app.record).getSpaceElement(f.container.value).css({width:"max-content"}));l++;l<r.length&&A(l)})(r[l])};A(0);C(t);break;case "index":A=l=>{(f=>{bst.filter.auth(f.user.value,
f.organization.value,f.group.value).then(m=>{m&&(f.view.value&&f.view.value!=t.viewId.toString()||bst.button.create(d.mobile,d.type,"bst-linkage-button"+l.toString(),f.label.value,f.message.value,()=>{bst.view.records.get(d.app.id,(d.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(g=>{var b=[];let k=(c,e)=>{bst.field.load(f.app.value).then(a=>{O(f,g[c]).then(x=>{var G=E(f,g[c],x.records);w(f,a,G,x.records);b.push(bst.view.records.transform(G));bst.progressUpdate();c++;c<g.length?
k(c,e):e()}).catch(()=>{})}).catch(()=>{})};0!=g.length?(bst.progressStart(g.length),k(0,()=>{bst.view.records.set(d.app.id,{put:b}).then(c=>bst.alert("Done!",()=>window.location.reload(!0))).catch(c=>bst.alert(bst.error.parse(c)))})):bst.alert("There are no records.")}).catch(g=>bst.alert(bst.error.parse(g)))}));l++;l<r.length&&A(l)}).catch(m=>{l++;l<r.length&&A(l)})})(r[l])},A(0),C(t)}}else C(t)})(JSON.parse(p.tab).map((r,w)=>bst.extend({sIndex:{value:w.toString()}},r.setting)).reduce((r,w)=>{switch(d.type){case "index":w.bulk.value.includes("bulk")&&
r.push(w);break;default:r.push(w)}return r},[]))}catch(r){bst.alert(bst.error.parse(r)),C(t)}}).catch(u=>C(t)):C(t)}).catch(p=>C(t))})("mobile"==t.type.split(".").first(),t.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
