/*
* FileName "plugins.delete.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(t=>{var l={},y=(b,e)=>new Promise((w,u)=>{var n={suspend:f=>{try{var g=(c,d)=>{var m=()=>{c++;c<b.length?g(c,d):d(!1)};(a=>{bst.filter.scan(l.app,e,a.condition.value)?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(p=>{p?a.suspendMessage.value?bst.filter.scan(l.app,e,a.suspendFilter.value)?a.suspendContinue.value.includes("continue")?bst.confirm(a.suspendMessage.value,v=>{v?d(v):m()},!0):bst.alert(a.suspendMessage.value,()=>d(!0)):m():m():m()}).catch(p=>{bst.alert(bst.error.parse(p));
d(!0)}):m()})(b[c])};g(0,c=>f(c))}catch(c){bst.alert(bst.error.parse(c)),f(!0)}},backup:f=>{try{var g=(c,d)=>{var m=()=>{c++;c<b.length?g(c,d):d(!1)};(a=>{bst.filter.scan(l.app,e,a.condition.value)?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(p=>{p?a.backupApp.value?kintone.api(kintone.api.url("/k/v1/app",!0),"GET",{id:l.app.id}).then(v=>{bst.field.load(a.backupApp.value).then(x=>{(q=>{a.backupID.value in q.external?a.backupName.value in q.external?a.backupUser.value in q.external?
a.backupDatetime.value in q.external?a.backupFile.value in q.external?a.backupRecord.value in q.external?(r=>{r.each((h,k)=>{h.keepName=h.name;h.name="file_"+k.toString()+"."+h.name.split(".").last()});bst.file.clone(r,!0).then(()=>{bst.record.comments.get(l.app.id,e.$id.value).then(h=>{bst.view.records.set(a.backupApp.value,{post:(()=>{var k={};k[a.backupID.value]={value:l.app.id};k[a.backupName.value]={value:v.name};k[a.backupUser.value]={value:[{code:bst.operator.code}]};k[a.backupDatetime.value]=
{value:(new Date).format("ISO")};k[a.backupFile.value]={value:r};k[a.backupRecord.value]={value:JSON.stringify({comments:h,record:e})};return[k]})()},!0).then(k=>m()).catch(k=>{bst.alert(bst.error.parse(k));d(!0)})}).catch(h=>{bst.alert(bst.error.parse(h));d(!0)})})})(Object.values(q.internal).reduce((r,h)=>{"FILE"==h.type&&(h.tableCode?e[h.tableCode].value.each((k,z)=>{k.value[h.code].value&&Array.prototype.push.apply(r,k.value[h.code].value)}):e[h.code].value&&Array.prototype.push.apply(r,e[h.code].value));
return r},[])):(bst.alert("No field to backup was found"),d(!0)):(bst.alert("No field to backup was found"),d(!0)):(bst.alert("No field to backup was found"),d(!0)):(bst.alert("No field to backup was found"),d(!0)):(bst.alert("No field to backup was found"),d(!0)):(bst.alert("No field to backup was found"),d(!0))})({external:x.parallelize,internal:l.fieldInfos.parallelize})}).catch(x=>{bst.alert(bst.error.parse(x));d(!0)})}).catch(v=>{bst.alert(bst.error.parse(v));d(!0)}):m():m()}).catch(p=>{bst.alert(bst.error.parse(p));
d(!0)}):m()})(b[c])};g(0,c=>f(c))}catch(c){bst.alert(bst.error.parse(c)),f(!0)}}};n.suspend(f=>{f?w({error:f}):b.some(g=>g.backupApp.value)&&(bst.loadStart(),n.backup(g=>{bst.loadEnd();w({error:g})}))})});kintone.events.on(["app.record.detail.delete.submit","app.record.index.delete.submit","mobile.app.record.detail.delete.submit"],b=>new Promise((e,w)=>{((u,n)=>{l.mobile=u;l.type=n;bst.config[t].config.get().then(f=>{0!=Object.keys(f).length?bst.field.load(bst.config[t].app,!0).then(g=>{l.app={id:bst.config[t].app,
fields:g.origin};l.fieldInfos=g;try{(c=>{0!=c.length?y(c,b.record).then(d=>{e(d.error?!1:b)}).catch(()=>{e(resp.error?!1:b)}):e(b)})(JSON.parse(f.tab).map((c,d)=>bst.extend({sIndex:{value:d.toString()}},c.setting)).reduce((c,d)=>{(l.mobile?["all","both","mobile"]:["all","both","pc"]).includes(d.device.value)&&c.push(d);return c},[]))}catch(c){bst.alert(bst.error.parse(c)),e(b)}}).catch(g=>e(b)):e(b)}).catch(f=>e(b))})("mobile"==b.type.split(".").first(),b.type.split(".").slice(-2).first())}));bst.event.on("bst.view.delete",
b=>new Promise((e,w)=>{bst.config[t].config.get().then(u=>{0!=Object.keys(u).length?bst.field.load(bst.config[t].app,!0).then(n=>{l.app={id:bst.config[t].app,fields:n.origin};l.fieldInfos=n;try{(f=>{0!=f.length?y(f,b.record).then(g=>{b.error=g.error;e(b)}).catch(()=>{b.error=!0;e(b)}):e(b)})(JSON.parse(u.tab).map((f,g)=>bst.extend({sIndex:{value:g.toString()}},f.setting)).reduce((f,g)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(g.device.value)&&f.push(g);return f},[]))}catch(f){bst.alert(bst.error.parse(f)),
e(b)}}).catch(n=>e(b)):e(b)}).catch(u=>e(b))}))})(kintone.$PLUGIN_ID);
