/*
* FileName "plugins.imap.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(y=>{var d={},A=e=>new Promise((q,m)=>{((l,t)=>{t.append(bst.create("div").addClass("kb-row").append(bst.field.activate(bst.field.create(l.fields.from).css({width:"50%"}),l,!1)).append(bst.field.activate(bst.field.create(l.fields.to).css({width:"50%"}),l,!1))).append(bst.create("div").addClass("kb-row").append(bst.field.activate(bst.field.create(l.fields.sender).css({width:"100%"}),l,!1)));bst.record.set(t,l,d.filter?d.filter:{from:{value:(new Date((new Date).format("Y-m-dT00:00:00Z"))).calc(bst.timezoneOffset()+
" hour").toISOString()},to:{value:(new Date((new Date).format("Y-m-dT23:59:00Z"))).calc(bst.timezoneOffset()+" hour").toISOString()},sender:{value:""}});(new BooooooostPopupform(t,600,null,{ok:()=>{d.filter=bst.record.get(t,l,!0).record;fetch("https://api.kintone-booster.com/mail/rv",{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(n=>{n.json().then(u=>{switch(n.status){case 200:(f=>{bst.loadStart();bst.encrypt(JSON.stringify(f),u.passphrase).then(h=>{fetch("https://api.kintone-booster.com/mail/rv",
{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({data:h.data,iv:h.iv,tag:h.tag})}).then(k=>{k.json().then(a=>{switch(k.status){case 200:var r=[],v=[],p=(b,c)=>{0!=r.length?bst.file.upload((g=>{var w=atob(g.binary),x=new Uint8Array(w.length);w.length.each(z=>x[z]=w.charCodeAt(z));return new File([new Blob([x.buffer],{type:g.contentType})],g.filename,{type:g.contentType})})(r[b]),!0).then(g=>{a[v[b].json].attachment[v[b].attachment]=g;b++;b<r.length?p(b,c):c()}).catch(g=>
{bst.alert(bst.error.parse(g));m()}):c()};a=a.reduce((b,c)=>{var g=new Date(c.date);g>=new Date(d.filter.from.value)&&g<=new Date(d.filter.to.value)&&(c.date=g.format("ISO"),b.push(c));return b},[]);r=a.reduce((b,c,g)=>{0!=c.attachment.length&&c.attachment.each((w,x)=>{b.push(w);v.push({json:g,attachment:x})});return b},[]);p(0,()=>q(a));break;default:bst.alert(bst.error.parse(a)),m()}})}).catch(k=>{bst.alert(bst.error.parse(k));m()})}).catch(h=>{bst.loadEnd();m()})})({host:e.host.value,port:e.port.value,
option:e.option.value?e.option.value:"/imap/ssl",mailbox:e.mailbox.value?e.mailbox.value:"INBOX",author:e.author.value,pwd:e.pwd.value,criteria:(()=>{var f='SINCE "'+(new Date(d.filter.from.value)).format("Y-m-d")+'" BEFORE "'+(new Date((new Date(d.filter.to.value)).format("Y-m-d"))).calc("1 day").format("Y-m-d")+'"';d.filter.sender.value&&(f+=' FROM "'+d.filter.sender.value+'"');return f})()});break;default:bst.alert(bst.error.parse(u)),m()}})}).catch(n=>{bst.alert(bst.error.parse(n));m()})},cancel:()=>
m()})).show()})({id:"IMAP_filter",fields:{from:{code:"from",type:"DATETIME",label:bst.constants.imap.caption.from[bst.operator.language],required:!0,noLabel:!1},to:{code:"to",type:"DATETIME",label:bst.constants.imap.caption.to[bst.operator.language],required:!0,noLabel:!1},sender:{code:"sender",type:"SINGLE_LINE_TEXT",label:bst.constants.imap.caption.sender[bst.operator.language],required:!0,noLabel:!1,format:"mail"}}},bst.create("div").addClass("kb-scope").attr("form-id","form_IMAP_filter"))});kintone.events.on(["app.record.index.show",
"mobile.app.record.index.show"],e=>new Promise((q,m)=>{((l,t)=>{d.mobile=l;d.type=t;bst.config[y].config.get().then(n=>{0!=Object.keys(n).length?bst.field.load(bst.config[y].app,!0).then(u=>{d.app={id:bst.config[y].app,fields:u.origin};d.fieldInfos=u;try{(f=>{if(0!=f.length){var h=k=>{(a=>{bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(r=>{r&&(a.view.value&&a.view.value!=e.viewId.toString()||bst.button.create(d.mobile,d.type,"kb-imap-button"+k.toString(),a.label.value,a.message.value,
()=>{A(a).then(v=>{0!=v.length?bst.view.records.set(d.app.id,{post:v.reduce((p,b)=>{var c={};c[a.uid.value]={value:b.uid};c[a.from.value]={value:b.from};c[a.date.value]={value:b.date};c[a.subject.value]={value:b.subject};c[a.body.value]={value:b.body};c[a.attachment.value]={value:b.attachment};a.cc&&a.cc.value&&(c[a.cc.value]={value:b.cc});a.bcc&&a.bcc.value&&(c[a.bcc.value]={value:b.bcc});p.push(c);return p},[])},!0).then(p=>bst.alert("Done!",()=>window.location.reload(!0))).catch(p=>bst.alert(bst.error.parse(p))):
bst.alert("There are no emails.")}).catch(()=>{})}));k++;k<f.length&&h(k)}).catch(r=>{k++;k<f.length&&h(k)})})(f[k])};h(0)}q(e)})(JSON.parse(n.tab).map((f,h)=>bst.extend({sIndex:{value:h.toString()}},f.setting)).reduce((f,h)=>{(d.mobile?["all","both","mobile"]:["all","both","pc"]).includes(h.device.value)&&f.push(h);return f},[]))}catch(f){bst.alert(bst.error.parse(f)),q(e)}}).catch(u=>q(e)):q(e)}).catch(n=>q(e))})("mobile"==e.type.split(".").first(),e.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
bst.constants=bst.extend({imap:{caption:{from:{en:"Since",ja:"\u4ee5\u964d",zh:"\u4ee5\u540e","zh-TW":"\u4ee5\u5f8c"},sender:{en:"Sender",ja:"\u5dee\u51fa\u4eba",zh:"\u53d1\u4ef6\u4eba","zh-TW":"\u767c\u4ef6\u4eba"},to:{en:"Before",ja:"\u4ee5\u524d",zh:"\u4ee5\u524d","zh-TW":"\u4ee5\u524d"}}}},bst.constants);
