/*
* FileName "plugins.submit.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(z=>{var a={handlers:{}},A=(g,e,v=!1,w={},y="record")=>new Promise((r,q)=>{var x=[],t=(h,b)=>{var m=()=>{h++;h<g.length?t(h,b):b()};(f=>{kb.filter.scan(a.app,e,f.condition.value)?kb.filter.auth(f.user.value,f.organization.value,f.group.value).then(p=>{if(p){var u={duplicate:l=>{try{f.duplicateCriteria.value.some(c=>!(c.value.external.value in a.fieldInfos.parallelize&&c.value.internal.value in a.fieldInfos.parallelize))?(kb.alert("No field to lookup was found"),q()):(c=>{c&&x.push(c);l()})(f.duplicateCriteria.value.reduce((c,
d)=>{c.push(kb.filter.query.create(a.fieldInfos.parallelize[d.value.external.value],d.value.operator.value,e[a.fieldInfos.parallelize[d.value.internal.value].code]));return c},[]).join(" and "))}catch(c){kb.alert(kb.error.parse(c)),q()}},error:l=>{try{if(f.errorMessage.value||0!=f.errorField.value.length){var c=kb.filter.scan(a.app,e,f.errorFilter.value);c?(f.errorField.value.each((d,k)=>{d.value.field.value in a.fieldInfos.parallelize&&(n=>{n.tableCode?c[n.tableCode].value.each((B,C)=>{B.value[d.value.field.value].error=
d.value.message.value}):e[d.value.field.value].error=d.value.message.value})(a.fieldInfos.parallelize[d.value.field.value])}),v||kb.loadEnd(),r({error:!0,message:f.errorMessage.value})):l()}else l()}catch(d){kb.alert(kb.error.parse(d)),q()}},numbering:l=>{try{if(f.numberingField.value in a.fieldInfos.parallelize)if(e[f.numberingField.value].value)l();else{var c="",d=f.numberingGroup.value.reduce((k,n)=>{if(n.value.field.value in a.fieldInfos.parallelize)switch(c+=e[n.value.field.value].value,a.fieldInfos.parallelize[n.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":k.push(n.value.field.value+
' in ("'+e[n.value.field.value].value+'")');break;default:k.push(n.value.field.value+'="'+e[n.value.field.value].value+'"')}return k},"$id"in e?['$id!="'+e.$id.value+'"']:[]);c in w?(w[c]++,e[f.numberingField.value].value=c+w[c].toString().lpad("0",parseInt(f.numberingDigits.value)),l()):kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:a.app.id,query:d.join(" and ")+" order by "+f.numberingField.value+" desc limit 1 offset 0"}).then(k=>{k=k.records;var n=0;0!=k.length&&(n=parseInt((k.first()[f.numberingField.value].value||
" ").replace(/[ ]+/g,"").replace(new RegExp("^"+c,"g"),"")),kb.isNumeric(n)||(n=0));n++;k=n;w[c]=k;e[f.numberingField.value].value=c+k.toString().lpad("0",parseInt(f.numberingDigits.value));l()}).catch(k=>{kb.alert(kb.error.parse(k));q()})}else l()}catch(k){kb.alert(kb.error.parse(k)),q()}},prompt:l=>{try{(c=>{0!=c.length?(d=>{c.each((k,n)=>{d.append(kb.field.activate(kb.field.create(k).css({width:"100%"}),a.app,!1))});v||kb.loadEnd();(new KintoneBoosterPopupform(d,600,"full",{ok:()=>{var k=kb.record.get(d,
a.app,!0);c.each((n,B)=>{e[n.code].value=k.record[n.code].value});v||kb.loadStart();l()},cancel:()=>{v||kb.loadStart();l()}})).show()})(kb.create("div").addClass("kb-scope").attr("form-id","form_"+a.app.id)):l()})(f.promptField.value.reduce((c,d)=>{d.value.field.value in a.fieldInfos.parallelize&&(f.promptOverwrite.value.includes("overwrite")?c.push(a.fieldInfos.parallelize[d.value.field.value]):kb.field.isEmpty(e[d.value.field.value].value)&&c.push(a.fieldInfos.parallelize[d.value.field.value]));
return c},[]))}catch(c){kb.alert(kb.error.parse(c)),q()}},verify:l=>{try{(c=>{0!=c.length?(d=>{c.each((k,n)=>{d.append(kb.field.activate(kb.field.create(k).addClass("kb-readonly").css({width:"100%"}),a.app,!1))});kb.record.set(d,a.app,e);v||kb.loadEnd();(new KintoneBoosterPopupform(d,600,"full",{ok:()=>{v||kb.loadStart();l()},cancel:()=>{v||kb.loadEnd();r({error:!0})}})).show()})(kb.create("div").addClass("kb-scope kb-verify").attr("form-id","form_"+a.app.id).append(kb.create("p").html(f.verifyMessage.value))):
l()})(f.verifyField.value.reduce((c,d)=>{d.value.field.value in a.fieldInfos.parallelize&&c.push(a.fieldInfos.parallelize[d.value.field.value]);return c},[]))}catch(c){kb.alert(kb.error.parse(c)),q()}}};u.numbering(()=>{"saved"!=y?u.prompt(()=>{u.verify(()=>{u.error(()=>{u.duplicate(()=>{m()})})})}):m()})}else m()}).catch(p=>{kb.alert(kb.error.parse(p));q()}):m()})(g[h])};v||kb.loadStart();t(0,()=>{v||kb.loadEnd();0!=x.length?kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:a.app.id,query:((h,
b)=>(b?"$id!="+b+" and ("+h+")":h)+" order by $id asc limit 5 offset 0")(x.map(h=>"("+h+")").join(" or "),"$id"in e?e.$id.value:"")}).then(h=>{0!=h.records.length?kb.confirm((b=>{h.records.each(m=>{b.append(kb.create("p").css({margin:"0"}).append(kb.create("a").attr("href",kb.record.page.detail(a.mobile,a.app.id,m.$id.value)).attr("target","_blank").html("Record No: "+m.$id.value)))});return b})(kb.create("div").append(kb.create("p").css({margin:"0"}).html(kb.constants.submit.message.duplicate[kb.operator.language]))),
b=>{r({error:b})},!0):r({error:!1})}).catch(h=>{kb.alert(kb.error.parse(h),()=>{r({error:!1})})}):r({error:!1})})});kintone.events.on("app.record.create.submit app.record.detail.show app.record.edit.submit app.record.index.show mobile.app.record.create.submit mobile.app.record.detail.show mobile.app.record.edit.submit mobile.app.record.index.show".split(" "),g=>new Promise((e,v)=>{((w,y)=>{a.mobile=w;a.type=y;for(var r in a.handlers)a.handlers[r].each((q,x)=>{kintone.events.off(r,q)});kb.config[z].config.get().then(q=>
{0!=Object.keys(q).length?kb.field.load(kb.config[z].app,!0).then(x=>{a.app={id:kb.config[z].app,fields:x.origin};a.fieldInfos=x;try{["detail"].includes(a.type)&&kintone.app.record.getPermissions().then(t=>{t.editRecord&&(h=>{0!=h.length&&((b,m)=>{kintone.events.on(b,m);b.each((f,p)=>{f in a.handlers||(a.handlers[f]=[]);a.handlers[f].push(m)})})(["app.record.detail.process.proceed","mobile.app.record.detail.process.proceed"],b=>new Promise((m,f)=>{try{(p=>{0!=p.length?A(p,b.record).then(u=>{u.error&&
(b.error="message"in u?u.message:kb.constants.submit.message.cancel.submit[kb.operator.language]);m(b)}).catch(()=>{b.error=kb.constants.submit.message.cancel.submit[kb.operator.language];m(b)}):m(b)})(h.filter(p=>p.action.value==b.action.value+":"+b.status.value+":"+b.nextStatus.value))}catch(p){kb.alert(kb.error.parse(p)),m(b)}}))})(JSON.parse(q.tab).map((h,b)=>kb.extend({sIndex:{value:b.toString()}},h.setting)).reduce((h,b)=>{(a.mobile?["all","both","mobile"]:["all","both","pc"]).includes(b.device.value)&&
b.event.value.includes("process")&&h.push(b);return h},[]))}).catch(()=>{}),(t=>{if(0!=t.length)switch(a.type){case "create":case "edit":A(t,g.record).then(b=>{b.error&&(g.error="message"in b?b.message:kb.constants.submit.message.cancel.submit[kb.operator.language]);e(g)}).catch(()=>{g.error=kb.constants.submit.message.cancel.submit[kb.operator.language];e(g)});(b=>{if(0!=b.length)kintone.events.on((a.mobile?"mobile.":"")+"app.record."+a.type+".submit.success",m=>new Promise((f,p)=>{var u=l=>{(c=>
{kb.filter.scan(a.app,m.record,c.condition.value)?kb.filter.auth(c.user.value,c.organization.value,c.group.value).then(d=>{if(d){d=c.url.value;var k=m.record,n;for(n in k)d=d.replace(new RegExp("%"+n+"%","g"),kb.field.stringify(a.fieldInfos.parallelize[n],k[n].value," / "));m.url=d}l++;l<b.length&&u(l)}).catch(d=>{l++;l<b.length&&u(l)}):(l++,l<b.length&&u(l))})(b[l])};u(0);f(m)}))})(t.filter(b=>b.url.value));break;case "index":var h=b=>{(m=>{kb.filter.auth(m.user.value,m.organization.value,m.group.value).then(f=>
{f&&(m.view.value&&m.view.value!=g.viewId.toString()||kb.button.create(a.mobile,a.type,"kb-submit-button"+b.toString(),m.label.value,m.message.value,()=>{kb.view.records.get(a.app.id,(a.mobile?kintone.mobile.app:kintone.app).getQueryCondition(),(p=>{p=p.match(/order by/g)?p.replace(/^.*order by/g,""):"";return(p=p.replace(/limit [0-9]+/g,"").replace(/ offset [0-9]+/g,"").replace(/^[ ]+/g,"").replace(/[ ]+$/g,""))?p:"$id asc"})((a.mobile?kintone.mobile.app:kintone.app).getQuery())).then(p=>{var u=
{},l=[];let c=(d,k)=>{A([m],p[d],!0,u,"saved").then(n=>{n.error?k(!0):(l.push(kb.view.records.transform(p[d])),kb.progressUpdate(),d++,d<p.length?c(d,k):k())}).catch(()=>{})};0!=p.length?(kb.progressStart(p.length),c(0,d=>{d||kb.view.records.set(a.app.id,{put:l}).then(k=>kb.alert("Done!",()=>window.location.reload(!0))).catch(k=>kb.alert(kb.error.parse(k)))})):kb.alert("There are no records.")}).catch(p=>kb.alert(kb.error.parse(p)))}));b++;b<t.length&&h(b)}).catch(f=>{b++;b<t.length&&h(b)})})(t[b])};
h(0);e(g)}else e(g)})(JSON.parse(q.tab).map((t,h)=>kb.extend({sIndex:{value:h.toString()}},t.setting)).reduce((t,h)=>{(a.mobile?["all","both","mobile"]:["all","both","pc"]).includes(h.device.value)&&h.event.value.includes(a.type)&&t.push(h);return t},[]))}catch(t){kb.alert(kb.error.parse(t)),e(g)}}).catch(x=>e(g)):e(g)}).catch(q=>e(g))})("mobile"==g.type.split(".").first(),g.type.split(".").slice(-2).first())}));kb.event.on("kb.submit.call",g=>new Promise((e,v)=>{kb.config[z].config.get().then(w=>
{0!=Object.keys(w).length?kb.field.load(kb.config[z].app,!0).then(y=>{a.app={id:kb.config[z].app,fields:y.origin};a.fieldInfos=y;try{(r=>{0!=r.length?A(r,g.record,!0,g.numbering).then(q=>{q.error?(g.error=!0,q.message?kb.alert(q.message,()=>e(g)):e(g)):e(g)}).catch(()=>{g.error=!0;e(g)}):e(g)})(JSON.parse(w.tab).map((r,q)=>kb.extend({sIndex:{value:q.toString()}},r.setting)).reduce((r,q)=>{(g.mobile?["all","both","mobile"]:["all","both","pc"]).includes(q.device.value)&&q.event.value.includes(g.pattern)&&
r.push(q);return r},[]))}catch(r){kb.alert(kb.error.parse(r)),e(g)}}).catch(y=>e(g)):e(g)}).catch(w=>e(g))}))})(kintone.$PLUGIN_ID);
kb.constants=kb.extend({submit:{message:{cancel:{process:{en:"The process action was canceled.",ja:"\u30d7\u30ed\u30bb\u30b9\u30a2\u30af\u30b7\u30e7\u30f3\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u8fdb\u7a0b\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002","zh-TW":"\u8655\u7406\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002"},submit:{en:"The submit was canceled.",ja:"\u4fdd\u5b58\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u4fdd\u5b58\u5df2\u88ab\u53d6\u6d88\u3002",
"zh-TW":"\u63d0\u4ea4\u5df2\u88ab\u53d6\u6d88\u3002"}},duplicate:{en:"A similar record already exists. Would you like to proceed with the registration anyway?",ja:"\u985e\u4f3c\u30ec\u30b3\u30fc\u30c9\u304c\u65e2\u306b\u767b\u9332\u3055\u308c\u3066\u3044\u307e\u3059\u304c\u3001\u3053\u306e\u307e\u307e\u767b\u9332\u3057\u3066\u3082\u5b9c\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u7ecf\u6709\u7c7b\u4f3c\u7684\u8bb0\u5f55\u5b58\u5728\u4e86\uff0c\u60a8\u8fd8\u8981\u7ee7\u7eed\u6ce8\u518c\u5417\uff1f",
"zh-TW":"\u5df2\u7d93\u6709\u985e\u4f3c\u7684\u8a18\u9304\u5b58\u5728\u4e86\uff0c\u60a8\u9084\u8981\u7e7c\u7e8c\u8a3b\u518a\u55ce\uff1f"}}}},kb.constants);
