/*
* FileName "plugins.restore.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(r=>{var p,t,u;kintone.events.on(["app.record.detail.show","mobile.app.record.detail.show"],c=>new Promise((k,C)=>{((y,z)=>{p=y;t=z;kb.config[r].config.get().then(q=>{Object.keys(q).length!=0?kb.field.load(kb.config[r].app,!0).then(v=>{u=v;try{(g=>{((l,w,e)=>{l&&"comments"in e&&"record"in e&&kb.button.create(p,t,"kb-restore-button",(()=>{var b="";switch(kb.operator.language){case "en":b="Restore the record";break;case "ja":b="\u30ec\u30b3\u30fc\u30c9\u3092\u5fa9\u5143\u3059\u308b";break;
case "zh":b="\u6062\u590d\u8bb0\u5f55";break;case "zh-TW":b="\u6062\u5fa9\u8a18\u9304"}return b})(),(()=>{var b="";switch(kb.operator.language){case "en":b="May I restore the record?";break;case "ja":b="\u30ec\u30b3\u30fc\u30c9\u3092\u5fa9\u5143\u3057\u3066\u3082\u3044\u3044\u3067\u3059\u304b\uff1f";break;case "zh":b="\u6211\u53ef\u4ee5\u6062\u590d\u8bb0\u5f55\u5417\uff1f";break;case "zh-TW":b="\u6211\u53ef\u4ee5\u6062\u5fa9\u8a18\u9304\u55ce\uff1f"}return b})(),()=>{kb.field.load(l).then(b=>{(A=>
{(m=>{kb.loadStart();kb.file.clone(m,!0).then(()=>{kb.view.records.set(l,{post:[kb.view.records.transform(e.record,"POST")]},!0).then(a=>{(f=>{kb.record.comments.set(l,a,e.comments,!0).then(d=>kb.alert("Done!",()=>window.open(f))).catch(d=>kb.alert(kb.error.parse(d)))})(kb.record.page.detail(p,l,a))}).catch(a=>kb.alert(kb.error.parse(a)))})})(Object.values(A.external).reduce((m,a)=>{a.type=="FILE"&&(a.tableCode?e.record[a.tableCode].value.each((f,d)=>{f.value[a.code].value&&(f.value[a.code].value=
f.value[a.code].value.reduce((n,h)=>{var x=w.filter(B=>B.name==h.name);x.length!=0&&(h.fileKey=x.first().fileKey,h.name=h.keepName,delete h.keepName,n.push(h));return n},[]),Array.prototype.push.apply(m,f.value[a.code].value))}):e.record[a.code].value&&(e.record[a.code].value=e.record[a.code].value.reduce((f,d)=>{var n=w.filter(h=>h.name==d.name);n.length!=0&&(d.fileKey=n.first().fileKey,d.name=d.keepName,delete d.keepName,f.push(d));return f},[]),Array.prototype.push.apply(m,e.record[a.code].value)));
return m},[]))})({external:b.parallelize,internal:u.parallelize})}).catch(b=>kb.alert(kb.error.parse(b)))})})(g.backupID.value in c.record?c.record[g.backupID.value].value:"",g.backupFile.value in c.record?c.record[g.backupFile.value].value:[],g.backupRecord.value in c.record?JSON.parse(c.record[g.backupRecord.value].value):{})})(JSON.parse(q.flat)),k(c)}catch(g){kb.alert(kb.error.parse(g)),k(c)}}).catch(v=>k(c)):k(c)}).catch(q=>k(c))})(c.type.split(".").first()=="mobile",c.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);