/*
* FileName "plugins.cascade.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(B=>{var a={handlers:{}},F=(g,e,G,w="record",z="detail")=>{var k={},m=(()=>{var x={},t=0;if("record"==w)for(var c in e)c in a.fieldInfos.tables&&e[c].value.each((f,r)=>{null==f.id&&(t++,f.id=t);x[f.id]=r},{});return x})();return new Promise((x,t)=>{var c=(f,r)=>{var E=h=>(b=>new Kuc.Dropdown({className:"control-gaia",items:[{label:"-----",value:""}].concat(Object.values(b.options).reduce((d,u)=>{d[u.index]=u;return d},Array(Object.values(b.options).length).fill("")).map(d=>({label:d.label,value:d.label}))),
label:b.noLabel||b.tableCode?"":b.label,requiredIcon:b.required}))(a.fieldInfos.parallelize[h.child.value]),C=(h,b)=>{var d=Object.keys(a.fieldInfos.parallelize[h.child.value].options);if(Array.isArray(b[h.parent.value].value)?0!=b[h.parent.value].value.length:b[h.parent.value].value)d=(Array.isArray(b[h.parent.value].value)?b[h.parent.value].value:[b[h.parent.value].value]).reduce((u,q)=>u=[...(new Set([...u,...h.relation.value[q]]))],[]);return d},H=h=>null==h||!1===h?"":String(h),A=h=>Array.from(h.childNodes).map(b=>
b.nodeType===Node.TEXT_NODE?b.nodeValue.trim():b.nodeType===Node.ELEMENT_NODE?A(b):"").join("");(h=>{(b=>{switch(w){case "record":b.parent.tableCode?b.parent.tableCode in e&&(d=>{(u=>{if(kb.elms(u).length!=e[b.parent.tableCode].value.length){let q=new MutationObserver(()=>{kb.elms(u).length==e[b.parent.tableCode].value.length&&(d(),q.disconnect())});q.observe(kb.elm(".subtable-"+a.fieldInfos.tables[b.parent.tableCode].id),{childList:!0,subtree:!0})}else d()})(".subtable-"+a.fieldInfos.tables[b.parent.tableCode].id+
(a.mobile?" .subtable-row-gaia":" tbody tr"))})(()=>{e[b.parent.tableCode].value.each((d,u)=>{b.parent.code in d.value&&(q=>{q&&(l=>{var p="";switch(a.fieldInfos.parallelize[b.child.code].type){case "CHECK_BOX":p=a.mobile?".checkbox-gaia":".input-checkbox-item-cybozu";break;case "DROP_DOWN":a.mobile?p="option":(n=>{if(!n.nextSibling||!n.nextSibling.tagName.toLowerCase().startsWith("kuc")){n.hide().insertAdjacentElement("afterend",E(h));let v=new MutationObserver(()=>{n.nextSibling.elms("[role=option]").each((y,
D)=>{y.attr("value")&&!l.includes(A(y))&&y.addClass("kb-cascade-disabled")});kb.event.call("kb.style.color.call",{field:n});kb.event.call("kb.style.display.call",{field:n});kb.event.call("kb.style.editable.call",{field:n});v.disconnect()});v.observe(n.nextSibling,{childList:!0,subtree:!0})}(v=>{v.handler&&v.removeEventListener("change",v.handler);v.handler=y=>{var D=(a.mobile?kintone.mobile.app.record:kintone.app.record).get();D.record[b.parent.tableCode].value[m[d.id]].value[b.child.code].value=
y.detail.value;(a.mobile?kintone.mobile.app.record:kintone.app.record).set(D)};v.addEventListener("change",v.handler);v.elms("[role=option]").each((y,D)=>{y.attr("value")&&!l.includes(A(y))&&y.addClass("kb-cascade-disabled")});v.value=H(e[b.parent.tableCode].value[m[d.id]].value[b.child.code].value)})(n.nextSibling)})(q[m[d.id]]);break;case "MULTI_SELECT":p=a.mobile?"option":".goog-menuitem";break;case "RADIO_BUTTON":p=a.mobile?".radio-gaia":".input-radio-item-cybozu"}p&&("option"==p?(n=>{n in k||
(k[n]={element:q[m[d.id]].value.elm("select"),options:[]});k[n].options=[...(new Set([...k[n].options,...l]))]})(b.child.code+"_"+m[d.id].toString()):q[m[d.id]].value.elms(p).each((n,v)=>{l.includes(A(n))||n.addClass("kb-cascade-disabled")}))})(C(h,d.value))})(kb.field.get(b.child,a.mobile,a.type||z))})}):b.parent.code in e&&(d=>{d&&(u=>{var q="";switch(a.fieldInfos.parallelize[b.child.code].type){case "CHECK_BOX":q=a.mobile?".checkbox-gaia":".input-checkbox-item-cybozu";break;case "DROP_DOWN":if(a.mobile)q=
"option";else{if(!d.nextSibling||!d.nextSibling.tagName.toLowerCase().startsWith("kuc")){d.hide().insertAdjacentElement("afterend",E(h));let l=new MutationObserver(()=>{d.nextSibling.elms("[role=option]").each((p,n)=>{p.attr("value")&&!u.includes(A(p))&&p.addClass("kb-cascade-disabled")});l.disconnect()});l.observe(d.nextSibling,{childList:!0,subtree:!0})}(l=>{l.handler&&l.removeEventListener("change",l.handler);l.handler=p=>{var n=(a.mobile?kintone.mobile.app.record:kintone.app.record).get();n.record[b.child.code].value=
p.detail.value;(a.mobile?kintone.mobile.app.record:kintone.app.record).set(n)};l.addEventListener("change",l.handler);l.elms("[role=option]").each((p,n)=>{p.attr("value")&&!u.includes(A(p))&&p.addClass("kb-cascade-disabled")});l.value=H(e[b.child.code].value)})(d.nextSibling)}break;case "MULTI_SELECT":q=a.mobile?"option":".goog-menuitem";break;case "RADIO_BUTTON":q=a.mobile?".radio-gaia":".input-radio-item-cybozu"}q&&("option"==q?(l=>{l in k||(k[l]={element:d.value.elm("select"),options:[]});k[l].options=
[...(new Set([...k[l].options,...u]))]})(b.child.code):d.value.elms(q).each((l,p)=>{u.includes(A(l))||l.addClass("kb-cascade-disabled")}))})(C(h,e))})(kb.field.get(b.child,a.mobile,a.type||z));break;case "view":b.parent.tableCode?b.parent.tableCode in e&&e[b.parent.tableCode].value.each((d,u)=>{b.parent.code in d.value&&(d.value[b.child.code].options=C(h,d.value))}):b.parent.code in e&&(e[b.child.code].options=C(h,e))}})({parent:a.fieldInfos.parallelize[h.parent.value],child:a.fieldInfos.parallelize[h.child.value]});
f++;f<g.length?c(f,r):r()})(g[f])};"record"==w&&kb.elms(".kb-cascade-disabled").each((f,r)=>{f.removeClass("kb-cascade-disabled")});c(0,()=>{for(var f in k)k[f].element.filteroption(k[f].options);x()})})};kintone.events.on(["app.record.create.show","app.record.edit.show","mobile.app.record.create.show","mobile.app.record.edit.show"],g=>new Promise((e,G)=>{((w,z)=>{a.mobile=w;a.type=z;for(var k in a.handlers)a.handlers[k].each((m,x)=>{kintone.events.off(k,m)});kb.config[B].config.get().then(m=>{0!=
Object.keys(m).length?kb.field.load(kb.config[B].app,!0).then(x=>{a.app={id:kb.config[B].app,fields:x.origin};a.fieldInfos=x;try{(t=>{0!=t.length&&(((c,f)=>{kintone.events.on(c,f);c.each((r,E)=>{r in a.handlers||(a.handlers[r]=[]);a.handlers[r].push(f)})})(t.reduce((c,f)=>{c.push("app.record.create.change."+f.parent.value);c.push("app.record.edit.change."+f.parent.value);c.push("mobile.app.record.create.change."+f.parent.value);c.push("mobile.app.record.edit.change."+f.parent.value);var r=a.fieldInfos.parallelize[f.parent.value].tableCode;
r&&(c.push("app.record.create.change."+r),c.push("app.record.edit.change."+r),c.push("mobile.app.record.create.change."+r),c.push("mobile.app.record.edit.change."+r));switch(a.fieldInfos.parallelize[f.child.value].type){case "DROP_DOWN":c.push("app.record.create.change."+f.child.value),c.push("app.record.edit.change."+f.child.value),c.push("mobile.app.record.create.change."+f.child.value),c.push("mobile.app.record.edit.change."+f.child.value)}return[...(new Set([...c]))]},[]),c=>{kb.event.call("kb.action.installed.change",
{installed:!1,mobile:a.mobile}).then(f=>{f.installed||F(t,c.record,kb.elm("body"),"record").then(r=>{}).catch(()=>{})});return c}),kb.event.call("kb.action.installed.show",{installed:!1,mobile:a.mobile}).then(c=>{c.installed?e(g):F(t,g.record,kb.elm("body"),"record").then(f=>e(g)).catch(()=>{})}))})(JSON.parse(m.tab).map((t,c)=>kb.extend({sIndex:{value:c.toString()}},t.setting)).reduce((t,c)=>{(a.mobile?["all","both","mobile"]:["all","both","pc"]).includes(c.device.value)&&c.parent.value in a.fieldInfos.parallelize&&
c.child.value in a.fieldInfos.parallelize&&(c.relation.value=JSON.parse(c.relation.value),t.push(c));return t},[]))}catch(t){kb.alert(kb.error.parse(t)),e(g)}}).catch(x=>e(g)):e(g)}).catch(m=>e(g))})("mobile"==g.type.split(".").first(),g.type.split(".").slice(-2).first())}));kb.event.on("kb.cascade.call",g=>new Promise((e,G)=>{["create","edit"].includes(g.pattern)?kb.config[B].config.get().then(w=>{0!=Object.keys(w).length?kb.field.load(kb.config[B].app,!0).then(z=>{a.app={id:kb.config[B].app,fields:z.origin};
a.fieldInfos=z;a.mobile="mobile"in a?a.mobile:g.mobile;try{(k=>{0!=k.length?F(k,g.record,g.container,g.workplace?g.workplace:"record",g.pattern).then(m=>e(g)).catch(()=>e(g)):e(g)})(JSON.parse(w.tab).map((k,m)=>kb.extend({sIndex:{value:m.toString()}},k.setting)).reduce((k,m)=>{(g.mobile?["all","both","mobile"]:["all","both","pc"]).includes(m.device.value)&&m.parent.value in a.fieldInfos.parallelize&&m.child.value in a.fieldInfos.parallelize&&(m.relation.value=JSON.parse(m.relation.value),k.push(m));
return k},[]))}catch(k){kb.alert(kb.error.parse(k)),e(g)}}).catch(z=>e(g)):e(g)}).catch(w=>e(g)):e(g)}))})(kintone.$PLUGIN_ID);
