/*
* FileName "plugins.omail.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(z=>{var c={handlers:{}},B=(f,n,C=!1)=>new Promise((x,v)=>{var u="",q=(w,g)=>{var l=()=>{w++;w<f.length?q(w,g):g()};(a=>{var b=bst.filter.scan(c.app,n,a.condition.value);b?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(e=>{if(e){var p=(k,r,h)=>{"HTML"==a.format.value&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var d in r){var m=r[d].value;d in c.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[d].type&&(m=m.replace(/\r/g,"").replace(/\n/g,
"<br>")),k=k.replace(new RegExp("%"+d+"%","g"),bst.field.stringify(c.fieldInfos.parallelize[d],m," / ",!0)))}for(d in h)m=h[d].value,d in c.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[d].type&&(m=m.replace(/\r/g,"").replace(/\n/g,"<br>")),k=k.replace(new RegExp("%"+d+"%","g"),bst.field.stringify(c.fieldInfos.parallelize[d],m," / ",!0)));return k};(k=>{var r=(h,d)=>{(m=>{var F=(t,y)=>{if(0!=m.attachment.length){var D=!1;window.hasOwnProperty("kb_report_temp")&&
m.attachment[t].fileKey in window.kb_report_temp&&(D=!0);D?(m.attachment[t].data=window.kb_report_temp[m.attachment[t].fileKey],t++,t<m.attachment.length?F(t,y):y()):bst.file.download(m.attachment[t],!0).then(A=>{bst.field.blobToBase64(A,G=>{m.attachment[t].data=G;t++;t<m.attachment.length?F(t,y):y()})}).catch(A=>{bst.alert(bst.error.parse(A));v()})}else y()};F(0,()=>{bst.encrypt(JSON.stringify(m.data),u).then(t=>{var y=fetch,D="https://api.kintone-booster.com/mail/oauth/"+bst.operator.language,A=
JSON,G=A.stringify;m.data=t.data;m.iv=t.iv;m.tag=t.tag;y(D,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:G.call(A,m)}).then(E=>{E.json().then(H=>{switch(E.status){case 200:h++;h<k.length?r(h,d):d();break;default:bst.alert(bst.error.parse(H)),v()}})}).catch(E=>{bst.alert(bst.error.parse(E));v()})}).catch(t=>{v()})})})(k[h])};0!=k.length?r(0,()=>{try{a.formula.value.map(h=>h.value).each((h,d)=>{h.field.value in c.fieldInfos.parallelize&&(d=c.fieldInfos.parallelize[h.field.value],
d.tableCode||(b[d.code].value=bst.formula.calculate(h,b,b,n,c.fieldInfos.parallelize),d.lookup&&(b[d.code].lookup=!0),h=b.$id.value,h in c.formulaRecords||(c.formulaRecords[h]={$id:{value:h}}),c.formulaRecords[h][d.code]=b[d.code]))}),l()}catch(h){bst.alert(bst.error.parse(h)),v()}}):l()})((()=>{var k=[];(c.fieldInfos.parallelize[a.to.value].tableCode?b[c.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:b}]).each((r,h)=>{r.value[a.to.value].value&&k.push({data:{client_id:a.client_id.value,
client_secret:a.client_secret.value,author:a.author.value,sender:a.sender.value,subdomain:location.host.split(".")[0],provider:(d=>{d="";switch(a.provider.value){case "GMail":d="google";break;case "Exchange Online":d="microsoft"}return d})(a.provider.value),to:r.value[a.to.value].value,cc:p(a.cc.value,b,c.fieldInfos.parallelize[a.to.value].tableCode?r.value:{}),bcc:p(a.bcc.value,b,c.fieldInfos.parallelize[a.to.value].tableCode?r.value:{}),html:"HTML"==a.format.value},subject:p(a.subject.value,b,c.fieldInfos.parallelize[a.to.value].tableCode?
r.value:{}),body:p(a.body.value,b,c.fieldInfos.parallelize[a.to.value].tableCode?r.value:{}),attachment:(()=>{var d=[];a.attachment.value&&a.attachment.value in c.fieldInfos.parallelize&&(d=(c.fieldInfos.parallelize[a.attachment.value].tableCode?r.value:b)[a.attachment.value].value);return d})()})});return k})())}else l()}).catch(e=>{bst.alert(bst.error.parse(e));v()}):l()})(f[w])};fetch("https://api.kintone-booster.com/mail/oauth/"+bst.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(w=>
{w.json().then(g=>{switch(w.status){case 200:u=g.passphrase;C||bst.loadStart();q(0,()=>{C||bst.loadEnd();x()});break;default:bst.alert(bst.error.parse(g)),v()}})}).catch(w=>{bst.alert(bst.error.parse(w));v()})});kintone.events.on("app.record.create.submit.success app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),f=>new Promise((n,
C)=>{((x,v)=>{c.mobile=x;c.type=v;for(var u in c.handlers)c.handlers[u].each((q,w)=>{kintone.events.off(u,q)});bst.config[z].config.get().then(q=>{0!=Object.keys(q).length?bst.field.load(bst.config[z].app,!0).then(w=>{c.app={id:bst.config[z].app,fields:w.origin};c.fieldInfos=w;c.formulaRecords={};try{["detail"].includes(c.type)&&kintone.app.record.getPermissions().then(g=>{g.editRecord&&(l=>{0!=l.length&&((a,b)=>{kintone.events.on(a,b);a.each((e,p)=>{e in c.handlers||(c.handlers[e]=[]);c.handlers[e].push(b)})})(["app.record.detail.process.proceed",
"mobile.app.record.detail.process.proceed"],a=>new Promise((b,e)=>{try{(p=>{0!=p.length?B(p,a.record).then(k=>b(a)).catch(()=>{}):b(a)})(l.filter(p=>p.action.value==a.action.value+":"+a.status.value+":"+a.nextStatus.value))}catch(p){bst.alert(bst.error.parse(p)),b(a)}}))})(JSON.parse(q.tab).map((l,a)=>bst.extend({sIndex:{value:a.toString()}},l.setting)).reduce((l,a)=>{(c.mobile?["all","both","mobile"]:["all","both","pc"]).includes(a.device.value)&&a.event.value.includes("process")&&l.push(a);return l},
[]))}).catch(()=>{}),(g=>{if(0!=g.length){var l=b=>{0!=Object.keys(c.formulaRecords).length?bst.view.records.set(c.app.id,{put:Object.values(c.formulaRecords).map(e=>bst.view.records.transform(e))},!1).then(e=>b()).catch(e=>bst.alert(bst.error.parse(e))):b()};"formula"in g.first()||(bst.alert(bst.error.config.update("Boost! OAuth Mail")),g=g.map(b=>{b.formula={value:[]};return b}));switch(c.type){case "create":case "edit":B(g,f.record).then(b=>l(()=>n(f))).catch(()=>{});break;case "detail":var a=
b=>{(e=>{bst.filter.scan(c.app,f.record,e.condition.value)?bst.filter.auth(e.user.value,e.organization.value,e.group.value).then(p=>{p&&bst.button.create(c.mobile,c.type,"kb-mail-button"+b.toString(),e.label.value,e.message.value,()=>B([e],f.record).then(k=>l(()=>bst.alert("Done!",()=>window.location.reload(!0)))).catch(()=>{}));b++;b<g.length&&a(b)}).catch(p=>{b++;b<g.length&&a(b)}):(b++,b<g.length&&a(b))})(g[b])};a(0);n(f);break;case "index":a=b=>{(e=>{bst.filter.auth(e.user.value,e.organization.value,
e.group.value).then(p=>{p&&(e.view.value&&e.view.value!=f.viewId.toString()||bst.button.create(c.mobile,c.type,"kb-mail-button"+b.toString(),e.label.value,e.message.value,()=>{bst.view.records.get(c.app.id,(c.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(k=>{let r=(h,d)=>{B([e],k[h],!0).then(m=>{bst.progressUpdate();h++;h<k.length?r(h,d):d()}).catch(()=>{})};0!=k.length?(bst.progressStart(k.length),r(0,()=>l(()=>bst.alert("Done!",()=>window.location.reload(!0))))):bst.alert("There are no records.")}).catch(k=>
bst.alert(bst.error.parse(k)))}));b++;b<g.length&&a(b)}).catch(p=>{b++;b<g.length&&a(b)})})(g[b])},a(0),n(f)}}else n(f)})(JSON.parse(q.tab).map((g,l)=>bst.extend({sIndex:{value:l.toString()}},g.setting)).reduce((g,l)=>{(c.mobile?["all","both","mobile"]:["all","both","pc"]).includes(l.device.value)&&l.event.value.includes(c.type)&&g.push(l);return g},[]))}catch(g){bst.alert(bst.error.parse(g)),n(f)}}).catch(w=>n(f)):n(f)}).catch(q=>n(f))})("mobile"==f.type.split(".").first(),(x=>{switch(x){case "submit":x=
f.type.split(".").slice(-3).first()}return x})(f.type.split(".").slice(-2).first()))}));bst.event.on("bst.omail.call",f=>new Promise((n,C)=>{bst.config[z].config.get().then(x=>{0!=Object.keys(x).length?bst.field.load(bst.config[z].app,!0).then(v=>{c.app={id:bst.config[z].app,fields:v.origin};c.fieldInfos=v;try{(u=>{0!=u.length?B(u,f.record,!0).then(q=>n(f)).catch(()=>n(f)):n(f)})(JSON.parse(x.tab).map((u,q)=>bst.extend({sIndex:{value:q.toString()}},u.setting)).reduce((u,q)=>{(f.mobile?["all","both",
"mobile"]:["all","both","pc"]).includes(q.device.value)&&q.event.value.includes(f.pattern)&&u.push(q);return u},[]))}catch(u){bst.alert(bst.error.parse(u)),n(f)}}).catch(v=>n(f)):n(f)}).catch(x=>n(f))}))})(kintone.$PLUGIN_ID);
