/*
* FileName "plugins.fusion.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(D=>{var b={},H=(h,u)=>new Promise((F,G)=>{var E=(t,q)=>{var c=(a,k,f)=>{var n=()=>{a++;a<h.source.value.length?c(a,k,f):(0!=h.sort.value.length&&(bst.progressStart(t.length,(()=>{var d="";switch(bst.operator.language){case "en":d="Sorting the statement details.";break;case "ja":d="\u5e33\u7968\u660e\u7d30\u306e\u30bd\u30fc\u30c8\u3092\u884c\u3063\u3066\u3044\u307e\u3059\u3002";break;case "zh":d="\u6b63\u5728\u6392\u5e8f\u8d26\u5355\u660e\u7ec6\u3002";break;case "zh-TW":d="\u6b63\u5728\u6392\u5e8f\u5e33\u55ae\u660e\u7d30\u3002"}return d})()),
t.each((d,r)=>{h.sort.value.each((e,m)=>{d[e.value.table.value].value.sort((l,w)=>{var v=0;e.value.fields.value.each((p,z)=>{switch(b.fieldInfos.parallelize[p.value.field.value].type){case "CALC":switch(b.fieldInfos.parallelize[p.value.field.value].format){case "NUMBER":case "NUMBER_DIGIT":z=l.value[p.value.field.value].value?parseFloat(l.value[p.value.field.value].value):0;var x=w.value[p.value.field.value].value?parseFloat(w.value[p.value.field.value].value):0;break;default:z=l.value[p.value.field.value].value,
x=w.value[p.value.field.value].value}break;case "CATEGORY":case "CHECK_BOX":case "CREATOR":case "FILE":case "GROUP_SELECT":case "MODIFIER":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "STATUS_ASSIGNEE":case "USER_SELECT":z=JSON.stringify(l.value[p.value.field.value].value);x=JSON.stringify(w.value[p.value.field.value].value);break;case "NUMBER":z=l.value[p.value.field.value].value?parseFloat(l.value[p.value.field.value].value):0;x=w.value[p.value.field.value].value?parseFloat(w.value[p.value.field.value].value):
0;break;default:z=l.value[p.value.field.value].value,x=w.value[p.value.field.value].value}switch(p.value.order.value){case "asc":z>x&&(v=1);z<x&&(v=-1);break;case "desc":z>x&&(v=-1),z<x&&(v=1)}if(v)return BST_BREAK});return v})});bst.progressUpdate()})),f(t))};((d,r)=>{bst.progressStart(t.length,(()=>{var e="";switch(bst.operator.language){case "en":e="Registering "+d.name+" data.";break;case "ja":e=d.name+"\u306e\u30c7\u30fc\u30bf\u3092\u767b\u9332\u3057\u3066\u3044\u307e\u3059\u3002";break;case "zh":e=
"\u6b63\u5728\u767b\u8bb0"+d.name+"\u6570\u636e\u3002";break;case "zh-TW":e="\u6b63\u5728\u767b\u9304"+d.name+"\u8cc7\u6599\u3002"}return e})());bst.view.records.get(d.id,(e=>{var m=[],l=w=>d.isTimeStamp?(w.getTime()/1E3).toString():d.isDateTime?w.toISOString():w.format("Y-m-d");m.push(d.date+(d.fieldInfos.parallelize[d.date].tableCode?' not in ("")':'!=""'));m.push(d.date+'>"'+l(e.start)+'"');m.push(d.date+'<"'+l(e.end)+'"');return m.join(" and ")})({start:(e=>d.isDateTime?e.calc("1 day").calc("-1 second").calc(bst.timezoneOffset()+
" hour"):e)(new Date(k?k:"1900-01-01")),end:(e=>d.isDateTime?e.calc("1 day").calc(bst.timezoneOffset()+" hour"):e.calc("1 day"))(new Date(b.preset.date))})).then(e=>{(m=>{t.each((l,w)=>{(v=>{e.each((p,z)=>{var x=bst.filter.scan({id:d.id,fields:d.fieldInfos.origin},p,(y=>{y&&(y+=" and ");return y+d.client+'="'+l[h.client.value].value+'" and '+d.date+'>"'+v.start+'" and '+d.date+'<"'+v.end+'"'})(d.filter));x&&(p=[],m?p=x[m].value.reduce((y,A)=>{for(var B in d.mapping){var C=d.mapping[B];C in A.value||
(A.value[C]={value:x[C].value})}y.push(A.value);return y},[]):p.push(x),l[r].value=(y=>{1==y.length&&(Object.values(y.first().value).some(A=>!bst.field.isEmpty(A.value))||y.pop());return y})(l[r].value),Array.prototype.push.apply(l[r].value,p.map(y=>({value:Object.entries(d.mapping).reduce((A,[B,C])=>{A[B].value=y[C].value;b.fieldInfos.parallelize[B].lookup&&(A[B].lookup=!0);return A},bst.extend({},b.preset.template.table[r]))}))))});bst.progressUpdate()})({start:(v=>d.isDateTime?v.calc("1 day").calc("-1 second").calc(bst.timezoneOffset()+
" hour").toISOString():v.format("Y-m-d"))(new Date(l[h.client.value].value in b.preset.latest?b.preset.latest[l[h.client.value].value]:k)),end:(v=>d.isDateTime?v.calc("1 day").calc(bst.timezoneOffset()+" hour").toISOString():v.calc("1 day").format("Y-m-d"))(new Date(b.preset.date))})});n()})(Object.values(d.mapping).map(m=>d.fieldInfos.parallelize[m].tableCode).filter(m=>m).first())}).catch(e=>bst.alert(bst.error.parse(e)))})(b.appInfos["_"+a.toString()],h.source.value[a].value.table.value)},g=(a,
k)=>{(f=>{f?kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:b.app.id,query:h.client.value+'="'+f[h.client.value].value+'" and '+h.issueDate.value+'<"'+f[h.issueDate.value].value+'" order by '+(h.issueDate.value+" desc,$id desc limit 1 offset 0")}).then(n=>{0!=n.records.length&&(f[h.previousAmount.value]={value:n.records.first()[h.totalAmount.value].value},(n=n.records.first()[h.issueDate.value].value)&&(b.preset.latest[f[h.client.value].value]=n));bst.progressUpdate();a++;a<t.length?g(a,
k):k(t)}).catch(n=>bst.alert(bst.error.parse(n))):(a++,a<t.length?g(a,k):k(t))})(t[a])};bst.progressStart(t.length,(()=>{var a="";switch(bst.operator.language){case "en":a="Registering previous amount data.";break;case "ja":a="\u524d\u56de\u91d1\u984d\u30c7\u30fc\u30bf\u3092\u767b\u9332\u3057\u3066\u3044\u307e\u3059\u3002";break;case "zh":a="\u6b63\u5728\u767b\u8bb0\u4e0a\u6b21\u91d1\u989d\u6570\u636e\u3002";break;case "zh-TW":a="\u6b63\u5728\u767b\u9304\u4e0a\u6b21\u91d1\u984d\u8cc7\u6599\u3002"}return a})());
g(0,a=>{c(0,0!=Object.values(b.preset.latest).length?Object.values(b.preset.latest).sort().first():"1900-01-01",k=>q(k))})};b.preset.latest={};(t=>{var q=(c,g,a)=>{var k=()=>{c++;c<g.length?q(c,g,a):a(g)};(f=>{f?kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:b.app.id,query:h.client.value+'="'+f[h.client.value].value+'" and '+h.issueDate.value+'="'+f[h.issueDate.value].value+'" order by $id desc limit 1 offset 0'}).then(n=>{0!=n.records.length&&(f.$id={value:n.records.first().$id.value});
bst.progressUpdate();k()}).catch(n=>bst.alert(bst.error.parse(n))):k()})(g[c])};bst.progressStart(0,(()=>{var c="";switch(bst.operator.language){case "en":c="Downloading client data.";break;case "ja":c="\u53d6\u5f15\u5148\u30c7\u30fc\u30bf\u3092\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u3057\u3066\u3044\u307e\u3059\u3002";break;case "zh":c="\u6b63\u5728\u4e0b\u8f7d\u53d6\u5f15\u5148\u6570\u636e\u3002";break;case "zh-TW":c="\u6b63\u5728\u4e0b\u8f09\u53d6\u5f15\u5148\u8cc7\u6599\u3002"}return c})());(c=>
{(g=>{g.lookup?bst.view.records.get(g.lookup.relatedApp.app,(a=>{g.lookup.filterCond&&a.push("("+g.lookup.filterCond+")");return a.join(" and ")})(Object.entries(u).map(([a,k])=>a+' in ("'+k+'")')),g.lookup.sort||"$id asc").then(a=>{bst.progressStart(a.length,(()=>{var k="";switch(bst.operator.language){case "en":k="Creating records for registration.";break;case "ja":k="\u767b\u9332\u7528\u30ec\u30b3\u30fc\u30c9\u3092\u4f5c\u6210\u3057\u3066\u3044\u307e\u3059\u3002";break;case "zh":k="\u6b63\u5728\u521b\u5efa\u7528\u4e8e\u6ce8\u518c\u7684\u8bb0\u5f55\u3002";
break;case "zh-TW":k="\u6b63\u5728\u5efa\u7acb\u7528\u65bc\u8a3b\u518a\u7684\u8a18\u9304\u3002"}return k})());c(a.map(k=>{var f=bst.extend({},b.preset.template.record);f[h.client.value]={value:k[g.lookup.relatedKeyField].value,lookup:!0};f[h.issueDate.value]={value:b.preset.date};bst.progressUpdate();return f}))}).catch(a=>bst.alert(bst.error.parse(a))):bst.alert("No client field to fusion was found")})(b.fieldInfos.parallelize[h.client.value])})(c=>{bst.progressStart(c.length,(()=>{var g="";switch(bst.operator.language){case "en":g=
"Checking registered records.";break;case "ja":g="\u767b\u9332\u6e08\u30ec\u30b3\u30fc\u30c9\u3092\u8abf\u3079\u3066\u3044\u307e\u3059\u3002";break;case "zh":g="\u6b63\u5728\u68c0\u67e5\u5df2\u6ce8\u518c\u7684\u8bb0\u5f55\u3002";break;case "zh-TW":g="\u6b63\u5728\u6aa2\u67e5\u5df2\u8a3b\u518a\u7684\u8a18\u9304\u3002"}return g})());q(0,c,g=>t(g))})})(t=>{E(t,q=>{var c={},g=(a,k)=>{0!=q.length?bst.event.call("bst.action.call",{container:bst.elm("body"),record:q[a],mobile:b.mobile,pattern:"change",fields:Object.values(b.fieldInfos.parallelize).reduce((f,
n)=>{n.tableCode&&(f.includes(n.tableCode)||f.push(n.tableCode));f.push(n.code);return f},[]),stopPropagation:!0,workplace:"view"}).then(f=>{f.error||bst.event.call("bst.submit.call",{record:f.record,mobile:f.mobile,numbering:c,pattern:f.record.$id.value?"edit":"create",workplace:"view"}).then(n=>{n.error||(a++,a<q.length?g(a,k):k())}).catch(()=>{})}).catch(()=>{}):k()};g(0,()=>{F({records:{post:q.filter(a=>!a.$id.value),put:q.reduce((a,k)=>{k.$id.value&&a.push({id:k.$id.value,record:k});return a},
[])}})})})})});kintone.events.on(["app.record.index.show","mobile.app.record.index.show"],h=>new Promise((u,F)=>{((G,E)=>{b.mobile=G;b.type=E;bst.config[D].config.get().then(t=>{0!=Object.keys(t).length?bst.field.load(bst.config[D].app,!0).then(q=>{b.app={id:bst.config[D].app,fields:q.origin};b.fieldInfos=q;b.preset={date:(new Date).format("Y-m-d"),template:{record:bst.record.create(b.app),table:Object.keys(q.tables).reduce((c,g)=>{c[g]=bst.record.create(q.origin[g],!1);return c},{})}};try{(c=>{c?
(()=>{var g=[];c.source.value=c.source.value.map(a=>{a.value.fields.value=JSON.parse(a.value.fields.value);g.push(a.value.table.value);return a});c.sort.value=c.sort.value.map(a=>{a.value.fields.value=JSON.parse(a.value.fields.value);g.push(a.value.table.value);return a});return g})().some(g=>!(g in q.tables))?(bst.alert("No table to fusion was found"),u(h)):[c.client.value,c.issueDate.value,c.totalAmount.value,c.previousAmount.value,...c.source.value.map(g=>g.value.fields.value.mapping.value.map(a=>
a.value.internal.value)).flat(),...c.sort.value.map(g=>g.value.fields.value.map(a=>a.value.field.value)).flat()].some(g=>!(g in q.parallelize))?(bst.alert("No field to fusion was found"),u(h)):bst.filter.auth(c.user.value,c.organization.value,c.group.value).then(g=>{g&&(c.view.value&&c.view.value!=h.viewId.toString()||bst.apps.load().then(a=>{var k=(f,n)=>{(d=>{((r,e)=>{r?bst.field.load(r.appId).then(m=>{(l=>[l.client.value,l.date.value,...l.mapping.value.map(w=>w.value.external.value)])(d.value.fields.value).some(l=>
!(l in m.parallelize))?(bst.alert("No field to fusion was found ["+r.name+"]"),u(h)):(b.appInfos[e]={id:r.appId,name:r.name,fieldInfos:m,client:d.value.fields.value.client.value,date:d.value.fields.value.date.value,filter:d.value.fields.value.filter.value,mapping:Object.fromEntries(d.value.fields.value.mapping.value.map(l=>[l.value.internal.value,l.value.external.value])),isDateTime:!1,isTimeStamp:!1},(l=>{switch(l.type){case "CALC":switch(l.format){case "DATE":b.appInfos[e].isDateTime=!1;break;case "DATETIME":b.appInfos[e].isDateTime=
!0}b.appInfos[e].isTimeStamp=!0;break;case "DATE":b.appInfos[e].isDateTime=!1;b.appInfos[e].isTimeStamp=!1;break;case "DATETIME":b.appInfos[e].isDateTime=!0;b.appInfos[e].isTimeStamp=!1;break;default:b.appInfos[e].isDateTime=!1,b.appInfos[e].isTimeStamp=!1}})(m.parallelize[d.value.fields.value.date.value]),f++,f<c.source.value.length?k(f,n):n())}).catch(m=>{bst.alert(bst.error.parse(m));u(h)}):(bst.alert("No app to fusion was found"),u(h))})(a.find(r=>r.appId==d.value.app.value),"_"+f.toString())})(c.source.value[f])};
b.appInfos={};b.appInfos[b.app.id]={id:b.app.id,name:a.find(f=>f.appId==b.app.id).name,fieldInfos:q};(f=>{f?bst.field.load(f.appId).then(n=>{(d=>{d.some(r=>!(r in n.parallelize))?(bst.alert("No field to fusion was found ["+f.name+"]"),u(h)):(b.appInfos[f.appId]={id:f.appId,name:f.name,fieldInfos:n},k(0,()=>{(r=>{r.elm(".bst-fusion-operation")||(r.addClass("bst-scope").attr("form-id","form_Fusion").append(bst.create("div").addClass("bst-fusion-operation"+(b.mobile?" bst-mobile":"")).append(bst.create("button").addClass("bst-fusion-pickup-button").on("click",
e=>{(m=>{bst.pickupDate(b.preset.date,l=>{b.preset.date=l;m.html(b.preset.date)})})(e.currentTarget.nextElementSibling)})).append(bst.create("span").addClass("bst-fusion-pickup-guide").html(b.preset.date))),d.map(e=>n.parallelize[e]).each((e,m)=>{m={id:"Fusion",fields:{[e.code]:{code:e.code,type:"DROP_DOWN",label:"",required:!1,noLabel:!0,options:e.options}}};r.append(bst.create("div").addClass("bst-fusion-operation"+(b.mobile?" bst-mobile":"")).append(bst.field.activate(bst.field.create(m.fields[e.code]).addClass("bst-"+
e.code),m)))}));bst.button.create(b.mobile,b.type,"bst-fusion-button",c.label.value,c.message.value,()=>{H(c,d.reduce((e,m)=>{e[m]=r.elm(".bst-"+CSS.escape(m)).elm("select").val();return e},{})).then(e=>{bst.view.records.set(b.app.id,e.records,!0).then(m=>bst.alert("Done!",()=>window.location.reload(!0))).catch(m=>bst.alert(bst.error.parse(m)))}).catch(()=>{})})})(b.mobile?kintone.mobile.app.getHeaderSpaceElement():kintone.app.getHeaderMenuSpaceElement())}))})(c.category.value.map(d=>d.value.field.value))}).catch(n=>
{bst.alert(bst.error.parse(n));u(h)}):(bst.alert("No app to fusion was found"),u(h))})(a.find(f=>f.appId==q.parallelize[c.client.value].lookup.relatedApp.app))}));u(h)}).catch(g=>u(h)):u(h)})(JSON.parse(t.flat))}catch(c){bst.alert(bst.error.parse(c)),u(h)}}).catch(q=>u(h)):u(h)}).catch(t=>u(h))})("mobile"==h.type.split(".").first(),h.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
