/*
* FileName "plugins.submit.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(z=>{var b={handlers:{}},A=(k,e,v=!1,w={},y="record")=>new Promise((r,p)=>{var x=[],t=(g,a)=>{var n=()=>{g++;g<k.length?t(g,a):a()};(f=>{bst.filter.scan(b.app,e,f.condition.value)?bst.filter.auth(f.user.value,f.organization.value,f.group.value).then(q=>{if(q){var u={duplicate:l=>{try{f.duplicateCriteria.value.some(c=>!(c.value.external.value in b.fieldInfos.parallelize&&c.value.internal.value in b.fieldInfos.parallelize))?(bst.alert("No field to lookup was found"),p()):(c=>{c&&x.push(c);l()})(f.duplicateCriteria.value.reduce((c,
d)=>{var h=b.fieldInfos.parallelize[d.value.external.value],m=d.value.operator.value;d=b.fieldInfos.parallelize[d.value.internal.value];f.duplicateFilled.value.includes("filled")&&bst.field.isEmpty(e[d.code].value)||c.push(bst.filter.query.create(h,m,e[d.code]));return c},[]).join(" and "))}catch(c){bst.alert(bst.error.parse(c)),p()}},error:l=>{try{if(f.errorMessage.value||0!=f.errorField.value.length){var c=bst.filter.scan(b.app,e,f.errorFilter.value);c?(f.errorField.value.each((d,h)=>{d.value.field.value in
b.fieldInfos.parallelize&&(m=>{m.tableCode?c[m.tableCode].value.each((B,C)=>{B.value[d.value.field.value].error=d.value.message.value}):e[d.value.field.value].error=d.value.message.value})(b.fieldInfos.parallelize[d.value.field.value])}),v||bst.loadEnd(),r({error:!0,message:f.errorMessage.value})):l()}else l()}catch(d){bst.alert(bst.error.parse(d)),p()}},numbering:l=>{try{if(f.numberingField.value in b.fieldInfos.parallelize)if(e[f.numberingField.value].value)l();else{var c="",d=f.numberingGroup.value.reduce((h,
m)=>{if(m.value.field.value in b.fieldInfos.parallelize)switch(c+=e[m.value.field.value].value,b.fieldInfos.parallelize[m.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":h.push(m.value.field.value+' in ("'+e[m.value.field.value].value+'")');break;default:h.push(m.value.field.value+'="'+e[m.value.field.value].value+'"')}return h},"$id"in e?['$id!="'+e.$id.value+'"']:[]);c in w?(w[c]++,e[f.numberingField.value].value=c+w[c].toString().lpad("0",parseInt(f.numberingDigits.value)),l()):kintone.api(kintone.api.url("/k/v1/records",
!0),"GET",{app:b.app.id,query:d.join(" and ")+" order by "+f.numberingField.value+" desc limit 1 offset 0"}).then(h=>{h=h.records;var m=0;0!=h.length&&(m=parseInt((h.first()[f.numberingField.value].value||" ").replace(/[ ]+/g,"").replace(new RegExp("^"+c,"g"),"")),bst.isNumeric(m)||(m=0));m++;h=m;w[c]=h;e[f.numberingField.value].value=c+h.toString().lpad("0",parseInt(f.numberingDigits.value));l()}).catch(h=>{bst.alert(bst.error.parse(h));p()})}else l()}catch(h){bst.alert(bst.error.parse(h)),p()}},
prompt:l=>{try{(c=>{0!=c.length?(d=>{c.each((h,m)=>{d.append(bst.field.activate(bst.field.create(h).css({width:"100%"}),b.app,!1))});v||bst.loadEnd();(new BooooooostPopupform(d,600,"full",{ok:()=>{var h=bst.record.get(d,b.app,!0);c.each((m,B)=>{e[m.code].value=h.record[m.code].value});v||bst.loadStart();l()},cancel:()=>{v||bst.loadStart();l()}})).show()})(bst.create("div").addClass("bst-scope").attr("form-id","form_"+b.app.id)):l()})(f.promptField.value.reduce((c,d)=>{d.value.field.value in b.fieldInfos.parallelize&&
(f.promptOverwrite.value.includes("overwrite")?c.push(b.fieldInfos.parallelize[d.value.field.value]):bst.field.isEmpty(e[d.value.field.value].value)&&c.push(b.fieldInfos.parallelize[d.value.field.value]));return c},[]))}catch(c){bst.alert(bst.error.parse(c)),p()}},verify:l=>{try{(c=>{0!=c.length?(d=>{c.each((h,m)=>{d.append(bst.field.activate(bst.field.create(h).addClass("bst-readonly").css({width:"100%"}),b.app,!1))});bst.record.set(d,b.app,e);v||bst.loadEnd();(new BooooooostPopupform(d,600,"full",
{ok:()=>{v||bst.loadStart();l()},cancel:()=>{v||bst.loadEnd();r({error:!0})}})).show()})(bst.create("div").addClass("bst-scope bst-verify").attr("form-id","form_"+b.app.id).append(bst.create("p").html(f.verifyMessage.value))):l()})(f.verifyField.value.reduce((c,d)=>{d.value.field.value in b.fieldInfos.parallelize&&c.push(b.fieldInfos.parallelize[d.value.field.value]);return c},[]))}catch(c){bst.alert(bst.error.parse(c)),p()}}};u.numbering(()=>{"saved"!=y?u.prompt(()=>{u.verify(()=>{u.error(()=>{u.duplicate(()=>
{n()})})})}):n()})}else n()}).catch(q=>{bst.alert(bst.error.parse(q));p()}):n()})(k[g])};v||bst.loadStart();t(0,()=>{v||bst.loadEnd();0!=x.length?kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:b.app.id,query:((g,a)=>(a?"$id!="+a+" and ("+g+")":g)+" order by $id asc limit 5 offset 0")(x.map(g=>"("+g+")").join(" or "),"$id"in e?e.$id.value:"")}).then(g=>{0!=g.records.length?bst.confirm((a=>{g.records.each(n=>{a.append(bst.create("p").css({margin:"0"}).append(bst.create("a").attr("href",
bst.record.page.detail(b.mobile,b.app.id,n.$id.value)).attr("target","_blank").html("Record No: "+n.$id.value)))});return a})(bst.create("div").append(bst.create("p").css({margin:"0"}).html(bst.constants.submit.message.duplicate[bst.operator.language]))),a=>{r({error:a})},!0):r({error:!1})}).catch(g=>{bst.alert(bst.error.parse(g),()=>{r({error:!1})})}):r({error:!1})})});kintone.events.on("app.record.create.submit app.record.detail.show app.record.edit.submit app.record.index.show mobile.app.record.create.submit mobile.app.record.detail.show mobile.app.record.edit.submit mobile.app.record.index.show".split(" "),
k=>new Promise((e,v)=>{((w,y)=>{b.mobile=w;b.type=y;for(var r in b.handlers)b.handlers[r].each((p,x)=>{kintone.events.off(r,p)});bst.config[z].config.get().then(p=>{0!=Object.keys(p).length?bst.field.load(bst.config[z].app,!0).then(x=>{b.app={id:bst.config[z].app,fields:x.origin};b.fieldInfos=x;try{["detail"].includes(b.type)&&kintone.app.record.getPermissions().then(t=>{t.editRecord&&(g=>{0!=g.length&&("duplicateFilled"in g.first()||(bst.alert(bst.error.config.update("Boost! Submit")),g.each(a=>
{a.duplicateFilled={value:[]}})),((a,n)=>{kintone.events.on(a,n);a.each((f,q)=>{f in b.handlers||(b.handlers[f]=[]);b.handlers[f].push(n)})})(["app.record.detail.process.proceed","mobile.app.record.detail.process.proceed"],a=>new Promise((n,f)=>{try{(q=>{0!=q.length?A(q,a.record).then(u=>{u.error&&(a.error="message"in u?u.message:bst.constants.submit.message.cancel.submit[bst.operator.language]);n(a)}).catch(()=>{a.error=bst.constants.submit.message.cancel.submit[bst.operator.language];n(a)}):n(a)})(g.filter(q=>
q.action.value==a.action.value+":"+a.status.value+":"+a.nextStatus.value))}catch(q){bst.alert(bst.error.parse(q)),n(a)}})))})(JSON.parse(p.tab).map((g,a)=>bst.extend({sIndex:{value:a.toString()}},g.setting)).reduce((g,a)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(a.device.value)&&a.event.value.includes("process")&&g.push(a);return g},[]))}).catch(()=>{}),(t=>{if(0!=t.length)switch("duplicateFilled"in t.first()||(bst.alert(bst.error.config.update("Boost! Submit")),t.each(a=>
{a.duplicateFilled={value:[]}})),b.type){case "create":case "edit":A(t,k.record).then(a=>{a.error&&(k.error="message"in a?a.message:bst.constants.submit.message.cancel.submit[bst.operator.language]);e(k)}).catch(()=>{k.error=bst.constants.submit.message.cancel.submit[bst.operator.language];e(k)});(a=>{if(0!=a.length)kintone.events.on((b.mobile?"mobile.":"")+"app.record."+b.type+".submit.success",n=>new Promise((f,q)=>{var u=l=>{(c=>{bst.filter.scan(b.app,n.record,c.condition.value)?bst.filter.auth(c.user.value,
c.organization.value,c.group.value).then(d=>{if(d){d=c.url.value;var h=n.record,m;for(m in h)d=d.replace(new RegExp("%"+m+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[m],h[m].value," / "));n.url=d}l++;l<a.length&&u(l)}).catch(d=>{l++;l<a.length&&u(l)}):(l++,l<a.length&&u(l))})(a[l])};u(0);f(n)}))})(t.filter(a=>a.url.value));break;case "index":var g=a=>{(n=>{bst.filter.auth(n.user.value,n.organization.value,n.group.value).then(f=>{f&&(n.view.value&&n.view.value!=k.viewId.toString()||bst.button.create(b.mobile,
b.type,"bst-submit-button"+a.toString(),n.label.value,n.message.value,()=>{bst.view.records.get(b.app.id,(b.mobile?kintone.mobile.app:kintone.app).getQueryCondition(),(q=>{q=q.match(/order by/g)?q.replace(/^.*order by/g,""):"";return(q=q.replace(/limit [0-9]+/g,"").replace(/ offset [0-9]+/g,"").replace(/^[ ]+/g,"").replace(/[ ]+$/g,""))?q:"$id asc"})((b.mobile?kintone.mobile.app:kintone.app).getQuery())).then(q=>{var u={},l=[];let c=(d,h)=>{A([n],q[d],!0,u,"saved").then(m=>{m.error?h(!0):(l.push(bst.view.records.transform(q[d])),
bst.progressUpdate(),d++,d<q.length?c(d,h):h())}).catch(()=>{})};0!=q.length?(bst.progressStart(q.length),c(0,d=>{d||bst.view.records.set(b.app.id,{put:l}).then(h=>bst.alert("Done!",()=>window.location.reload(!0))).catch(h=>bst.alert(bst.error.parse(h)))})):bst.alert("There are no records.")}).catch(q=>bst.alert(bst.error.parse(q)))}));a++;a<t.length&&g(a)}).catch(f=>{a++;a<t.length&&g(a)})})(t[a])};g(0);e(k)}else e(k)})(JSON.parse(p.tab).map((t,g)=>bst.extend({sIndex:{value:g.toString()}},t.setting)).reduce((t,
g)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(g.device.value)&&g.event.value.includes(b.type)&&t.push(g);return t},[]))}catch(t){bst.alert(bst.error.parse(t)),e(k)}}).catch(x=>e(k)):e(k)}).catch(p=>e(k))})("mobile"==k.type.split(".").first(),k.type.split(".").slice(-2).first())}));bst.event.on("bst.submit.call",k=>new Promise((e,v)=>{bst.config[z].config.get().then(w=>{0!=Object.keys(w).length?bst.field.load(bst.config[z].app,!0).then(y=>{b.app={id:bst.config[z].app,fields:y.origin};
b.fieldInfos=y;try{(r=>{0!=r.length?("duplicateFilled"in r.first()||(bst.alert(bst.error.config.update("Boost! Submit")),r.each(p=>{p.duplicateFilled={value:[]}})),A(r,k.record,!0,k.numbering).then(p=>{p.error?(k.error=!0,p.message?bst.alert(p.message,()=>e(k)):e(k)):e(k)}).catch(()=>{k.error=!0;e(k)})):e(k)})(JSON.parse(w.tab).map((r,p)=>bst.extend({sIndex:{value:p.toString()}},r.setting)).reduce((r,p)=>{(k.mobile?["all","both","mobile"]:["all","both","pc"]).includes(p.device.value)&&p.event.value.includes(k.pattern)&&
r.push(p);return r},[]))}catch(r){bst.alert(bst.error.parse(r)),e(k)}}).catch(y=>e(k)):e(k)}).catch(w=>e(k))}))})(kintone.$PLUGIN_ID);
bst.constants=bst.extend({submit:{message:{cancel:{process:{en:"The process action was canceled.",ja:"\u30d7\u30ed\u30bb\u30b9\u30a2\u30af\u30b7\u30e7\u30f3\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u8fdb\u7a0b\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002","zh-TW":"\u8655\u7406\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002"},submit:{en:"The submit was canceled.",ja:"\u4fdd\u5b58\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u4fdd\u5b58\u5df2\u88ab\u53d6\u6d88\u3002",
"zh-TW":"\u63d0\u4ea4\u5df2\u88ab\u53d6\u6d88\u3002"}},duplicate:{en:"A similar record already exists. Would you like to proceed with the registration anyway?",ja:"\u985e\u4f3c\u30ec\u30b3\u30fc\u30c9\u304c\u65e2\u306b\u767b\u9332\u3055\u308c\u3066\u3044\u307e\u3059\u304c\u3001\u3053\u306e\u307e\u307e\u767b\u9332\u3057\u3066\u3082\u5b9c\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u7ecf\u6709\u7c7b\u4f3c\u7684\u8bb0\u5f55\u5b58\u5728\u4e86\uff0c\u60a8\u8fd8\u8981\u7ee7\u7eed\u6ce8\u518c\u5417\uff1f",
"zh-TW":"\u5df2\u7d93\u6709\u985e\u4f3c\u7684\u8a18\u9304\u5b58\u5728\u4e86\uff0c\u60a8\u9084\u8981\u7e7c\u7e8c\u8a3b\u518a\u55ce\uff1f"}}}},bst.constants);
