/*
* FileName "plugins.upsert.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(J=>{var h={handlers:{}},M=(m,v,K=!1)=>new Promise((B,y)=>{var x=(t,G)=>{var p=(c,f)=>{t++;c&&f.formulaSource.value.map(b=>b.value).each((b,g)=>{b.field.value in h.fieldInfos.parallelize&&(g=h.fieldInfos.parallelize[b.field.value],g.tableCode||(c[g.code].value=bst.formula.calculate(b,c,c,v,h.fieldInfos.parallelize),g.lookup&&(c[g.code].lookup=!0),b=c.$id.value,b in h.formulaRecords||(h.formulaRecords[b]={$id:{value:b}}),h.formulaRecords[b][g.code]=c[g.code]))});t<m.length?x(t,G):G()};(c=>{var f=bst.filter.scan(h.app,
v,c.condition.value);f?bst.filter.auth(c.user.value,c.organization.value,c.group.value).then(b=>{b?bst.field.load(c.app.value).then(g=>{var w={id:c.app.value,fields:g.origin};(q=>{var H=[],C=[],L=[],D={},E={table:"",index:l=>E.table&&E.table==l.tableCode?u.progress.record:u.progress.row},u={record:1,row:1,progress:{record:0,row:0}},N=()=>{var l=[],r={field:(e,d)=>{d=e.tableCode?f[e.tableCode].value.length>d?f[e.tableCode].value[d].value[e.code]:bst.record.create({fields:{empty:e}}).empty:f[e.code];
return bst.extend({type:e.type},d)},record:e=>{u.row.each(d=>{var A=(a=>{var n=bst.filter.scan(w,e,a.query);if(!n&&"upsert"==c.pattern.value){for(var k in a.rows)0==bst.filter.result[k].value.length&&(e[k].value.push({value:bst.extend({},a.rows[k])}),bst.filter.result[k]={value:[e[k].value.last()]});n=bst.filter.result}return n})((()=>{var a={rows:{},query:[]};u.progress.row=d;H.each((n,k)=>{n.external.tableCode&&(n.external.tableCode in a.rows||(a.rows[n.external.tableCode]=bst.record.create(w.fields[n.external.tableCode],
!1)),k=r.field(n.internal,E.index(n.internal)),["=","in"].includes(n.operator.trim())&&(a.rows[n.external.tableCode][n.external.code]=z(n.external,k)),a.query.push(bst.filter.query.create(n.external,n.operator,k)))});C.each((n,k)=>{n.field.tableCode&&a.query.push(n.field.code+" "+n.operator+" "+n.value)});a.query=a.query.join(" and ");return a})());A&&L.each((a,n)=>{a.external.tableCode?a.external.tableCode in D?(e[a.external.tableCode]={value:D[a.external.tableCode]},D[a.external.tableCode].each((k,
I)=>{k.value[a.external.code]=z(a.external,r.field(a.internal,I));"FILE"==a.external.type&&k.value[a.external.code].value&&Array.prototype.push.apply(l,k.value[a.external.code].value)})):A[a.external.tableCode].value.each((k,I)=>{k.value[a.external.code]=z(a.external,r.field(a.internal,E.index(a.internal)));"FILE"==a.external.type&&k.value[a.external.code].value&&Array.prototype.push.apply(l,k.value[a.external.code].value)}):(e[a.external.code]=z(a.external,r.field(a.internal,u.progress.record)),
"FILE"==a.external.type&&e[a.external.code].value&&Array.prototype.push.apply(l,e[a.external.code].value))})});return e}},z=(e,d)=>{switch(e.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":Array.isArray(d.value)||(d.value=[d.value])}d.type=e.type;return e.lookup?bst.extend({lookup:!0},d):d},F=e=>{e.each((d,A)=>{c.formulaDestination.value.map(a=>a.value).each((a,n)=>{a.field.value in q.external&&(k=>{k.tableCode?d[k.tableCode].value.each((I,
O)=>{I.value[k.code].value=bst.formula.calculate(a,I.value,d,d,q.external);k.lookup&&(I.value[k.code].lookup=!0)}):(d[k.code].value=bst.formula.calculate(a,d,d,d,q.external),k.lookup&&(d[k.code].lookup=!0))})(q.external[a.field.value])})});return e};"insert"==c.pattern.value?(e=>{bst.file.clone(l,!0).then(()=>{bst.view.records.set(c.app.value,{post:e},K).then(d=>{u.progress.record++;u.progress.record<u.record?N():p(f,c)}).catch(d=>{bst.alert(bst.error.parse(d));y()})})})(F([r.record(bst.record.create(w))])):
bst.view.records.get(c.app.value,(()=>{var e=[];H.each((d,A)=>{d.external.tableCode||e.push(bst.filter.query.create(d.external,d.operator,r.field(d.internal,u.progress.record)))});C.each((d,A)=>{d.field.tableCode||e.push(d.field.code+" "+d.operator+" "+d.value)});return e.join(" and ")})()).then(e=>{e=(d=>{var A=[];0!=d.length?A=d.map(a=>r.record(a)):"upsert"==c.pattern.value&&(a=>{A.push(r.record((()=>{var n=bst.record.create(w);a.each((k,I)=>{k.external.tableCode?n[k.external.tableCode]={value:[]}:
["=","in"].includes(k.operator.trim())&&(n[k.external.code]=z(k.external,r.field(k.internal,u.progress.record)))});return n})()))})(H.filter(a=>!bst.field.reserved.includes(a.external.type)));return F(A)})(e);bst.file.clone(l,!0).then(()=>{bst.view.records.set(c.app.value,{post:e.filter(d=>!d.$id.value),put:e.reduce((d,A)=>{A.$id.value&&d.push(bst.view.records.transform(A));return d},[])},K).then(d=>{u.progress.record++;u.progress.record<u.record?N():p(f,c)}).catch(d=>{bst.alert(bst.error.parse(d));
y()})})}).catch(e=>{bst.alert(bst.error.parse(e));y()})};c.mapping.value.some(l=>!(l.value.external.value in q.external&&l.value.internal.value in q.internal))?(bst.alert("No field to transfer was found"),y()):c.criteria.value.some(l=>!(l.value.external.value in q.external&&l.value.internal.value in q.internal))?(bst.alert("No field to transfer was found"),y()):([...c.mapping.value,...c.criteria.value].each((l,r)=>{r=q.internal[l.value.internal.value];!q.external[l.value.external.value].tableCode&&
r.tableCode&&(E.table=r.tableCode,u.record=0==f[r.tableCode].value.length?0:f[r.tableCode].value.length)}),c.mapping.value.each((l,r)=>{((z,F)=>{z.tableCode&&(E.table&&E.table==F.tableCode||(D[z.tableCode]=(e=>{e=e?e.length:1;F.tableCode&&(e=e<f[F.tableCode].value.length?f[F.tableCode].value.length:e);return Array(e).fill().map(()=>({value:bst.record.create(w.fields[z.tableCode],!1)}))})(D[z.tableCode])));L.push({external:z,internal:F})})(q.external[l.value.external.value],q.internal[l.value.internal.value])}),
c.criteria.value.each((l,r)=>{r=q.external[l.value.external.value];var z=l.value.operator.value;l=q.internal[l.value.internal.value];r.tableCode&&(r.tableCode in D&&delete D[r.tableCode],!E.table&&l.tableCode&&(u.row=u.row<f[l.tableCode].value.length?f[l.tableCode].value.length:u.row));H.push({external:r,operator:z,internal:l})}),bst.filter.query.parse.expand({id:c.app.value,fields:g.origin},c.filter.value).each((l,r)=>{C.push({field:q.external[l.field],operator:l.operator,value:l.value})}),0!=u.record?
(u.progress.record=0,u.progress.row=0,N()):p())})({external:g.parallelize,internal:h.fieldInfos.parallelize})}).catch(g=>{bst.alert(bst.error.parse(g));y()}):p()}).catch(b=>{bst.alert(bst.error.parse(b));y()}):p()})(m[t])};K||bst.loadStart();x(0,()=>{K||bst.loadEnd();B()})});kintone.events.on("app.record.create.submit.success app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),
m=>new Promise((v,K)=>{((B,y)=>{h.mobile=B;h.type=y;for(var x in h.handlers)h.handlers[x].each((t,G)=>{kintone.events.off(x,t)});bst.config[J].config.get().then(t=>{0!=Object.keys(t).length?bst.field.load(bst.config[J].app,!0).then(G=>{h.app={id:bst.config[J].app,fields:G.origin};h.fieldInfos=G;h.formulaRecords={};try{["detail"].includes(h.type)&&kintone.app.record.getPermissions().then(p=>{p.editRecord&&(c=>{0!=c.length&&((f,b)=>{kintone.events.on(f,b);f.each((g,w)=>{g in h.handlers||(h.handlers[g]=
[]);h.handlers[g].push(b)})})(["app.record.detail.process.proceed","mobile.app.record.detail.process.proceed"],f=>new Promise((b,g)=>{try{(w=>{0!=w.length?M(w,f.record).then(q=>b(f)).catch(()=>{}):b(f)})(c.filter(w=>w.action.value==f.action.value+":"+f.status.value+":"+f.nextStatus.value))}catch(w){bst.alert(bst.error.parse(w)),b(f)}}))})(JSON.parse(t.tab).map((c,f)=>bst.extend({sIndex:{value:f.toString()}},c.setting)).reduce((c,f)=>{(h.mobile?["all","both","mobile"]:["all","both","pc"]).includes(f.device.value)&&
f.event.value.includes("process")&&c.push(f);return c},[]))}).catch(()=>{}),(p=>{if(0!=p.length){"formula"in p.first()&&(bst.alert(bst.error.config.update("Boost! Upsert")),p.each(b=>{b.formulaDestination=b.formula;b.formulaSource={value:[]}}));var c=b=>{0!=Object.keys(h.formulaRecords).length?bst.view.records.set(h.app.id,{put:Object.values(h.formulaRecords).map(g=>bst.view.records.transform(g))},!1).then(g=>b()).catch(g=>bst.alert(bst.error.parse(g))):b()};switch(h.type){case "create":case "edit":M(p,
m.record).then(b=>c(()=>v(m))).catch(()=>{});break;case "detail":var f=b=>{(g=>{bst.filter.scan(h.app,m.record,g.condition.value)?bst.filter.auth(g.user.value,g.organization.value,g.group.value).then(w=>{w&&bst.button.create(h.mobile,h.type,"bst-upsert-button"+b.toString(),g.label.value,g.message.value,()=>M([g],m.record).then(q=>c(()=>bst.alert("Done!",()=>window.location.reload(!0)))).catch(()=>{}));b++;b<p.length&&f(b)}).catch(w=>{b++;b<p.length&&f(b)}):(b++,b<p.length&&f(b))})(p[b])};f(0);v(m);
break;case "index":f=b=>{(g=>{bst.filter.auth(g.user.value,g.organization.value,g.group.value).then(w=>{w&&(g.view.value&&g.view.value!=m.viewId.toString()||bst.button.create(h.mobile,h.type,"bst-upsert-button"+b.toString(),g.label.value,g.message.value,()=>{bst.view.records.get(h.app.id,(h.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(q=>{let H=(C,L)=>{M([g],q[C],!0).then(D=>{bst.progressUpdate();C++;C<q.length?H(C,L):L()}).catch(()=>{})};0!=q.length?(bst.progressStart(q.length),
H(0,()=>c(()=>bst.alert("Done!",()=>window.location.reload(!0))))):bst.alert("There are no records.")}).catch(q=>bst.alert(bst.error.parse(q)))}));b++;b<p.length&&f(b)}).catch(w=>{b++;b<p.length&&f(b)})})(p[b])},f(0),v(m)}}else v(m)})(JSON.parse(t.tab).map((p,c)=>bst.extend({sIndex:{value:c.toString()}},p.setting)).reduce((p,c)=>{(h.mobile?["all","both","mobile"]:["all","both","pc"]).includes(c.device.value)&&c.event.value.includes(h.type)&&p.push(c);return p},[]))}catch(p){bst.alert(bst.error.parse(p)),
v(m)}}).catch(G=>v(m)):v(m)}).catch(t=>v(m))})("mobile"==m.type.split(".").first(),(B=>{switch(B){case "submit":B=m.type.split(".").slice(-3).first()}return B})(m.type.split(".").slice(-2).first()))}));bst.event.on("bst.upsert.call",m=>new Promise((v,K)=>{bst.config[J].config.get().then(B=>{0!=Object.keys(B).length?bst.field.load(bst.config[J].app,!0).then(y=>{h.app={id:bst.config[J].app,fields:y.origin};h.fieldInfos=y;h.formulaRecords={};try{(x=>{0!=x.length?("formula"in x.first()&&(bst.alert(bst.error.config.update("Boost! Upsert")),
x.each(t=>{t.formulaDestination=t.formula;t.formulaSource={value:[]}})),M(x,m.record,!0).then(t=>v(m)).catch(()=>v(m))):v(m)})(JSON.parse(B.tab).map((x,t)=>bst.extend({sIndex:{value:t.toString()}},x.setting)).reduce((x,t)=>{(m.mobile?["all","both","mobile"]:["all","both","pc"]).includes(t.device.value)&&t.event.value.includes(m.pattern)&&x.push(t);return x},[]))}catch(x){bst.alert(bst.error.parse(x)),v(m)}}).catch(y=>v(m)):v(m)}).catch(B=>v(m))}))})(kintone.$PLUGIN_ID);
