/*
* FileName "plugins.omail.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(z=>{var b={handlers:{}},B=(f,n,C=!1)=>new Promise((x,v)=>{var u="",q=(w,h)=>{var l=()=>{w++;w<f.length?q(w,h):h()};(a=>{var c=bst.filter.scan(b.app,n,a.condition.value);c?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(e=>{if(e){var p=(k,r,g)=>{"HTML"==a.format.value&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var d in r){var m=r[d].value;d in b.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[d].type&&(m=m.replace(/\r/g,"").replace(/\n/g,
"<br>")),k=k.replace(new RegExp("%"+d+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[d],m," / ",!0)))}for(d in g)m=g[d].value,d in b.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[d].type&&(m=m.replace(/\r/g,"").replace(/\n/g,"<br>")),k=k.replace(new RegExp("%"+d+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[d],m," / ",!0)));return k};(k=>{var r=(g,d)=>{(m=>{var F=(t,y)=>{if(0!=m.attachment.length){var D=!1;window.hasOwnProperty("bst_report_temp")&&
m.attachment[t].fileKey in window.bst_report_temp&&(D=!0);D?(m.attachment[t].data=window.bst_report_temp[m.attachment[t].fileKey],t++,t<m.attachment.length?F(t,y):y()):bst.file.download(m.attachment[t],!0).then(A=>{bst.field.blobToBase64(A,G=>{m.attachment[t].data=G;t++;t<m.attachment.length?F(t,y):y()})}).catch(A=>{bst.alert(bst.error.parse(A));v()})}else y()};F(0,()=>{bst.encrypt(JSON.stringify(m.data),u).then(t=>{var y=fetch,D="https://api.booooooost.com/mail/oauth/"+bst.operator.language,A=JSON,
G=A.stringify;m.data=t.data;m.iv=t.iv;m.tag=t.tag;y(D,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:G.call(A,m)}).then(E=>{E.json().then(H=>{switch(E.status){case 200:g++;g<k.length?r(g,d):d();break;default:bst.alert(bst.error.parse(H)),v()}})}).catch(E=>{bst.alert(bst.error.parse(E));v()})}).catch(t=>{v()})})})(k[g])};0!=k.length?r(0,()=>{try{a.formula.value.map(g=>g.value).each((g,d)=>{g.field.value in b.fieldInfos.parallelize&&(d=b.fieldInfos.parallelize[g.field.value],d.tableCode||
(c[d.code].value=bst.formula.calculate(g,c,c,n,b.fieldInfos.parallelize),d.lookup&&(c[d.code].lookup=!0),g=c.$id.value,g in b.formulaRecords||(b.formulaRecords[g]={$id:{value:g}}),b.formulaRecords[g][d.code]=c[d.code]))}),l()}catch(g){bst.alert(bst.error.parse(g)),v()}}):l()})((()=>{var k=[];(b.fieldInfos.parallelize[a.to.value].tableCode?c[b.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:c}]).each((r,g)=>{r.value[a.to.value].value&&k.push({data:{client_id:a.client_id.value,client_secret:a.client_secret.value,
author:a.author.value,sender:a.sender.value,subdomain:location.host.split(".")[0],provider:(d=>{d="";switch(a.provider.value){case "GMail":d="google";break;case "Exchange Online":d="microsoft"}return d})(a.provider.value),to:r.value[a.to.value].value,cc:p(a.cc.value,c,b.fieldInfos.parallelize[a.to.value].tableCode?r.value:{}),bcc:p(a.bcc.value,c,b.fieldInfos.parallelize[a.to.value].tableCode?r.value:{}),html:"HTML"==a.format.value},subject:p(a.subject.value,c,b.fieldInfos.parallelize[a.to.value].tableCode?
r.value:{}),body:p(a.body.value,c,b.fieldInfos.parallelize[a.to.value].tableCode?r.value:{}),attachment:(()=>{var d=[];a.attachment.value&&a.attachment.value in b.fieldInfos.parallelize&&(d=(b.fieldInfos.parallelize[a.attachment.value].tableCode?r.value:c)[a.attachment.value].value);return d})()})});return k})())}else l()}).catch(e=>{bst.alert(bst.error.parse(e));v()}):l()})(f[w])};fetch("https://api.booooooost.com/mail/oauth/"+bst.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(w=>
{w.json().then(h=>{switch(w.status){case 200:u=h.passphrase;C||bst.loadStart();q(0,()=>{C||bst.loadEnd();x()});break;default:bst.alert(bst.error.parse(h)),v()}})}).catch(w=>{bst.alert(bst.error.parse(w));v()})});kintone.events.on("app.record.create.submit.success app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),f=>new Promise((n,
C)=>{((x,v)=>{b.mobile=x;b.type=v;for(var u in b.handlers)b.handlers[u].each((q,w)=>{kintone.events.off(u,q)});bst.config[z].config.get().then(q=>{0!=Object.keys(q).length?bst.field.load(bst.config[z].app,!0).then(w=>{b.app={id:bst.config[z].app,fields:w.origin};b.fieldInfos=w;b.formulaRecords={};try{["detail"].includes(b.type)&&kintone.app.record.getPermissions().then(h=>{h.editRecord&&(l=>{0!=l.length&&((a,c)=>{kintone.events.on(a,c);a.each((e,p)=>{e in b.handlers||(b.handlers[e]=[]);b.handlers[e].push(c)})})(["app.record.detail.process.proceed",
"mobile.app.record.detail.process.proceed"],a=>new Promise((c,e)=>{try{(p=>{0!=p.length?B(p,a.record).then(k=>c(a)).catch(()=>{}):c(a)})(l.filter(p=>p.action.value==a.action.value+":"+a.status.value+":"+a.nextStatus.value))}catch(p){bst.alert(bst.error.parse(p)),c(a)}}))})(JSON.parse(q.tab).map((l,a)=>bst.extend({sIndex:{value:a.toString()}},l.setting)).reduce((l,a)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(a.device.value)&&a.event.value.includes("process")&&l.push(a);return l},
[]))}).catch(()=>{}),(h=>{if(0!=h.length){var l=c=>{0!=Object.keys(b.formulaRecords).length?bst.view.records.set(b.app.id,{put:Object.values(b.formulaRecords).map(e=>bst.view.records.transform(e))},!1).then(e=>c()).catch(e=>bst.alert(bst.error.parse(e))):c()};switch(b.type){case "create":case "edit":B(h,f.record).then(c=>l(()=>n(f))).catch(()=>{});break;case "detail":var a=c=>{(e=>{bst.filter.scan(b.app,f.record,e.condition.value)?bst.filter.auth(e.user.value,e.organization.value,e.group.value).then(p=>
{p&&bst.button.create(b.mobile,b.type,"bst-mail-button"+c.toString(),e.label.value,e.message.value,()=>B([e],f.record).then(k=>l(()=>bst.alert("Done!",()=>window.location.reload(!0)))).catch(()=>{}));c++;c<h.length&&a(c)}).catch(p=>{c++;c<h.length&&a(c)}):(c++,c<h.length&&a(c))})(h[c])};a(0);n(f);break;case "index":a=c=>{(e=>{bst.filter.auth(e.user.value,e.organization.value,e.group.value).then(p=>{p&&(e.view.value&&e.view.value!=f.viewId.toString()||bst.button.create(b.mobile,b.type,"bst-mail-button"+
c.toString(),e.label.value,e.message.value,()=>{bst.view.records.get(b.app.id,(b.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(k=>{let r=(g,d)=>{B([e],k[g],!0).then(m=>{bst.progressUpdate();g++;g<k.length?r(g,d):d()}).catch(()=>{})};0!=k.length?(bst.progressStart(k.length),r(0,()=>l(()=>bst.alert("Done!",()=>window.location.reload(!0))))):bst.alert("There are no records.")}).catch(k=>bst.alert(bst.error.parse(k)))}));c++;c<h.length&&a(c)}).catch(p=>{c++;c<h.length&&a(c)})})(h[c])},
a(0),n(f)}}else n(f)})(JSON.parse(q.tab).map((h,l)=>bst.extend({sIndex:{value:l.toString()}},h.setting)).reduce((h,l)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(l.device.value)&&l.event.value.includes(b.type)&&h.push(l);return h},[]))}catch(h){bst.alert(bst.error.parse(h)),n(f)}}).catch(w=>n(f)):n(f)}).catch(q=>n(f))})("mobile"==f.type.split(".").first(),(x=>{switch(x){case "submit":x=f.type.split(".").slice(-3).first()}return x})(f.type.split(".").slice(-2).first()))}));bst.event.on("bst.omail.call",
f=>new Promise((n,C)=>{bst.config[z].config.get().then(x=>{0!=Object.keys(x).length?bst.field.load(bst.config[z].app,!0).then(v=>{b.app={id:bst.config[z].app,fields:v.origin};b.fieldInfos=v;try{(u=>{0!=u.length?B(u,f.record,!0).then(q=>n(f)).catch(()=>n(f)):n(f)})(JSON.parse(x.tab).map((u,q)=>bst.extend({sIndex:{value:q.toString()}},u.setting)).reduce((u,q)=>{(f.mobile?["all","both","mobile"]:["all","both","pc"]).includes(q.device.value)&&q.event.value.includes(f.pattern)&&u.push(q);return u},[]))}catch(u){bst.alert(bst.error.parse(u)),
n(f)}}).catch(v=>n(f)):n(f)}).catch(x=>n(f))}))})(kintone.$PLUGIN_ID);
