/*
* FileName "plugins.mail.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(z=>{var b={handlers:{}},C=(e,n,D=!1)=>new Promise((x,v)=>{var u="",r=(w,h)=>{var m=()=>{w++;w<e.length?r(w,h):h()};(a=>{var c=bst.filter.scan(b.app,n,a.condition.value);c?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(d=>{if(d){var q=(k,t,f)=>{"HTML"==a.format.value&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var g in t){var l=t[g].value;g in b.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[g].type&&(l=l.replace(/\r/g,"").replace(/\n/g,
"<br>")),k=k.replace(new RegExp("%"+g+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[g],l," / ",!0)))}for(g in f)l=f[g].value,g in b.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[g].type&&(l=l.replace(/\r/g,"").replace(/\n/g,"<br>")),k=k.replace(new RegExp("%"+g+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[g],l," / ",!0)));return k};(k=>{var t=(f,g)=>{(l=>{var B=(p,y)=>{if(0!=l.attachment.length){var E=!1;window.hasOwnProperty("bst_report_temp")&&
l.attachment[p].fileKey in window.bst_report_temp&&(E=!0);E?(l.attachment[p].data=window.bst_report_temp[l.attachment[p].fileKey],p++,p<l.attachment.length?B(p,y):y()):bst.file.download(l.attachment[p],!0).then(A=>{bst.field.blobToBase64(A,G=>{l.attachment[p].data=G;p++;p<l.attachment.length?B(p,y):y()})}).catch(A=>{bst.alert(bst.error.parse(A));v()})}else y()};B(0,()=>{bst.encrypt(JSON.stringify(l.data),u).then(p=>{var y=fetch,E="https://api.booooooost.com/mail/"+bst.operator.language,A=JSON,G=A.stringify;
l.data=p.data;l.iv=p.iv;l.tag=p.tag;y(E,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:G.call(A,l)}).then(F=>{F.json().then(H=>{switch(F.status){case 200:f++;f<k.length?t(f,g):g();break;default:bst.alert(bst.error.parse(H)),v()}})}).catch(F=>{bst.alert(bst.error.parse(F));v()})}).catch(p=>{v()})})})(k[f])};0!=k.length?t(0,()=>{try{a.formula.value.map(f=>f.value).each((f,g)=>{f.field.value in b.fieldInfos.parallelize&&(g=b.fieldInfos.parallelize[f.field.value],g.tableCode||(c[g.code].value=
bst.formula.calculate(f,c,c,n,b.fieldInfos.parallelize),g.lookup&&(c[g.code].lookup=!0),f=c.$id.value,f in b.formulaRecords||(b.formulaRecords[f]={$id:{value:f}}),b.formulaRecords[f][g.code]=c[g.code]))}),m()}catch(f){bst.alert(bst.error.parse(f)),v()}}):m()})((()=>{var k=[];(b.fieldInfos.parallelize[a.to.value].tableCode?c[b.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:c}]).each((t,f)=>{if(t.value[a.to.value].value){f=k.push;var g={mail:a.mail.value,sender:a.sender.value,host:a.host.value,
port:a.port.value,author:a.author.value,pwd:a.pwd.value,secure:a.secure.value,to:t.value[a.to.value].value,cc:q(a.cc.value,c,b.fieldInfos.parallelize[a.to.value].tableCode?t.value:{}),bcc:q(a.bcc.value,c,b.fieldInfos.parallelize[a.to.value].tableCode?t.value:{}),html:"HTML"==a.format.value},l=q(a.subject.value,c,b.fieldInfos.parallelize[a.to.value].tableCode?t.value:{}),B=q(a.body.value,c,b.fieldInfos.parallelize[a.to.value].tableCode?t.value:{}),p=[];a.attachment.value&&a.attachment.value in b.fieldInfos.parallelize&&
(p=(b.fieldInfos.parallelize[a.attachment.value].tableCode?t.value:c)[a.attachment.value].value);f.call(k,{data:g,subject:l,body:B,attachment:p})}});return k})())}else m()}).catch(d=>{bst.alert(bst.error.parse(d));v()}):m()})(e[w])};fetch("https://api.booooooost.com/mail/"+bst.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(w=>{w.json().then(h=>{switch(w.status){case 200:u=h.passphrase;D||bst.loadStart();r(0,()=>{D||bst.loadEnd();x()});break;default:bst.alert(bst.error.parse(h)),
v()}})}).catch(w=>{bst.alert(bst.error.parse(w));v()})});kintone.events.on("app.record.create.submit.success app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),e=>new Promise((n,D)=>{((x,v)=>{b.mobile=x;b.type=v;for(var u in b.handlers)b.handlers[u].each((r,w)=>{kintone.events.off(u,r)});bst.config[z].config.get().then(r=>{0!=
Object.keys(r).length?bst.field.load(bst.config[z].app,!0).then(w=>{b.app={id:bst.config[z].app,fields:w.origin};b.fieldInfos=w;b.formulaRecords={};try{["detail"].includes(b.type)&&kintone.app.record.getPermissions().then(h=>{h.editRecord&&(m=>{0!=m.length&&((a,c)=>{kintone.events.on(a,c);a.each((d,q)=>{d in b.handlers||(b.handlers[d]=[]);b.handlers[d].push(c)})})(["app.record.detail.process.proceed","mobile.app.record.detail.process.proceed"],a=>new Promise((c,d)=>{try{(q=>{0!=q.length?C(q,a.record).then(k=>
c(a)).catch(()=>{}):c(a)})(m.filter(q=>q.action.value==a.action.value+":"+a.status.value+":"+a.nextStatus.value))}catch(q){bst.alert(bst.error.parse(q)),c(a)}}))})(JSON.parse(r.tab).map((m,a)=>bst.extend({sIndex:{value:a.toString()}},m.setting)).reduce((m,a)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(a.device.value)&&a.event.value.includes("process")&&m.push(a);return m},[]))}).catch(()=>{}),(h=>{if(0!=h.length){var m=c=>{0!=Object.keys(b.formulaRecords).length?bst.view.records.set(b.app.id,
{put:Object.values(b.formulaRecords).map(d=>bst.view.records.transform(d))},!1).then(d=>c()).catch(d=>bst.alert(bst.error.parse(d))):c()};switch(b.type){case "create":case "edit":C(h,e.record).then(c=>m(()=>n(e))).catch(()=>{});break;case "detail":var a=c=>{(d=>{bst.filter.scan(b.app,e.record,d.condition.value)?bst.filter.auth(d.user.value,d.organization.value,d.group.value).then(q=>{q&&bst.button.create(b.mobile,b.type,"bst-mail-button"+c.toString(),d.label.value,d.message.value,()=>C([d],e.record).then(k=>
m(()=>bst.alert("Done!",()=>window.location.reload(!0)))).catch(()=>{}));c++;c<h.length&&a(c)}).catch(q=>{c++;c<h.length&&a(c)}):(c++,c<h.length&&a(c))})(h[c])};a(0);n(e);break;case "index":a=c=>{(d=>{bst.filter.auth(d.user.value,d.organization.value,d.group.value).then(q=>{q&&(d.view.value&&d.view.value!=e.viewId.toString()||bst.button.create(b.mobile,b.type,"bst-mail-button"+c.toString(),d.label.value,d.message.value,()=>{bst.view.records.get(b.app.id,(b.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(k=>
{let t=(f,g)=>{C([d],k[f],!0).then(l=>{bst.progressUpdate();f++;f<k.length?t(f,g):g()}).catch(()=>{})};0!=k.length?(bst.progressStart(k.length),t(0,()=>m(()=>bst.alert("Done!",()=>window.location.reload(!0))))):bst.alert("There are no records.")}).catch(k=>bst.alert(bst.error.parse(k)))}));c++;c<h.length&&a(c)}).catch(q=>{c++;c<h.length&&a(c)})})(h[c])},a(0),n(e)}}else n(e)})(JSON.parse(r.tab).map((h,m)=>bst.extend({sIndex:{value:m.toString()}},h.setting)).reduce((h,m)=>{(b.mobile?["all","both","mobile"]:
["all","both","pc"]).includes(m.device.value)&&m.event.value.includes(b.type)&&h.push(m);return h},[]))}catch(h){bst.alert(bst.error.parse(h)),n(e)}}).catch(w=>n(e)):n(e)}).catch(r=>n(e))})("mobile"==e.type.split(".").first(),(x=>{switch(x){case "submit":x=e.type.split(".").slice(-3).first()}return x})(e.type.split(".").slice(-2).first()))}));bst.event.on("bst.mail.call",e=>new Promise((n,D)=>{bst.config[z].config.get().then(x=>{0!=Object.keys(x).length?bst.field.load(bst.config[z].app,!0).then(v=>
{b.app={id:bst.config[z].app,fields:v.origin};b.fieldInfos=v;try{(u=>{0!=u.length?C(u,e.record,!0).then(r=>n(e)).catch(()=>n(e)):n(e)})(JSON.parse(x.tab).map((u,r)=>bst.extend({sIndex:{value:r.toString()}},u.setting)).reduce((u,r)=>{(e.mobile?["all","both","mobile"]:["all","both","pc"]).includes(r.device.value)&&r.event.value.includes(e.pattern)&&u.push(r);return u},[]))}catch(u){bst.alert(bst.error.parse(u)),n(e)}}).catch(v=>n(e)):n(e)}).catch(x=>n(e))}))})(kintone.$PLUGIN_ID);
