/*
* FileName "plugins.upsert.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(J=>{var h={handlers:{}},M=(m,v,K=!1)=>new Promise((B,y)=>{var x=(t,G)=>{var p=(a,e)=>{t++;a&&e.formulaSource.value.map(c=>c.value).each((c,g)=>{c.field.value in h.fieldInfos.parallelize&&(g=h.fieldInfos.parallelize[c.field.value],g.tableCode||(a[g.code].value=bst.formula.calculate(c,a,a,v,h.fieldInfos.parallelize),g.lookup&&(a[g.code].lookup=!0),c=a.$id.value,c in h.formulaRecords||(h.formulaRecords[c]={$id:{value:c}}),h.formulaRecords[c][g.code]=a[g.code]))});t<m.length?x(t,G):G()};(a=>{var e=bst.filter.scan(h.app,
v,a.condition.value);e?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(c=>{c?bst.field.load(a.app.value).then(g=>{var w={id:a.app.value,fields:g.origin};(q=>{var H=[],C=[],L=[],D={},E={table:"",index:l=>E.table&&E.table==l.tableCode?u.progress.record:u.progress.row},u={record:1,row:1,progress:{record:0,row:0}},N=()=>{var l=[],r={field:(f,d)=>{d=f.tableCode?e[f.tableCode].value.length>d?e[f.tableCode].value[d].value[f.code]:bst.record.create({fields:{empty:f}}).empty:e[f.code];
return bst.extend({type:f.type},d)},record:f=>{u.row.each(d=>{var A=(b=>{var n=bst.filter.scan(w,f,b.query);if(!n&&"upsert"==a.pattern.value){for(var k in b.rows)0==bst.filter.result[k].value.length&&(f[k].value.push({value:bst.extend({},b.rows[k])}),bst.filter.result[k]={value:[f[k].value.last()]});n=bst.filter.result}return n})((()=>{var b={rows:{},query:[]};u.progress.row=d;H.each((n,k)=>{n.external.tableCode&&(n.external.tableCode in b.rows||(b.rows[n.external.tableCode]=bst.record.create(w.fields[n.external.tableCode],
!1)),k=r.field(n.internal,E.index(n.internal)),["=","in"].includes(n.operator.trim())&&(b.rows[n.external.tableCode][n.external.code]=z(n.external,k)),b.query.push(bst.filter.query.create(n.external,n.operator,k)))});C.each((n,k)=>{n.field.tableCode&&b.query.push(n.field.code+" "+n.operator+" "+n.value)});b.query=b.query.join(" and ");return b})());A&&L.each((b,n)=>{b.external.tableCode?b.external.tableCode in D?(f[b.external.tableCode]={value:D[b.external.tableCode]},D[b.external.tableCode].each((k,
I)=>{k.value[b.external.code]=z(b.external,r.field(b.internal,I));"FILE"==b.external.type&&k.value[b.external.code].value&&Array.prototype.push.apply(l,k.value[b.external.code].value)})):A[b.external.tableCode].value.each((k,I)=>{k.value[b.external.code]=z(b.external,r.field(b.internal,E.index(b.internal)));"FILE"==b.external.type&&k.value[b.external.code].value&&Array.prototype.push.apply(l,k.value[b.external.code].value)}):(f[b.external.code]=z(b.external,r.field(b.internal,u.progress.record)),
"FILE"==b.external.type&&f[b.external.code].value&&Array.prototype.push.apply(l,f[b.external.code].value))})});return f}},z=(f,d)=>{switch(f.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":Array.isArray(d.value)||(d.value=[d.value])}d.type=f.type;return f.lookup?bst.extend({lookup:!0},d):d},F=f=>{f.each((d,A)=>{a.formulaDestination.value.map(b=>b.value).each((b,n)=>{b.field.value in q.external&&(k=>{k.tableCode?d[k.tableCode].value.each((I,
O)=>{I.value[k.code].value=bst.formula.calculate(b,I.value,d,d,q.external);k.lookup&&(I.value[k.code].lookup=!0)}):(d[k.code].value=bst.formula.calculate(b,d,d,d,q.external),k.lookup&&(d[k.code].lookup=!0))})(q.external[b.field.value])})});return f};"insert"==a.pattern.value?(f=>{bst.file.clone(l,!0).then(()=>{bst.view.records.set(a.app.value,{post:f},K).then(d=>{u.progress.record++;u.progress.record<u.record?N():p(e,a)}).catch(d=>{bst.alert(bst.error.parse(d));y()})})})(F([r.record(bst.record.create(w))])):
bst.view.records.get(a.app.value,(()=>{var f=[];H.each((d,A)=>{d.external.tableCode||f.push(bst.filter.query.create(d.external,d.operator,r.field(d.internal,u.progress.record)))});C.each((d,A)=>{d.field.tableCode||f.push(d.field.code+" "+d.operator+" "+d.value)});return f.join(" and ")})()).then(f=>{f=(d=>{var A=[];0!=d.length?A=d.map(b=>r.record(b)):"upsert"==a.pattern.value&&(b=>{A.push(r.record((()=>{var n=bst.record.create(w);b.each((k,I)=>{k.external.tableCode?n[k.external.tableCode]={value:[]}:
["=","in"].includes(k.operator.trim())&&(n[k.external.code]=z(k.external,r.field(k.internal,u.progress.record)))});return n})()))})(H.filter(b=>!bst.field.reserved.includes(b.external.type)));return F(A)})(f);bst.file.clone(l,!0).then(()=>{bst.view.records.set(a.app.value,{post:f.filter(d=>!d.$id.value),put:f.reduce((d,A)=>{A.$id.value&&d.push(bst.view.records.transform(A));return d},[])},K).then(d=>{u.progress.record++;u.progress.record<u.record?N():p(e,a)}).catch(d=>{bst.alert(bst.error.parse(d));
y()})})}).catch(f=>{bst.alert(bst.error.parse(f));y()})};a.mapping.value.some(l=>!(l.value.external.value in q.external&&l.value.internal.value in q.internal))?(bst.alert("No field to transfer was found"),y()):a.criteria.value.some(l=>!(l.value.external.value in q.external&&l.value.internal.value in q.internal))?(bst.alert("No field to transfer was found"),y()):([...a.mapping.value,...a.criteria.value].each((l,r)=>{r=q.internal[l.value.internal.value];!q.external[l.value.external.value].tableCode&&
r.tableCode&&(E.table=r.tableCode,u.record=0==e[r.tableCode].value.length?0:e[r.tableCode].value.length)}),a.mapping.value.each((l,r)=>{((z,F)=>{z.tableCode&&(E.table&&E.table==F.tableCode||(D[z.tableCode]=(f=>{f=f?f.length:1;F.tableCode&&(f=f<e[F.tableCode].value.length?e[F.tableCode].value.length:f);return Array(f).fill().map(()=>({value:bst.record.create(w.fields[z.tableCode],!1)}))})(D[z.tableCode])));L.push({external:z,internal:F})})(q.external[l.value.external.value],q.internal[l.value.internal.value])}),
a.criteria.value.each((l,r)=>{r=q.external[l.value.external.value];var z=l.value.operator.value;l=q.internal[l.value.internal.value];r.tableCode&&(r.tableCode in D&&delete D[r.tableCode],!E.table&&l.tableCode&&(u.row=u.row<e[l.tableCode].value.length?e[l.tableCode].value.length:u.row));H.push({external:r,operator:z,internal:l})}),bst.filter.query.parse.expand({id:a.app.value,fields:g.origin},a.filter.value).each((l,r)=>{C.push({field:q.external[l.field],operator:l.operator,value:l.value})}),0!=u.record?
(u.progress.record=0,u.progress.row=0,N()):p())})({external:g.parallelize,internal:h.fieldInfos.parallelize})}).catch(g=>{bst.alert(bst.error.parse(g));y()}):p()}).catch(c=>{bst.alert(bst.error.parse(c));y()}):p()})(m[t])};K||bst.loadStart();x(0,()=>{K||bst.loadEnd();B()})});kintone.events.on("app.record.create.submit.success app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),
m=>new Promise((v,K)=>{((B,y)=>{h.mobile=B;h.type=y;for(var x in h.handlers)h.handlers[x].each((t,G)=>{kintone.events.off(x,t)});bst.config[J].config.get().then(t=>{0!=Object.keys(t).length?bst.field.load(bst.config[J].app,!0).then(G=>{h.app={id:bst.config[J].app,fields:G.origin};h.fieldInfos=G;h.formulaRecords={};try{["detail"].includes(h.type)&&kintone.app.record.getPermissions().then(p=>{p.editRecord&&(a=>{0!=a.length&&("formula"in a.first()&&(bst.alert(bst.error.config.update("Boost! Upsert")),
a.each(e=>{e.formulaDestination=e.formula;e.formulaSource={value:[]}})),((e,c)=>{kintone.events.on(e,c);e.each((g,w)=>{g in h.handlers||(h.handlers[g]=[]);h.handlers[g].push(c)})})(["app.record.detail.process.proceed","mobile.app.record.detail.process.proceed"],e=>new Promise((c,g)=>{try{(w=>{0!=w.length?M(w,e.record).then(q=>c(e)).catch(()=>{}):c(e)})(a.filter(w=>w.action.value==e.action.value+":"+e.status.value+":"+e.nextStatus.value))}catch(w){bst.alert(bst.error.parse(w)),c(e)}})))})(JSON.parse(t.tab).map((a,
e)=>bst.extend({sIndex:{value:e.toString()}},a.setting)).reduce((a,e)=>{(h.mobile?["all","both","mobile"]:["all","both","pc"]).includes(e.device.value)&&e.event.value.includes("process")&&a.push(e);return a},[]))}).catch(()=>{}),(p=>{if(0!=p.length){"formula"in p.first()&&(bst.alert(bst.error.config.update("Boost! Upsert")),p.each(c=>{c.formulaDestination=c.formula;c.formulaSource={value:[]}}));var a=c=>{0!=Object.keys(h.formulaRecords).length?bst.view.records.set(h.app.id,{put:Object.values(h.formulaRecords).map(g=>
bst.view.records.transform(g))},!1).then(g=>c()).catch(g=>bst.alert(bst.error.parse(g))):c()};switch(h.type){case "create":case "edit":M(p,m.record).then(c=>a(()=>v(m))).catch(()=>{});break;case "detail":var e=c=>{(g=>{bst.filter.scan(h.app,m.record,g.condition.value)?bst.filter.auth(g.user.value,g.organization.value,g.group.value).then(w=>{w&&bst.button.create(h.mobile,h.type,"bst-upsert-button"+c.toString(),g.label.value,g.message.value,()=>M([g],m.record).then(q=>a(()=>bst.alert("Done!",()=>window.location.reload(!0)))).catch(()=>
{}));c++;c<p.length&&e(c)}).catch(w=>{c++;c<p.length&&e(c)}):(c++,c<p.length&&e(c))})(p[c])};e(0);v(m);break;case "index":e=c=>{(g=>{bst.filter.auth(g.user.value,g.organization.value,g.group.value).then(w=>{w&&(g.view.value&&g.view.value!=m.viewId.toString()||bst.button.create(h.mobile,h.type,"bst-upsert-button"+c.toString(),g.label.value,g.message.value,()=>{bst.view.records.get(h.app.id,(h.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(q=>{let H=(C,L)=>{M([g],q[C],!0).then(D=>
{bst.progressUpdate();C++;C<q.length?H(C,L):L()}).catch(()=>{})};0!=q.length?(bst.progressStart(q.length),H(0,()=>a(()=>bst.alert("Done!",()=>window.location.reload(!0))))):bst.alert("There are no records.")}).catch(q=>bst.alert(bst.error.parse(q)))}));c++;c<p.length&&e(c)}).catch(w=>{c++;c<p.length&&e(c)})})(p[c])},e(0),v(m)}}else v(m)})(JSON.parse(t.tab).map((p,a)=>bst.extend({sIndex:{value:a.toString()}},p.setting)).reduce((p,a)=>{(h.mobile?["all","both","mobile"]:["all","both","pc"]).includes(a.device.value)&&
a.event.value.includes(h.type)&&p.push(a);return p},[]))}catch(p){bst.alert(bst.error.parse(p)),v(m)}}).catch(G=>v(m)):v(m)}).catch(t=>v(m))})("mobile"==m.type.split(".").first(),(B=>{switch(B){case "submit":B=m.type.split(".").slice(-3).first()}return B})(m.type.split(".").slice(-2).first()))}));bst.event.on("bst.upsert.call",m=>new Promise((v,K)=>{bst.config[J].config.get().then(B=>{0!=Object.keys(B).length?bst.field.load(bst.config[J].app,!0).then(y=>{h.app={id:bst.config[J].app,fields:y.origin};
h.fieldInfos=y;h.formulaRecords={};try{(x=>{0!=x.length?("formula"in x.first()&&(bst.alert(bst.error.config.update("Boost! Upsert")),x.each(t=>{t.formulaDestination=t.formula;t.formulaSource={value:[]}})),M(x,m.record,!0).then(t=>v(m)).catch(()=>v(m))):v(m)})(JSON.parse(B.tab).map((x,t)=>bst.extend({sIndex:{value:t.toString()}},x.setting)).reduce((x,t)=>{(m.mobile?["all","both","mobile"]:["all","both","pc"]).includes(t.device.value)&&t.event.value.includes(m.pattern)&&x.push(t);return x},[]))}catch(x){bst.alert(bst.error.parse(x)),
v(m)}}).catch(y=>v(m)):v(m)}).catch(B=>v(m))}))})(kintone.$PLUGIN_ID);
