/*
* FileName "plugins.lookup.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(C=>{var b={handlers:{},intervals:[],observers:[]},E=x=>new Promise((B,F)=>{var D=(n,m)=>(c=>{let z=null,v=null;const k=(g=>(t=>{t.addEventListener("change",e=>{e.target==t&&(b.mobile?m.value:m.value.elm("input")).val(e.detail.value)});(e=>{(new MutationObserver(d=>{for(const a of d)"attributes"===a.type&&"placeholder"===a.attributeName&&t.elm("input").attr("placeholder",e.attr("placeholder"))})).observe(e,{attributes:!0,attributeFilter:["placeholder"]})})(b.mobile?m.value:m.value.elm("input"));return t})(b.mobile?
new Kuc.MobileText(g):(new Kuc.Text(g)).css({boxSizing:"border-box",width:c.tableCode?"auto":m.css("width")})))({buttons:{clear:kb.create("button").css({whiteSpace:"nowrap"}).on("click",g=>{kb.confirm(kb.constants.lookup.message.confirm.clear[kb.operator.language],()=>{if(0!=n.tableCopy.value.length)k.lookupAction="CLEAR",k.lookupRecord=null,k.value=" ",(b.mobile?m.value:m.value.elm("input")).val("");else{var t=kb.field.get(c,b.mobile,b.type),e=b.mobile?kintone.mobile.app.record:kintone.app.record,
d=e.set,a=(b.mobile?kintone.mobile.app.record:kintone.app.record).get().record,h={};c.tableCode?(h[c.tableCode]=a[c.tableCode],h[c.tableCode].value[t.indexOf(m)].value[c.code]={lookup:"CLEAR",type:c.type,value:""}):h[c.code]={lookup:"CLEAR",type:c.type,value:""};k.lookupAction="CLEAR";k.lookupRecord=null;d.call(e,{record:h})}})}).html((()=>{var g="";switch(kb.operator.language){case "en":g="Clear";break;case "ja":g="\u30af\u30ea\u30a2";break;case "zh":g="\u6e05\u9664";break;case "zh-TW":g="\u6e05\u9664"}return g})()),
lookup:kb.create("button").css({whiteSpace:"nowrap"}).on("click",g=>{((t,e)=>{var d=()=>{b.recordPicker.show({app:c.lookup.relatedApp.app,query:c.query.filter(h=>h).join(" and "),sort:c.lookup.sort||"$id asc",picker:c.picker},h=>a(h))},a=h=>{if(0!=n.tableCopy.value.length)k.lookupAction="UPDATE",k.lookupRecord=h,k.value="",(b.mobile?m.value:m.value.elm("input")).val(h[c.lookup.relatedKeyField].value);else{var f=b.mobile?kintone.mobile.app.record:kintone.app.record,l=f.set,r=(b.mobile?kintone.mobile.app.record:
kintone.app.record).get().record,p={};c.tableCode?(p[c.tableCode]=r[c.tableCode],p[c.tableCode].value[t.indexOf(m)].value[c.code]={lookup:"UPDATE",type:c.type,value:h[c.lookup.relatedKeyField].value}):p[c.code]={lookup:"UPDATE",type:c.type,value:h[c.lookup.relatedKeyField].value};k.lookupAction="UPDATE";k.lookupRecord=h;l.call(f,{record:p})}};c.query=k.buildQuery();e&&c.query.push(c.lookup.relatedKeyField+(["LINK","SINGLE_LINE_TEXT"].includes(c.type)?" like ":"=")+'"'+e+'"');kintone.api(kintone.api.url("/k/v1/records",
!0),"GET",{app:c.lookup.relatedApp.app,query:c.query.filter(h=>h).join(" and ")}).then(h=>{if(0==h.records.length){h=kb;var f=h.alert,l="";switch(kb.operator.language){case "en":l="(None)";break;case "ja":l="\u30c7\u30fc\u30bf\u304c\u3042\u308a\u307e\u305b\u3093\u3002";break;case "zh":l="\u6682\u65e0\u6570\u636e\u3002";break;case "zh-TW":l="\u7121\u8cc7\u6599\u3002"}f.call(h,l)}else 1==h.records.length?a(h.records.first()):d()}).catch(h=>kb.alert(kb.error.parse(h)))})(kb.field.get(c,b.mobile,b.type),
(b.mobile?m.value:m.value.elm("input")).val())}).html((()=>{var g="";switch(kb.operator.language){case "en":g="Lookup";break;case "ja":g="\u53d6\u5f97";break;case "zh":g="\u641c\u9009";break;case "zh-TW":g="\u9078\u53d6"}return g})())},className:"control-gaia kb-lookup-field-"+c.id,label:c.noLabel||c.tableCode?"":c.label,lookupAction:"",lookupRecord:null,placeholder:(b.mobile?m.value:m.value.elm("input")).attr("placeholder"),requiredIcon:c.required,value:(b.mobile?m.value:m.value.elm("input")).val()});
Object.defineProperty(k,"disabledOptions",{set(g){[k.buttons.lookup,k.buttons.clear].each((t,e)=>t.css({opacity:g?"0":"1"}));0!=n.cascade.value.length&&k.elms("[class*=kb-lookup-cascade-]").each((t,e)=>{t.disabled=g})},enumerable:!0,configurable:!0});v=new MutationObserver(()=>{(g=>{kb.field.load(c.lookup.relatedApp.app).then(t=>{k.buildQuery=()=>{var e=[b.fieldInfos.parallelize[n.lookup.value].lookup.filterCond];((d,a)=>{e=n.dynamicFilter.value.reduce((h,f)=>{var l=t.parallelize[f.value.external.value],
r=f.value.operator.value;f=b.fieldInfos.parallelize[f.value.internal.value];var p=f.tableCode?a[f.tableCode].value[d.indexOf(m)].value:a;n.ignore.value.includes("ignore")&&kb.field.isEmpty(p[f.code].value)||h.push(kb.filter.query.create(l,r,p[f.code]));return h},e);0!=n.cascade.value.length&&(e=e.concat(k.buildQuery.cascade(n.cascade.value)))})(kb.field.get(c,b.mobile,b.type),(b.mobile?kintone.mobile.app.record:kintone.app.record).get().record);return e.filter(d=>d)};k.buildQuery.cascade=e=>e.reduce((d,
a)=>{var h=g.parentNode.elm(".kb-lookup-cascade-"+c.code+"-"+a.value.field.value);if(0!=h.selectedIndex)switch(t.parallelize[a.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":d.push(a.value.field.value+' in ("'+h.value+'")');break;default:d.push(a.value.field.value+' = "'+h.value+'"')}return d},[]).filter(d=>d);k.refreshForm=(e,d)=>{kb.event.call("kb.action.call",{container:kb.elm("body"),record:e,mobile:b.mobile,pattern:"change",fields:d,stopPropagation:!0,workplace:"record"}).then(a=>
{kb.event.call("kb.style.call",{container:a.container,record:a.record,mobile:a.mobile,pattern:"$id"in a.record?a.record.$id.value?"edit":"create":"create",workplace:a.workplace}).then(h=>{kb.event.call("kb.cascade.call",h).then(f=>{(b.mobile?kintone.mobile.app.record:kintone.app.record).set({record:f.record})}).catch(()=>{})}).catch(()=>{})}).catch(()=>{})};c.picker=(e=>{var d={};e.each((a,h)=>{a in t.parallelize&&(d[a]=kb.extend({},t.parallelize[a]))});0==Object.keys(d).length&&(d.$id={code:"$id",
type:"RECORD_NUMBER",label:kb.constants.picker.caption.recordnumber[kb.operator.language],required:!1,noLabel:!1});return d})(c.lookup.lookupPickerFields);n.cascade.value=n.cascade.value.reduce((e,d)=>{d.value.field.value in t.parallelize&&e.push(d);return e},[]);n.dynamicFilter.value=n.dynamicFilter.value.reduce((e,d)=>{d.value.external.value in t.parallelize&&d.value.internal.value in b.fieldInfos.parallelize&&e.push(d);return e},[]);n.multiCopy.value=n.multiCopy.value.reduce((e,d)=>{d.value.external.value in
t.parallelize&&d.value.internal.value in b.fieldInfos.parallelize&&e.push(d);return e},[]);n.tableCopy.value=n.tableCopy.value.reduce((e,d)=>{d.value.external.value in t.tables&&d.value.internal.value in b.fieldInfos.tables&&(a=>{d.value.fields.value=d.value.fields.value.reduce((h,f)=>{f.value.external.value in a.external.fields&&f.value.internal.value in a.internal.fields&&h.push(f);return h},[]);0!=d.value.fields.value.length&&d.value.identifier.value in a.internal.fields&&e.push(d)})({external:t.tables[d.value.external.value],
internal:b.fieldInfos.tables[d.value.internal.value]});return e},[]);(e=>{b.mobile?g.insertAdjacentElement("afterend",kb.create("div").css({display:"flex",padding:"0 0.5em"}).append(k.buttons.lookup.addClass("forms-lookup-lookup-gaia")).append(k.buttons.clear.addClass("forms-lookup-clear-gaia"))):(g.parentNode.insertAdjacentElement("beforeend",k.buttons.lookup.addClass("button-simple-cybozu input-lookup-gaia")),g.parentNode.insertAdjacentElement("beforeend",k.buttons.clear.addClass("button-simple-cybozu input-clear-gaia")),
(d=>{g.parentNode.parentNode.insertAdjacentElement("beforeend",d.hide());(new MutationObserver(a=>{(a=m.elm(".validator-valid-cybozu"))?d.show().textContent=a.textContent:d.hide()})).observe(m,{childList:!0,subtree:!0})})(kb.create("div").addClass("validator-valid-cybozu")));0!=n.cascade.value.length?n.cascade.value.each((d,a)=>{(h=>{g.insertAdjacentElement("beforebegin",(f=>{b.mobile&&f.css({borderBottom:"none"});f.reload=()=>new Promise((r,p)=>{kb.view.records.get(c.lookup.relatedApp.app,m.nextSibling.buildQuery.cascade(n.cascade.value.slice(0,
a)).join(" and "),d.value.field.value+" "+d.value.order.value).then(q=>{f.items=[{label:"-----",value:""}].concat(Array.from(new Set(q.map(u=>u[d.value.field.value].value))).map(u=>({label:u,value:u})));f.value="";r()}).catch(q=>{kb.alert(kb.error.parse(q));p()})});f.addEventListener("change",r=>{r.target==f&&a<n.cascade.value.length-1&&(0!=f.selectedIndex?f.nextSibling.reload():n.cascade.value.slice(a+1).each(p=>{p=g.parentNode.elm(".kb-lookup-cascade-"+c.code+"-"+p.value.field.value);p.items=[{label:"-----",
value:""}];p.value=""}))});let l=new MutationObserver(()=>{(r=>{r.each((p,q)=>p.disabled=m.nextSibling.disabled);b.mobile||c.tableCode||m.nextSibling.css({width:r.reduce((p,q)=>p+=q.outerWidth(!0),parseFloat(m.css("width"))).toString()+"px"})})(g.parentNode.elms("[class*=kb-lookup-cascade-]"));0==a&&f.reload().then(r=>e()).catch(r=>{});l.disconnect()});l.observe(f,{childList:!0,subtree:!0});return f.css(b.mobile?{marginBottom:"0.5em"}:{marginRight:"8px"})})(b.mobile?new Kuc.MobileDropdown(h):new Kuc.Dropdown(h)))})({className:"kb-lookup-cascade-"+
c.code+"-"+d.value.field.value,items:[{label:"-----",value:""}]})}):e()})(()=>{z=setInterval(()=>{m&&m.parentNode?(e=>{k.value!=e&&(k.value=e,0!=n.cascade.value.length||0!=n.tableCopy.value.length?(d=>{"CLEAR"==k.lookupAction?d():k.lookupRecord?d(k.lookupRecord):kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:c.lookup.relatedApp.app,query:c.lookup.relatedKeyField+'="'+e+'"'}).then(a=>{0==a.records.length?d():d(a.records.first())}).catch(a=>kb.alert(kb.error.parse(a)))})(d=>{(a=>{if(d){if(0!=
n.cascade.value.length){var h=f=>{(l=>{(r=>{r.reload().then(p=>{r.value=d[l.value.field.value].value;f++;f<n.cascade.value.length&&h(f)}).catch(p=>{})})(g.parentNode.elm(".kb-lookup-cascade-"+c.code+"-"+l.value.field.value))})(n.cascade.value[f])};h(0)}0!=n.tableCopy.value.length&&((f,l)=>{0==Object.keys(a).length?kb.alert(kb.constants.lookup.message.invalid.notfound[kb.operator.language]):k.refreshForm((r=>{kb.preset?kb.preset.files={}:kb.preset={files:{}};for(var p in a)l[p].value=(q=>{0!=q.length&&
(Object.values(q.last().value).some(u=>!kb.field.isEmpty(u.value))||q.pop());return q})((l[p].value||[]).filter(q=>q.value[a[p].identifier].value!=r)),d[a[p].source].value.each((q,u)=>{l[p].value.push(((w,y)=>{a[p].fields.each((A,G)=>{w[A.value.internal.value].value=q.value[A.value.external.value].value;b.fieldInfos.parallelize[A.value.internal.value].lookup&&(w[A.value.internal.value].lookup="UPDATE");"FILE"==b.fieldInfos.parallelize[A.value.internal.value].type&&(A.value.internal.value in kb.preset.files||
(kb.preset.files[A.value.internal.value]={}),kb.preset.files[A.value.internal.value][y.toString()]=q.value[A.value.external.value].value)});w[a[p].identifier].value=r;w[a[p].identifier].disabled=!0;return{value:w}})(kb.extend({},a[p].row),l[p].value.length))});k.lookupAction&&(c.tableCode?(q=>{q[c.code].lookup="UPDATE";q[c.code].value=d[c.lookup.relatedKeyField].value;c.lookup.fieldMappings.each((u,w)=>{q[u.field].value=d[u.relatedField].value})})(l[c.tableCode].value[f.indexOf(m)].value):(l[c.code].lookup=
"UPDATE",l[c.code].value=d[c.lookup.relatedKeyField].value,c.lookup.fieldMappings.each((q,u)=>{l[q.field].value=d[q.relatedField].value})));return l})(c.id+"_"+(c.tableCode?f.indexOf(m).toString().lpad("0",3):"000")),Object.keys(a).reduce((r,p)=>r=r.concat(Object.keys(b.fieldInfos.tables[p].fields)),Object.keys(a).concat(c.lookup.triggerField)).filter(r=>r))})(kb.field.get(c,b.mobile,b.type),(b.mobile?kintone.mobile.app.record:kintone.app.record).get().record)}else 0!=n.cascade.value.length&&n.cascade.value.each((f,
l)=>{f=g.parentNode.elm(".kb-lookup-cascade-"+c.code+"-"+f.value.field.value);0!=l&&(f.items=[{label:"-----",value:""}]);f.value=""}),0!=n.tableCopy.value.length&&((f,l)=>{0==Object.keys(a).length?kb.alert(kb.constants.lookup.message.invalid.notfound[kb.operator.language]):k.refreshForm((r=>{kb.preset?kb.preset.files={}:kb.preset={files:{}};for(var p in a)l[p].value=(l[p].value||[]).filter(q=>q.value[a[p].identifier].value!=r);k.lookupAction&&(c.tableCode?(q=>{q[c.code].lookup="CLEAR";q[c.code].value=
"";c.lookup.fieldMappings.each((u,w)=>{w=b.fieldInfos.parallelize[u.field];switch(w.type){case "CHECK_BOX":case "CONDITION":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":q[u.field].value=[];break;case "RADIO_BUTTON":q[u.field].value=w.defaultValue;break;default:q[u.field].value=""}})})(l[c.tableCode].value[f.indexOf(m)].value):(l[c.code].lookup="CLEAR",l[c.code].value="",c.lookup.fieldMappings.each((q,u)=>{u=b.fieldInfos.parallelize[q.field];switch(u.type){case "CHECK_BOX":case "CONDITION":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":l[q.field].value=
[];break;case "RADIO_BUTTON":l[q.field].value=u.defaultValue;break;default:l[q.field].value=""}})));return l})(c.id+"_"+(c.tableCode?f.indexOf(m).toString().lpad("0",3):"000")),Object.keys(a).concat(c.lookup.triggerField).filter(r=>r))})(kb.field.get(c,b.mobile,b.type),(b.mobile?kintone.mobile.app.record:kintone.app.record).get().record);k.lookupAction="";k.lookupRecord=null})((a=>a.reduce((h,f)=>{h[f.value.internal.value]={fields:f.value.fields.value,identifier:f.value.identifier.value,row:kb.record.create(b.fieldInfos.origin[f.value.internal.value],
!1),source:f.value.external.value};return h},{}))(n.tableCopy.value))}):(k.lookupAction="",k.lookupRecord=null))})((b.mobile?m.value:m.value.elm("input")).val()):(clearInterval(z),b.intervals=b.intervals.filter(e=>e!=z))},500)});(e=>{e.each((d,a)=>{d in b.fieldInfos.parallelize&&(h=>{(Array.isArray(h)?h:[h]).each((f,l)=>{f.elms(".disabled-cybozu").each((r,p)=>r.removeClass("disabled-cybozu"));f.elms(".disabled-field-gaia").each((r,p)=>r.removeClass("disabled-field-gaia"));f.elms("[disabled]").each((r,
p)=>r.removeAttr("disabled"))})})(kb.field.get(b.fieldInfos.parallelize[d],b.mobile,b.type))})})(n.dynamicFilter.value.reduce((e,d)=>{b.fieldInfos.disables.includes(d.value.internal.value)&&e.push(d.value.internal.value);return e},[]));(e=>{e&&e.css({boxSizing:"border-box",padding:"0 8px",width:b.mobile?"100%":"max-content"}).append(kb.create("button").addClass("kb-action-button kb-page-detail "+(b.mobile?" kb-mobile":"")).html(n.label.value).on("click",d=>{kb.confirm(n.message.value,()=>{(a=>{0==
Object.keys(a).length?kb.alert(kb.constants.lookup.message.invalid.notfound[kb.operator.language]):b.recordMultiPicker.show({app:c.lookup.relatedApp.app,query:k.buildQuery().join(" and "),sort:c.lookup.sort||"$id asc",picker:c.picker},h=>{0!=h.length&&k.refreshForm((f=>{kb.preset?kb.preset.files={}:kb.preset={files:{}};for(var l in a)0!=f[l].value.length&&(Object.values(f[l].value.last().value).some(r=>!kb.field.isEmpty(r.value))||f[l].value.pop());h.each((r,p)=>{for(var q in a)f[q].value.push(((u,
w)=>{a[q].fields.each((y,A)=>{u[y.value.internal.value].value=r[y.value.external.value].value;b.fieldInfos.parallelize[y.value.internal.value].lookup&&(u[y.value.internal.value].lookup="UPDATE");"FILE"==b.fieldInfos.parallelize[y.value.internal.value].type&&(y.value.internal.value in kb.preset.files||(kb.preset.files[y.value.internal.value]={}),kb.preset.files[y.value.internal.value][w.toString()]=r[y.value.external.value].value)});return{value:u}})(kb.extend({},a[q].row),f[q].value.length))});return f})((b.mobile?
kintone.mobile.app.record:kintone.app.record).get().record),Object.keys(a).reduce((f,l)=>f=f.concat(Object.keys(b.fieldInfos.tables[l].fields)),Object.keys(a)))})})((a=>Array.from(new Set(a.map(h=>b.fieldInfos.parallelize[h.value.internal.value].tableCode))).reduce((h,f)=>{f&&(h[f]={fields:a.filter(l=>b.fieldInfos.parallelize[l.value.internal.value].tableCode==f),row:kb.record.create(b.fieldInfos.origin[f],!1)});return h},{}))(n.multiCopy.value))})}))})((b.mobile?kintone.mobile.app.record:kintone.app.record).getSpaceElement(n.container.value));
kb.event.call("kb.attachment.lookup.call",{field:m});kb.event.call("kb.style.color.call",{field:m});kb.event.call("kb.style.display.call",{field:m});kb.event.call("kb.style.editable.call",{field:m})})})(k.elm("input").parentNode);v.disconnect()});v.observe(k,{childList:!0,subtree:!0});return k})(b.fieldInfos.parallelize[n.lookup.value]);(n=>{(Array.isArray(n)?n:[n]).each((m,c)=>{m.nextSibling&&m.nextSibling.tagName.toLowerCase().startsWith("kuc")||m.hide().insertAdjacentElement("afterend",D(x,m))})})(kb.field.get(b.fieldInfos.parallelize[x.lookup.value],
b.mobile,b.type));B()});kintone.events.on(["app.record.create.show","app.record.edit.show","mobile.app.record.create.show","mobile.app.record.edit.show"],x=>new Promise((B,F)=>{((D,n)=>{b.mobile=D;b.type=n;for(var m in b.handlers)b.handlers[m].each((c,z)=>{kintone.events.off(m,c)});b.intervals.each((c,z)=>clearInterval(c));b.intervals=[];b.observers.each((c,z)=>c.disconnect());b.observers=[];kb.config[C].config.get().then(c=>{0!=Object.keys(c).length&&"object"===typeof Kuc?kb.field.load(kb.config[C].app,
!0).then(z=>{b.app={id:kb.config[C].app,fields:z.origin};b.fieldInfos=z;b.recordPicker=new KintoneBoosterRecordPicker("record");b.recordMultiPicker=new KintoneBoosterRecordPicker("record",!0);try{(v=>{if(0!=v.length){let k={handler:{get:g=>{(t=>{kb.elms(t).each((e,d)=>{(a=>{if(!a.hasClass("kb-table-add-button-"+g.code))a.addClass("kb-table-add-button-"+g.code).on("mousedown,touchstart",h=>{k.index.add=kb.elms(".kb-table-add-button-"+g.code).indexOf(a)+1})})(e.elm(b.mobile?".subtable-row-add-gaia":
".add-row-image-gaia"));(a=>{if(!a.hasClass("kb-table-del-button-"+g.code))a.addClass("kb-table-del-button-"+g.code).on("mousedown,touchstart",h=>{k.index.del=kb.elms(".kb-table-del-button-"+g.code).indexOf(a)})})(e.elm(b.mobile?".subtable-row-delete-gaia":".remove-row-image-gaia"))})})(".subtable-"+g.id+(b.mobile?" .subtable-row-gaia":" tbody tr"))},set:g=>{g.tableCode in k.setting&&(t=>{t.each((e,d)=>{if(kb.isNumeric(k.index.add))for(let a=g.record[e.source.tableCode].value.length-1;a>k.index.add;a--)e.fields.each((h,
f)=>{h.code in b.fieldInfos.parallelize&&g.record[h.tableCode].value.each((l,r)=>{l.value[h.code].value==e.source.id+"_"+(a-1).toString().lpad("0",3)&&(l.value[h.code].value=e.source.id+"_"+a.toString().lpad("0",3))})});if(kb.isNumeric(k.index.del)){e.fields.each((a,h)=>{a.code in b.fieldInfos.parallelize&&(g.record[a.tableCode].value=g.record[a.tableCode].value.filter(f=>f.value[a.code].value!=e.source.id+"_"+k.index.del.toString().lpad("0",3)))});for(let a=k.index.del;a<g.record[e.source.tableCode].value.length;a++)e.fields.each((h,
f)=>{h.code in b.fieldInfos.parallelize&&g.record[h.tableCode].value.each((l,r)=>{l.value[h.code].value==e.source.id+"_"+(a+1).toString().lpad("0",3)&&(l.value[h.code].value=e.source.id+"_"+a.toString().lpad("0",3))})})}})})(k.setting[g.tableCode]);k.index.add=null;k.index.del=null;return g}},index:{add:null,del:null},setting:{}};v.each((g,t)=>{(e=>{e.tableCode?(d=>{(a=>{a.observe(kb.elm(".subtable-"+d.id+(b.mobile?"":" tbody")),{childList:!0,subtree:!1});kb.elms(".subtable-"+d.id+(b.mobile?" .subtable-row-gaia":
" tbody tr")).length==x.record[d.code].value.length&&(E(g),k.handler.get(d));b.observers.push(a)})(new MutationObserver(()=>{E(g);k.handler.get(d)}));0!=g.tableCopy.value.length&&(d.code in k.setting||(k.setting[d.code]=[]),k.setting[d.code].push({fields:g.tableCopy.value.map(a=>b.fieldInfos.parallelize[a.value.identifier.value]),source:e}))})(b.fieldInfos.tables[e.tableCode]):E(g)})(b.fieldInfos.parallelize[g.lookup.value])});((g,t)=>{kintone.events.on(g,t);g.each((e,d)=>{e in b.handlers||(b.handlers[e]=
[]);b.handlers[e].push(t)});kb.event.on("kb.lookup.identifier.call",e=>k.handler.set(e))})(Object.keys(k.setting).reduce((g,t)=>{g.push("app.record.create.change."+t);g.push("app.record.edit.change."+t);g.push("mobile.app.record.create.change."+t);g.push("mobile.app.record.edit.change."+t);return g},[]),g=>{kb.event.call("kb.action.installed.change",{installed:!1,mobile:b.mobile}).then(t=>{t.installed||(g.tableCode=g.type.split(".").last(),(b.mobile?kintone.mobile.app.record:kintone.app.record).set(k.handler.set(g)))});
return g});B(x)}})(JSON.parse(c.tab).map((v,k)=>kb.extend({sIndex:{value:k.toString()}},v.setting)).reduce((v,k)=>{k.lookup.value in b.fieldInfos.parallelize&&(k.tableCopy.value.each((g,t)=>{g.value.fields.value=JSON.parse(g.value.fields.value)}),v.push(k));return v},[]))}catch(v){kb.alert(kb.error.parse(v)),B(x)}}).catch(z=>B(x)):B(x)}).catch(c=>B(x))})("mobile"==x.type.split(".").first(),x.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
kb.constants=kb.extend({lookup:{message:{confirm:{clear:{en:"Are you sure you want to clear the lookup value? All retrieved values will also be cleared.",ja:"\u53c2\u7167\u5148\u304b\u3089\u53d6\u5f97\u3057\u305f\u5024\u3082\u30af\u30ea\u30a2\u3055\u308c\u307e\u3059\u3002\u3088\u308d\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u83b7\u53d6\u7684\u503c\u4e5f\u4f1a\u88ab\u6e05\u9664\u3002\u662f\u5426\u7ee7\u7eed\uff1f","zh-TW":"\u78ba\u5b9a\u8981\u6e05\u9664\u5df2\u53d6\u5f97\u7684\u503c\u55ce\uff1f"}},
invalid:{notfound:{en:"No fields to be copied were found. Please check the plugin settings.",ja:"\u30b3\u30d4\u30fc\u3059\u308b\u30d5\u30a3\u30fc\u30eb\u30c9\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3002\u30d7\u30e9\u30b0\u30a4\u30f3\u306e\u8a2d\u5b9a\u3092\u78ba\u8a8d\u3057\u3066\u304f\u3060\u3055\u3044\u3002",zh:"\u672a\u627e\u5230\u8981\u590d\u5236\u7684\u5b57\u6bb5\u3002\u8bf7\u68c0\u67e5\u63d2\u4ef6\u7684\u8bbe\u5b9a\u5185\u5bb9\u3002","zh-TW":"\u627e\u4e0d\u5230\u8981\u8907\u88fd\u7684\u6b04\u4f4d\u3002\u8acb\u78ba\u8a8d\u5916\u639b\u7684\u8a2d\u5b9a\u5167\u5bb9\u3002"}}}}},
kb.constants);
