/*
* FileName "plugins.oimap.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(y=>{var e={},A=f=>new Promise((q,m)=>{((l,t)=>{t.append(kb.create("div").addClass("kb-row").append(kb.field.activate(kb.field.create(l.fields.from).css({width:"50%"}),l,!1)).append(kb.field.activate(kb.field.create(l.fields.to).css({width:"50%"}),l,!1))).append(kb.create("div").addClass("kb-row").append(kb.field.activate(kb.field.create(l.fields.sender).css({width:"100%"}),l,!1)));kb.record.set(t,l,e.filter?e.filter:{from:{value:(new Date((new Date).format("Y-m-dT00:00:00Z"))).calc(kb.timezoneOffset()+
" hour").toISOString()},to:{value:(new Date((new Date).format("Y-m-dT23:59:00Z"))).calc(kb.timezoneOffset()+" hour").toISOString()},sender:{value:""}});(new KintoneBoosterPopupform(t,600,null,{ok:()=>{e.filter=kb.record.get(t,l,!0).record;fetch("https://api.kintone-booster.com/mail/oauth/rv",{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(n=>{n.json().then(u=>{switch(n.status){case 200:(d=>{kb.loadStart();kb.encrypt(JSON.stringify(d),u.passphrase).then(h=>{fetch("https://api.kintone-booster.com/mail/oauth/rv",
{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({data:h.data,iv:h.iv,tag:h.tag})}).then(k=>{k.json().then(a=>{switch(k.status){case 200:var r=[],v=[],p=(b,c)=>{r.length!=0?kb.file.upload((g=>{var w=atob(g.binary),x=new Uint8Array(w.length);w.length.each(z=>x[z]=w.charCodeAt(z));return new File([new Blob([x.buffer],{type:g.contentType})],g.filename,{type:g.contentType})})(r[b]),!0).then(g=>{a[v[b].json].attachment[v[b].attachment]=g;b++;b<r.length?p(b,c):c()}).catch(g=>
{kb.alert(kb.error.parse(g));m()}):c()};a=a.reduce((b,c)=>{var g=new Date(c.date);g>=new Date(e.filter.from.value)&&g<=new Date(e.filter.to.value)&&(c.date=g.format("ISO"),b.push(c));return b},[]);r=a.reduce((b,c,g)=>{c.attachment.length!=0&&c.attachment.each((w,x)=>{b.push(w);v.push({json:g,attachment:x})});return b},[]);p(0,()=>q(a));break;default:kb.alert(kb.error.parse(a)),m()}})}).catch(k=>{kb.alert(kb.error.parse(k));m()})}).catch(h=>{kb.loadEnd();m()})})({client_id:f.client_id.value,client_secret:f.client_secret.value,
author:f.author.value,subdomain:location.host.split(".")[0],provider:(d=>{d="";switch(f.provider.value){case "GMail":d="google";break;case "Exchange Online":d="microsoft"}return d})(f.provider.value),criteria:{since:(new Date(e.filter.from.value)).format("Y-m-d"),before:(new Date((new Date(e.filter.to.value)).format("Y-m-d"))).calc("1 day").format("Y-m-d"),from:e.filter.sender.value?e.filter.sender.value:""}});break;default:kb.alert(kb.error.parse(u)),m()}})}).catch(n=>{kb.alert(kb.error.parse(n));
m()})},cancel:()=>m()})).show()})({id:"IMAP_filter",fields:{from:{code:"from",type:"DATETIME",label:kb.constants.imap.caption.from[kb.operator.language],required:!0,noLabel:!1},to:{code:"to",type:"DATETIME",label:kb.constants.imap.caption.to[kb.operator.language],required:!0,noLabel:!1},sender:{code:"sender",type:"SINGLE_LINE_TEXT",label:kb.constants.imap.caption.sender[kb.operator.language],required:!0,noLabel:!1,format:"mail"}}},kb.create("div").addClass("kb-scope").attr("form-id","form_IMAP_filter"))});
kintone.events.on(["app.record.index.show","mobile.app.record.index.show"],f=>new Promise((q,m)=>{((l,t)=>{e.mobile=l;e.type=t;kb.config[y].config.get().then(n=>{Object.keys(n).length!=0?kb.field.load(kb.config[y].app,!0).then(u=>{e.app={id:kb.config[y].app,fields:u.origin};e.fieldInfos=u;try{(d=>{if(d.length!=0){var h=k=>{(a=>{kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(r=>{r&&(a.view.value&&a.view.value!=f.viewId.toString()||kb.button.create(e.mobile,e.type,"kb-imap-button"+
k.toString(),a.label.value,a.message.value,()=>{A(a).then(v=>{v.length!=0?kb.view.records.set(e.app.id,{post:v.reduce((p,b)=>{var c={};c[a.uid.value]={value:b.uid};c[a.from.value]={value:b.from};c[a.date.value]={value:b.date};c[a.subject.value]={value:b.subject};c[a.body.value]={value:b.body};c[a.attachment.value]={value:b.attachment};a.cc&&a.cc.value&&(c[a.cc.value]={value:b.cc});p.push(c);return p},[])},!0).then(p=>kb.alert("Done!",()=>window.location.reload(!0))).catch(p=>kb.alert(kb.error.parse(p))):
kb.alert("There are no emails.")}).catch(()=>{})}));k++;k<d.length&&h(k)}).catch(r=>{k++;k<d.length&&h(k)})})(d[k])};h(0)}q(f)})(JSON.parse(n.tab).map((d,h)=>kb.extend({sIndex:{value:h.toString()}},d.setting)).reduce((d,h)=>{(e.mobile?["all","both","mobile"]:["all","both","pc"]).includes(h.device.value)&&d.push(h);return d},[]))}catch(d){kb.alert(kb.error.parse(d)),q(f)}}).catch(u=>q(f)):q(f)}).catch(n=>q(f))})(f.type.split(".").first()=="mobile",f.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
kb.constants=kb.extend({imap:{caption:{from:{en:"Since",ja:"\u4ee5\u964d",zh:"\u4ee5\u540e","zh-TW":"\u4ee5\u5f8c"},sender:{en:"Sender",ja:"\u5dee\u51fa\u4eba",zh:"\u53d1\u4ef6\u4eba","zh-TW":"\u767c\u4ef6\u4eba"},to:{en:"Before",ja:"\u4ee5\u524d",zh:"\u4ee5\u524d","zh-TW":"\u4ee5\u524d"}}}},kb.constants);