/*
* FileName "plugins.decoder.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(A=>{var a={guideMargin:.15,lastCode:null,matchCount:0,reader:null,requestId:null,video:null,observers:[]},F=f=>{var k=a.video.getBoundingClientRect(),g={width:null,height:null},b={left:null,top:null,width:null,height:null},d=(c=>{c.source={width:a.video.monitor.videoWidth,height:a.video.monitor.videoHeight};return c})(a.video.monitor.getBoundingClientRect());if(!(d.width&&d.height&&d.source.width&&d.source.height))return null;g=(c=>({width:d.source.width*c,height:d.source.height*c}))(Math.min(d.width/
d.source.width,d.height/d.source.height));b=(()=>{var c="qrcode"==f?Math.min(g.width,g.height)*(1-2*a.guideMargin):g.width*(1-2*a.guideMargin),p="qrcode"==f?c:Math.min(g.height,Math.max(100,.25*g.height));return{left:(g.width-c)/2,top:(g.height-p)/2,width:c,height:p}})();a.video.guide.css({left:d.left-k.left+(d.width-g.width)/2+b.left+"px",top:d.top-k.top+(d.height-g.height)/2+b.top+"px",width:b.width+"px",height:b.height+"px"});return{x:b.left/g.width*d.source.width,y:b.top/g.height*d.source.height,
w:b.width/g.width*d.source.width,h:b.height/g.height*d.source.height}},D=(f,k,g)=>{a.video.monitor.autoplay&&setTimeout(()=>{a.video.monitor.autoplay&&a.video.monitor.srcObject&&((b,d)=>{try{var c=F(f)||{x:0,y:0,w:a.video.monitor.videoWidth,h:a.video.monitor.videoHeight},p=m=>{try{return(new TextDecoder("utf-8",{fatal:!0})).decode(m)}catch(B){return(new TextDecoder("shift_jis")).decode(m)}};b.width=c.w;b.height=c.h;if(b.width&&b.height)if(b.getContext("2d").drawImage(a.video.monitor,c.x,c.y,c.w,c.h,
0,0,c.w,c.h),"qrcode"==f){var n=jsQR(b.getContext("2d").getImageData(0,0,b.width,b.height).data,b.width,b.height);n?d(n.binaryData?p(new Uint8Array(n.binaryData)):n.data):d(null)}else Quagga.decodeSingle({locator:{patchSize:"medium",halfSample:!1},decoder:{readers:[k.readers]},numOfWorkers:0,locate:!1,src:b.toDataURL("image/png")},m=>d(m&&m.codeResult?m.codeResult.code:null));else d(null)}catch{d(null)}})(bst.create("canvas"),b=>{if(b&&b==a.lastCode){if(a.matchCount++,1<a.matchCount){g(b);return}}else a.lastCode=
b,a.matchCount=b?1:0;D(f,k,g)})},250)},G=(f,k,g)=>{(b=>{b.observe(bst.elm(".subtable-"+f.id+(a.mobile?"":" tbody")),{childList:!0,subtree:!1});(d=>{bst.elms(d).length==k[f.code].value.length&&g.each((c,p)=>c({record:k}))})(".subtable-"+f.id+(a.mobile?" .subtable-row-gaia":" tbody tr"));a.observers.push(b)})(new MutationObserver(()=>{g.each((b,d)=>b({record:k}))}))},y=()=>{a.requestId=null;a.video.monitor.srcObject&&a.video.monitor.srcObject.getTracks().forEach(f=>f.stop());a.video.monitor.autoplay=
!1;a.video.monitor.srcObject=null};kintone.events.on(["app.record.create.show","app.record.edit.show","mobile.app.record.create.show","mobile.app.record.edit.show"],f=>new Promise((k,g)=>{((b,d)=>{a.mobile=b;a.type=d;a.video=(c=>{c.guide=bst.create("div").css({boxSizing:"border-box",border:"1px solid #ffc107",pointerEvents:"none",position:"absolute"});c.monitor=bst.create("video").attr("muted","muted").attr("playsinline","playsinline").css({boxSizing:"border-box",height:"100%",objectFit:"contain",
width:"100%"});return c.append(c.monitor).append(c.guide)})(bst.create("div").css({boxSizing:"border-box",height:"100%",position:"relative",width:"100%"}));a.reader=a.video.popup("full","full",[],y);a.observers.each((c,p)=>c.disconnect());a.observers=[];bst.config[A].config.get().then(c=>{0!=Object.keys(c).length?bst.field.load(bst.config[A].app,!0).then(p=>{a.app={id:bst.config[A].app,fields:p.origin};a.fieldInfos=p;try{(n=>{var m={};n=[...n.barcode.value.map(e=>{e.value.type={value:"barcode"};return e.value}),
...n.qrcode.value.map(e=>{e.value.type={value:"qrcode"};return e.value})].reduce((e,u)=>{u.field.value in a.fieldInfos.parallelize&&(e[u.field.value]={fieldInfo:a.fieldInfos.parallelize[u.field.value],format:"format"in u?u.format.value:"",type:u.type.value});return e},{});bst.event.off("bst.decoder.call");Object.values(n).each((e,u)=>{(z=>{if(e.fieldInfo.tableCode){var q=a.fieldInfos.tables[e.fieldInfo.tableCode];q.code in m||(m[q.code]=[]);m[q.code].push(z);a.mobile&&z({record:f.record})}else z({record:f.record})})(z=>
{((q,w)=>{q&&(Array.isArray(q)?q:[q]).each((h,H)=>{h.value.parentNode.elm(".bst-decoder-operation")||(w(h,h.value,a.mobile?h.value:h.value.elm("input[type=text]")),e.fieldInfo.lookup&&(h.nextSibling&&h.nextSibling.tagName.toLowerCase().startsWith("kuc")&&(l=>{l&&w(h,a.mobile?l:l.parentNode,l)})(h.nextSibling.elm("input[type=text]")),bst.event.on("bst.decoder.call",l=>{if(l.field==h&&h.nextSibling&&h.nextSibling.tagName.toLowerCase().startsWith("kuc")&&!h.nextSibling.elm(".bst-decoder-operation")){var r=
h.nextSibling.elm("input[type=text]");w(h,a.mobile?r:r.parentNode,r)}return l})))})})(bst.field.get(e.fieldInfo,a.mobile,a.type),(q,w,h)=>{w.parentNode.css(a.mobile?{alignItems:"center"}:{alignItems:"center",display:"flex"}).insertBefore(bst.create("button").addClass("bst-icon bst-icon-camera bst-decoder-operation"+(a.mobile?" bst-mobile":"")).on("click",H=>{const l=Symbol();a.requestId=l;a.video.monitor.autoplay=!0;a.video.monitor.muted=!0;navigator.mediaDevices.getUserMedia({audio:!1,video:{facingMode:{ideal:"environment"}}}).then(r=>
{a.requestId!==l?r.getTracks().forEach(v=>v.stop()):(a.video.monitor.srcObject=r,a.video.monitor.play().then(()=>{a.requestId!==l?r.getTracks().forEach(v=>v.stop()):(a.lastCode="",a.matchCount=0,a.reader.show(),D(e.type,{readers:e.format},v=>{a.reader.hide();y();((C,E)=>{bst.event.call("bst.action.call",{container:bst.elm("body"),record:(t=>{var x={};e.fieldInfo.tableCode?(x[e.fieldInfo.tableCode]=t[e.fieldInfo.tableCode],x[e.fieldInfo.tableCode].value[C.indexOf(q)].value[e.fieldInfo.code]=E):x[e.fieldInfo.code]=
E;return x})((a.mobile?kintone.mobile.app.record:kintone.app.record).get().record),mobile:a.mobile,pattern:"change",fields:[e.fieldInfo.code],stopPropagation:!0,workplace:"record"}).then(t=>{bst.event.call("bst.style.call",{container:t.container,record:t.record,mobile:t.mobile,pattern:"$id"in t.record?t.record.$id.value?"edit":"create":"create",workplace:t.workplace}).then(x=>{bst.event.call("bst.cascade.call",x).then(I=>{(a.mobile?kintone.mobile.app.record:kintone.app.record).set({record:I.record})}).catch(()=>
{})}).catch(()=>{})}).catch(()=>{})})(bst.field.get(e.fieldInfo,a.mobile,a.type),bst.extend({type:e.fieldInfo.type,value:v},e.fieldInfo.lookup?{lookup:"UPDATE"}:{}))}))}).catch(v=>{r.getTracks().forEach(C=>C.stop());a.requestId===l&&(a.reader.hide(),y(),bst.alert(bst.error.parse(v)))}))}).catch(r=>{a.requestId===l&&(a.reader.hide(),y(),bst.alert(bst.error.parse(r)))})}),w.nextSibling);a.mobile&&h.addClass("bst-decoder-operation-input bst-mobile")})})});for(var B in m)G(a.fieldInfos.tables[B],f.record,
m[B])})(JSON.parse(c.flat)),k(f)}catch(n){bst.alert(bst.error.parse(n)),k(f)}}).catch(p=>k(f)):k(f)}).catch(c=>k(f))})("mobile"==f.type.split(".").first(),f.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
