/*
* FileName "plugins.linkage.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(L=>{var e={handlers:{},stats:{}},O=(t,C)=>new Promise((M,J)=>{kb.field.load(t.app.value).then(z=>{(D=>{t.criteria.value.some(p=>!(p.value.external.value in D.external&&p.value.internal.value in D.internal))?(kb.alert("No field to linkage was found"),J()):t.mapping.value.some(p=>!(p.value.external.value in D.external))?(kb.alert("No field to linkage was found"),J()):(p=>{p.api=p.api.join(" and ");p.url=p.url.join(" and ");kb.view.records.get(t.app.value,p.api).then(u=>{0!=u.length?((r,w,E)=>{M((A=>
{A.records.sort((k,d)=>{var m=0;t.sort.value.filter(g=>g.value.field.value in z.parallelize).each((g,b)=>{switch(z.parallelize[g.value.field.value].type){case "CALC":switch(z.parallelize[g.value.field.value].format){case "NUMBER":case "NUMBER_DIGIT":b=k[g.value.field.value].value?parseFloat(k[g.value.field.value].value):0;var l=d[g.value.field.value].value?parseFloat(d[g.value.field.value].value):0;break;default:b=k[g.value.field.value].value,l=d[g.value.field.value].value}break;case "CATEGORY":case "CHECK_BOX":case "CREATOR":case "FILE":case "GROUP_SELECT":case "MODIFIER":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "STATUS_ASSIGNEE":case "USER_SELECT":b=
JSON.stringify(k[g.value.field.value].value);l=JSON.stringify(d[g.value.field.value].value);break;case "NUMBER":b=k[g.value.field.value].value?parseFloat(k[g.value.field.value].value):0;l=d[g.value.field.value].value?parseFloat(d[g.value.field.value].value):0;break;default:b=k[g.value.field.value].value,l=d[g.value.field.value].value}switch(g.value.order.value){case "asc":b>l&&(m=1);b<l&&(m=-1);break;case "desc":b>l&&(m=-1),b<l&&(m=1)}if(m)return KB_BREAK});return m});return A})(r.reduce((A,k)=>{Array(E?
k[E].value.length:1).fill().map(()=>({})).each((d,m)=>{d.$id=k.$id;for(var g in z.parallelize)z.parallelize[g].tableCode?z.parallelize[g].tableCode==E&&(d[g]=k[E].value[m].value[g]):"$rowId"!=g?d[g]=k[g]:d.$rowId=E?{value:k[E].value[m].id}:{value:""};A.records.push(d)});return A},{offset:0,origin:w,query:p.url,records:[]})))})(u.reduce((r,w)=>{(w=kb.filter.scan({fields:z.origin},w,p.api))&&r.push(w);return r},[]),u,Array.from(new Set(t.mapping.value.map(r=>z.parallelize[r.value.external.value].tableCode))).join("")):
M({offset:0,records:[]})}).catch(u=>{kb.alert(kb.error.parse(u));J()})})(t.criteria.value.reduce((p,u)=>{p.api.push(kb.filter.query.create(D.external[u.value.external.value],u.value.operator.value,C[u.value.internal.value]));D.external[u.value.external.value].tableCode||p.url.push(p.api.last());return p},kb.filter.query.parse.expand({id:t.app.value,fields:z.origin},t.filter.value).reduce((p,u)=>{p.api.push(u.field+" "+u.operator+" "+u.value);D.external[u.field].tableCode||p.url.push(p.api.last());
return p},{api:[],url:[]})))})({external:z.parallelize,internal:e.fieldInfos.parallelize})}).catch(z=>{kb.alert(kb.error.parse(z));J()})});kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.index.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show mobile.app.record.index.show".split(" "),t=>new Promise((C,M)=>{((J,z)=>{e.mobile=J;e.type=z;for(var D in e.handlers)e.handlers[D].each((p,u)=>{kintone.events.off(D,p)});
kb.config[L].config.get().then(p=>{0!=Object.keys(p).length?kb.field.load(kb.config[L].app,!0).then(u=>{e.app={id:kb.config[L].app,fields:u.origin};e.fieldInfos=u;e.stats={};try{(r=>{if(0!=r.length){var w=(k,d,m,g)=>{var b=k.mapping.value.reduce((c,f)=>{if(f.value.external.value in d.parallelize)switch(d.parallelize[f.value.external.value].type){case "CALC":switch(d.parallelize[f.value.external.value].format){case "DATE":case "DATETIME":c[f.value.external.value]={max:"",min:""};break;case "NUMBER":case "NUMBER_DIGIT":c[f.value.external.value]=
{count:0,sum:"",avg:"",max:"",min:""}}break;case "CREATED_TIME":case "DATE":case "DATETIME":case "UPDATED_TIME":c[f.value.external.value]={max:"",min:""};break;case "NUMBER":c[f.value.external.value]={count:0,sum:"",avg:"",max:"",min:""}}return c},{});g.each((c,f)=>{for(var a in c)if(a in d.parallelize)switch(d.parallelize[a].type){case "CALC":switch(d.parallelize[a].format){case "DATE":case "DATETIME":if(a in b&&c[a].value){if(!b[a].max||c[a].value>b[a].max)b[a].max=c[a].value;if(!b[a].min||c[a].value<
b[a].min)b[a].min=c[a].value}break;case "NUMBER":case "NUMBER_DIGIT":if(a in b&&kb.isNumeric(c[a].value)){if(!kb.isNumeric(b[a].max)||Number(c[a].value)>b[a].max)b[a].max=Number(c[a].value);if(!kb.isNumeric(b[a].min)||Number(c[a].value)<b[a].min)b[a].min=Number(c[a].value);kb.isNumeric(b[a].sum)||(b[a].sum=0);b[a].sum+=Number(c[a].value);b[a].count++}}break;case "CREATED_TIME":case "DATE":case "DATETIME":case "UPDATED_TIME":if(a in b&&c[a].value){if(!b[a].max||c[a].value>b[a].max)b[a].max=c[a].value;
if(!b[a].min||c[a].value<b[a].min)b[a].min=c[a].value}break;case "NUMBER":if(a in b&&kb.isNumeric(c[a].value)){if(!kb.isNumeric(b[a].max)||Number(c[a].value)>b[a].max)b[a].max=Number(c[a].value);if(!kb.isNumeric(b[a].min)||Number(c[a].value)<b[a].min)b[a].min=Number(c[a].value);kb.isNumeric(b[a].sum)||(b[a].sum=0);b[a].sum+=Number(c[a].value);b[a].count++}}});for(var l in b)b[l].count&&(b[l].avg=b[l].sum/b[l].count),k.mapping.value.each((c,f)=>{if(c.value.external.value==l){c=JSON.parse(c.value.stats.value||
"{}");for(var a in c)f=c[a],f.value in e.fieldInfos.origin&&(m[f.value]={type:e.fieldInfos.origin[f.value].type,value:e.stats[f.value].value=b[l][a]})}});switch(e.type){case "create":case "edit":(c=>{try{c()}catch(a){var f=setInterval(()=>{try{c(),clearInterval(f)}catch(x){}},500)}})(()=>{0!=Object.keys(m).length&&(e.mobile?kintone.mobile.app.record:kintone.app.record).set({record:m})});break;case "detail":for(l in m)(c=>{var f=kb.field.stringify(c,m[l].value," / ");e.mobile?kb.field.get(c,e.mobile,
e.type).value.html(f):kb.field.get(c,e.mobile,e.type).value.elm("span").html(f)})(e.fieldInfos.parallelize[l])}},E=(k,d,m)=>{var g=(b=>Array.from(new Set(b.map(l=>e.fieldInfos.parallelize[l.value.internal.value].tableCode))).reduce((l,c)=>{d[c].value=[];l[c]={fields:b.filter(f=>e.fieldInfos.parallelize[f.value.internal.value].tableCode==c),row:kb.record.create(e.fieldInfos.origin[c],!1)};return l},{}))(k.mapping.value.reduce((b,l)=>{l.value.internal.value in e.fieldInfos.parallelize&&b.push(l);return b},
[]));m.each((b,l)=>{for(var c in g)d[c].value.push((f=>{g[c].fields.each((a,x)=>{a.value.internal.value in e.fieldInfos.parallelize&&(f[a.value.internal.value].value=b[a.value.external.value].value,e.fieldInfos.parallelize[a.value.internal.value].lookup&&(f[a.value.internal.value].lookup=!0))});return{value:f}})(kb.extend({},g[c].row)))});return d};r.first().mapping.value.some(k=>!("stats"in k.value))&&(kb.alert(kb.error.config.update("Boost! Linkage")),r=r.map(k=>{k.mapping.value=k.mapping.value.map(d=>
{d.value.stats={value:""};return d});return k}));r.each((k,d)=>{k.mapping.value.each((m,g)=>{m=JSON.parse(m.value.stats.value||"{}");for(var b in m)((l,c)=>{c.value in e.fieldInfos.origin&&(c.value in e.stats||((f,a)=>{kintone.events.on(f,a);f.each((x,G)=>{x in e.handlers||(e.handlers[x]=[]);e.handlers[x].push(a)})})(["app.record.create.change."+c.value,"app.record.edit.change."+c.value,"mobile.app.record.create.change."+c.value,"mobile.app.record.edit.change."+c.value],f=>{f.record[c.value].value!=
e.stats[c.value].value&&(f.record[c.value].value=e.stats[c.value].value);return f}),e.stats[c.value]={value:""})})(b,m[b])})});e.mobile&&kb.elm("body").addClass("kb-mobile");switch(e.type){case "create":case "edit":case "detail":var A=k=>{(d=>{(m=>{m&&kb.field.load(d.app.value).then(g=>{(b=>{((l,c)=>{var f={},a={copy:kb.create("button").addClass("kb-linkage-container-button").html(d.label.value).on("click",n=>{kb.confirm(d.message.value,()=>{kb.event.call("kb.action.call",{container:kb.elm("body"),
record:E(d,(e.mobile?kintone.mobile.app.record:kintone.app.record).get().record,f.records),mobile:e.mobile,pattern:"change",fields:(h=>h.reduce((q,v)=>q=q.concat(Object.keys(e.fieldInfos.tables[v].fields)),h))(d.mapping.value.reduce((h,q)=>{q.value.internal.value in e.fieldInfos.parallelize&&h.push(e.fieldInfos.parallelize[q.value.internal.value].tableCode);return h},[])),stopPropagation:!0,workplace:"record"}).then(h=>{kb.event.call("kb.style.call",{container:h.container,record:h.record,mobile:h.mobile,
pattern:"$id"in h.record?h.record.$id.value?"edit":"create":"create",workplace:h.workplace}).then(q=>{kb.event.call("kb.cascade.call",q).then(v=>{(e.mobile?kintone.mobile.app.record:kintone.app.record).set({record:v.record})}).catch(()=>{})}).catch(()=>{})}).catch(()=>{})})}),edit:kb.create("button").addClass("kb-icon kb-icon-edit").on("click",n=>{[a.total,a.reload,a.open,a.edit,a.prev,a.next,a.copy].each((h,q)=>h.addClass("kb-hidden"));[a.submit,a.cancel].each((h,q)=>h.removeClass("kb-hidden"));
l.elms(".kb-field").each((h,q)=>h.removeClass("kb-readonly"));(h=>{h=kb.elm(".kb_spread_style_"+CSS.escape(h));h.parentNode.removeChild(h)})("view_"+b.id+"_"+b.view.id+"_"+location.host.split(".").first());m.parentNode.show()}),submit:kb.create("button").addClass("kb-linkage-container-button").on("click",n=>{var h=l.tr.reduce((v,y,H)=>{v.error||"unsaved"!=y.elm(".kb-scope").attr("unsaved")||(y=kb.record.get(y.elm(".kb-scope"),b),y.error?v.error=!0:v.records["row"+H.toString()]=y.record);return v},
{error:!1,records:{}}),q=(v=!1)=>{[a.total,a.reload,a.open,a.edit,a.prev,a.next,a.copy].each((y,H)=>y.removeClass("kb-hidden"));[a.submit,a.cancel].each((y,H)=>y.addClass("kb-hidden"));v?G((e.mobile?kintone.mobile.app.record:kintone.app.record).get().record):x()};h.error||0==Object.keys(h.records).length?q():kb.confirm(kb.constants.common.message.confirm.submit[kb.operator.language],v=>{if(v)q();else{var y={},H;for(H in h.records)((I,R)=>{var K=I.$id.value,S=I.$rowId.value,N=JSON.parse(JSON.stringify(f.origin.find(B=>
B.$id.value==K)||{}));0!=Object.keys(N)&&(K in y||(y[K]=(B=>{var F={id:K,record:{$id:N.$id}};B&&(F.record[B]=N[B]);return F})(Array.from(new Set(d.mapping.value.map(B=>g.parallelize[B.value.external.value].tableCode))).join(""))),y[K].record=b.view.fields.reduce((B,F)=>{l.tr[R].elm('[field-id="'+CSS.escape(F)+'"]').hasAttribute("edited")&&(P=>{P?B[P].value.each((Q,T)=>{Q.id==S&&(Q.value[F]=I[F])}):B[F]=I[F]})(b.fields[F].tableCode);return B},y[K].record))})(h.records[H],H.replace(/^row/g,""));kb.view.records.set(b.id,
{put:Object.values(y)},!1,!0).then(I=>{q(!0)}).catch(I=>{kb.alert(kb.error.parse(I));q()})}},!0)}).html(kb.constants.common.caption.button.submit[kb.operator.language]).addClass("kb-hidden"),cancel:kb.create("button").addClass("kb-linkage-container-button").on("click",n=>{[a.total,a.reload,a.open,a.edit,a.prev,a.next,a.copy].each((h,q)=>h.removeClass("kb-hidden"));[a.submit,a.cancel].each((h,q)=>h.addClass("kb-hidden"));x()}).html(kb.constants.common.caption.button.cancel[kb.operator.language]).addClass("kb-hidden"),
open:kb.create("button").addClass("kb-icon kb-icon-open").on("click",n=>{window.open(kb.record.page.view(e.mobile,b.id,"20",f.query))}),prev:kb.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-left").on("click",n=>{f.offset-=c;x()}),next:kb.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-right").on("click",n=>{f.offset+=c;x()}),reload:kb.create("button").addClass("kb-icon kb-icon-reload").on("click",n=>{G((e.mobile?kintone.mobile.app.record:kintone.app.record).get().record)}),
total:kb.create("span").addClass("kb-linkage-container-monitor").html("")},x=()=>{var n=f.records.slice(f.offset,f.offset+c);l.clearRows();n.each((h,q)=>{(v=>{kb.record.set(v.elm("[form-id=form_"+b.id+"]"),b,h).then(()=>{v.elm(".kb-view-row-edit").attr("href",kb.record.page.detail(e.mobile,b.id,h.$id.value)).attr("target","_blank");q==n.length-1&&m.parentNode.show()})})(l.addRow())});switch(kb.operator.language){case "en":a.total.html(f.records.length.toString()+"records in total");break;case "ja":a.total.html("\u7dcf"+
f.records.length.toString()+"\u884c");break;case "zh":a.total.html("\u5171"+f.records.length.toString()+"\u6761\u8bb0\u5f55");break;case "zh-TW":a.total.html("\u5171"+f.records.length.toString()+"\u7b46\u8a18\u9304")}0<f.offset?a.prev.removeAttr("disabled"):a.prev.attr("disabled","disabled");f.offset+(c==n.length?c:n.length)<f.records.length?a.next.removeAttr("disabled"):a.next.attr("disabled","disabled")},G=n=>{O(d,n).then(h=>{f=h;x();w(d,g,{},f.records)}).catch(()=>{f={offset:0,records:[]};x();
w(d,g,{},f.records)})};switch(e.type){case "create":case "edit":m.append(kb.create("div").addClass("kb-linkage-container-footer").append(a.total).append(a.reload).append(a.open).append(a.edit).append(a.prev).append(a.next).append(a.copy).append(a.submit).append(a.cancel));break;case "detail":m.append(kb.create("div").addClass("kb-linkage-container-footer").append(a.total).append(a.reload).append(a.open).append(a.edit).append(a.prev).append(a.next).append(a.submit).append(a.cancel))}d.editable.value.includes("editable")||
a.edit.addClass("kb-hidden");((n,h)=>{kintone.events.on(n,h);n.each((q,v)=>{q in e.handlers||(e.handlers[q]=[]);e.handlers[q].push(h)})})(d.criteria.value.reduce((n,h)=>{n.push("app.record.create.change."+h.value.internal.value);n.push("app.record.edit.change."+h.value.internal.value);n.push("mobile.app.record.create.change."+h.value.internal.value);n.push("mobile.app.record.edit.change."+h.value.internal.value);return n},[]),n=>{G(n.record);return n});b.view.fields.each((n,h)=>{kb.event.on("kb.change."+
n,q=>{q.container.elm('[field-id="'+CSS.escape(n)+'"]').attr("edited","edited");return q})});G(t.record)})(kb.view.create(m.addClass("kb-linkage-container"),b,b.view.id,e.mobile).elm(".kb-view"),parseInt(d.limit.value))})({id:d.app.value,disables:[],fields:(b=>{b.$rowId={code:"$rowId",type:"SINGLE_LINE_TEXT",label:"",required:!1,noLabel:!0,placeholder:""};return b})(g.parallelize),view:{id:"linkage_"+d.app.value+"_"+d.container.value,buttons:["delete"],fields:d.mapping.value.map(b=>b.value.external.value),
mode:"viewer"}})}).catch(()=>{})})((e.mobile?kintone.mobile.app.record:kintone.app.record).getSpaceElement(d.container.value).css({width:"max-content"}));k++;k<r.length&&A(k)})(r[k])};A(0);C(t);break;case "index":A=k=>{(d=>{kb.filter.auth(d.user.value,d.organization.value,d.group.value).then(m=>{m&&(d.view.value&&d.view.value!=t.viewId.toString()||kb.button.create(e.mobile,e.type,"kb-linkage-button"+k.toString(),d.label.value,d.message.value,()=>{kb.view.records.get(e.app.id,(e.mobile?kintone.mobile.app:
kintone.app).getQueryCondition()).then(g=>{var b=[];let l=(c,f)=>{kb.field.load(d.app.value).then(a=>{O(d,g[c]).then(x=>{var G=E(d,g[c],x.records);w(d,a,G,x.records);b.push(kb.view.records.transform(G));kb.progressUpdate();c++;c<g.length?l(c,f):f()}).catch(()=>{})}).catch(()=>{})};0!=g.length?(kb.progressStart(g.length),l(0,()=>{kb.view.records.set(e.app.id,{put:b}).then(c=>kb.alert("Done!",()=>window.location.reload(!0))).catch(c=>kb.alert(kb.error.parse(c)))})):kb.alert("There are no records.")}).catch(g=>
kb.alert(kb.error.parse(g)))}));k++;k<r.length&&A(k)}).catch(m=>{k++;k<r.length&&A(k)})})(r[k])},A(0),C(t)}}else C(t)})(JSON.parse(p.tab).map((r,w)=>kb.extend({sIndex:{value:w.toString()}},r.setting)).reduce((r,w)=>{switch(e.type){case "index":w.bulk.value.includes("bulk")&&r.push(w);break;default:r.push(w)}return r},[]))}catch(r){kb.alert(kb.error.parse(r)),C(t)}}).catch(u=>C(t)):C(t)}).catch(p=>C(t))})("mobile"==t.type.split(".").first(),t.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
