/*
* FileName "plugins.style.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(A=>{var c={handlers:{}},C=(f,l,y,u="record",w="detail")=>{var p=(()=>{var r={},v=0;if("record"==u)for(var t in l)t in c.fieldInfos.tables&&l[t].value.each((k,g)=>{null==k.id&&(v++,k.id=v);r[k.id]=g},{});return r})();return new Promise((r,v)=>{var t={},k=(g,q)=>{var z={color:(e,h,m)=>{if(e.nextSibling&&e.nextSibling.tagName.toLowerCase().startsWith("kuc"))switch(h.type){case "DROP_DOWN":e.nextSibling.elm("button")&&e.nextSibling.elm("button").css(m);break;case "FILE":e.nextSibling.firstElementChild&&
(e.nextSibling.firstElementChild.css(m),e.nextSibling.firstElementChild.elms("*").filter(a=>a instanceof HTMLElement).each((a,x)=>a.css(m)));(new MutationObserver(()=>{e.nextSibling.firstElementChild.css(m);e.nextSibling.firstElementChild.elms("*").filter(a=>a instanceof HTMLElement).each((a,x)=>a.css(m))})).observe(e.nextSibling,{childList:!0,subtree:!0});break;case "NUMBER":case "SINGLE_LINE_TEXT":h.lookup&&e.nextSibling.elm("input[type=text]")&&(a=>{a.css(m);m.backgroundColor?a.addClass("kb-inherit-backcolor"):
a.removeClass("kb-inherit-backcolor");m.color.value?a.addClass("kb-inherit-forecolor"):a.removeClass("kb-inherit-forecolor")})(e.nextSibling.elm("input[type=text]"))}switch(h.type){case "DROP_DOWN":kb.event.on("kb.style.color.call",a=>{a.field==e&&e.nextSibling.elm("button")&&e.nextSibling.elm("button").css(m);return a});break;case "NUMBER":case "SINGLE_LINE_TEXT":if(h.lookup)kb.event.on("kb.style.color.call",a=>{if(a.field==e&&e.nextSibling.elm("input[type=text]")){var x=e.nextSibling.elm("input[type=text]");
x.css(m);m.backgroundColor?x.addClass("kb-inherit-backcolor"):x.removeClass("kb-inherit-backcolor");m.color.value?x.addClass("kb-inherit-forecolor"):x.removeClass("kb-inherit-forecolor")}return a})}},display:(e,h,m)=>{e.nextSibling&&e.nextSibling.tagName.toLowerCase().startsWith("kuc")&&(e.nextSibling.visible=m);kb.event.on("kb.style.display.call",a=>{a.field==e&&(e.nextSibling.visible=m);return a})},editable:(e,h,m)=>{if(e.nextSibling&&e.nextSibling.tagName.toLowerCase().startsWith("kuc"))switch(e.nextSibling.disabled=
m,h.type){case "NUMBER":case "SINGLE_LINE_TEXT":h.lookup&&(e.nextSibling.disabledOptions=m)}kb.event.on("kb.style.editable.call",a=>{if(a.field==e)switch(e.nextSibling.disabled=m,h.type){case "NUMBER":case "SINGLE_LINE_TEXT":h.lookup&&(e.nextSibling.disabledOptions=m)}return a})}};(e=>{var h=kb.filter.scan(c.app,l,e.condition.value);h?kb.filter.auth(e.user.value,e.organization.value,e.group.value).then(m=>{m&&(e.color.value.map(a=>a.value).each((a,x)=>{a.field.value in c.fieldInfos.parallelize&&(b=>
{switch(u){case "record":b.tableCode?b.tableCode in h&&(d=>{(n=>{if(kb.elms(n).length!=l[b.tableCode].value.length){let B=new MutationObserver(()=>{kb.elms(n).length==l[b.tableCode].value.length&&(d(),B.disconnect())});B.observe(kb.elm(".subtable-"+c.fieldInfos.tables[b.tableCode].id),{childList:!0,subtree:!0})}else d()})(".subtable-"+c.fieldInfos.tables[b.tableCode].id+(c.mobile?" .subtable-row-gaia":" tbody tr"))})(()=>{h[b.tableCode].value.each((d,n)=>{b.code in d.value&&(n=kb.field.get(b,c.mobile,
c.type||w))&&(n[p[d.id]].value.css({backgroundColor:a.backcolor.value,color:a.forecolor.value}),z.color(n[p[d.id]],b,{backgroundColor:a.backcolor.value,color:a.forecolor.value}),a.backcolor.value?n[p[d.id]].value.addClass("kb-inherit-backcolor"):n[p[d.id]].value.removeClass("kb-inherit-backcolor"),a.forecolor.value?n[p[d.id]].value.addClass("kb-inherit-forecolor"):n[p[d.id]].value.removeClass("kb-inherit-forecolor"))})}):b.code in h&&(d=>{d&&(d.value.css({backgroundColor:a.backcolor.value,color:a.forecolor.value}),
z.color(d,b,{backgroundColor:a.backcolor.value,color:a.forecolor.value}),a.backcolor.value?d.value.addClass("kb-inherit-backcolor"):d.value.removeClass("kb-inherit-backcolor"),a.forecolor.value?d.value.addClass("kb-inherit-forecolor"):d.value.removeClass("kb-inherit-forecolor"))})(kb.field.get(b,c.mobile,c.type||w));break;case "view":b.tableCode?b.tableCode in h&&h[b.tableCode].value.each((d,n)=>{b.code in d.value&&(d.value[b.code].backcolor=a.backcolor.value,d.value[b.code].forecolor=a.forecolor.value)}):
b.code in h&&(h[b.code].backcolor=a.backcolor.value,h[b.code].forecolor=a.forecolor.value)}})(c.fieldInfos.parallelize[a.field.value])}),e.display.value.map(a=>a.value).each((a,x)=>{switch(u){case "record":((b,d)=>{if(b&&!b.tableCode){var n=kb.field.get(b,c.mobile,c.type||w);n&&n.nextSibling&&n.nextSibling.tagName.toLowerCase().startsWith("kuc")&&(z.display(n,b,"show"==a.state.value),d=!0)}d||(c.mobile?kintone.mobile.app.record:kintone.app.record).setFieldShown(a.field.value,"show"==a.state.value)})(c.fieldInfos.parallelize[a.field.value],
!1);break;case "view":a.field.value in c.fieldInfos.groups?c.fieldInfos.groups[a.field.value].fields.map(b=>b.code).each((b,d)=>{b in c.fieldInfos.parallelize&&b in h&&(h[b].hidden="hide"==a.state.value)}):a.field.value in c.fieldInfos.tables?a.field.value in h&&(h[a.field.value].hidden="hide"==a.state.value):(b=>{b.tableCode?b.tableCode in h&&h[b.tableCode].value.each((d,n)=>{b.code in d.value&&(d.value[b.code].hidden="hide"==a.state.value)}):b.code in h&&(h[b.code].hidden="hide"==a.state.value)})(c.fieldInfos.parallelize[a.field.value])}}),
e.toggle.value.map(a=>a.value).each((a,x)=>{switch(u){case "record":(c.mobile?kintone.mobile.app.record:kintone.app.record).setGroupFieldOpen(a.field.value,"open"==a.state.value)}}),(["create","edit"].includes(c.type||w)||"view"==u)&&e.editable.value.map(a=>a.value).each((a,x)=>{a.field.value in c.fieldInfos.parallelize&&(b=>{c.fieldInfos.disables.includes(b.code)||(b.tableCode?b.tableCode in h&&(h[b.tableCode].value.each((d,n)=>{b.code in d.value&&(d.value[b.code].disabled="disable"==a.state.value)}),
t[b.code]=l[b.tableCode].value.map(d=>d.value[b.code].disabled?"disabled":""),"record"==u&&(d=>{(n=>{if(kb.elms(n).length!=l[b.tableCode].value.length){let B=new MutationObserver(()=>{kb.elms(n).length==l[b.tableCode].value.length&&(d(),B.disconnect())});B.observe(kb.elm(".subtable-"+c.fieldInfos.tables[b.tableCode].id),{childList:!0,subtree:!0})}else d()})(".subtable-"+c.fieldInfos.tables[b.tableCode].id+(c.mobile?" .subtable-row-gaia":" tbody tr"))})(()=>{h[b.tableCode].value.each((d,n)=>{b.code in
d.value&&(n=kb.field.get(b,c.mobile,c.type||w))&&z.editable(n[p[d.id]],b,"disable"==a.state.value)})})):b.code in h&&(h[b.code].disabled="disable"==a.state.value,"record"==u&&(d=>{d&&z.editable(d,b,"disable"==a.state.value)})(kb.field.get(b,c.mobile,c.type||w)),t[b.code]=l[b.code].disabled?"disabled":""))})(c.fieldInfos.parallelize[a.field.value])}));g++;g<f.length?k(g,q):q()}).catch(m=>{kb.alert(kb.error.parse(m));v()}):(g++,g<f.length?k(g,q):q())})(f[g])};"record"==u&&(kb.elms(".kb-inherit-backcolor").each((g,
q)=>{g.css({backgroundColor:""});g.removeClass("kb-inherit-backcolor")}),kb.elms(".kb-inherit-forecolor").each((g,q)=>{g.css({color:""});g.removeClass("kb-inherit-forecolor")}));kb.event.off(["kb.style.color.call","kb.style.display.call","kb.style.editable.call"]);k(0,()=>{y.latest?y.latest.style||(y.latest.style="{}"):y.latest={style:"{}"};var g=JSON.stringify(t),q="{}"!=g?y.latest.style!=g:!1;q&&(y.latest.style=g);r({performed:q})})})};kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.print.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show".split(" "),
f=>new Promise((l,y)=>{((u,w)=>{c.mobile=u;c.type=w;for(var p in c.handlers)c.handlers[p].each((r,v)=>{kintone.events.off(p,r)});kb.config[A].config.get().then(r=>{0!=Object.keys(r).length?(f.reuse&&(v=>{"reusecolor"in v&&v.reusecolor.value&&kintone.app.record.getHeaderMenuSpaceElement().nextSibling.firstElementChild.css({backgroundColor:v.reusecolor.value})})(JSON.parse(r.flat)),kb.field.load(kb.config[A].app,!0).then(v=>{c.app={id:kb.config[A].app,fields:v.origin};c.fieldInfos=v;try{(t=>{0!=t.length?
["create","edit"].includes(c.type)?(((k,g)=>{kintone.events.on(k,g);k.each((q,z)=>{q in c.handlers||(c.handlers[q]=[]);c.handlers[q].push(g)})})(v.changes.reduce((k,g)=>{k.push("app.record.create.change."+g);k.push("app.record.edit.change."+g);k.push("mobile.app.record.create.change."+g);k.push("mobile.app.record.edit.change."+g);return k},[]),k=>{if((()=>{var g=!0;["DATETIME","TIME"].includes(k.changes.field.type)&&(q=>{q&&(Array.isArray(q)?q:[q]).each((z,e)=>{z.elm(".control-errors-content-gaia")&&
(g=!1)})})(kb.field.get(c.fieldInfos.parallelize[k.type.split(".").last()],c.mobile,c.type));return g})())return kb.event.call("kb.action.installed.change",{installed:!1,mobile:c.mobile}).then(g=>{g.installed||C(t,k.record,kb.elm("body"),"record").then(q=>{q.performed&&(c.mobile?kintone.mobile.app.record:kintone.app.record).set(k)}).catch(()=>{})}),k}),kb.event.call("kb.action.installed.show",{installed:!1,mobile:c.mobile}).then(k=>{k.installed?l(f):C(t,f.record,kb.elm("body"),"record").then(g=>l(f)).catch(()=>
{})})):C(t,f.record,kb.elm("body"),"record").then(k=>l(f)).catch(()=>{}):l(f)})(JSON.parse(r.tab).map((t,k)=>kb.extend({sIndex:{value:k.toString()}},t.setting)).reduce((t,k)=>{(c.mobile?["all","both","mobile"]:["all","both","pc"]).includes(k.device.value)&&k.page.value.includes(c.type)&&t.push(k);return t},[]))}catch(t){kb.alert(kb.error.parse(t)),l(f)}}).catch(v=>l(f))):l(f)}).catch(r=>l(f))})("mobile"==f.type.split(".").first(),f.type.split(".").slice(-2).first())}));kb.event.on("kb.style.call",
f=>new Promise((l,y)=>{kb.config[A].config.get().then(u=>{0!=Object.keys(u).length?kb.field.load(kb.config[A].app,!0).then(w=>{c.app={id:kb.config[A].app,fields:w.origin};c.fieldInfos=w;c.mobile="mobile"in c?c.mobile:f.mobile;try{(p=>{0!=p.length?C(p,f.record,f.container,f.workplace?f.workplace:"record",f.pattern).then(r=>{f.performed=r.performed;l(f)}).catch(()=>l(f)):l(f)})(JSON.parse(u.tab).map((p,r)=>kb.extend({sIndex:{value:r.toString()}},p.setting)).reduce((p,r)=>{(f.mobile?["all","both","mobile"]:
["all","both","pc"]).includes(r.device.value)&&r.page.value.includes(f.pattern)&&p.push(r);return p},[]))}catch(p){kb.alert(kb.error.parse(p)),l(f)}}).catch(w=>l(f)):l(f)}).catch(u=>l(f))}))})(kintone.$PLUGIN_ID);
