/*
* FileName "plugins.report.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(E=>{var e={},G=(b,c,F=!1)=>new Promise((x,v)=>{var p=(h,f)=>{var l=()=>{h++;h<b.length?p(h,f):f()};(a=>{kb.filter.scan(e.app,c,a.condition.value)?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(m=>{if(m)if(a.attachment.value in e.fieldInfos.origin){var y=Object.values(e.fieldInfos.tables).reduce((n,B)=>{Object.values(B.fields).each((C,k)=>{n[C.code]={index:-1,limit:c[B.code].value.length,status:"ready",table:B.code}});return n},{});(n=>{if(0!=n.sheets.length){var B=(k,r,z)=>
{(u=>{var g=!1,A=kb.extend({},u),D;for(D in e.fieldInfos.parallelize)(d=>{u.cells.each((L,J)=>{L.each((q,K)=>{if(q.value.match(new RegExp("%"+d.code+"%")))switch(d.type){case "FILE":(t=>{Array.isArray(t)?(w=>{if(w){q.type="image";var M=u.rows.slice(J,J+parseInt(q.rowSpan||"1")).reduce((H,I)=>H+=I.origin,0),N=u.cols.slice(K,K+parseInt(q.colSpan||"1")).reduce((H,I)=>H+=I.origin,0);r.push({cell:q,fileKey:w.fileKey,size:{height:M,width:N}});g=!0}else q.value=""})(t.find(w=>w.contentType.match(/image/g))):
q.value=""})((()=>{var t=null;if(d.code in y){var w=y[d.code];"complete"!=w.status&&(w.index++,w.status=w.index==w.limit-1?"complete":"processing",t=c[w.table].value[w.index].value[d.code].value)}else t=c[d.code].value;return t})());break;default:d.code in y?(t=>{"complete"!=t.status?(t.index++,t.status=t.index==t.limit-1?"complete":"processing",q.value=q.value.replace(new RegExp("%"+d.code+"%","g"),kb.field.stringify(d,c[t.table].value[t.index].value[d.code].value," / ",!0)),g=!0):q.value=q.value.replace(new RegExp("%"+
d.code+"%","g"),"")})(y[d.code]):(q.value=q.value.replace(new RegExp("%"+d.code+"%","g"),kb.field.stringify(d,c[d.code].value," / ",!0)),g=!0)}q.value.match(/^=(TODAY|DATE_FORMAT)/)&&(q.value=eval(q.value.replace(/^=/g,"kb.formula.report.")))})})})(e.fieldInfos.parallelize[D]);u.repeat&&(Object.values(y).some(d=>"processing"==d.status)?n.sheets.splice(k+1,0,A):g||(n.sheets.splice(k,1),k--));k++;k<n.sheets.length?B(k,r,z):z(r)})(n.sheets[k])},C=(k,r,z)=>{0!=r.length?kb.file.download(r[k],!0).then(u=>
{var g=new Image;g.onload=()=>{var A=Math.min(r[k].size.width/g.width,r[k].size.height/g.height),D=Math.round(g.height*A);A=Math.round(g.width*A);var d=kb.create("canvas");d.width=A;d.height=D;d.getContext("2d").drawImage(g,0,0,A,D);r[k].cell.value=d.toDataURL("image/png");k++;k<r.length?C(k,r,z):z()};g.src=URL.createObjectURL(u)}).catch(u=>kb.alert(kb.error.parse(u),()=>v())):z()};B(0,[],k=>{C(0,k,()=>{(r=>{fetch("https://api.pandafirm.jp/layup/report",{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},
body:JSON.stringify({lang:kb.operator.language,name:r,datas:n})}).then(z=>{z.json().then(u=>{switch(z.status){case 200:kb.file.upload((g=>{var A=atob(g.binary),D=new Uint8Array(A.length);A.length.each(d=>D[d]=A.charCodeAt(d));return new File([new Blob([D.buffer],{type:g.contentType})],g.filename,{type:g.contentType})})(u.file),!0).then(g=>{window.hasOwnProperty("kb_report_temp")||(window.kb_report_temp={});window.kb_report_temp[g.fileKey]=u.file.binary;c[a.attachment.value].value.push(g);l()}).catch(g=>
{kb.alert(kb.error.parse(g),()=>v())});break;default:kb.alert(kb.error.parse(u),()=>v())}})}).catch(z=>kb.alert(kb.error.parse(z),()=>v()))})((a.name.value in e.fieldInfos.origin?c[a.name.value].value:"")||"report")})})}else l()})(a.template.value?JSON.parse(a.template.value):{sheets:[]})}else l();else l()}).catch(m=>kb.alert(kb.error.parse(m),()=>v())):l()})(b[h])};F||kb.loadStart();p(0,()=>{kb.view.records.set(e.app.id,{put:[kb.view.records.transform(b.reduce((h,f)=>{f.attachment.value in e.fieldInfos.origin&&
(h[f.attachment.value]=c[f.attachment.value]);return h},{$id:c.$id}))]},!0).then(h=>{F||kb.loadEnd();x()}).catch(h=>kb.alert(kb.error.parse(h),()=>v()))})});kintone.events.on("app.record.create.submit.success app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),b=>new Promise((c,F)=>{((x,v)=>{e.mobile=x;e.type=v;kb.config[E].config.get().then(p=>
{0!=Object.keys(p).length?kb.field.load(kb.config[E].app,!0).then(h=>{e.app={id:kb.config[E].app,fields:h.origin};e.fieldInfos=h;try{(f=>{if(0!=f.length)switch(e.type){case "create":case "edit":G(f,b.record).then(a=>c(b)).catch(()=>c(b));break;case "detail":var l=a=>{(m=>{kb.filter.scan(e.app,b.record,m.condition.value)?kb.filter.auth(m.user.value,m.organization.value,m.group.value).then(y=>{y&&kb.button.create(e.mobile,e.type,"kb-report-button"+a.toString(),m.label.value,m.message.value,()=>G([m],
b.record).then(n=>kb.alert("Done!",()=>window.location.reload(!0))).catch(()=>{}));a++;a<f.length&&l(a)}).catch(y=>{a++;a<f.length&&l(a)}):(a++,a<f.length&&l(a))})(f[a])};l(0);c(b);break;case "index":l=a=>{(m=>{kb.filter.auth(m.user.value,m.organization.value,m.group.value).then(y=>{y&&(m.view.value&&m.view.value!=b.viewId.toString()||kb.button.create(e.mobile,e.type,"kb-report-button"+a.toString(),m.label.value,m.message.value,()=>{kb.view.records.get(e.app.id,(e.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(n=>
{let B=(C,k)=>{G([m],n[C],!0).then(r=>{kb.progressUpdate();C++;C<n.length?B(C,k):k()}).catch(()=>{})};0!=n.length?(kb.progressStart(n.length),B(0,()=>kb.alert("Done!",()=>window.location.reload(!0)))):kb.alert("There are no records.")}).catch(n=>kb.alert(kb.error.parse(n)))}));a++;a<f.length&&l(a)}).catch(y=>{a++;a<f.length&&l(a)})})(f[a])},l(0),c(b)}else c(b)})(JSON.parse(p.tab).map((f,l)=>kb.extend({sIndex:{value:l.toString()}},f.setting)).reduce((f,l)=>{(e.mobile?["all","both","mobile"]:["all",
"both","pc"]).includes(l.device.value)&&l.event.value.includes(e.type)&&f.push(l);return f},[]))}catch(f){kb.alert(kb.error.parse(f),()=>c(b))}}).catch(h=>c(b)):c(b)}).catch(p=>c(b))})("mobile"==b.type.split(".").first(),(x=>{switch(x){case "submit":x=b.type.split(".").slice(-3).first()}return x})(b.type.split(".").slice(-2).first()))}));kb.event.on("kb.report.call",b=>new Promise((c,F)=>{kb.config[E].config.get().then(x=>{0!=Object.keys(x).length?kb.field.load(kb.config[E].app,!0).then(v=>{e.app=
{id:kb.config[E].app,fields:v.origin};e.fieldInfos=v;try{(p=>{0!=p.length?G(p,b.record,!0).then(h=>c(b)).catch(()=>c(b)):c(b)})(JSON.parse(x.tab).map((p,h)=>kb.extend({sIndex:{value:h.toString()}},p.setting)).reduce((p,h)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(h.device.value)&&h.event.value.includes(b.pattern)&&p.push(h);return p},[]))}catch(p){kb.alert(kb.error.parse(p),()=>c(b))}}).catch(v=>c(b)):c(b)}).catch(x=>c(b))}))})(kintone.$PLUGIN_ID);
