/*
* FileName "main.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';window.BooooooostInjector=class{constructor(){this.fields={}}build(m,n){try{window.bst.attachment=new BooooooostAttachment,window.bst.field=new BooooooostField,window.bst.filter=new BooooooostFilter,window.bst.formula=new BooooooostFormula,window.bst.record=new BooooooostRecord,window.bst.table=new BooooooostTable,window.kb.attachment=window.bst.attachment,window.kb.field=window.bst.field,window.kb.filter=window.bst.filter,window.kb.formula=window.bst.formula,window.kb.record=window.bst.record,window.kb.table=
window.bst.table,bst.field.load(m).then(k=>{this.app={id:m,fields:k.origin};this.queries=(a=>{var b={id:"",fields:{},pattern:"",sender:""};"id"in a&&(b.id=bst.isNumeric(a.id)?a.id:"");"pattern"in a&&(b.pattern=a.pattern);"pre"in a&&(b.fields=JSON.parse((new TextDecoder).decode(Uint8Array.from(atob(decodeURIComponent(a.pre)).split("").map(d=>d.charCodeAt(0))))));"sender"in a&&(b.sender=decodeURIComponent(a.sender));return b})(bst.queries());this.setting=bst.extend({ui:{}},n);bst.elm("body").append((a=>
{this.setting.ui.container=a;"detail"==this.queries.pattern&&this.setting.ui.container.addClass("kb-uneditable");return a})(bst.create("div").addClass("kb-injector")).append(bst.create("div").addClass("kb-injector-main").append((a=>this.setting.ui.header=a)(bst.create("header").addClass("kb-injector-header")).append(bst.create("div").addClass("kb-injector-header-title").html(this.setting.title)).append(bst.create("div").addClass("kb-injector-header-description").html(this.setting.description?this.setting.description.replace(/\n/g,
"<br>"):"")).append(bst.create("div").addClass("kb-injector-header-space"))).append((a=>this.setting.ui.body=a)(bst.create("main").addClass("kb-injector-body"))).append((a=>{this.setting.ui.footer=a;this.setting.ui.buttons={ok:bst.create("button").addClass("kb-injector-button").html(bst.constants.injector.caption.button.submit[bst.operator.language])};return a.append(this.setting.ui.buttons.ok)})(bst.create("footer").addClass("kb-injector-footer")))));((a,b,d)=>{this.setting.fields.each((c,f)=>{c.code in
this.app.fields&&((e,g)=>{switch(g.type){case "SUBTABLE":if("alter"in e){e.alter.label&&(g.label=e.alter.label.replace(/\n/g,"<br>"));for(var h in e.alter.fields)h in g.fields&&e.alter.fields[h].label&&(g.fields[h].label=e.alter.fields[h].label.replace(/\n/g,"<br>"))}g.noLabel||a.append(bst.create("div").append(bst.create("span").addClass("kb-table-caption").html(g.label)));a.append(bst.table.activate(bst.table.create(g,!0,!1,!0,!0),this.app));break;default:"alter"in e&&e.alter.label&&(g.label=e.alter.label.replace(/\n/g,
"<br>")),g.lookup&&Array.prototype.push.apply(d,g.lookup.fieldMappings.map(l=>l.field)),a.append(bst.field.activate(bst.field.create(g,!0),this.app))}})(c,this.app.fields[c.code])});b.each((c,f)=>{c.code in this.app.fields&&(e=>{switch(e.type){case "SUBTABLE":a.append(bst.table.activate(bst.table.create(e),this.app).addClass("kb-unuse"));break;default:a.append(bst.field.activate(bst.field.create(e),this.app).addClass("kb-unuse"))}})(this.app.fields[c.code])});d.each((c,f)=>{a.elm('[field-id="'+CSS.escape(c)+
'"]')&&a.elm('[field-id="'+CSS.escape(c)+'"]').addClass("kb-readonly")});a.addClass("kb-scope").attr("form-id","form_"+this.app.id).append(bst.create("input").attr("type","hidden").attr("data-type","id")).elms("input,select,textarea").each((c,f)=>c.initialize())})(this.setting.ui.body,Object.values(this.app.fields).reduce((a,b)=>{this.setting.fields.some(d=>d.code==b.code)||a.push(b);return a},[]),[]);this.setting.ui.buttons.ok.on("click",a=>{a=bst.record.get(this.setting.ui.body,this.app);a.error||
bst.event.call("bst.submit.call",{record:a.record,pattern:this.queries.id?"edit":"create"}).then(b=>{b.error||(bst.loadStart(),bst.event.call(this.queries.id?"bst.edit.submit":"bst.create.submit",{container:this.setting.ui.body,record:b.record}).then(d=>{d.error?bst.loadEnd():bst.confirm(bst.constants.common.message.confirm.submit[bst.operator.language],()=>{bst.loadStart();bst.record.api.set(this.app.id,{post:this.queries.id?[]:[d.record],put:this.queries.id?[{id:this.queries.id,record:d.record}]:
[]},!0,!0,!0).then(c=>{bst.api(bst.api.url("/api/record"),"GET",{app:this.app.id,id:c?c:this.queries.id}).then(f=>{bst.event.call(this.queries.id?"bst.edit.submit.success":"bst.create.submit.success",{container:d.container,record:f.record}).then(e=>{e.error||bst.event.call("bst.report.call",{record:f.record,pattern:this.queries.id?"edit":"create"}).then(g=>{g.error||bst.event.call("bst.mail.call",{record:f.record,pattern:this.queries.id?"edit":"create"}).then(h=>{h.error||bst.event.call("bst.omail.call",
{record:f.record,pattern:this.queries.id?"edit":"create"}).then(l=>{l.error||bst.event.call("bst.upsert.call",{record:f.record,pattern:this.queries.id?"edit":"create"}).then(p=>{p.error||(this.setting.ui.body.removeAttr("unsaved"),bst.alert("Done!",()=>{this.queries.sender?window.parent.postMessage("Done",this.queries.sender):window.location.reload(!0)}))}).catch(()=>{})}).catch(()=>{})}).catch(()=>{})}).catch(()=>{})})}).catch(f=>bst.alert(bst.error.parse(f)))}).catch(c=>bst.alert(bst.error.parse(c)))})}))}).catch(()=>
{})});window.on("beforeunload",a=>{this.setting.ui.body.hasAttribute("unsaved")&&(a.returnValue=bst.constants.injector.message.confirm.changed[bst.operator.language])});this.queries.id?bst.api(bst.api.url("/api/record"),"GET",{app:this.app.id,id:this.queries.id}).then(a=>{bst.event.call("bst.edit.load",{container:this.setting.ui.body,record:a.record}).then(b=>{b.error||bst.event.call("bst.action.call",{container:this.setting.ui.body,record:b.record,pattern:"edit"}).then(d=>{bst.event.call("bst.style.call",
{container:this.setting.ui.body,record:d.record,pattern:"edit"}).then(c=>{bst.event.call("bst.cascade.call",c).then(f=>{bst.record.set(this.setting.ui.body.removeAttr("unsaved"),this.app,f.record).then(()=>{bst.event.call("bst.edit.load.complete",{container:this.setting.ui.body});this.setting.ui.body.elm("input,select,textarea").focus()})}).catch(()=>{})}).catch(()=>{})}).catch(()=>{})})}).catch(a=>bst.alert(bst.error.parse(a))):bst.event.call("bst.create.load",{container:this.setting.ui.body,record:(()=>
{bst.record.clear(this.setting.ui.body,this.app);var a=bst.record.get(this.setting.ui.body,this.app,!0).record;for(var b in this.queries.fields)a[b]=this.queries.fields[b];return a})()}).then(a=>{a.error||bst.event.call("bst.action.call",{container:this.setting.ui.body,record:a.record,pattern:"create"}).then(b=>{bst.event.call("bst.style.call",{container:this.setting.ui.body,record:b.record,pattern:"create"}).then(d=>{bst.event.call("bst.cascade.call",d).then(c=>{bst.record.set(this.setting.ui.body.removeAttr("unsaved"),
this.app,c.record).then(()=>{bst.event.call("bst.create.load.complete",{container:this.setting.ui.body});this.setting.ui.body.elm("input,select,textarea").focus()})}).catch(()=>{})}).catch(()=>{})}).catch(()=>{})})})}catch(k){bst.alert(bst.error.parse(k))}}};window.bst.injector||(window.bst.injector=new BooooooostInjector);
bst.constants=bst.extend({injector:{caption:{button:{submit:{en:"Submit",ja:"\u9001\u4fe1",zh:"\u63d0\u4ea4","zh-TW":"\u63d0\u4ea4"}}},description:{},message:{confirm:{changed:{en:"Your changes have not been saved.<br>Can I continue?",ja:"\u5909\u66f4\u304c\u4fdd\u5b58\u3055\u308c\u3066\u3044\u307e\u305b\u3093\u3002<br>\u3053\u306e\u307e\u307e\u7d9a\u884c\u3057\u307e\u3059\u304b\uff1f",zh:"\u66f4\u6539\u5c1a\u672a\u4fdd\u5b58\u3002<br>\u662f\u5426\u7ee7\u7eed\uff1f","zh-TW":"\u66f4\u6539\u5c1a\u672a\u4fdd\u5b58\u3002<br>\u662f\u5426\u7e7c\u7e8c\uff1f"}},
invalid:{}}}},bst.constants);window.kb.injector||(window.kb.injector=window.bst.injector);
