/*
* FileName "plugin.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';bst.event.on("bst.action.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.action)&&0!=bst.plugin.action.length){var b={},O=(C,g,k)=>new Promise((G,D)=>{var M=JSON.stringify(bst.record.simplify({fields:b.fieldInfos.origin},g)),I=(E,F)=>{var r=()=>{E++;E<C.length?I(E,F):F()};(a=>{var l=bst.filter.scan(b.app,g,a.condition.value);l?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var J={clear:d=>{try{a.clear.value.map(c=>c.value).each((c,f)=>{c.table.value in b.fieldInfos.tables&&
(g[c.table.value].value=g[c.table.value].value.filter(e=>!l[c.table.value].value.includes(e)),l[c.table.value].value=[])}),d()}catch(c){bst.alert(bst.error.parse(c)),D()}},fill:d=>{try{a.fill.value.map(c=>c.value).each((c,f)=>{c.table.value in b.fieldInfos.tables&&(e=>{e=bst.isNumeric(e)?parseInt(e)-l[c.table.value].value.length:0;0<e&&Array(e).fill().map(()=>bst.record.create(b.fieldInfos.origin[c.table.value],!1)).each((h,t)=>{g[c.table.value]==l[c.table.value]?g[c.table.value].value.push({value:h}):
(g[c.table.value].value.push({value:h}),l[c.table.value].value.push({value:h}))})})(bst.formula.calculate({field:{value:Object.values(b.fieldInfos.parallelize).first().code},formula:c.range},l,l,g,b.fieldInfos.parallelize))}),d()}catch(c){bst.alert(bst.error.parse(c)),D()}},formula:d=>{try{a.formula.value.map(c=>c.value).each((c,f)=>{c.field.value in b.fieldInfos.parallelize&&(e=>{e.tableCode?l[e.tableCode].value.each((h,t)=>{h.value[e.code].value=bst.formula.calculate(c,h.value,l,g,b.fieldInfos.parallelize);
e.lookup&&(h.value[e.code].lookup=!0)}):(l[e.code].value=bst.formula.calculate(c,l,l,g,b.fieldInfos.parallelize),e.lookup&&(l[e.code].lookup=!0))})(b.fieldInfos.parallelize[c.field.value])}),d()}catch(c){bst.alert(bst.error.parse(c)),D()}},lookup:d=>{try{a.lookupApp.value?bst.field.load(a.lookupApp.value).then(c=>{(f=>{var e=[],h=[],t=(A,n)=>{var v=(B,x)=>B.lookup?bst.extend({lookup:!0,type:B.type},x):bst.extend({type:B.type},x);bst.record.api.get(a.lookupApp.value,n.query,n.sort).then(B=>{0!=B.length?
(x=>{a.lookupLimited.value.includes("limited")||1==B.length?x(B.first()):b.picker.show({app:a.lookupApp.value,query:n.query,sort:n.sort,picker:e.reduce((u,m)=>{u[m.external.code]=m.external;return u},{})},u=>x(u))})(x=>{e.each((u,m)=>{if(a.lookupOverwrite.value.includes("overwrite")||bst.field.isEmpty(n.record[u.internal.code].value))n.record[u.internal.code]=v(u.internal,x[u.external.code])});A++;A<h.length?t(A,h[A]):(k.latest.action[a.sIndex.value].lookup=q(),d())}):(a.lookupReset.value.includes("reset")&&
e.each((x,u)=>{n.record[x.internal.code]=v(x.internal,bst.record.create({fields:{empty:x.internal}}).empty)}),A++,A<h.length?t(A,h[A]):(k.latest.action[a.sIndex.value].lookup=q(),d()))}).catch(B=>{bst.alert(bst.error.parse(B));D()})},q=()=>(A=>JSON.stringify(h.reduce((n,v)=>{n.push(v.query);n.push(bst.record.simplify({fields:A},v.record));return n},[])))(e.reduce((A,n)=>{A[n.internal.code]=n.internal;return A},{}));a.lookupCriteria.value.some(A=>!(A.value.external.value in f.external&&A.value.internal.value in
f.internal))?(bst.alert("No field to lookup was found"),D()):a.lookupMapping.value.some(A=>!(A.value.external.value in f.external&&A.value.internal.value in f.internal))?(bst.alert("No field to lookup was found"),D()):(e=a.lookupMapping.value.map(A=>({external:f.external[A.value.external.value],internal:f.internal[A.value.internal.value]})),h=(A=>A.map(n=>({query:a.lookupCriteria.value.reduce((v,B)=>{var x=f.external[B.value.external.value],u=B.value.operator.value;B=f.internal[B.value.internal.value];
var m=B.tableCode?n.value:g;a.lookupIgnore.value.includes("ignore")&&bst.field.isEmpty(m[B.code].value)||v.push(bst.filter.query.create(x,u,m[B.code]));return v},bst.filter.query.parse.expand({id:a.lookupApp.value,fields:c.origin},a.lookupFilter.value).map(v=>v.field+" "+v.operator+" "+v.value)).join(" and "),sort:(0!=a.lookupSort.value.length?a.lookupSort.value.map(v=>v.value.field.value+" "+v.value.order.value):["$id asc"]).join(","),record:n.value})))((A=>A?l[A].value:[{value:g}])(Array.from(new Set(e.map(A=>
A.internal.tableCode))).first())),0!=h.length?k.latest.action[a.sIndex.value].lookup&&k.latest.action[a.sIndex.value].lookup==q()?d():t(0,h.first()):d())})({external:c.origin,internal:b.fieldInfos.parallelize})}).catch(c=>{bst.alert(bst.error.parse(c));D()}):d()}catch(c){bst.alert(bst.error.parse(c)),D()}},user:d=>{try{if(a.userSource.value){var c=[],f=[],e=(t,q)=>{(n=>{c.each((v,B)=>{if(v.isCustom)switch(v.field.type){case "USER_SELECT":v.value=n.reduce((x,u)=>{"customItemValues"in u&&(m=>{0!=m.length&&
(K=>{(y=>{0!=y.length&&(x.some(L=>L.code==y.first().info.code)||x.push({code:y.first().info.code,name:y.first().info.name}))})(bst.roleSet.user.filter(y=>y.info.id==K))})(m.first().value)})(u.customItemValues.filter(m=>m.code==v.item));return Array.from(new Set(x)).filter(m=>m)},[]);break;default:v.value=n.reduce((x,u)=>{"customItemValues"in u&&(m=>{0!=m.length&&x.push(m.first().value)})(u.customItemValues.filter(m=>m.code==v.item));return Array.from(new Set(x)).filter(m=>m)},[]).join(",")}else switch(v.item){case "groups":case "organizations":v.value=
n.map(x=>x.code);break;case "primaryOrganization":v.value=n.reduce((x,u)=>{v.item in u&&(m=>{0!=m.length&&(x.some(K=>K.code==m.first().info.code)||x.push({code:m.first().info.code,name:m.first().info.name}))})(bst.roleSet.organization.filter(m=>m.info.id==u[v.item]));return x},[]);break;default:v.value=n.reduce((x,u)=>{v.item in u&&x.push(u[v.item]);return Array.from(new Set(x)).filter(m=>m)},[]).join(",")}})})(q[a.userSource.value].value.reduce((n,v)=>{(B=>{0!=B.length&&n.push(B.first().info)})(bst.roleSet.user.filter(B=>
B.info.code==v.code));return n},[]));var A=(n,v)=>{((B,x)=>{var u=(m,K,y)=>{bst.api(bst.api.url("/api/user/affiliations"),"GET",{code:B.value[m]}).then(L=>{switch(B.item){case "groups":L.groups&&(K=L.groups.reduce((H,N)=>{H.some(Q=>Q.code==N.code)||H.push({code:N.code,name:N.name});return H},K),m++,m<B.value.length?u(m,K,y):y(K));break;case "organizations":L.organizations&&(K=L.organizations.reduce((H,N)=>{H.some(Q=>Q.code==N.code)||H.push({code:N.code,name:N.name});return H},K),m++,m<B.value.length?
u(m,K,y):y(K))}}).catch(L=>{bst.alert(bst.error.parse(L));D()})};a.userOverwrite.value.includes("overwrite")||bst.field.isEmpty(q[B.field.code].value)||x();switch(B.item){case "groups":case "organizations":0!=B.value.length?u(0,[],m=>{q[B.field.code].value=m;x()}):(q[B.field.code].value=B.value,x());break;default:q[B.field.code].value=B.value,x()}})(c[n],()=>{n++;n<c.length?A(n,v):v()})};A(0,()=>{t++;t<f.length?e(t,f[t]):(k.latest.action[a.sIndex.value].user=h(),d())})},h=()=>(t=>JSON.stringify(f.map(q=>
bst.record.simplify({fields:t},q))))(c.reduce((t,q)=>{t[q.field.code]=q.field;return t},(t=>{var q={};q[t]=b.fieldInfos.parallelize[t];return q})(a.userSource.value)));a.userCustomItem.value.some(t=>!(t.value.field.value in b.fieldInfos.parallelize))?(bst.alert("No field to user informations was found"),D()):a.userMapping.value.some(t=>!(t.value.field.value in b.fieldInfos.parallelize))?(bst.alert("No field to user informations was found"),D()):(a.userCustomItem.value.each((t,q)=>{c.push({isCustom:!0,
item:t.value.item.value,field:b.fieldInfos.parallelize[t.value.field.value],value:[]})}),a.userMapping.value.each((t,q)=>{c.push({isCustom:!1,item:t.value.item.value,field:b.fieldInfos.parallelize[t.value.field.value],value:[]})}),a.userPrimaryOrganization.value&&a.userPrimaryOrganization.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"primaryOrganization",field:b.fieldInfos.parallelize[a.userPrimaryOrganization.value],value:[]}),a.userOrganization.value&&a.userOrganization.value in b.fieldInfos.parallelize&&
c.push({isCustom:!1,item:"organizations",field:b.fieldInfos.parallelize[a.userOrganization.value],value:[]}),a.userGroup.value&&a.userGroup.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"groups",field:b.fieldInfos.parallelize[a.userGroup.value],value:[]}),f=(t=>t?l[t].value:[{value:g}])(b.fieldInfos.parallelize[a.userSource.value].tableCode).map(t=>t.value),0!=f.length?k.latest.action[a.sIndex.value].user&&k.latest.action[a.sIndex.value].user==h()?d():0!=c.length?e(0,f.first()):d():
d())}else d()}catch(t){bst.alert(bst.error.parse(t)),D()}}};J.clear(()=>{J.fill(()=>{J.formula(()=>{J.lookup(()=>{J.user(()=>{r()})})})})})}else r()}).catch(w=>{bst.alert(bst.error.parse(w));D()}):r()})((a=>{k.latest?k.latest.action||(k.latest.action={}):k.latest={action:{}};a.sIndex.value in k.latest.action||(k.latest.action[a.sIndex.value]={lookup:"[]",user:"[]"});return a})(C[E]))};I(0,()=>{G({record:g,performed:M!=JSON.stringify(bst.record.simplify({fields:b.fieldInfos.origin},g))})})});bst.field.load(bst.injector.app.id).then(C=>
{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;b.picker=new BooooooostRecordPicker("record");try{(g=>{if(0!=g.length){var k=(()=>{var G=g;"change"==p.pattern&&(G=g.filter(D=>(M=>"fields"in p?!M.first()||p.fields.some(I=>M.includes(I)):!M.first()||M.includes(p.field))(D.triggers.value.map(M=>M.value.field.value))));return G})();0!=k.length?O(k,p.record,p.container).then(G=>{p.stopPropagation&&(b.latest={record:JSON.stringify(bst.record.simplify({fields:C.origin},p.record)),time:(new Date).getTime()});
p.performed=G.performed;z(p)}).catch(()=>z(p)):z(p)}else z(p)})(bst.plugin.action.reduce((g,k)=>{k.event.value.includes(p.pattern)&&g.push(k);return g},[]))}catch(g){bst.alert(bst.error.parse(g)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.cascade.call",p=>new Promise((z,P)=>{if(["create","edit"].includes(p.pattern))if(Array.isArray(bst.plugin.cascade)&&0!=bst.plugin.cascade.length){var b={},O=(C,g,k)=>new Promise((G,D)=>{var M=(I,E)=>{var F=(r,a)=>{var l=Object.keys(b.fieldInfos.parallelize[r.child.value].options);if(Array.isArray(a[r.parent.value].value)?0!=a[r.parent.value].value.length:a[r.parent.value].value)l=(Array.isArray(a[r.parent.value].value)?a[r.parent.value].value:[a[r.parent.value].value]).reduce((w,
J)=>w=[...(new Set([...w,...r.relation.value[J]]))],[]);return l};(r=>{(a=>{a.parent.tableCode?a.parent.tableCode in g&&g[a.parent.tableCode].value.each((l,w)=>{a.parent.code in l.value&&(l.value[a.child.code].options=F(r,l.value))}):a.parent.code in g&&(g[a.child.code].options=F(r,g))})({parent:b.fieldInfos.parallelize[r.parent.value],child:b.fieldInfos.parallelize[r.child.value]});I++;I<C.length?M(I,E):E()})(C[I])};M(0,()=>G())});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,
fields:C.origin};b.fieldInfos=C;try{(g=>{0!=g.length?O(g,p.record,p.container).then(k=>z(p)).catch(()=>z(p)):z(p)})(bst.plugin.cascade.reduce((g,k)=>{k.parent.value in b.fieldInfos.parallelize&&k.child.value in b.fieldInfos.parallelize&&("string"===typeof k.relation.value&&(k.relation.value=JSON.parse(k.relation.value)),g.push(k));return g},[]))}catch(g){bst.alert(bst.error.parse(g)),z(p)}}).catch(C=>z(p))}else z(p);else z(p)}));
bst.event.on("bst.mail.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.mail)&&0!=bst.plugin.mail.length){var b={},O=(C,g,k=!1)=>new Promise((G,D)=>{var M="",I=(E,F)=>{var r=()=>{E++;E<C.length?I(E,F):F()};(a=>{var l=bst.filter.scan(b.app,g,a.condition.value);l?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var J=(d,c,f)=>{"HTML"==a.format.value&&(d=d.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var e in c){var h=c[e].value;e in b.fieldInfos.parallelize&&("HTML"==
a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[e].type&&(h=h.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[e],h," / ",!0)))}for(e in f)h=f[e].value,e in b.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[e].type&&(h=h.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[e],h," / ",!0)));return d};
(d=>{var c=(f,e)=>{(h=>{var t=(q,A)=>{if(0!=h.attachment.length){var n=!1;window.hasOwnProperty("bst_report_temp")&&h.attachment[q].fileKey in window.bst_report_temp&&(n=!0);n?(h.attachment[q].data=window.bst_report_temp[h.attachment[q].fileKey],q++,q<h.attachment.length?t(q,A):A()):bst.file.download(h.attachment[q],!0).then(v=>{bst.field.blobToBase64(v,B=>{h.attachment[q].data=B;q++;q<h.attachment.length?t(q,A):A()})}).catch(v=>{bst.alert(bst.error.parse(v));D()})}else A()};t(0,()=>{bst.encrypt(JSON.stringify(h.data),
M).then(q=>{var A=fetch,n="https://api.booooooost.com/mail/"+bst.operator.language,v=JSON,B=v.stringify;h.data=q.data;h.iv=q.iv;h.tag=q.tag;A(n,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:B.call(v,h)}).then(x=>{x.json().then(u=>{switch(x.status){case 200:f++;f<d.length?c(f,e):e();break;default:bst.alert(bst.error.parse(u)),D()}})}).catch(x=>{bst.alert(bst.error.parse(x));D()})}).catch(q=>{D()})})})(d[f])};0!=d.length?c(0,()=>{try{(a.formula||{value:[]}).value.map(f=>f.value).each((f,
e)=>{f.field.value in b.fieldInfos.parallelize&&(e=b.fieldInfos.parallelize[f.field.value],e.tableCode||(l[e.code].value=bst.formula.calculate(f,l,l,g,b.fieldInfos.parallelize),e.lookup&&(l[e.code].lookup=!0),f=l.$id.value,f in b.formulaRecords||(b.formulaRecords[f]={$id:{value:f}}),b.formulaRecords[f][e.code]=l[e.code]))}),r()}catch(f){bst.alert(bst.error.parse(f)),D()}}):r()})((()=>{var d=[];(b.fieldInfos.parallelize[a.to.value].tableCode?l[b.fieldInfos.parallelize[a.to.value].tableCode].value:
[{value:l}]).each((c,f)=>{if(c.value[a.to.value].value){f=d.push;var e={mail:a.mail.value,sender:a.sender.value,host:a.host.value,port:a.port.value,author:a.author.value,pwd:a.pwd.value,secure:a.secure.value,to:c.value[a.to.value].value,cc:J(a.cc.value,l,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),bcc:J(a.bcc.value,l,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),html:"HTML"==a.format.value},h=J(a.subject.value,l,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),
t=J(a.body.value,l,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),q=[];a.attachment.value&&a.attachment.value in b.fieldInfos.parallelize&&(q=(b.fieldInfos.parallelize[a.attachment.value].tableCode?c.value:l)[a.attachment.value].value);f.call(d,{data:e,subject:h,body:t,attachment:q})}});return d})())}else r()}).catch(w=>{bst.alert(bst.error.parse(w));D()}):r()})(C[E])};fetch("https://api.booooooost.com/mail/"+bst.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(E=>
{E.json().then(F=>{switch(E.status){case 200:M=F.passphrase;k||bst.loadStart();I(0,()=>{k||bst.loadEnd();G()});break;default:bst.alert(bst.error.parse(F)),D()}})}).catch(E=>{bst.alert(bst.error.parse(E));D()})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;b.formulaRecords={};try{var g=k=>{0!=Object.keys(b.formulaRecords).length?bst.record.api.set(b.app.id,{put:Object.values(b.formulaRecords).map(G=>bst.record.api.transform(G))},!0).then(G=>
k()).catch(G=>bst.alert(bst.error.parse(G),()=>z(p))):k()};(k=>{0!=k.length?O(k,p.record,!0).then(G=>g(()=>z(p))).catch(()=>z(p)):z(p)})(bst.plugin.mail.reduce((k,G)=>{G.event.value.includes(p.pattern)&&k.push(G);return k},[]))}catch(k){bst.alert(bst.error.parse(k)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.omail.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.omail)&&0!=bst.plugin.omail.length){var b={},O=(C,g,k=!1)=>new Promise((G,D)=>{var M="",I=(E,F)=>{var r=()=>{E++;E<C.length?I(E,F):F()};(a=>{var l=bst.filter.scan(b.app,g,a.condition.value);l?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var J=(d,c,f)=>{"HTML"==a.format.value&&(d=d.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var e in c){var h=c[e].value;e in b.fieldInfos.parallelize&&
("HTML"==a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[e].type&&(h=h.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[e],h," / ",!0)))}for(e in f)h=f[e].value,e in b.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[e].type&&(h=h.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[e],h," / ",!0)));
return d};(d=>{var c=(f,e)=>{(h=>{var t=(q,A)=>{if(0!=h.attachment.length){var n=!1;window.hasOwnProperty("bst_report_temp")&&h.attachment[q].fileKey in window.bst_report_temp&&(n=!0);n?(h.attachment[q].data=window.bst_report_temp[h.attachment[q].fileKey],q++,q<h.attachment.length?t(q,A):A()):bst.file.download(h.attachment[q],!0).then(v=>{bst.field.blobToBase64(v,B=>{h.attachment[q].data=B;q++;q<h.attachment.length?t(q,A):A()})}).catch(v=>{bst.alert(bst.error.parse(v));D()})}else A()};t(0,()=>{bst.encrypt(JSON.stringify(h.data),
M).then(q=>{var A=fetch,n="https://api.booooooost.com/mail/oauth/"+bst.operator.language,v=JSON,B=v.stringify;h.data=q.data;h.iv=q.iv;h.tag=q.tag;A(n,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:B.call(v,h)}).then(x=>{x.json().then(u=>{switch(x.status){case 200:f++;f<d.length?c(f,e):e();break;default:bst.alert(bst.error.parse(u)),D()}})}).catch(x=>{bst.alert(bst.error.parse(x));D()})}).catch(q=>{D()})})})(d[f])};0!=d.length?c(0,()=>{try{(a.formula||{value:[]}).value.map(f=>f.value).each((f,
e)=>{f.field.value in b.fieldInfos.parallelize&&(e=b.fieldInfos.parallelize[f.field.value],e.tableCode||(l[e.code].value=bst.formula.calculate(f,l,l,g,b.fieldInfos.parallelize),e.lookup&&(l[e.code].lookup=!0),f=l.$id.value,f in b.formulaRecords||(b.formulaRecords[f]={$id:{value:f}}),b.formulaRecords[f][e.code]=l[e.code]))}),r()}catch(f){bst.alert(bst.error.parse(f)),D()}}):r()})((()=>{var d=[];(b.fieldInfos.parallelize[a.to.value].tableCode?l[b.fieldInfos.parallelize[a.to.value].tableCode].value:
[{value:l}]).each((c,f)=>{c.value[a.to.value].value&&d.push({data:{client_id:a.client_id.value,client_secret:a.client_secret.value,author:a.author.value,sender:a.sender.value,subdomain:bst.operator.domain,provider:(e=>{e="";switch(a.provider.value){case "GMail":e="google";break;case "Exchange Online":e="microsoft"}return e})(a.provider.value),to:c.value[a.to.value].value,cc:J(a.cc.value,l,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),bcc:J(a.bcc.value,l,b.fieldInfos.parallelize[a.to.value].tableCode?
c.value:{}),html:"HTML"==a.format.value},subject:J(a.subject.value,l,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),body:J(a.body.value,l,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),attachment:(()=>{var e=[];a.attachment.value&&a.attachment.value in b.fieldInfos.parallelize&&(e=(b.fieldInfos.parallelize[a.attachment.value].tableCode?c.value:l)[a.attachment.value].value);return e})()})});return d})())}else r()}).catch(w=>{bst.alert(bst.error.parse(w));D()}):r()})(C[E])};
fetch("https://api.booooooost.com/mail/oauth/"+bst.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(E=>{E.json().then(F=>{switch(E.status){case 200:M=F.passphrase;k||bst.loadStart();I(0,()=>{k||bst.loadEnd();G()});break;default:bst.alert(bst.error.parse(F)),D()}})}).catch(E=>{bst.alert(bst.error.parse(E));D()})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;b.formulaRecords={};try{var g=k=>{0!=Object.keys(b.formulaRecords).length?
bst.record.api.set(b.app.id,{put:Object.values(b.formulaRecords).map(G=>bst.record.api.transform(G))},!0).then(G=>k()).catch(G=>bst.alert(bst.error.parse(G),()=>z(p))):k()};(k=>{0!=k.length?O(k,p.record,!0).then(G=>g(()=>z(p))).catch(()=>z(p)):z(p)})(bst.plugin.omail.reduce((k,G)=>{G.event.value.includes(p.pattern)&&k.push(G);return k},[]))}catch(k){bst.alert(bst.error.parse(k)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.report.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.report)&&0!=bst.plugin.report.length){var b={},O=(C,g,k=!1)=>new Promise((G,D)=>{var M=(I,E)=>{var F=()=>{I++;I<C.length?M(I,E):E()};(r=>{bst.filter.scan(b.app,g,r.condition.value)?bst.filter.auth(r.user.value,r.organization.value,r.group.value).then(a=>{if(a)if(r.attachment.value in b.fieldInfos.origin){var l=Object.values(b.fieldInfos.tables).reduce((w,J)=>{Object.values(J.fields).each((d,c)=>{w[d.code]={index:-1,
limit:g[J.code].value.length,status:"ready",table:J.code}});return w},{});(w=>{if(0!=w.sheets.length){var J=(c,f,e)=>{(h=>{var t=!1,q=bst.extend({},h),A;for(A in b.fieldInfos.parallelize)(n=>{h.cells.each((v,B)=>{v.each((x,u)=>{if(x.value.match(new RegExp("%"+n.code+"%")))switch(n.type){case "FILE":(m=>{Array.isArray(m)?(K=>{if(K){x.type="image";var y=h.rows.slice(B,B+parseInt(x.rowSpan||"1")).reduce((H,N)=>H+=N.origin,0),L=h.cols.slice(u,u+parseInt(x.colSpan||"1")).reduce((H,N)=>H+=N.origin,0);f.push({cell:x,
fileKey:K.fileKey,size:{height:y,width:L}});t=!0}else x.value=""})(m.find(K=>K.contentType.match(/image/g))):x.value=""})((()=>{var m=null;if(n.code in l){var K=l[n.code];"complete"!=K.status&&(K.index++,K.status=K.index==K.limit-1?"complete":"processing",m=g[K.table].value[K.index].value[n.code].value)}else m=g[n.code].value;return m})());break;default:n.code in l?(m=>{"complete"!=m.status?(m.index++,m.status=m.index==m.limit-1?"complete":"processing",x.value=x.value.replace(new RegExp("%"+n.code+
"%","g"),bst.field.stringify(n,g[m.table].value[m.index].value[n.code].value," / ",!0)),t=!0):x.value=x.value.replace(new RegExp("%"+n.code+"%","g"),"")})(l[n.code]):(x.value=x.value.replace(new RegExp("%"+n.code+"%","g"),bst.field.stringify(n,g[n.code].value," / ",!0)),t=!0)}x.value.match(/^=(TODAY|DATE_FORMAT)/)&&(x.value=eval(x.value.replace(/^=/g,"bst.formula.report.")))})})})(b.fieldInfos.parallelize[A]);h.repeat&&(Object.values(l).some(n=>"processing"==n.status)?w.sheets.splice(c+1,0,q):t||
(w.sheets.splice(c,1),c--));c++;c<w.sheets.length?J(c,f,e):e(f)})(w.sheets[c])},d=(c,f,e)=>{0!=f.length?bst.file.download(f[c],!0).then(h=>{var t=new Image;t.onload=()=>{var q=Math.min(f[c].size.width/t.width,f[c].size.height/t.height),A=Math.round(t.height*q);q=Math.round(t.width*q);var n=bst.create("canvas");n.width=q;n.height=A;n.getContext("2d").drawImage(t,0,0,q,A);f[c].cell.value=n.toDataURL("image/png");c++;c<f.length?d(c,f,e):e()};t.src=URL.createObjectURL(h)}).catch(h=>bst.alert(bst.error.parse(h),
()=>D())):e()};J(0,[],c=>{d(0,c,()=>{(f=>{fetch("https://api.pandafirm.jp/layup/report",{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({lang:bst.operator.language,name:f,datas:w})}).then(e=>{e.json().then(h=>{switch(e.status){case 200:bst.file.upload((t=>{var q=atob(t.binary),A=new Uint8Array(q.length);q.length.each(n=>A[n]=q.charCodeAt(n));return new File([new Blob([A.buffer],{type:t.contentType})],t.filename,{type:t.contentType})})(h.file),!0).then(t=>{window.hasOwnProperty("bst_report_temp")||
(window.bst_report_temp={});window.bst_report_temp[t.fileKey]=h.file.binary;g[r.attachment.value].value.push(t);F()}).catch(t=>{bst.alert(bst.error.parse(t),()=>D())});break;default:bst.alert(bst.error.parse(h),()=>D())}})}).catch(e=>bst.alert(bst.error.parse(e),()=>D()))})((r.name.value in b.fieldInfos.origin?g[r.name.value].value:"")||"report")})})}else F()})(r.template.value?JSON.parse(r.template.value):{sheets:[]})}else F();else F()}).catch(a=>bst.alert(bst.error.parse(a),()=>D())):F()})(C[I])};
k||bst.loadStart();M(0,()=>{bst.record.api.set(b.app.id,{put:[bst.record.api.transform(C.reduce((I,E)=>{E.attachment.value in b.fieldInfos.origin&&(I[E.attachment.value]=g[E.attachment.value]);return I},{$id:g.$id}))]},!0).then(I=>{k||bst.loadEnd();G()}).catch(I=>bst.alert(bst.error.parse(I),()=>D()))})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;try{(g=>{0!=g.length?O(g,p.record,!0).then(k=>z(p)).catch(()=>z(p)):z(p)})(bst.plugin.report.reduce((g,
k)=>{k.event.value.includes(p.pattern)&&g.push(k);return g},[]))}catch(g){bst.alert(bst.error.parse(g)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.style.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.style)&&0!=bst.plugin.style.length){var b={},O=(C,g,k)=>new Promise((G,D)=>{var M={},I=(E,F)=>{(r=>{var a=bst.filter.scan(b.app,g,r.condition.value);a?bst.filter.auth(r.user.value,r.organization.value,r.group.value).then(l=>{l&&(r.color.value.map(w=>w.value).each((w,J)=>{w.field.value in b.fieldInfos.parallelize&&(d=>{d.tableCode?d.tableCode in a&&a[d.tableCode].value.each((c,f)=>{d.code in c.value&&(c.value[d.code].backcolor=
w.backcolor.value,c.value[d.code].forecolor=w.forecolor.value)}):d.code in a&&(a[d.code].backcolor=w.backcolor.value,a[d.code].forecolor=w.forecolor.value)})(b.fieldInfos.parallelize[w.field.value])}),r.editable.value.map(w=>w.value).each((w,J)=>{w.field.value in b.fieldInfos.parallelize&&(d=>{b.fieldInfos.disables.includes(d.code)||(d.tableCode?d.tableCode in a&&(a[d.tableCode].value.each((c,f)=>{d.code in c.value&&(c.value[d.code].disabled="disable"==w.state.value)}),M[d.code]=g[d.tableCode].value.map(c=>
c.value[d.code].disabled?"disabled":"")):d.code in a&&(a[d.code].disabled="disable"==w.state.value,M[d.code]=g[d.code].disabled?"disabled":""))})(b.fieldInfos.parallelize[w.field.value])}),r.display.value.map(w=>w.value).each((w,J)=>{w.field.value in b.fieldInfos.groups?b.fieldInfos.groups[w.field.value].fields.map(d=>d.code).each((d,c)=>{d in b.fieldInfos.parallelize&&d in a&&(a[d].hidden="hide"==w.state.value)}):w.field.value in b.fieldInfos.tables?w.field.value in a&&(a[w.field.value].hidden="hide"==
w.state.value):(d=>{d.tableCode?d.tableCode in a&&a[d.tableCode].value.each((c,f)=>{d.code in c.value&&(c.value[d.code].hidden="hide"==w.state.value)}):d.code in a&&(a[d.code].hidden="hide"==w.state.value)})(b.fieldInfos.parallelize[w.field.value])}));E++;E<C.length?I(E,F):F()}).catch(l=>{bst.alert(bst.error.parse(l));D()}):(E++,E<C.length?I(E,F):F())})(C[E])};I(0,()=>{k.latest?k.latest.style||(k.latest.style="{}"):k.latest={style:"{}"};var E=JSON.stringify(M),F="{}"!=E?k.latest.style!=E:!1;F&&(k.latest.style=
E);G({performed:F})})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;try{(g=>{0!=g.length?O(g,p.record,p.container).then(k=>{p.performed=k.performed;z(p)}).catch(()=>z(p)):z(p)})(bst.plugin.style.reduce((g,k)=>{k.page.value.includes(p.pattern)&&g.push(k);return g},[]))}catch(g){bst.alert(bst.error.parse(g)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.submit.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.submit)&&0!=bst.plugin.submit.length){var b={},O=(C,g,k=!1,G={})=>new Promise((D,M)=>{var I=[],E=(F,r)=>{var a=()=>{F++;F<C.length?E(F,r):r()};(l=>{bst.filter.scan(b.app,g,l.condition.value)?bst.filter.auth(l.user.value,l.organization.value,l.group.value).then(w=>{if(w){var J={duplicate:d=>{try{l.duplicateCriteria.value.some(c=>!(c.value.external.value in b.fieldInfos.parallelize&&c.value.internal.value in b.fieldInfos.parallelize))?
(bst.alert("No field to lookup was found"),M()):(c=>{c&&I.push(c);d()})(l.duplicateCriteria.value.reduce((c,f)=>{c.push(bst.filter.query.create(b.fieldInfos.parallelize[f.value.external.value],f.value.operator.value,g[b.fieldInfos.parallelize[f.value.internal.value].code]));return c},[]).join(" and "))}catch(c){bst.alert(bst.error.parse(c)),M()}},error:d=>{try{if(l.errorMessage.value||0!=l.errorField.value.length){var c=bst.filter.scan(b.app,g,l.errorFilter.value);c?(l.errorField.value.each((f,e)=>
{f.value.field.value in b.fieldInfos.parallelize&&(h=>{h.tableCode?c[h.tableCode].value.each((t,q)=>{t.value[f.value.field.value].error=f.value.message.value}):g[f.value.field.value].error=f.value.message.value})(b.fieldInfos.parallelize[f.value.field.value])}),k||bst.loadEnd(),D({error:!0,message:l.errorMessage.value})):d()}else d()}catch(f){bst.alert(bst.error.parse(f)),M()}},numbering:d=>{try{if(l.numberingField.value in b.fieldInfos.parallelize)if(g[l.numberingField.value].value)d();else{var c=
"",f=l.numberingGroup.value.reduce((e,h)=>{if(h.value.field.value in b.fieldInfos.parallelize)switch(c+=g[h.value.field.value].value,b.fieldInfos.parallelize[h.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":e.push(h.value.field.value+' in ("'+g[h.value.field.value].value+'")');break;default:e.push(h.value.field.value+'="'+g[h.value.field.value].value+'"')}return e},"$id"in g?['$id!="'+g.$id.value+'"']:[]);c in G?(G[c]++,g[l.numberingField.value].value=c+G[c].toString().lpad("0",parseInt(l.numberingDigits.value)),
d()):bst.api(bst.api.url("/api/records"),"GET",{app:b.app.id,query:f.join(" and ")+" order by "+l.numberingField.value+" desc limit 1 offset 0"}).then(e=>{e=e.records;var h=0;0!=e.length&&(h=parseInt((e.first()[l.numberingField.value].value||" ").replace(/[ ]+/g,"").replace(new RegExp("^"+c,"g"),"")),bst.isNumeric(h)||(h=0));h++;e=h;G[c]=e;g[l.numberingField.value].value=c+e.toString().lpad("0",parseInt(l.numberingDigits.value));d()}).catch(e=>{bst.alert(bst.error.parse(e));M()})}else d()}catch(e){bst.alert(bst.error.parse(e)),
M()}},prompt:d=>{try{(c=>{0!=c.length?(f=>{c.each((e,h)=>{f.append(bst.field.activate(bst.field.create(e).css({width:"100%"}),b.app,!1))});k||bst.loadEnd();(new BooooooostPopupform(f,600,"full",{ok:()=>{var e=bst.record.get(f,b.app,!0);c.each((h,t)=>{g[h.code].value=e.record[h.code].value});k||bst.loadStart();d()},cancel:()=>{k||bst.loadStart();d()}})).show()})(bst.create("div").addClass("bst-scope").attr("form-id","form_"+b.app.id)):d()})(l.promptField.value.reduce((c,f)=>{f.value.field.value in
b.fieldInfos.parallelize&&(l.promptOverwrite.value.includes("overwrite")?c.push(b.fieldInfos.parallelize[f.value.field.value]):bst.field.isEmpty(g[f.value.field.value].value)&&c.push(b.fieldInfos.parallelize[f.value.field.value]));return c},[]))}catch(c){bst.alert(bst.error.parse(c)),M()}},verify:d=>{try{(c=>{0!=c.length?(f=>{c.each((e,h)=>{f.append(bst.field.activate(bst.field.create(e).addClass("bst-readonly").css({width:"100%"}),b.app,!1))});bst.record.set(f,b.app,g);k||bst.loadEnd();(new BooooooostPopupform(f,
600,"full",{ok:()=>{k||bst.loadStart();d()},cancel:()=>{k||bst.loadEnd();D({error:!0})}})).show()})(bst.create("div").addClass("bst-scope bst-verify").attr("form-id","form_"+b.app.id).append(bst.create("p").html(l.verifyMessage.value))):d()})(l.verifyField.value.reduce((c,f)=>{f.value.field.value in b.fieldInfos.parallelize&&c.push(b.fieldInfos.parallelize[f.value.field.value]);return c},[]))}catch(c){bst.alert(bst.error.parse(c)),M()}}};J.numbering(()=>{J.prompt(()=>{J.verify(()=>{J.error(()=>{J.duplicate(()=>
{a()})})})})})}else a()}).catch(w=>{bst.alert(bst.error.parse(w));M()}):a()})(C[F])};k||bst.loadStart();E(0,()=>{k||bst.loadEnd();0!=I.length?bst.api(bst.api.url("/api/records"),"GET",{app:b.app.id,query:((F,r)=>(r?"$id!="+r+" and ("+F+")":F)+" order by $id asc limit 5 offset 0")(I.map(F=>"("+F+")").join(" or "),"$id"in g?g.$id.value:"")}).then(F=>{0!=F.records.length?bst.confirm(bst.create("div").append(bst.create("p").css({margin:"0"}).html(bst.constants.submit.message.duplicate[bst.operator.language])),
r=>{D({error:r})},!0):D({error:!1})}).catch(F=>{bst.alert(bst.error.parse(F),()=>{D({error:!1})})}):D({error:!1})})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;try{(g=>{0!=g.length?O(g,p.record,!0,p.numbering).then(k=>{k.error?(p.error=!0,k.message?bst.alert(k.message,()=>z(p)):z(p)):z(p)}).catch(()=>{p.error=!0;z(p)}):z(p)})(bst.plugin.submit.reduce((g,k)=>{k.event.value.includes(p.pattern)&&g.push(k);return g},[]))}catch(g){bst.alert(bst.error.parse(g)),
z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.upsert.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.upsert)&&0!=bst.plugin.upsert.length){var b={},O=(C,g,k=!1)=>new Promise((G,D)=>{var M=(I,E)=>{var F=(r,a)=>{I++;r&&(a.formulaSource||{value:[]}).value.map(l=>l.value).each((l,w)=>{l.field.value in b.fieldInfos.parallelize&&(w=b.fieldInfos.parallelize[l.field.value],w.tableCode||(r[w.code].value=bst.formula.calculate(l,r,r,g,b.fieldInfos.parallelize),w.lookup&&(r[w.code].lookup=!0),l=r.$id.value,l in b.formulaRecords||
(b.formulaRecords[l]={$id:{value:l}}),b.formulaRecords[l][w.code]=r[w.code]))});I<C.length?M(I,E):E()};(r=>{var a=bst.filter.scan(b.app,g,r.condition.value);a?bst.filter.auth(r.user.value,r.organization.value,r.group.value).then(l=>{l?bst.field.load(r.app.value).then(w=>{var J={id:r.app.value,fields:w.origin};(d=>{var c=[],f=[],e=[],h={},t={table:"",index:n=>t.table&&t.table==n.tableCode?q.progress.record:q.progress.row},q={record:1,row:1,progress:{record:0,row:0}},A=()=>{var n=[],v={field:(u,m)=>
{m=u.tableCode?a[u.tableCode].value.length>m?a[u.tableCode].value[m].value[u.code]:bst.record.create({fields:{empty:u}}).empty:a[u.code];return bst.extend({type:u.type},m)},record:u=>{q.row.each(m=>{var K=(y=>{var L=bst.filter.scan(J,u,y.query);if(!L&&"upsert"==r.pattern.value){for(var H in y.rows)0==bst.filter.result[H].value.length&&(u[H].value.push({value:bst.extend({},y.rows[H])}),bst.filter.result[H]={value:[u[H].value.last()]});L=bst.filter.result}return L})((()=>{var y={rows:{},query:[]};q.progress.row=
m;c.each((L,H)=>{L.external.tableCode&&(L.external.tableCode in y.rows||(y.rows[L.external.tableCode]=bst.record.create(J.fields[L.external.tableCode],!1)),H=v.field(L.internal,t.index(L.internal)),["=","in"].includes(L.operator.trim())&&(y.rows[L.external.tableCode][L.external.code]=B(L.external,H)),y.query.push(bst.filter.query.create(L.external,L.operator,H)))});f.each((L,H)=>{L.field.tableCode&&y.query.push(L.field.code+" "+L.operator+" "+L.value)});y.query=y.query.join(" and ");return y})());
K&&e.each((y,L)=>{y.external.tableCode?y.external.tableCode in h?(u[y.external.tableCode]={value:h[y.external.tableCode]},h[y.external.tableCode].each((H,N)=>{H.value[y.external.code]=B(y.external,v.field(y.internal,N));"FILE"==y.external.type&&H.value[y.external.code].value&&Array.prototype.push.apply(n,H.value[y.external.code].value)})):K[y.external.tableCode].value.each((H,N)=>{H.value[y.external.code]=B(y.external,v.field(y.internal,t.index(y.internal)));"FILE"==y.external.type&&H.value[y.external.code].value&&
Array.prototype.push.apply(n,H.value[y.external.code].value)}):(u[y.external.code]=B(y.external,v.field(y.internal,q.progress.record)),"FILE"==y.external.type&&u[y.external.code].value&&Array.prototype.push.apply(n,u[y.external.code].value))})});return u}},B=(u,m)=>{switch(u.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":Array.isArray(m.value)||(m.value=[m.value])}m.type=u.type;return u.lookup?bst.extend({lookup:!0},m):m},x=
u=>{u.each((m,K)=>{(r.formulaDestination||r.formula||{value:[]}).value.map(y=>y.value).each((y,L)=>{y.field.value in d.external&&(H=>{H.tableCode?m[H.tableCode].value.each((N,Q)=>{N.value[H.code].value=bst.formula.calculate(y,N.value,m,m,d.external);H.lookup&&(N.value[H.code].lookup=!0)}):(m[H.code].value=bst.formula.calculate(y,m,m,m,d.external),H.lookup&&(m[H.code].lookup=!0))})(d.external[y.field.value])})});return u};"insert"==r.pattern.value?(u=>{bst.file.clone(n,!0).then(()=>{bst.record.api.set(r.app.value,
{post:u},k).then(m=>{q.progress.record++;q.progress.record<q.record?A():F(a,r)}).catch(m=>{bst.alert(bst.error.parse(m));D()})})})(x([v.record(bst.record.create(J))])):bst.record.api.get(r.app.value,(()=>{var u=[];c.each((m,K)=>{m.external.tableCode||u.push(bst.filter.query.create(m.external,m.operator,v.field(m.internal,q.progress.record)))});f.each((m,K)=>{m.field.tableCode||u.push(m.field.code+" "+m.operator+" "+m.value)});return u.join(" and ")})()).then(u=>{u=(m=>{var K=[];0!=m.length?K=m.map(y=>
v.record(y)):"upsert"==r.pattern.value&&(y=>{K.push(v.record((()=>{var L=bst.record.create(J);y.each((H,N)=>{H.external.tableCode?L[H.external.tableCode]={value:[]}:["=","in"].includes(H.operator.trim())&&(L[H.external.code]=B(H.external,v.field(H.internal,q.progress.record)))});return L})()))})(c.filter(y=>!bst.field.reserved.includes(y.external.type)));return x(K)})(u);bst.file.clone(n,!0).then(()=>{bst.record.api.set(r.app.value,{post:u.filter(m=>!m.$id.value),put:u.reduce((m,K)=>{K.$id.value&&
m.push(bst.record.api.transform(K));return m},[])},k).then(m=>{q.progress.record++;q.progress.record<q.record?A():F(a,r)}).catch(m=>{bst.alert(bst.error.parse(m));D()})})}).catch(u=>{bst.alert(bst.error.parse(u));D()})};r.mapping.value.some(n=>!(n.value.external.value in d.external&&n.value.internal.value in d.internal))?(bst.alert("No field to transfer was found"),D()):r.criteria.value.some(n=>!(n.value.external.value in d.external&&n.value.internal.value in d.internal))?(bst.alert("No field to transfer was found"),
D()):([...r.mapping.value,...r.criteria.value].each((n,v)=>{v=d.internal[n.value.internal.value];!d.external[n.value.external.value].tableCode&&v.tableCode&&(t.table=v.tableCode,q.record=0==a[v.tableCode].value.length?0:a[v.tableCode].value.length)}),r.mapping.value.each((n,v)=>{((B,x)=>{B.tableCode&&(t.table&&t.table==x.tableCode||(h[B.tableCode]=(u=>{u=u?u.length:1;x.tableCode&&(u=u<a[x.tableCode].value.length?a[x.tableCode].value.length:u);return Array(u).fill().map(()=>({value:bst.record.create(J.fields[B.tableCode],
!1)}))})(h[B.tableCode])));e.push({external:B,internal:x})})(d.external[n.value.external.value],d.internal[n.value.internal.value])}),r.criteria.value.each((n,v)=>{v=d.external[n.value.external.value];var B=n.value.operator.value;n=d.internal[n.value.internal.value];v.tableCode&&(v.tableCode in h&&delete h[v.tableCode],!t.table&&n.tableCode&&(q.row=q.row<a[n.tableCode].value.length?a[n.tableCode].value.length:q.row));c.push({external:v,operator:B,internal:n})}),bst.filter.query.parse.expand({id:r.app.value,
fields:w.origin},r.filter.value).each((n,v)=>{f.push({field:d.external[n.field],operator:n.operator,value:n.value})}),0!=q.record?(q.progress.record=0,q.progress.row=0,A()):F())})({external:w.parallelize,internal:b.fieldInfos.parallelize})}).catch(w=>{bst.alert(bst.error.parse(w));D()}):F()}).catch(l=>{bst.alert(bst.error.parse(l));D()}):F()})(C[I])};k||bst.loadStart();M(0,()=>{k||bst.loadEnd();G()})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=
C;b.formulaRecords={};try{var g=k=>{0!=Object.keys(b.formulaRecords).length?bst.record.api.set(b.app.id,{put:Object.values(b.formulaRecords).map(G=>bst.record.api.transform(G))},!0).then(G=>k()).catch(G=>bst.alert(bst.error.parse(G),()=>z(p))):k()};(k=>{0!=k.length?O(k,p.record,!0).then(G=>g(()=>z(p))).catch(()=>z(p)):z(p)})(bst.plugin.upsert.reduce((k,G)=>{G.event.value.includes(p.pattern)&&k.push(G);return k},[]))}catch(k){bst.alert(bst.error.parse(k)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.constants=bst.extend({submit:{message:{cancel:{process:{en:"The process action was canceled.",ja:"\u30d7\u30ed\u30bb\u30b9\u30a2\u30af\u30b7\u30e7\u30f3\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u8fdb\u7a0b\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002","zh-TW":"\u7a0b\u5e8f\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002"},submit:{en:"The submit was canceled.",ja:"\u4fdd\u5b58\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u4fdd\u5b58\u5df2\u88ab\u53d6\u6d88\u3002",
"zh-TW":"\u63d0\u4ea4\u5df2\u88ab\u53d6\u6d88\u3002"}},duplicate:{en:"A similar record already exists. Would you like to proceed with the registration anyway?",ja:"\u985e\u4f3c\u30ec\u30b3\u30fc\u30c9\u304c\u65e2\u306b\u767b\u9332\u3055\u308c\u3066\u3044\u307e\u3059\u304c\u3001\u3053\u306e\u307e\u307e\u767b\u9332\u3057\u3066\u3082\u5b9c\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u7ecf\u6709\u7c7b\u4f3c\u7684\u8bb0\u5f55\u5b58\u5728\u4e86\uff0c\u60a8\u8fd8\u8981\u7ee7\u7eed\u6ce8\u518c\u5417\uff1f",
"zh-TW":"\u5df2\u6709\u985e\u4f3c\u7684\u8a18\u9304\u5b58\u5728\uff0c\u60a8\u9084\u8981\u7e7c\u7e8c\u8a3b\u518a\u55ce\uff1f"}}}},bst.constants);
