/*
* FileName "plugin.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';bst.event.on("bst.action.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.action)&&0!=bst.plugin.action.length){var b={},O=(C,h,l)=>new Promise((H,D)=>{var M=JSON.stringify(bst.record.simplify({fields:b.fieldInfos.origin},h)),K=(F,G)=>{var q=()=>{F++;F<C.length?K(F,G):G()};(a=>{var m=bst.filter.scan(b.app,h,a.condition.value);m?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var L={clear:d=>{try{a.clear.value.map(c=>c.value).each((c,f)=>{c.table.value in b.fieldInfos.tables&&
(h[c.table.value].value=h[c.table.value].value.filter(e=>!m[c.table.value].value.includes(e)),m[c.table.value].value=[])}),d()}catch(c){bst.alert(bst.error.parse(c)),D()}},fill:d=>{try{a.fill.value.map(c=>c.value).each((c,f)=>{c.table.value in b.fieldInfos.tables&&(e=>{e=bst.isNumeric(e)?parseInt(e)-m[c.table.value].value.length:0;0<e&&Array(e).fill().map(()=>bst.record.create(b.fieldInfos.origin[c.table.value],!1)).each((k,u)=>{h[c.table.value]==m[c.table.value]?h[c.table.value].value.push({value:k}):
(h[c.table.value].value.push({value:k}),m[c.table.value].value.push({value:k}))})})(bst.formula.calculate({field:{value:Object.values(b.fieldInfos.parallelize).first().code},formula:c.range},m,m,h,b.fieldInfos.parallelize))}),d()}catch(c){bst.alert(bst.error.parse(c)),D()}},formula:d=>{try{a.formula.value.map(c=>c.value).each((c,f)=>{c.field.value in b.fieldInfos.parallelize&&(e=>{e.tableCode?m[e.tableCode].value.each((k,u)=>{k.value[e.code].value=bst.formula.calculate(c,k.value,m,h,b.fieldInfos.parallelize);
e.lookup&&(k.value[e.code].lookup=!0)}):(m[e.code].value=bst.formula.calculate(c,m,m,h,b.fieldInfos.parallelize),e.lookup&&(m[e.code].lookup=!0))})(b.fieldInfos.parallelize[c.field.value])}),d()}catch(c){bst.alert(bst.error.parse(c)),D()}},lookup:d=>{try{a.lookupApp.value?bst.field.load(a.lookupApp.value).then(c=>{(f=>{var e=[],k=[],u=(A,n)=>{var v=(B,x)=>B.lookup?bst.extend({lookup:!0,type:B.type},x):bst.extend({type:B.type},x);bst.record.api.get(a.lookupApp.value,n.query,n.sort).then(B=>{0!=B.length?
(x=>{a.lookupLimited.value.includes("limited")||1==B.length?x(B.first()):b.picker.show({app:a.lookupApp.value,query:n.query,sort:n.sort,picker:e.reduce((t,g)=>{t[g.external.code]=g.external;return t},{})},t=>x(t))})(x=>{e.each((t,g)=>{if(a.lookupOverwrite.value.includes("overwrite")||bst.field.isEmpty(n.record[t.internal.code].value))n.record[t.internal.code]=v(t.internal,x[t.external.code])});A++;A<k.length?u(A,k[A]):(l.latest.action[a.sIndex.value].lookup=r(),d())}):(a.lookupReset.value.includes("reset")&&
e.each((x,t)=>{n.record[x.internal.code]=v(x.internal,bst.record.create({fields:{empty:x.internal}}).empty)}),A++,A<k.length?u(A,k[A]):(l.latest.action[a.sIndex.value].lookup=r(),d()))}).catch(B=>{bst.alert(bst.error.parse(B));D()})},r=()=>(A=>JSON.stringify(k.reduce((n,v)=>{n.push(v.query);n.push(bst.record.simplify({fields:A},v.record));return n},[])))(e.reduce((A,n)=>{A[n.internal.code]=n.internal;return A},{}));a.lookupCriteria.value.some(A=>!(A.value.external.value in f.external&&A.value.internal.value in
f.internal))?(bst.alert("No field to lookup was found"),D()):a.lookupMapping.value.some(A=>!(A.value.external.value in f.external&&A.value.internal.value in f.internal))?(bst.alert("No field to lookup was found"),D()):(e=a.lookupMapping.value.map(A=>({external:f.external[A.value.external.value],internal:f.internal[A.value.internal.value]})),k=(A=>A.map(n=>({query:a.lookupCriteria.value.reduce((v,B)=>{var x=f.external[B.value.external.value],t=B.value.operator.value;B=f.internal[B.value.internal.value];
var g=B.tableCode?n.value:h;a.lookupIgnore.value.includes("ignore")&&bst.field.isEmpty(g[B.code].value)||v.push(bst.filter.query.create(x,t,g[B.code]));return v},bst.filter.query.parse.expand({id:a.lookupApp.value,fields:c.origin},a.lookupFilter.value).map(v=>v.field+" "+v.operator+" "+v.value)).join(" and "),sort:(0!=a.lookupSort.value.length?a.lookupSort.value.map(v=>v.value.field.value+" "+v.value.order.value):["$id asc"]).join(","),record:n.value})))((A=>A?m[A].value:[{value:h}])(Array.from(new Set(e.map(A=>
A.internal.tableCode))).first())),0!=k.length?l.latest.action[a.sIndex.value].lookup&&l.latest.action[a.sIndex.value].lookup==r()?d():u(0,k.first()):d())})({external:c.origin,internal:b.fieldInfos.parallelize})}).catch(c=>{bst.alert(bst.error.parse(c));D()}):d()}catch(c){bst.alert(bst.error.parse(c)),D()}},user:d=>{try{if(a.userSource.value){var c=[],f=[],e=(u,r)=>{(n=>{c.each((v,B)=>{if(v.isCustom)switch(v.field.type){case "USER_SELECT":v.value=n.reduce((x,t)=>{"customItemValues"in t&&(g=>{0!=g.length&&
(E=>{(y=>{0!=y.length&&(x.some(J=>J.code==y.first().info.code)||x.push({code:y.first().info.code,name:y.first().info.name}))})(bst.roleSet.user.filter(y=>y.info.id==E))})(g.first().value)})(t.customItemValues.filter(g=>g.code==v.item));return Array.from(new Set(x)).filter(g=>g)},[]);break;default:v.value=n.reduce((x,t)=>{"customItemValues"in t&&(g=>{0!=g.length&&x.push(g.first().value)})(t.customItemValues.filter(g=>g.code==v.item));return Array.from(new Set(x)).filter(g=>g)},[]).join(",")}else switch(v.item){case "groups":case "organizations":v.value=
n.map(x=>x.code);break;case "primaryOrganization":v.value=n.reduce((x,t)=>{v.item in t&&(g=>{0!=g.length&&(x.some(E=>E.code==g.first().info.code)||x.push({code:g.first().info.code,name:g.first().info.name}))})(bst.roleSet.organization.filter(g=>g.info.id==t[v.item]));return x},[]);break;default:v.value=n.reduce((x,t)=>{v.item in t&&x.push(t[v.item]);return Array.from(new Set(x)).filter(g=>g)},[]).join(",")}})})(r[a.userSource.value].value.reduce((n,v)=>{(B=>{0!=B.length&&n.push(B.first().info)})(bst.roleSet.user.filter(B=>
B.info.code==v.code));return n},[]));var A=(n,v)=>{((B,x)=>{var t=(g,E,y)=>{bst.api(bst.api.url("/api/user/affiliations"),"GET",{code:B.value[g]}).then(J=>{switch(B.item){case "groups":J.groups&&(E=J.groups.reduce((I,N)=>{I.some(Q=>Q.code==N.code)||I.push({code:N.code,name:N.name});return I},E),g++,g<B.value.length?t(g,E,y):y(E));break;case "organizations":J.organizations&&(E=J.organizations.reduce((I,N)=>{I.some(Q=>Q.code==N.code)||I.push({code:N.code,name:N.name});return I},E),g++,g<B.value.length?
t(g,E,y):y(E))}}).catch(J=>{bst.alert(bst.error.parse(J));D()})};a.userOverwrite.value.includes("overwrite")||bst.field.isEmpty(r[B.field.code].value)||x();switch(B.item){case "groups":case "organizations":0!=B.value.length?t(0,[],g=>{r[B.field.code].value=g;x()}):(r[B.field.code].value=B.value,x());break;default:r[B.field.code].value=B.value,x()}})(c[n],()=>{n++;n<c.length?A(n,v):v()})};A(0,()=>{u++;u<f.length?e(u,f[u]):(l.latest.action[a.sIndex.value].user=k(),d())})},k=()=>(u=>JSON.stringify(f.map(r=>
bst.record.simplify({fields:u},r))))(c.reduce((u,r)=>{u[r.field.code]=r.field;return u},(u=>{var r={};r[u]=b.fieldInfos.parallelize[u];return r})(a.userSource.value)));a.userCustomItem.value.some(u=>!(u.value.field.value in b.fieldInfos.parallelize))?(bst.alert("No field to user informations was found"),D()):a.userMapping.value.some(u=>!(u.value.field.value in b.fieldInfos.parallelize))?(bst.alert("No field to user informations was found"),D()):(a.userCustomItem.value.each((u,r)=>{c.push({isCustom:!0,
item:u.value.item.value,field:b.fieldInfos.parallelize[u.value.field.value],value:[]})}),a.userMapping.value.each((u,r)=>{c.push({isCustom:!1,item:u.value.item.value,field:b.fieldInfos.parallelize[u.value.field.value],value:[]})}),a.userPrimaryOrganization.value&&a.userPrimaryOrganization.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"primaryOrganization",field:b.fieldInfos.parallelize[a.userPrimaryOrganization.value],value:[]}),a.userOrganization.value&&a.userOrganization.value in b.fieldInfos.parallelize&&
c.push({isCustom:!1,item:"organizations",field:b.fieldInfos.parallelize[a.userOrganization.value],value:[]}),a.userGroup.value&&a.userGroup.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"groups",field:b.fieldInfos.parallelize[a.userGroup.value],value:[]}),f=(u=>u?m[u].value:[{value:h}])(b.fieldInfos.parallelize[a.userSource.value].tableCode).map(u=>u.value),0!=f.length?l.latest.action[a.sIndex.value].user&&l.latest.action[a.sIndex.value].user==k()?d():0!=c.length?e(0,f.first()):d():
d())}else d()}catch(u){bst.alert(bst.error.parse(u)),D()}}};L.clear(()=>{L.fill(()=>{L.formula(()=>{L.lookup(()=>{L.user(()=>{q()})})})})})}else q()}).catch(w=>{bst.alert(bst.error.parse(w));D()}):q()})((a=>{l.latest?l.latest.action||(l.latest.action={}):l.latest={action:{}};a.sIndex.value in l.latest.action||(l.latest.action[a.sIndex.value]={lookup:"[]",user:"[]"});return a})(C[F]))};K(0,()=>{H({record:h,performed:M!=JSON.stringify(bst.record.simplify({fields:b.fieldInfos.origin},h))})})});bst.field.load(bst.injector.app.id).then(C=>
{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;b.picker=new BooooooostRecordPicker("record");try{(h=>{if(0!=h.length){var l=(()=>{var H=h;"change"==p.pattern&&(H=h.filter(D=>(M=>"fields"in p?!M.first()||p.fields.some(K=>M.includes(K)):!M.first()||M.includes(p.field))(D.triggers.value.map(M=>M.value.field.value))));return H})();0!=l.length?O(l,p.record,p.container).then(H=>{p.stopPropagation&&(b.latest={record:JSON.stringify(bst.record.simplify({fields:C.origin},p.record)),time:(new Date).getTime()});
p.performed=H.performed;z(p)}).catch(()=>z(p)):z(p)}else z(p)})(bst.plugin.action.reduce((h,l)=>{l.event.value.includes(p.pattern)&&h.push(l);return h},[]))}catch(h){bst.alert(bst.error.parse(h)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.cascade.call",p=>new Promise((z,P)=>{if(["create","edit"].includes(p.pattern))if(Array.isArray(bst.plugin.cascade)&&0!=bst.plugin.cascade.length){var b={},O=(C,h,l)=>new Promise((H,D)=>{var M=(K,F)=>{var G=(q,a)=>{var m=Object.keys(b.fieldInfos.parallelize[q.child.value].options);if(Array.isArray(a[q.parent.value].value)?0!=a[q.parent.value].value.length:a[q.parent.value].value)m=(Array.isArray(a[q.parent.value].value)?a[q.parent.value].value:[a[q.parent.value].value]).reduce((w,
L)=>w=[...(new Set([...w,...q.relation.value[L]]))],[]);return m};(q=>{(a=>{a.parent.tableCode?a.parent.tableCode in h&&h[a.parent.tableCode].value.each((m,w)=>{a.parent.code in m.value&&(m.value[a.child.code].options=G(q,m.value))}):a.parent.code in h&&(h[a.child.code].options=G(q,h))})({parent:b.fieldInfos.parallelize[q.parent.value],child:b.fieldInfos.parallelize[q.child.value]});K++;K<C.length?M(K,F):F()})(C[K])};M(0,()=>H())});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,
fields:C.origin};b.fieldInfos=C;try{(h=>{0!=h.length?O(h,p.record,p.container).then(l=>z(p)).catch(()=>z(p)):z(p)})(bst.plugin.cascade.reduce((h,l)=>{l.parent.value in b.fieldInfos.parallelize&&l.child.value in b.fieldInfos.parallelize&&("string"===typeof l.relation.value&&(l.relation.value=JSON.parse(l.relation.value)),h.push(l));return h},[]))}catch(h){bst.alert(bst.error.parse(h)),z(p)}}).catch(C=>z(p))}else z(p);else z(p)}));
bst.event.on("bst.mail.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.mail)&&0!=bst.plugin.mail.length){var b={},O=(C,h,l=!1)=>new Promise((H,D)=>{var M="",K=(F,G)=>{var q=()=>{F++;F<C.length?K(F,G):G()};(a=>{var m=bst.filter.scan(b.app,h,a.condition.value);m?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var L=(d,c,f)=>{"HTML"==a.format.value&&(d=d.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var e in c){var k=c[e].value;e in b.fieldInfos.parallelize&&("HTML"==
a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[e].type&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[e],k," / ",!0)))}for(e in f)k=f[e].value,e in b.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[e].type&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[e],k," / ",!0)));return d};
(d=>{var c=(f,e)=>{(k=>{var u=(r,A)=>{if(0!=k.attachment.length){var n=!1;window.hasOwnProperty("bst_report_temp")&&k.attachment[r].fileKey in window.bst_report_temp&&(n=!0);n?(k.attachment[r].data=window.bst_report_temp[k.attachment[r].fileKey],r++,r<k.attachment.length?u(r,A):A()):bst.file.download(k.attachment[r],!0).then(v=>{bst.field.blobToBase64(v,B=>{k.attachment[r].data=B;r++;r<k.attachment.length?u(r,A):A()})}).catch(v=>{bst.alert(bst.error.parse(v));D()})}else A()};u(0,()=>{bst.encrypt(JSON.stringify(k.data),
M).then(r=>{var A=fetch,n="https://api.booooooost.com/mail/"+bst.operator.language,v=JSON,B=v.stringify;k.data=r.data;k.iv=r.iv;k.tag=r.tag;A(n,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:B.call(v,k)}).then(x=>{x.json().then(t=>{switch(x.status){case 200:f++;f<d.length?c(f,e):e();break;default:bst.alert(bst.error.parse(t)),D()}})}).catch(x=>{bst.alert(bst.error.parse(x));D()})}).catch(r=>{D()})})})(d[f])};0!=d.length?c(0,()=>{try{(a.formula||{value:[]}).value.map(f=>f.value).each((f,
e)=>{f.field.value in b.fieldInfos.parallelize&&(e=b.fieldInfos.parallelize[f.field.value],e.tableCode||(m[e.code].value=bst.formula.calculate(f,m,m,h,b.fieldInfos.parallelize),e.lookup&&(m[e.code].lookup=!0),f=m.$id.value,f in b.formulaRecords||(b.formulaRecords[f]={$id:{value:f}}),b.formulaRecords[f][e.code]=m[e.code]))}),q()}catch(f){bst.alert(bst.error.parse(f)),D()}}):q()})((()=>{var d=[];(b.fieldInfos.parallelize[a.to.value].tableCode?m[b.fieldInfos.parallelize[a.to.value].tableCode].value:
[{value:m}]).each((c,f)=>{if(c.value[a.to.value].value){f=d.push;var e={mail:a.mail.value,sender:a.sender.value,host:a.host.value,port:a.port.value,author:a.author.value,pwd:a.pwd.value,secure:a.secure.value,to:c.value[a.to.value].value,cc:L(a.cc.value,m,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),bcc:L(a.bcc.value,m,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),html:"HTML"==a.format.value},k=L(a.subject.value,m,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),
u=L(a.body.value,m,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),r=[];a.attachment.value&&a.attachment.value in b.fieldInfos.parallelize&&(r=(b.fieldInfos.parallelize[a.attachment.value].tableCode?c.value:m)[a.attachment.value].value);f.call(d,{data:e,subject:k,body:u,attachment:r})}});return d})())}else q()}).catch(w=>{bst.alert(bst.error.parse(w));D()}):q()})(C[F])};fetch("https://api.booooooost.com/mail/"+bst.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(F=>
{F.json().then(G=>{switch(F.status){case 200:M=G.passphrase;l||bst.loadStart();K(0,()=>{l||bst.loadEnd();H()});break;default:bst.alert(bst.error.parse(G)),D()}})}).catch(F=>{bst.alert(bst.error.parse(F));D()})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;b.formulaRecords={};try{var h=l=>{0!=Object.keys(b.formulaRecords).length?bst.record.api.set(b.app.id,{put:Object.values(b.formulaRecords).map(H=>bst.record.api.transform(H))},!0).then(H=>
l()).catch(H=>bst.alert(bst.error.parse(H),()=>z(p))):l()};(l=>{0!=l.length?O(l,p.record,!0).then(H=>h(()=>z(p))).catch(()=>z(p)):z(p)})(bst.plugin.mail.reduce((l,H)=>{H.event.value.includes(p.pattern)&&l.push(H);return l},[]))}catch(l){bst.alert(bst.error.parse(l)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.omail.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.omail)&&0!=bst.plugin.omail.length){var b={},O=(C,h,l=!1)=>new Promise((H,D)=>{var M="",K=(F,G)=>{var q=()=>{F++;F<C.length?K(F,G):G()};(a=>{var m=bst.filter.scan(b.app,h,a.condition.value);m?bst.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var L=(d,c,f)=>{"HTML"==a.format.value&&(d=d.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var e in c){var k=c[e].value;e in b.fieldInfos.parallelize&&
("HTML"==a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[e].type&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[e],k," / ",!0)))}for(e in f)k=f[e].value,e in b.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==b.fieldInfos.parallelize[e].type&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),bst.field.stringify(b.fieldInfos.parallelize[e],k," / ",!0)));
return d};(d=>{var c=(f,e)=>{(k=>{var u=(r,A)=>{if(0!=k.attachment.length){var n=!1;window.hasOwnProperty("bst_report_temp")&&k.attachment[r].fileKey in window.bst_report_temp&&(n=!0);n?(k.attachment[r].data=window.bst_report_temp[k.attachment[r].fileKey],r++,r<k.attachment.length?u(r,A):A()):bst.file.download(k.attachment[r],!0).then(v=>{bst.field.blobToBase64(v,B=>{k.attachment[r].data=B;r++;r<k.attachment.length?u(r,A):A()})}).catch(v=>{bst.alert(bst.error.parse(v));D()})}else A()};u(0,()=>{bst.encrypt(JSON.stringify(k.data),
M).then(r=>{var A=fetch,n="https://api.booooooost.com/mail/oauth/"+bst.operator.language,v=JSON,B=v.stringify;k.data=r.data;k.iv=r.iv;k.tag=r.tag;A(n,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:B.call(v,k)}).then(x=>{x.json().then(t=>{switch(x.status){case 200:f++;f<d.length?c(f,e):e();break;default:bst.alert(bst.error.parse(t)),D()}})}).catch(x=>{bst.alert(bst.error.parse(x));D()})}).catch(r=>{D()})})})(d[f])};0!=d.length?c(0,()=>{try{(a.formula||{value:[]}).value.map(f=>f.value).each((f,
e)=>{f.field.value in b.fieldInfos.parallelize&&(e=b.fieldInfos.parallelize[f.field.value],e.tableCode||(m[e.code].value=bst.formula.calculate(f,m,m,h,b.fieldInfos.parallelize),e.lookup&&(m[e.code].lookup=!0),f=m.$id.value,f in b.formulaRecords||(b.formulaRecords[f]={$id:{value:f}}),b.formulaRecords[f][e.code]=m[e.code]))}),q()}catch(f){bst.alert(bst.error.parse(f)),D()}}):q()})((()=>{var d=[];(b.fieldInfos.parallelize[a.to.value].tableCode?m[b.fieldInfos.parallelize[a.to.value].tableCode].value:
[{value:m}]).each((c,f)=>{c.value[a.to.value].value&&d.push({data:{client_id:a.client_id.value,client_secret:a.client_secret.value,author:a.author.value,sender:a.sender.value,subdomain:bst.operator.domain,provider:(e=>{e="";switch(a.provider.value){case "GMail":e="google";break;case "Exchange Online":e="microsoft"}return e})(a.provider.value),to:c.value[a.to.value].value,cc:L(a.cc.value,m,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),bcc:L(a.bcc.value,m,b.fieldInfos.parallelize[a.to.value].tableCode?
c.value:{}),html:"HTML"==a.format.value},subject:L(a.subject.value,m,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),body:L(a.body.value,m,b.fieldInfos.parallelize[a.to.value].tableCode?c.value:{}),attachment:(()=>{var e=[];a.attachment.value&&a.attachment.value in b.fieldInfos.parallelize&&(e=(b.fieldInfos.parallelize[a.attachment.value].tableCode?c.value:m)[a.attachment.value].value);return e})()})});return d})())}else q()}).catch(w=>{bst.alert(bst.error.parse(w));D()}):q()})(C[F])};
fetch("https://api.booooooost.com/mail/oauth/"+bst.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(F=>{F.json().then(G=>{switch(F.status){case 200:M=G.passphrase;l||bst.loadStart();K(0,()=>{l||bst.loadEnd();H()});break;default:bst.alert(bst.error.parse(G)),D()}})}).catch(F=>{bst.alert(bst.error.parse(F));D()})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;b.formulaRecords={};try{var h=l=>{0!=Object.keys(b.formulaRecords).length?
bst.record.api.set(b.app.id,{put:Object.values(b.formulaRecords).map(H=>bst.record.api.transform(H))},!0).then(H=>l()).catch(H=>bst.alert(bst.error.parse(H),()=>z(p))):l()};(l=>{0!=l.length?O(l,p.record,!0).then(H=>h(()=>z(p))).catch(()=>z(p)):z(p)})(bst.plugin.omail.reduce((l,H)=>{H.event.value.includes(p.pattern)&&l.push(H);return l},[]))}catch(l){bst.alert(bst.error.parse(l)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.report.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.report)&&0!=bst.plugin.report.length){var b={},O=(C,h,l=!1)=>new Promise((H,D)=>{var M=(K,F)=>{var G=()=>{K++;K<C.length?M(K,F):F()};(q=>{bst.filter.scan(b.app,h,q.condition.value)?bst.filter.auth(q.user.value,q.organization.value,q.group.value).then(a=>{if(a)if(q.attachment.value in b.fieldInfos.origin){var m=Object.values(b.fieldInfos.tables).reduce((w,L)=>{Object.values(L.fields).each((d,c)=>{w[d.code]={index:-1,
limit:h[L.code].value.length,status:"ready",table:L.code}});return w},{});(w=>{if(0!=w.sheets.length){var L=(c,f,e)=>{(k=>{var u=!1,r=bst.extend({},k),A;for(A in b.fieldInfos.parallelize)(n=>{k.cells.each((v,B)=>{v.each((x,t)=>{if(x.value.match(new RegExp("%"+n.code+"%")))switch(n.type){case "FILE":(g=>{Array.isArray(g)?(E=>{if(E){x.type="image";var y=k.rows.slice(B,B+parseInt(x.rowSpan||"1")).reduce((I,N)=>I+=N.origin,0),J=k.cols.slice(t,t+parseInt(x.colSpan||"1")).reduce((I,N)=>I+=N.origin,0);f.push({cell:x,
fileKey:E.fileKey,size:{height:y,width:J}});u=!0}else x.value=""})(g.find(E=>E.contentType.match(/image/g))):x.value=""})((()=>{var g=null;if(n.code in m){var E=m[n.code];"complete"!=E.status&&(E.index++,E.status=E.index==E.limit-1?"complete":"processing",g=h[E.table].value[E.index].value[n.code].value)}else g=h[n.code].value;return g})());break;default:n.code in m?(g=>{"complete"!=g.status?(g.index++,g.status=g.index==g.limit-1?"complete":"processing",x.value=x.value.replace(new RegExp("%"+n.code+
"%","g"),bst.field.stringify(n,h[g.table].value[g.index].value[n.code].value," / ",!0)),u=!0):x.value=x.value.replace(new RegExp("%"+n.code+"%","g"),"")})(m[n.code]):(x.value=x.value.replace(new RegExp("%"+n.code+"%","g"),bst.field.stringify(n,h[n.code].value," / ",!0)),u=!0)}x.value.match(/^=(TODAY|DATE_FORMAT)/)&&(x.value=eval(x.value.replace(/^=/g,"bst.formula.report.")))})})})(b.fieldInfos.parallelize[A]);k.repeat&&(Object.values(m).some(n=>"processing"==n.status)?w.sheets.splice(c+1,0,r):u||
(w.sheets.splice(c,1),c--));c++;c<w.sheets.length?L(c,f,e):e(f)})(w.sheets[c])},d=(c,f,e)=>{0!=f.length?bst.file.download(f[c],!0).then(k=>{var u=new Image;u.onload=()=>{var r=Math.min(f[c].size.width/u.width,f[c].size.height/u.height),A=Math.round(u.height*r);r=Math.round(u.width*r);var n=bst.create("canvas");n.width=r;n.height=A;n.getContext("2d").drawImage(u,0,0,r,A);f[c].cell.value=n.toDataURL("image/png");c++;c<f.length?d(c,f,e):e()};u.src=URL.createObjectURL(k)}).catch(k=>bst.alert(bst.error.parse(k),
()=>D())):e()};L(0,[],c=>{d(0,c,()=>{(f=>{fetch("https://api.pandafirm.jp/layup/report",{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({lang:bst.operator.language,name:f,datas:w})}).then(e=>{e.json().then(k=>{switch(e.status){case 200:bst.file.upload((u=>{var r=atob(u.binary),A=new Uint8Array(r.length);r.length.each(n=>A[n]=r.charCodeAt(n));return new File([new Blob([A.buffer],{type:u.contentType})],u.filename,{type:u.contentType})})(k.file),!0).then(u=>{window.hasOwnProperty("bst_report_temp")||
(window.bst_report_temp={});window.bst_report_temp[u.fileKey]=k.file.binary;h[q.attachment.value].value.push(u);G()}).catch(u=>{bst.alert(bst.error.parse(u),()=>D())});break;default:bst.alert(bst.error.parse(k),()=>D())}})}).catch(e=>bst.alert(bst.error.parse(e),()=>D()))})((q.name.value in b.fieldInfos.origin?h[q.name.value].value:"")||"report")})})}else G()})(q.template.value?JSON.parse(q.template.value):{sheets:[]})}else G();else G()}).catch(a=>bst.alert(bst.error.parse(a),()=>D())):G()})(C[K])};
l||bst.loadStart();M(0,()=>{bst.record.api.set(b.app.id,{put:[bst.record.api.transform(C.reduce((K,F)=>{F.attachment.value in b.fieldInfos.origin&&(K[F.attachment.value]=h[F.attachment.value]);return K},{$id:h.$id}))]},!0).then(K=>{l||bst.loadEnd();H()}).catch(K=>bst.alert(bst.error.parse(K),()=>D()))})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;try{(h=>{0!=h.length?O(h,p.record,!0).then(l=>z(p)).catch(()=>z(p)):z(p)})(bst.plugin.report.reduce((h,
l)=>{l.event.value.includes(p.pattern)&&h.push(l);return h},[]))}catch(h){bst.alert(bst.error.parse(h)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.style.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.style)&&0!=bst.plugin.style.length){var b={},O=(C,h,l)=>new Promise((H,D)=>{var M={},K=(F,G)=>{(q=>{var a=bst.filter.scan(b.app,h,q.condition.value);a?bst.filter.auth(q.user.value,q.organization.value,q.group.value).then(m=>{m&&(q.color.value.map(w=>w.value).each((w,L)=>{w.field.value in b.fieldInfos.parallelize&&(d=>{d.tableCode?d.tableCode in a&&a[d.tableCode].value.each((c,f)=>{d.code in c.value&&(c.value[d.code].backcolor=
w.backcolor.value,c.value[d.code].forecolor=w.forecolor.value)}):d.code in a&&(a[d.code].backcolor=w.backcolor.value,a[d.code].forecolor=w.forecolor.value)})(b.fieldInfos.parallelize[w.field.value])}),q.editable.value.map(w=>w.value).each((w,L)=>{w.field.value in b.fieldInfos.parallelize&&(d=>{b.fieldInfos.disables.includes(d.code)||(d.tableCode?d.tableCode in a&&(a[d.tableCode].value.each((c,f)=>{d.code in c.value&&(c.value[d.code].disabled="disable"==w.state.value)}),M[d.code]=h[d.tableCode].value.map(c=>
c.value[d.code].disabled?"disabled":"")):d.code in a&&(a[d.code].disabled="disable"==w.state.value,M[d.code]=h[d.code].disabled?"disabled":""))})(b.fieldInfos.parallelize[w.field.value])}),q.display.value.map(w=>w.value).each((w,L)=>{w.field.value in b.fieldInfos.groups?b.fieldInfos.groups[w.field.value].fields.map(d=>d.code).each((d,c)=>{d in b.fieldInfos.parallelize&&d in a&&(a[d].hidden="hide"==w.state.value)}):w.field.value in b.fieldInfos.tables?w.field.value in a&&(a[w.field.value].hidden="hide"==
w.state.value):(d=>{d.tableCode?d.tableCode in a&&a[d.tableCode].value.each((c,f)=>{d.code in c.value&&(c.value[d.code].hidden="hide"==w.state.value)}):d.code in a&&(a[d.code].hidden="hide"==w.state.value)})(b.fieldInfos.parallelize[w.field.value])}));F++;F<C.length?K(F,G):G()}).catch(m=>{bst.alert(bst.error.parse(m));D()}):(F++,F<C.length?K(F,G):G())})(C[F])};K(0,()=>{l.latest?l.latest.style||(l.latest.style="{}"):l.latest={style:"{}"};var F=JSON.stringify(M),G="{}"!=F?l.latest.style!=F:!1;G&&(l.latest.style=
F);H({performed:G})})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;try{(h=>{0!=h.length?O(h,p.record,p.container).then(l=>{p.performed=l.performed;z(p)}).catch(()=>z(p)):z(p)})(bst.plugin.style.reduce((h,l)=>{l.page.value.includes(p.pattern)&&h.push(l);return h},[]))}catch(h){bst.alert(bst.error.parse(h)),z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.submit.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.submit)&&0!=bst.plugin.submit.length){var b={},O=(C,h,l=!1,H={})=>new Promise((D,M)=>{var K=[],F=(G,q)=>{var a=()=>{G++;G<C.length?F(G,q):q()};(m=>{bst.filter.scan(b.app,h,m.condition.value)?bst.filter.auth(m.user.value,m.organization.value,m.group.value).then(w=>{if(w){var L={duplicate:d=>{try{m.duplicateCriteria.value.some(c=>!(c.value.external.value in b.fieldInfos.parallelize&&c.value.internal.value in b.fieldInfos.parallelize))?
(bst.alert("No field to lookup was found"),M()):(c=>{c&&K.push(c);d()})(m.duplicateCriteria.value.reduce((c,f)=>{var e=b.fieldInfos.parallelize[f.value.external.value],k=f.value.operator.value;f=b.fieldInfos.parallelize[f.value.internal.value];(m.duplicateFilled||{value:[]}).value.includes("filled")&&bst.field.isEmpty(h[f.code].value)||c.push(bst.filter.query.create(e,k,h[f.code]));return c},[]).join(" and "))}catch(c){bst.alert(bst.error.parse(c)),M()}},error:d=>{try{if(m.errorMessage.value||0!=
m.errorField.value.length){var c=bst.filter.scan(b.app,h,m.errorFilter.value);c?(m.errorField.value.each((f,e)=>{f.value.field.value in b.fieldInfos.parallelize&&(k=>{k.tableCode?c[k.tableCode].value.each((u,r)=>{u.value[f.value.field.value].error=f.value.message.value}):h[f.value.field.value].error=f.value.message.value})(b.fieldInfos.parallelize[f.value.field.value])}),l||bst.loadEnd(),D({error:!0,message:m.errorMessage.value})):d()}else d()}catch(f){bst.alert(bst.error.parse(f)),M()}},numbering:d=>
{try{if(m.numberingField.value in b.fieldInfos.parallelize)if(h[m.numberingField.value].value)d();else{var c="",f=m.numberingGroup.value.reduce((e,k)=>{if(k.value.field.value in b.fieldInfos.parallelize)switch(c+=h[k.value.field.value].value,b.fieldInfos.parallelize[k.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":e.push(k.value.field.value+' in ("'+h[k.value.field.value].value+'")');break;default:e.push(k.value.field.value+'="'+h[k.value.field.value].value+'"')}return e},"$id"in h?
['$id!="'+h.$id.value+'"']:[]);c in H?(H[c]++,h[m.numberingField.value].value=c+H[c].toString().lpad("0",parseInt(m.numberingDigits.value)),d()):bst.api(bst.api.url("/api/records"),"GET",{app:b.app.id,query:f.join(" and ")+" order by "+m.numberingField.value+" desc limit 1 offset 0"}).then(e=>{e=e.records;var k=0;0!=e.length&&(k=parseInt((e.first()[m.numberingField.value].value||" ").replace(/[ ]+/g,"").replace(new RegExp("^"+c,"g"),"")),bst.isNumeric(k)||(k=0));k++;e=k;H[c]=e;h[m.numberingField.value].value=
c+e.toString().lpad("0",parseInt(m.numberingDigits.value));d()}).catch(e=>{bst.alert(bst.error.parse(e));M()})}else d()}catch(e){bst.alert(bst.error.parse(e)),M()}},prompt:d=>{try{(c=>{0!=c.length?(f=>{c.each((e,k)=>{f.append(bst.field.activate(bst.field.create(e).css({width:"100%"}),b.app,!1))});l||bst.loadEnd();(new BooooooostPopupform(f,600,"full",{ok:()=>{var e=bst.record.get(f,b.app,!0);c.each((k,u)=>{h[k.code].value=e.record[k.code].value});l||bst.loadStart();d()},cancel:()=>{l||bst.loadStart();
d()}})).show()})(bst.create("div").addClass("bst-scope").attr("form-id","form_"+b.app.id)):d()})(m.promptField.value.reduce((c,f)=>{f.value.field.value in b.fieldInfos.parallelize&&(m.promptOverwrite.value.includes("overwrite")?c.push(b.fieldInfos.parallelize[f.value.field.value]):bst.field.isEmpty(h[f.value.field.value].value)&&c.push(b.fieldInfos.parallelize[f.value.field.value]));return c},[]))}catch(c){bst.alert(bst.error.parse(c)),M()}},verify:d=>{try{(c=>{0!=c.length?(f=>{c.each((e,k)=>{f.append(bst.field.activate(bst.field.create(e).addClass("bst-readonly").css({width:"100%"}),
b.app,!1))});bst.record.set(f,b.app,h);l||bst.loadEnd();(new BooooooostPopupform(f,600,"full",{ok:()=>{l||bst.loadStart();d()},cancel:()=>{l||bst.loadEnd();D({error:!0})}})).show()})(bst.create("div").addClass("bst-scope bst-verify").attr("form-id","form_"+b.app.id).append(bst.create("p").html(m.verifyMessage.value))):d()})(m.verifyField.value.reduce((c,f)=>{f.value.field.value in b.fieldInfos.parallelize&&c.push(b.fieldInfos.parallelize[f.value.field.value]);return c},[]))}catch(c){bst.alert(bst.error.parse(c)),
M()}}};L.numbering(()=>{L.prompt(()=>{L.verify(()=>{L.error(()=>{L.duplicate(()=>{a()})})})})})}else a()}).catch(w=>{bst.alert(bst.error.parse(w));M()}):a()})(C[G])};l||bst.loadStart();F(0,()=>{l||bst.loadEnd();0!=K.length?bst.api(bst.api.url("/api/records"),"GET",{app:b.app.id,query:((G,q)=>(q?"$id!="+q+" and ("+G+")":G)+" order by $id asc limit 5 offset 0")(K.map(G=>"("+G+")").join(" or "),"$id"in h?h.$id.value:"")}).then(G=>{0!=G.records.length?bst.confirm(bst.create("div").append(bst.create("p").css({margin:"0"}).html(bst.constants.submit.message.duplicate[bst.operator.language])),
q=>{D({error:q})},!0):D({error:!1})}).catch(G=>{bst.alert(bst.error.parse(G),()=>{D({error:!1})})}):D({error:!1})})});bst.field.load(bst.injector.app.id).then(C=>{b.app={id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;try{(h=>{0!=h.length?O(h,p.record,!0,p.numbering).then(l=>{l.error?(p.error=!0,l.message?bst.alert(l.message,()=>z(p)):z(p)):z(p)}).catch(()=>{p.error=!0;z(p)}):z(p)})(bst.plugin.submit.reduce((h,l)=>{l.event.value.includes(p.pattern)&&h.push(l);return h},[]))}catch(h){bst.alert(bst.error.parse(h)),
z(p)}}).catch(C=>z(p))}else z(p)}));
bst.event.on("bst.upsert.call",p=>new Promise((z,P)=>{if(Array.isArray(bst.plugin.upsert)&&0!=bst.plugin.upsert.length){var b={},O=(C,h,l=!1)=>new Promise((H,D)=>{var M=(K,F)=>{var G=(q,a)=>{K++;q&&(a.formulaSource||{value:[]}).value.map(m=>m.value).each((m,w)=>{m.field.value in b.fieldInfos.parallelize&&(w=b.fieldInfos.parallelize[m.field.value],w.tableCode||(q[w.code].value=bst.formula.calculate(m,q,q,h,b.fieldInfos.parallelize),w.lookup&&(q[w.code].lookup=!0),m=q.$id.value,m in b.formulaRecords||
(b.formulaRecords[m]={$id:{value:m}}),b.formulaRecords[m][w.code]=q[w.code]))});K<C.length?M(K,F):F()};(q=>{var a=bst.filter.scan(b.app,h,q.condition.value);a?bst.filter.auth(q.user.value,q.organization.value,q.group.value).then(m=>{m?bst.field.load(q.app.value).then(w=>{var L={id:q.app.value,fields:w.origin};(d=>{var c=[],f=[],e=[],k={},u={table:"",index:n=>u.table&&u.table==n.tableCode?r.progress.record:r.progress.row},r={record:1,row:1,progress:{record:0,row:0}},A=()=>{var n=[],v={field:(t,g)=>
{g=t.tableCode?a[t.tableCode].value.length>g?a[t.tableCode].value[g].value[t.code]:bst.record.create({fields:{empty:t}}).empty:a[t.code];return bst.extend({type:t.type},g)},record:t=>{r.row.each(g=>{var E=(y=>{var J=bst.filter.scan(L,t,y.query);if(!J&&"upsert"==q.pattern.value){for(var I in y.rows)0==bst.filter.result[I].value.length&&(t[I].value.push({value:bst.extend({},y.rows[I])}),bst.filter.result[I]={value:[t[I].value.last()]});J=bst.filter.result}return J})((()=>{var y={rows:{},query:[]};r.progress.row=
g;c.each((J,I)=>{J.external.tableCode&&(J.external.tableCode in y.rows||(y.rows[J.external.tableCode]=bst.record.create(L.fields[J.external.tableCode],!1)),I=v.field(J.internal,u.index(J.internal)),["=","in"].includes(J.operator.trim())&&(y.rows[J.external.tableCode][J.external.code]=B(J.external,I)),y.query.push(bst.filter.query.create(J.external,J.operator,I)))});f.each((J,I)=>{J.field.tableCode&&y.query.push(J.field.code+" "+J.operator+" "+J.value)});y.query=y.query.join(" and ");return y})());
E&&e.each((y,J)=>{y.external.tableCode?y.external.tableCode in k?(t[y.external.tableCode]={value:k[y.external.tableCode]},k[y.external.tableCode].each((I,N)=>{I.value[y.external.code]=B(y.external,v.field(y.internal,N));"FILE"==y.external.type&&I.value[y.external.code].value&&Array.prototype.push.apply(n,I.value[y.external.code].value)})):E[y.external.tableCode].value.each((I,N)=>{I.value[y.external.code]=B(y.external,v.field(y.internal,u.index(y.internal)));"FILE"==y.external.type&&I.value[y.external.code].value&&
Array.prototype.push.apply(n,I.value[y.external.code].value)}):(t[y.external.code]=B(y.external,v.field(y.internal,r.progress.record)),"FILE"==y.external.type&&t[y.external.code].value&&Array.prototype.push.apply(n,t[y.external.code].value))})});return t}},B=(t,g)=>{switch(t.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":Array.isArray(g.value)||(g.value=[g.value])}g.type=t.type;return t.lookup?bst.extend({lookup:!0},g):g},x=
t=>{t.each((g,E)=>{(q.formulaDestination||q.formula||{value:[]}).value.map(y=>y.value).each((y,J)=>{y.field.value in d.external&&(I=>{I.tableCode?g[I.tableCode].value.each((N,Q)=>{N.value[I.code].value=bst.formula.calculate(y,N.value,g,g,d.external);I.lookup&&(N.value[I.code].lookup=!0)}):(g[I.code].value=bst.formula.calculate(y,g,g,g,d.external),I.lookup&&(g[I.code].lookup=!0))})(d.external[y.field.value])})});(g=>{t.each((E,y)=>{for(var J in E)g.includes(J)||delete E[J]})})(["$id",...Object.keys(w.tables),
...c.filter(g=>!bst.field.reserved.includes(g.external.type)).reduce((g,E)=>{"upsert"==q.pattern.value&&(E.external.tableCode||["=","in"].includes(E.operator.trim())&&g.push(E.external.code));return g},[]),...e.reduce((g,E)=>{E.external.tableCode||g.push(E.external.code);return g},[]),...(q.formulaDestination||q.formula||{value:[]}).value.reduce((g,E)=>{E.value.field.value in d.external&&(E=d.external[E.value.field.value],E.tableCode||g.push(E.code));return g},[])]);return t};"insert"==q.pattern.value?
(t=>{bst.file.clone(n,!0).then(()=>{bst.record.api.set(q.app.value,{post:t},l).then(g=>{r.progress.record++;r.progress.record<r.record?A():G(a,q)}).catch(g=>{bst.alert(bst.error.parse(g));D()})})})(x([v.record(bst.record.create(L))])):bst.record.api.get(q.app.value,(()=>{var t=[];c.each((g,E)=>{g.external.tableCode||t.push(bst.filter.query.create(g.external,g.operator,v.field(g.internal,r.progress.record)))});f.each((g,E)=>{g.field.tableCode||t.push(g.field.code+" "+g.operator+" "+g.value)});return t.join(" and ")})()).then(t=>
{t=(g=>{var E=[];0!=g.length?E=g.map(y=>v.record(y)):"upsert"==q.pattern.value&&(y=>{E.push(v.record((()=>{var J=bst.record.create(L);y.each((I,N)=>{I.external.tableCode?J[I.external.tableCode]={value:[]}:["=","in"].includes(I.operator.trim())&&(J[I.external.code]=B(I.external,v.field(I.internal,r.progress.record)))});return J})()))})(c.filter(y=>!bst.field.reserved.includes(y.external.type)));return x(E)})(t);bst.file.clone(n,!0).then(()=>{bst.record.api.set(q.app.value,{post:t.filter(g=>!g.$id.value),
put:t.reduce((g,E)=>{E.$id.value&&g.push(bst.record.api.transform(E));return g},[])},l).then(g=>{r.progress.record++;r.progress.record<r.record?A():G(a,q)}).catch(g=>{bst.alert(bst.error.parse(g));D()})})}).catch(t=>{bst.alert(bst.error.parse(t));D()})};q.mapping.value.some(n=>!(n.value.external.value in d.external&&n.value.internal.value in d.internal))?(bst.alert("No field to transfer was found"),D()):q.criteria.value.some(n=>!(n.value.external.value in d.external&&n.value.internal.value in d.internal))?
(bst.alert("No field to transfer was found"),D()):([...q.mapping.value,...q.criteria.value].each((n,v)=>{v=d.internal[n.value.internal.value];!d.external[n.value.external.value].tableCode&&v.tableCode&&(u.table=v.tableCode,r.record=0==a[v.tableCode].value.length?0:a[v.tableCode].value.length)}),q.mapping.value.each((n,v)=>{((B,x)=>{B.tableCode&&(u.table&&u.table==x.tableCode||(k[B.tableCode]=(t=>{t=t?t.length:1;x.tableCode&&(t=t<a[x.tableCode].value.length?a[x.tableCode].value.length:t);return Array(t).fill().map(()=>
({value:bst.record.create(L.fields[B.tableCode],!1)}))})(k[B.tableCode])));e.push({external:B,internal:x})})(d.external[n.value.external.value],d.internal[n.value.internal.value])}),q.criteria.value.each((n,v)=>{v=d.external[n.value.external.value];var B=n.value.operator.value;n=d.internal[n.value.internal.value];v.tableCode&&(v.tableCode in k&&delete k[v.tableCode],!u.table&&n.tableCode&&(r.row=r.row<a[n.tableCode].value.length?a[n.tableCode].value.length:r.row));c.push({external:v,operator:B,internal:n})}),
bst.filter.query.parse.expand({id:q.app.value,fields:w.origin},q.filter.value).each((n,v)=>{f.push({field:d.external[n.field],operator:n.operator,value:n.value})}),0!=r.record?(r.progress.record=0,r.progress.row=0,A()):G())})({external:w.parallelize,internal:b.fieldInfos.parallelize})}).catch(w=>{bst.alert(bst.error.parse(w));D()}):G()}).catch(m=>{bst.alert(bst.error.parse(m));D()}):G()})(C[K])};l||bst.loadStart();M(0,()=>{l||bst.loadEnd();H()})});bst.field.load(bst.injector.app.id).then(C=>{b.app=
{id:bst.injector.app.id,fields:C.origin};b.fieldInfos=C;b.formulaRecords={};try{var h=l=>{0!=Object.keys(b.formulaRecords).length?bst.record.api.set(b.app.id,{put:Object.values(b.formulaRecords).map(H=>bst.record.api.transform(H))},!0).then(H=>l()).catch(H=>bst.alert(bst.error.parse(H),()=>z(p))):l()};(l=>{0!=l.length?O(l,p.record,!0).then(H=>h(()=>z(p))).catch(()=>z(p)):z(p)})(bst.plugin.upsert.reduce((l,H)=>{H.event.value.includes(p.pattern)&&l.push(H);return l},[]))}catch(l){bst.alert(bst.error.parse(l)),
z(p)}}).catch(C=>z(p))}else z(p)}));
bst.constants=bst.extend({submit:{message:{cancel:{process:{en:"The process action was canceled.",ja:"\u30d7\u30ed\u30bb\u30b9\u30a2\u30af\u30b7\u30e7\u30f3\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u8fdb\u7a0b\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002","zh-TW":"\u7a0b\u5e8f\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002"},submit:{en:"The submit was canceled.",ja:"\u4fdd\u5b58\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u4fdd\u5b58\u5df2\u88ab\u53d6\u6d88\u3002",
"zh-TW":"\u63d0\u4ea4\u5df2\u88ab\u53d6\u6d88\u3002"}},duplicate:{en:"A similar record already exists. Would you like to proceed with the registration anyway?",ja:"\u985e\u4f3c\u30ec\u30b3\u30fc\u30c9\u304c\u65e2\u306b\u767b\u9332\u3055\u308c\u3066\u3044\u307e\u3059\u304c\u3001\u3053\u306e\u307e\u307e\u767b\u9332\u3057\u3066\u3082\u5b9c\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u7ecf\u6709\u7c7b\u4f3c\u7684\u8bb0\u5f55\u5b58\u5728\u4e86\uff0c\u60a8\u8fd8\u8981\u7ee7\u7eed\u6ce8\u518c\u5417\uff1f",
"zh-TW":"\u5df2\u6709\u985e\u4f3c\u7684\u8a18\u9304\u5b58\u5728\uff0c\u60a8\u9084\u8981\u7e7c\u7e8c\u8a3b\u518a\u55ce\uff1f"}}}},bst.constants);
