/*
* FileName "plugin.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';kb.event.on("kb.action.call",m=>new Promise((z,Q)=>{if(Array.isArray(kb.plugin.action)&&0!=kb.plugin.action.length){var c={},P=(C,g,k)=>new Promise((I,D)=>{var M=JSON.stringify(kb.record.simplify({fields:c.fieldInfos.origin},g)),J=(F,G)=>{var r=()=>{F++;F<C.length?J(F,G):G()};(a=>{var l=kb.filter.scan(c.app,g,a.condition.value);l?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(y=>{if(y){var K={clear:d=>{try{a.clear.value.map(b=>b.value).each((b,f)=>{b.table.value in c.fieldInfos.tables&&
(g[b.table.value].value=g[b.table.value].value.filter(e=>!l[b.table.value].value.includes(e)),l[b.table.value].value=[])}),d()}catch(b){kb.alert(kb.error.parse(b)),D()}},fill:d=>{try{a.fill.value.map(b=>b.value).each((b,f)=>{b.table.value in c.fieldInfos.tables&&(e=>{e=kb.isNumeric(e)?parseInt(e)-l[b.table.value].value.length:0;0<e&&Array(e).fill().map(()=>kb.record.create(c.fieldInfos.origin[b.table.value],!1)).each((h,n)=>{g[b.table.value]==l[b.table.value]?g[b.table.value].value.push({value:h}):
(g[b.table.value].value.push({value:h}),l[b.table.value].value.push({value:h}))})})(kb.formula.calculate({field:{value:Object.values(c.fieldInfos.parallelize).first().code},formula:b.range},l,l,g,c.fieldInfos.parallelize))}),d()}catch(b){kb.alert(kb.error.parse(b)),D()}},formula:d=>{try{a.formula.value.map(b=>b.value).each((b,f)=>{b.field.value in c.fieldInfos.parallelize&&(e=>{e.tableCode?l[e.tableCode].value.each((h,n)=>{h.value[e.code].value=kb.formula.calculate(b,h.value,l,g,c.fieldInfos.parallelize);
e.lookup&&(h.value[e.code].lookup=!0)}):(l[e.code].value=kb.formula.calculate(b,l,l,g,c.fieldInfos.parallelize),e.lookup&&(l[e.code].lookup=!0))})(c.fieldInfos.parallelize[b.field.value])}),d()}catch(b){kb.alert(kb.error.parse(b)),D()}},lookup:d=>{try{a.lookupApp.value?kb.field.load(a.lookupApp.value).then(b=>{(f=>{var e=[],h=[],n=(w,u)=>{var E=(q,p)=>q.lookup?kb.extend({lookup:!0,type:q.type},p):kb.extend({type:q.type},p);kb.record.api.get(a.lookupApp.value,u.query,u.sort).then(q=>{0!=q.length?(p=>
{a.lookupLimited.value.includes("limited")||1==q.length?p(q.first()):c.picker.show({app:a.lookupApp.value,query:u.query,sort:u.sort,picker:e.reduce((H,x)=>{H[x.external.code]=x.external;return H},{})},H=>p(H))})(p=>{e.each((H,x)=>{if(a.lookupOverwrite.value.includes("overwrite")||kb.field.isEmpty(u.record[H.internal.code].value))u.record[H.internal.code]=E(H.internal,p[H.external.code])});w++;w<h.length?n(w,h[w]):(k.latest.action[a.sIndex.value].lookup=t(),d())}):(a.lookupReset.value.includes("reset")&&
e.each((p,H)=>{u.record[p.internal.code]=E(p.internal,kb.record.create({fields:{empty:p.internal}}).empty)}),w++,w<h.length?n(w,h[w]):(k.latest.action[a.sIndex.value].lookup=t(),d()))}).catch(q=>{kb.alert(kb.error.parse(q));D()})},t=()=>(w=>JSON.stringify(h.reduce((u,E)=>{u.push(E.query);u.push(kb.record.simplify({fields:w},E.record));return u},[])))(e.reduce((w,u)=>{w[u.internal.code]=u.internal;return w},{}));a.lookupCriteria.value.some(w=>!(w.value.external.value in f.external&&w.value.internal.value in
f.internal))?(kb.alert("No field to lookup was found"),D()):a.lookupMapping.value.some(w=>!(w.value.external.value in f.external&&w.value.internal.value in f.internal))?(kb.alert("No field to lookup was found"),D()):(e=a.lookupMapping.value.map(w=>({external:f.external[w.value.external.value],internal:f.internal[w.value.internal.value]})),h=(w=>w.map(u=>({query:a.lookupCriteria.value.reduce((E,q)=>{var p=f.external[q.value.external.value],H=q.value.operator.value;q=f.internal[q.value.internal.value];
var x=q.tableCode?u.value:g;a.lookupIgnore.value.includes("ignore")&&kb.field.isEmpty(x[q.code].value)||E.push(kb.filter.query.create(p,H,x[q.code]));return E},kb.filter.query.parse.expand({id:a.lookupApp.value,fields:b.origin},a.lookupFilter.value).map(E=>E.field+" "+E.operator+" "+E.value)).join(" and "),sort:(0!=a.lookupSort.value.length?a.lookupSort.value.map(E=>E.value.field.value+" "+E.value.order.value):["$id asc"]).join(","),record:u.value})))((w=>w?l[w].value:[{value:g}])(Array.from(new Set(e.map(w=>
w.internal.tableCode))).first())),0!=h.length?k.latest.action[a.sIndex.value].lookup&&k.latest.action[a.sIndex.value].lookup==t()?d():n(0,h.first()):d())})({external:b.origin,internal:c.fieldInfos.parallelize})}).catch(b=>{kb.alert(kb.error.parse(b));D()}):d()}catch(b){kb.alert(kb.error.parse(b)),D()}},user:d=>{try{if(a.userSource.value){var b=[],f=[],e=(n,t)=>{(u=>{b.each((E,q)=>{if(E.isCustom)switch(E.field.type){case "USER_SELECT":E.value=u.reduce((p,H)=>{"customItemValues"in H&&(x=>{0!=x.length&&
(v=>{(A=>{0!=A.length&&(p.some(O=>O.code==A.first().info.code)||p.push({code:A.first().info.code,name:A.first().info.name}))})(kb.roleSet.user.filter(A=>A.info.id==v))})(x.first().value)})(H.customItemValues.filter(x=>x.code==E.item));return Array.from(new Set(p)).filter(x=>x)},[]);break;default:E.value=u.reduce((p,H)=>{"customItemValues"in H&&(x=>{0!=x.length&&p.push(x.first().value)})(H.customItemValues.filter(x=>x.code==E.item));return Array.from(new Set(p)).filter(x=>x)},[]).join(",")}else switch(E.item){case "groups":case "organizations":E.value=
u.map(p=>p.code);break;case "primaryOrganization":E.value=u.reduce((p,H)=>{E.item in H&&(x=>{0!=x.length&&(p.some(v=>v.code==x.first().info.code)||p.push({code:x.first().info.code,name:x.first().info.name}))})(kb.roleSet.organization.filter(x=>x.info.id==H[E.item]));return p},[]);break;default:E.value=u.reduce((p,H)=>{E.item in H&&p.push(H[E.item]);return Array.from(new Set(p)).filter(x=>x)},[]).join(",")}})})(t[a.userSource.value].value.reduce((u,E)=>{(q=>{0!=q.length&&u.push(q.first().info)})(kb.roleSet.user.filter(q=>
q.info.code==E.code));return u},[]));var w=(u,E)=>{((q,p)=>{var H=(x,v,A)=>{kb.api(kb.api.url("/api/user/affiliations"),"GET",{code:q.value[x]}).then(O=>{switch(q.item){case "groups":O.groups&&(v=O.groups.reduce((B,L)=>{B.some(N=>N.code==L.code)||B.push({code:L.code,name:L.name});return B},v),x++,x<q.value.length?H(x,v,A):A(v));break;case "organizations":O.organizations&&(v=O.organizations.reduce((B,L)=>{B.some(N=>N.code==L.code)||B.push({code:L.code,name:L.name});return B},v),x++,x<q.value.length?
H(x,v,A):A(v))}}).catch(O=>kb.alert(kb.error.parse(O)))};a.userOverwrite.value.includes("overwrite")||kb.field.isEmpty(t[q.field.code].value)||p();switch(q.item){case "groups":case "organizations":0!=q.value.length?H(0,[],x=>{t[q.field.code].value=x;p()}):(t[q.field.code].value=q.value,p());break;default:t[q.field.code].value=q.value,p()}})(b[u],()=>{u++;u<b.length?w(u,E):E()})};w(0,()=>{n++;n<f.length?e(n,f[n]):(k.latest.action[a.sIndex.value].user=h(),d())})},h=()=>(n=>JSON.stringify(f.map(t=>kb.record.simplify({fields:n},
t))))(b.reduce((n,t)=>{n[t.field.code]=t.field;return n},(n=>{var t={};t[n]=c.fieldInfos.parallelize[n];return t})(a.userSource.value)));a.userCustomItem.value.some(n=>!(n.value.field.value in c.fieldInfos.parallelize))?(kb.alert("No field to user informations was found"),D()):a.userMapping.value.some(n=>!(n.value.field.value in c.fieldInfos.parallelize))?(kb.alert("No field to user informations was found"),D()):(a.userCustomItem.value.each((n,t)=>{b.push({isCustom:!0,item:n.value.item.value,field:c.fieldInfos.parallelize[n.value.field.value],
value:[]})}),a.userMapping.value.each((n,t)=>{b.push({isCustom:!1,item:n.value.item.value,field:c.fieldInfos.parallelize[n.value.field.value],value:[]})}),a.userPrimaryOrganization.value&&a.userPrimaryOrganization.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"primaryOrganization",field:c.fieldInfos.parallelize[a.userPrimaryOrganization.value],value:[]}),a.userOrganization.value&&a.userOrganization.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"organizations",field:c.fieldInfos.parallelize[a.userOrganization.value],
value:[]}),a.userGroup.value&&a.userGroup.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"groups",field:c.fieldInfos.parallelize[a.userGroup.value],value:[]}),f=(n=>n?l[n].value:[{value:g}])(c.fieldInfos.parallelize[a.userSource.value].tableCode).map(n=>n.value),0!=f.length?k.latest.action[a.sIndex.value].user&&k.latest.action[a.sIndex.value].user==h()?d():0!=b.length?e(0,f.first()):d():d())}else d()}catch(n){kb.alert(kb.error.parse(n)),D()}}};K.clear(()=>{K.fill(()=>{K.formula(()=>{K.lookup(()=>
{K.user(()=>{r()})})})})})}else r()}).catch(y=>{kb.alert(kb.error.parse(y));D()}):r()})((a=>{k.latest?k.latest.action||(k.latest.action={}):k.latest={action:{}};a.sIndex.value in k.latest.action||(k.latest.action[a.sIndex.value]={lookup:"[]",user:"[]"});return a})(C[F]))};J(0,()=>{I({record:g,performed:M!=JSON.stringify(kb.record.simplify({fields:c.fieldInfos.origin},g))})})});kb.field.load(kb.injector.app.id).then(C=>{c.app={id:kb.injector.app.id,fields:C.origin};c.fieldInfos=C;c.picker=new KintoneBoosterRecordPicker("record");
try{(g=>{if(0!=g.length){var k=(()=>{var I=g;"change"==m.pattern&&(I=g.filter(D=>(M=>"fields"in m?!M.first()||m.fields.some(J=>M.includes(J)):!M.first()||M.includes(m.field))(D.triggers.value.map(M=>M.value.field.value))));return I})();0!=k.length?P(k,m.record,m.container).then(I=>{m.stopPropagation&&(c.latest={record:JSON.stringify(kb.record.simplify({fields:C.origin},m.record)),time:(new Date).getTime()});m.performed=I.performed;z(m)}).catch(()=>z(m)):z(m)}else z(m)})(kb.plugin.action.reduce((g,
k)=>{k.event.value.includes(m.pattern)&&g.push(k);return g},[]))}catch(g){kb.alert(kb.error.parse(g)),z(m)}}).catch(C=>z(m))}else z(m)}));
kb.event.on("kb.cascade.call",m=>new Promise((z,Q)=>{if(["create","edit"].includes(m.pattern))if(Array.isArray(kb.plugin.cascade)&&0!=kb.plugin.cascade.length){var c={},P=(C,g,k)=>new Promise((I,D)=>{var M=(J,F)=>{var G=(r,a)=>{var l=Object.keys(c.fieldInfos.parallelize[r.child.value].options);if(Array.isArray(a[r.parent.value].value)?0!=a[r.parent.value].value.length:a[r.parent.value].value)l=(Array.isArray(a[r.parent.value].value)?a[r.parent.value].value:[a[r.parent.value].value]).reduce((y,K)=>
y=[...(new Set([...y,...r.relation.value[K]]))],[]);return l};(r=>{(a=>{a.parent.tableCode?a.parent.tableCode in g&&g[a.parent.tableCode].value.each((l,y)=>{a.parent.code in l.value&&(l.value[a.child.code].options=G(r,l.value))}):a.parent.code in g&&(g[a.child.code].options=G(r,g))})({parent:c.fieldInfos.parallelize[r.parent.value],child:c.fieldInfos.parallelize[r.child.value]});J++;J<C.length?M(J,F):F()})(C[J])};M(0,()=>I())});kb.field.load(kb.injector.app.id).then(C=>{c.app={id:kb.injector.app.id,
fields:C.origin};c.fieldInfos=C;try{(g=>{0!=g.length?P(g,m.record,m.container).then(k=>z(m)).catch(()=>z(m)):z(m)})(kb.plugin.cascade.reduce((g,k)=>{k.parent.value in c.fieldInfos.parallelize&&k.child.value in c.fieldInfos.parallelize&&("string"===typeof k.relation.value&&(k.relation.value=JSON.parse(k.relation.value)),g.push(k));return g},[]))}catch(g){kb.alert(kb.error.parse(g)),z(m)}}).catch(C=>z(m))}else z(m);else z(m)}));
kb.event.on("kb.mail.call",m=>new Promise((z,Q)=>{if(Array.isArray(kb.plugin.mail)&&0!=kb.plugin.mail.length){var c={},P=(C,g,k=!1)=>new Promise((I,D)=>{var M="",J=(F,G)=>{var r=()=>{F++;F<C.length?J(F,G):G()};(a=>{var l=kb.filter.scan(c.app,g,a.condition.value);l?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(y=>{if(y){var K=(d,b,f)=>{"HTML"==a.format.value&&(d=d.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var e in b){var h=b[e].value;e in c.fieldInfos.parallelize&&("HTML"==
a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[e].type&&(h=h.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[e],h," / ",!0)))}for(e in f)h=f[e].value,e in c.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[e].type&&(h=h.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[e],h," / ",!0)));return d};
(d=>{var b=(f,e)=>{(h=>{var n=(t,w)=>{if(0!=h.attachment.length){var u=!1;window.hasOwnProperty("kb_report_temp")&&h.attachment[t].fileKey in window.kb_report_temp&&(u=!0);u?(h.attachment[t].data=window.kb_report_temp[h.attachment[t].fileKey],t++,t<h.attachment.length?n(t,w):w()):kb.file.download(h.attachment[t],!0).then(E=>{kb.field.blobToBase64(E,q=>{h.attachment[t].data=q;t++;t<h.attachment.length?n(t,w):w()})}).catch(E=>{kb.alert(kb.error.parse(E));D()})}else w()};n(0,()=>{kb.encrypt(JSON.stringify(h.data),
M).then(t=>{var w=fetch,u="https://api.kintone-booster.com/mail/"+kb.operator.language,E=JSON,q=E.stringify;h.data=t.data;h.iv=t.iv;h.tag=t.tag;w(u,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:q.call(E,h)}).then(p=>{p.json().then(H=>{switch(p.status){case 200:f++;f<d.length?b(f,e):e();break;default:kb.alert(kb.error.parse(H)),D()}})}).catch(p=>{kb.alert(kb.error.parse(p));D()})}).catch(t=>{D()})})})(d[f])};0!=d.length?b(0,()=>{try{(a.formula||{value:[]}).value.map(f=>f.value).each((f,
e)=>{f.field.value in c.fieldInfos.parallelize&&(e=c.fieldInfos.parallelize[f.field.value],e.tableCode||(l[e.code].value=kb.formula.calculate(f,l,l,g,c.fieldInfos.parallelize),e.lookup&&(l[e.code].lookup=!0),f=l.$id.value,f in c.formulaRecords||(c.formulaRecords[f]={$id:{value:f}}),c.formulaRecords[f][e.code]=l[e.code]))}),r()}catch(f){kb.alert(kb.error.parse(f)),D()}}):r()})((()=>{var d=[];(c.fieldInfos.parallelize[a.to.value].tableCode?l[c.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:l}]).each((b,
f)=>{if(b.value[a.to.value].value){f=d.push;var e={mail:a.mail.value,sender:a.sender.value,host:a.host.value,port:a.port.value,author:a.author.value,pwd:a.pwd.value,secure:a.secure.value,to:b.value[a.to.value].value,cc:K(a.cc.value,l,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),bcc:K(a.bcc.value,l,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),html:"HTML"==a.format.value},h=K(a.subject.value,l,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),n=K(a.body.value,l,
c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),t=[];a.attachment.value&&a.attachment.value in c.fieldInfos.parallelize&&(t=(c.fieldInfos.parallelize[a.attachment.value].tableCode?b.value:l)[a.attachment.value].value);f.call(d,{data:e,subject:h,body:n,attachment:t})}});return d})())}else r()}).catch(y=>{kb.alert(kb.error.parse(y));D()}):r()})(C[F])};fetch("https://api.kintone-booster.com/mail/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(F=>{F.json().then(G=>
{switch(F.status){case 200:M=G.passphrase;k||kb.loadStart();J(0,()=>{k||kb.loadEnd();I()});break;default:kb.alert(kb.error.parse(G)),D()}})}).catch(F=>{kb.alert(kb.error.parse(F));D()})});kb.field.load(kb.injector.app.id).then(C=>{c.app={id:kb.injector.app.id,fields:C.origin};c.fieldInfos=C;c.formulaRecords={};try{var g=k=>{0!=Object.keys(c.formulaRecords).length?kb.record.api.set(c.app.id,{put:Object.values(c.formulaRecords).map(I=>kb.record.api.transform(I))},!0).then(I=>k()).catch(I=>kb.alert(kb.error.parse(I),
()=>z(m))):k()};(k=>{0!=k.length?P(k,m.record,!0).then(I=>g(()=>z(m))).catch(()=>z(m)):z(m)})(kb.plugin.mail.reduce((k,I)=>{I.event.value.includes(m.pattern)&&k.push(I);return k},[]))}catch(k){kb.alert(kb.error.parse(k)),z(m)}}).catch(C=>z(m))}else z(m)}));
kb.event.on("kb.omail.call",m=>new Promise((z,Q)=>{if(Array.isArray(kb.plugin.omail)&&0!=kb.plugin.omail.length){var c={},P=(C,g,k=!1)=>new Promise((I,D)=>{var M="",J=(F,G)=>{var r=()=>{F++;F<C.length?J(F,G):G()};(a=>{var l=kb.filter.scan(c.app,g,a.condition.value);l?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(y=>{if(y){var K=(d,b,f)=>{"HTML"==a.format.value&&(d=d.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var e in b){var h=b[e].value;e in c.fieldInfos.parallelize&&("HTML"==
a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[e].type&&(h=h.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[e],h," / ",!0)))}for(e in f)h=f[e].value,e in c.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[e].type&&(h=h.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+e+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[e],h," / ",!0)));return d};
(d=>{var b=(f,e)=>{(h=>{var n=(t,w)=>{if(0!=h.attachment.length){var u=!1;window.hasOwnProperty("kb_report_temp")&&h.attachment[t].fileKey in window.kb_report_temp&&(u=!0);u?(h.attachment[t].data=window.kb_report_temp[h.attachment[t].fileKey],t++,t<h.attachment.length?n(t,w):w()):kb.file.download(h.attachment[t],!0).then(E=>{kb.field.blobToBase64(E,q=>{h.attachment[t].data=q;t++;t<h.attachment.length?n(t,w):w()})}).catch(E=>{kb.alert(kb.error.parse(E));D()})}else w()};n(0,()=>{kb.encrypt(JSON.stringify(h.data),
M).then(t=>{var w=fetch,u="https://api.kintone-booster.com/mail/oauth/"+kb.operator.language,E=JSON,q=E.stringify;h.data=t.data;h.iv=t.iv;h.tag=t.tag;w(u,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:q.call(E,h)}).then(p=>{p.json().then(H=>{switch(p.status){case 200:f++;f<d.length?b(f,e):e();break;default:kb.alert(kb.error.parse(H)),D()}})}).catch(p=>{kb.alert(kb.error.parse(p));D()})}).catch(t=>{D()})})})(d[f])};0!=d.length?b(0,()=>{try{(a.formula||{value:[]}).value.map(f=>f.value).each((f,
e)=>{f.field.value in c.fieldInfos.parallelize&&(e=c.fieldInfos.parallelize[f.field.value],e.tableCode||(l[e.code].value=kb.formula.calculate(f,l,l,g,c.fieldInfos.parallelize),e.lookup&&(l[e.code].lookup=!0),f=l.$id.value,f in c.formulaRecords||(c.formulaRecords[f]={$id:{value:f}}),c.formulaRecords[f][e.code]=l[e.code]))}),r()}catch(f){kb.alert(kb.error.parse(f)),D()}}):r()})((()=>{var d=[];(c.fieldInfos.parallelize[a.to.value].tableCode?l[c.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:l}]).each((b,
f)=>{b.value[a.to.value].value&&d.push({data:{client_id:a.client_id.value,client_secret:a.client_secret.value,author:a.author.value,sender:a.sender.value,subdomain:kb.operator.domain,provider:(e=>{e="";switch(a.provider.value){case "GMail":e="google";break;case "Exchange Online":e="microsoft"}return e})(a.provider.value),to:b.value[a.to.value].value,cc:K(a.cc.value,l,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),bcc:K(a.bcc.value,l,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:
{}),html:"HTML"==a.format.value},subject:K(a.subject.value,l,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),body:K(a.body.value,l,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),attachment:(()=>{var e=[];a.attachment.value&&a.attachment.value in c.fieldInfos.parallelize&&(e=(c.fieldInfos.parallelize[a.attachment.value].tableCode?b.value:l)[a.attachment.value].value);return e})()})});return d})())}else r()}).catch(y=>{kb.alert(kb.error.parse(y));D()}):r()})(C[F])};fetch("https://api.kintone-booster.com/mail/oauth/"+
kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(F=>{F.json().then(G=>{switch(F.status){case 200:M=G.passphrase;k||kb.loadStart();J(0,()=>{k||kb.loadEnd();I()});break;default:kb.alert(kb.error.parse(G)),D()}})}).catch(F=>{kb.alert(kb.error.parse(F));D()})});kb.field.load(kb.injector.app.id).then(C=>{c.app={id:kb.injector.app.id,fields:C.origin};c.fieldInfos=C;c.formulaRecords={};try{var g=k=>{0!=Object.keys(c.formulaRecords).length?kb.record.api.set(c.app.id,
{put:Object.values(c.formulaRecords).map(I=>kb.record.api.transform(I))},!0).then(I=>k()).catch(I=>kb.alert(kb.error.parse(I),()=>z(m))):k()};(k=>{0!=k.length?P(k,m.record,!0).then(I=>g(()=>z(m))).catch(()=>z(m)):z(m)})(kb.plugin.omail.reduce((k,I)=>{I.event.value.includes(m.pattern)&&k.push(I);return k},[]))}catch(k){kb.alert(kb.error.parse(k)),z(m)}}).catch(C=>z(m))}else z(m)}));
kb.event.on("kb.report.call",m=>new Promise((z,Q)=>{if(Array.isArray(kb.plugin.report)&&0!=kb.plugin.report.length){var c={},P=(C,g,k=!1)=>new Promise((I,D)=>{var M=(J,F)=>{var G=()=>{J++;J<C.length?M(J,F):F()};(r=>{kb.filter.scan(c.app,g,r.condition.value)?kb.filter.auth(r.user.value,r.organization.value,r.group.value).then(a=>{if(a)if(r.attachment.value in c.fieldInfos.origin){var l=Object.values(c.fieldInfos.tables).reduce((y,K)=>{Object.values(K.fields).each((d,b)=>{y[d.code]={index:-1,limit:g[K.code].value.length,
status:"ready",table:K.code}});return y},{});(y=>{if(0!=y.sheets.length){var K=(b,f,e)=>{(h=>{var n=!1,t=kb.extend({},h),w;for(w in c.fieldInfos.parallelize)(u=>{h.cells.each((E,q)=>{E.each((p,H)=>{if(p.value.match(new RegExp("%"+u.code+"%")))switch(u.type){case "FILE":(x=>{Array.isArray(x)?(v=>{if(v){p.type="image";var A=h.rows.slice(q,q+parseInt(p.rowSpan||"1")).reduce((B,L)=>B+=L.origin,0),O=h.cols.slice(H,H+parseInt(p.colSpan||"1")).reduce((B,L)=>B+=L.origin,0);f.push({cell:p,fileKey:v.fileKey,
size:{height:A,width:O}});n=!0}else p.value=""})(x.find(v=>v.contentType.match(/image/g))):p.value=""})((()=>{var x=null;if(u.code in l){var v=l[u.code];"complete"!=v.status&&(v.index++,v.status=v.index==v.limit-1?"complete":"processing",x=g[v.table].value[v.index].value[u.code].value)}else x=g[u.code].value;return x})());break;default:u.code in l?(x=>{"complete"!=x.status?(x.index++,x.status=x.index==x.limit-1?"complete":"processing",p.value=p.value.replace(new RegExp("%"+u.code+"%","g"),kb.field.stringify(u,
g[x.table].value[x.index].value[u.code].value," / ",!0)),n=!0):p.value=p.value.replace(new RegExp("%"+u.code+"%","g"),"")})(l[u.code]):(p.value=p.value.replace(new RegExp("%"+u.code+"%","g"),kb.field.stringify(u,g[u.code].value," / ",!0)),n=!0)}p.value.match(/^=(TODAY|DATE_FORMAT)/)&&(p.value=eval(p.value.replace(/^=/g,"kb.formula.report.")))})})})(c.fieldInfos.parallelize[w]);h.repeat&&(Object.values(l).some(u=>"processing"==u.status)?y.sheets.splice(b+1,0,t):n||(y.sheets.splice(b,1),b--));b++;b<
y.sheets.length?K(b,f,e):e(f)})(y.sheets[b])},d=(b,f,e)=>{0!=f.length?kb.file.download(f[b],!0).then(h=>{var n=new Image;n.onload=()=>{var t=Math.min(f[b].size.width/n.width,f[b].size.height/n.height),w=Math.round(n.height*t);t=Math.round(n.width*t);var u=kb.create("canvas");u.width=t;u.height=w;u.getContext("2d").drawImage(n,0,0,t,w);f[b].cell.value=u.toDataURL("image/png");b++;b<f.length?d(b,f,e):e()};n.src=URL.createObjectURL(h)}).catch(h=>kb.alert(kb.error.parse(h),()=>D())):e()};K(0,[],b=>{d(0,
b,()=>{(f=>{fetch("https://api.pandafirm.jp/layup/report",{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({lang:kb.operator.language,name:f,datas:y})}).then(e=>{e.json().then(h=>{switch(e.status){case 200:kb.file.upload((n=>{var t=atob(n.binary),w=new Uint8Array(t.length);t.length.each(u=>w[u]=t.charCodeAt(u));return new File([new Blob([w.buffer],{type:n.contentType})],n.filename,{type:n.contentType})})(h.file),!0).then(n=>{window.hasOwnProperty("kb_report_temp")||
(window.kb_report_temp={});window.kb_report_temp[n.fileKey]=h.file.binary;g[r.attachment.value].value.push(n);G()}).catch(n=>{kb.alert(kb.error.parse(n),()=>D())});break;default:kb.alert(kb.error.parse(h),()=>D())}})}).catch(e=>kb.alert(kb.error.parse(e),()=>D()))})((r.name.value in c.fieldInfos.origin?g[r.name.value].value:"")||"report.pdf")})})}else G()})(r.template.value?JSON.parse(r.template.value):{sheets:[]})}else G();else G()}).catch(a=>kb.alert(kb.error.parse(a),()=>D())):G()})(C[J])};k||
kb.loadStart();M(0,()=>{kb.record.api.set(c.app.id,{put:[kb.record.api.transform(C.reduce((J,F)=>{F.attachment.value in c.fieldInfos.origin&&(J[F.attachment.value]=g[F.attachment.value]);return J},{$id:g.$id}))]},!0).then(J=>{k||kb.loadEnd();I()}).catch(J=>kb.alert(kb.error.parse(J),()=>D()))})});kb.field.load(kb.injector.app.id).then(C=>{c.app={id:kb.injector.app.id,fields:C.origin};c.fieldInfos=C;try{(g=>{0!=g.length?P(g,m.record,!0).then(k=>z(m)).catch(()=>z(m)):z(m)})(kb.plugin.report.reduce((g,
k)=>{k.event.value.includes(m.pattern)&&g.push(k);return g},[]))}catch(g){kb.alert(kb.error.parse(g)),z(m)}}).catch(C=>z(m))}else z(m)}));
kb.event.on("kb.style.call",m=>new Promise((z,Q)=>{if(Array.isArray(kb.plugin.style)&&0!=kb.plugin.style.length){var c={},P=(C,g,k)=>new Promise((I,D)=>{var M={},J=(F,G)=>{(r=>{var a=kb.filter.scan(c.app,g,r.condition.value);a?kb.filter.auth(r.user.value,r.organization.value,r.group.value).then(l=>{l&&(r.color.value.map(y=>y.value).each((y,K)=>{y.field.value in c.fieldInfos.parallelize&&(d=>{d.tableCode?d.tableCode in a&&a[d.tableCode].value.each((b,f)=>{d.code in b.value&&(b.value[d.code].backcolor=
y.backcolor.value,b.value[d.code].forecolor=y.forecolor.value)}):d.code in a&&(a[d.code].backcolor=y.backcolor.value,a[d.code].forecolor=y.forecolor.value)})(c.fieldInfos.parallelize[y.field.value])}),r.editable.value.map(y=>y.value).each((y,K)=>{y.field.value in c.fieldInfos.parallelize&&(d=>{c.fieldInfos.disables.includes(d.code)||(d.tableCode?d.tableCode in a&&(a[d.tableCode].value.each((b,f)=>{d.code in b.value&&(b.value[d.code].disabled="disable"==y.state.value)}),M[d.code]=g[d.tableCode].value.map(b=>
b.value[d.code].disabled?"disabled":"")):d.code in a&&(a[d.code].disabled="disable"==y.state.value,M[d.code]=g[d.code].disabled?"disabled":""))})(c.fieldInfos.parallelize[y.field.value])}),r.display.value.map(y=>y.value).each((y,K)=>{y.field.value in c.fieldInfos.groups?c.fieldInfos.groups[y.field.value].fields.map(d=>d.code).each((d,b)=>{d in c.fieldInfos.parallelize&&d in a&&(a[d].hidden="hide"==y.state.value)}):y.field.value in c.fieldInfos.tables?y.field.value in a&&(a[y.field.value].hidden="hide"==
y.state.value):(d=>{d.tableCode?d.tableCode in a&&a[d.tableCode].value.each((b,f)=>{d.code in b.value&&(b.value[d.code].hidden="hide"==y.state.value)}):d.code in a&&(a[d.code].hidden="hide"==y.state.value)})(c.fieldInfos.parallelize[y.field.value])}));F++;F<C.length?J(F,G):G()}).catch(l=>{kb.alert(kb.error.parse(l));D()}):(F++,F<C.length?J(F,G):G())})(C[F])};J(0,()=>{k.latest?k.latest.style||(k.latest.style="{}"):k.latest={style:"{}"};var F=JSON.stringify(M),G="{}"!=F?k.latest.style!=F:!1;G&&(k.latest.style=
F);I({performed:G})})});kb.field.load(kb.injector.app.id).then(C=>{c.app={id:kb.injector.app.id,fields:C.origin};c.fieldInfos=C;try{(g=>{0!=g.length?P(g,m.record,m.container).then(k=>{m.performed=k.performed;z(m)}).catch(()=>z(m)):z(m)})(kb.plugin.style.reduce((g,k)=>{k.page.value.includes(m.pattern)&&g.push(k);return g},[]))}catch(g){kb.alert(kb.error.parse(g)),z(m)}}).catch(C=>z(m))}else z(m)}));
kb.event.on("kb.submit.call",m=>new Promise((z,Q)=>{if(Array.isArray(kb.plugin.submit)&&0!=kb.plugin.submit.length){var c={},P=(C,g,k=!1,I={})=>new Promise((D,M)=>{var J=[],F=(G,r)=>{var a=()=>{G++;G<C.length?F(G,r):r()};(l=>{kb.filter.scan(c.app,g,l.condition.value)?kb.filter.auth(l.user.value,l.organization.value,l.group.value).then(y=>{if(y){var K={duplicate:d=>{try{l.duplicateCriteria.value.some(b=>!(b.value.external.value in c.fieldInfos.parallelize&&b.value.internal.value in c.fieldInfos.parallelize))?
(kb.alert("No field to lookup was found"),M()):(b=>{b&&J.push(b);d()})(l.duplicateCriteria.value.reduce((b,f)=>{b.push(kb.filter.query.create(c.fieldInfos.parallelize[f.value.external.value],f.value.operator.value,g[c.fieldInfos.parallelize[f.value.internal.value].code]));return b},[]).join(" and "))}catch(b){kb.alert(kb.error.parse(b)),M()}},error:d=>{try{if(l.errorMessage.value||0!=l.errorField.value.length){var b=kb.filter.scan(c.app,g,l.errorFilter.value);b?(l.errorField.value.each((f,e)=>{f.value.field.value in
c.fieldInfos.parallelize&&(h=>{h.tableCode?b[h.tableCode].value.each((n,t)=>{n.value[f.value.field.value].error=f.value.message.value}):g[f.value.field.value].error=f.value.message.value})(c.fieldInfos.parallelize[f.value.field.value])}),k||kb.loadEnd(),D({error:!0,message:l.errorMessage.value})):d()}else d()}catch(f){kb.alert(kb.error.parse(f)),M()}},numbering:d=>{try{if(l.numberingField.value in c.fieldInfos.parallelize)if(g[l.numberingField.value].value)d();else{var b="",f=l.numberingGroup.value.reduce((e,
h)=>{if(h.value.field.value in c.fieldInfos.parallelize)switch(b+=g[h.value.field.value].value,c.fieldInfos.parallelize[h.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":e.push(h.value.field.value+' in ("'+g[h.value.field.value].value+'")');break;default:e.push(h.value.field.value+'="'+g[h.value.field.value].value+'"')}return e},"$id"in g?['$id!="'+g.$id.value+'"']:[]);b in I?(I[b]++,g[l.numberingField.value].value=b+I[b].toString().lpad("0",parseInt(l.numberingDigits.value)),d()):kb.api(kb.api.url("/api/records"),
"GET",{app:c.app.id,query:f.join(" and ")+" order by "+l.numberingField.value+" desc limit 1 offset 0"}).then(e=>{e=e.records;var h=0;0!=e.length&&(h=parseInt((e.first()[l.numberingField.value].value||" ").replace(/[ ]+/g,"").replace(new RegExp("^"+b,"g"),"")),kb.isNumeric(h)||(h=0));h++;e=h;I[b]=e;g[l.numberingField.value].value=b+e.toString().lpad("0",parseInt(l.numberingDigits.value));d()}).catch(e=>{kb.alert(kb.error.parse(e));M()})}else d()}catch(e){kb.alert(kb.error.parse(e)),M()}},prompt:d=>
{try{(b=>{0!=b.length?(f=>{b.each((e,h)=>{f.append(kb.field.activate(kb.field.create(e).css({width:"100%"}),c.app,!1))});k||kb.loadEnd();(new KintoneBoosterPopupform(f,600,"full",{ok:()=>{var e=kb.record.get(f,c.app,!0);b.each((h,n)=>{g[h.code].value=e.record[h.code].value});k||kb.loadStart();d()},cancel:()=>{k||kb.loadStart();d()}})).show()})(kb.create("div").addClass("kb-scope").attr("form-id","form_"+c.app.id)):d()})(l.promptField.value.reduce((b,f)=>{f.value.field.value in c.fieldInfos.parallelize&&
(l.promptOverwrite.value.includes("overwrite")?b.push(c.fieldInfos.parallelize[f.value.field.value]):kb.field.isEmpty(g[f.value.field.value].value)&&b.push(c.fieldInfos.parallelize[f.value.field.value]));return b},[]))}catch(b){kb.alert(kb.error.parse(b)),M()}},verify:d=>{try{(b=>{0!=b.length?(f=>{b.each((e,h)=>{f.append(kb.field.activate(kb.field.create(e).addClass("kb-readonly").css({width:"100%"}),c.app,!1))});kb.record.set(f,c.app,g);k||kb.loadEnd();(new KintoneBoosterPopupform(f,600,"full",{ok:()=>
{k||kb.loadStart();d()},cancel:()=>{k||kb.loadEnd();D({error:!0})}})).show()})(kb.create("div").addClass("kb-scope kb-verify").attr("form-id","form_"+c.app.id).append(kb.create("p").html(l.verifyMessage.value))):d()})(l.verifyField.value.reduce((b,f)=>{f.value.field.value in c.fieldInfos.parallelize&&b.push(c.fieldInfos.parallelize[f.value.field.value]);return b},[]))}catch(b){kb.alert(kb.error.parse(b)),M()}}};K.numbering(()=>{K.prompt(()=>{K.verify(()=>{K.error(()=>{K.duplicate(()=>{a()})})})})})}else a()}).catch(y=>
{kb.alert(kb.error.parse(y));M()}):a()})(C[G])};k||kb.loadStart();F(0,()=>{k||kb.loadEnd();0!=J.length?kb.api(kb.api.url("/api/records"),"GET",{app:c.app.id,query:((G,r)=>(r?"$id!="+r+" and ("+G+")":G)+" order by $id asc limit 5 offset 0")(J.map(G=>"("+G+")").join(" or "),"$id"in g?g.$id.value:"")}).then(G=>{0!=G.records.length?kb.confirm(kb.create("div").append(kb.create("p").css({margin:"0"}).html(kb.constants.submit.message.duplicate[kb.operator.language])),r=>{D({error:r})},!0):D({error:!1})}).catch(G=>
{kb.alert(kb.error.parse(G),()=>{D({error:!1})})}):D({error:!1})})});kb.field.load(kb.injector.app.id).then(C=>{c.app={id:kb.injector.app.id,fields:C.origin};c.fieldInfos=C;try{(g=>{0!=g.length?P(g,m.record,!0,m.numbering).then(k=>{k.error?(m.error=!0,k.message?kb.alert(k.message,()=>z(m)):z(m)):z(m)}).catch(()=>{m.error=!0;z(m)}):z(m)})(kb.plugin.submit.reduce((g,k)=>{k.event.value.includes(m.pattern)&&g.push(k);return g},[]))}catch(g){kb.alert(kb.error.parse(g)),z(m)}}).catch(C=>z(m))}else z(m)}));
kb.event.on("kb.upsert.call",m=>new Promise((z,Q)=>{if(Array.isArray(kb.plugin.upsert)&&0!=kb.plugin.upsert.length){var c={},P=(C,g,k=!1)=>new Promise((I,D)=>{var M=(J,F)=>{var G=()=>{J++;J<C.length?M(J,F):F()};(r=>{var a=kb.filter.scan(c.app,g,r.condition.value);a?kb.filter.auth(r.user.value,r.organization.value,r.group.value).then(l=>{l?kb.field.load(r.app.value).then(y=>{var K={id:r.app.value,fields:y.origin};(d=>{var b=[],f=[],e=[],h={},n=1,t=1,w=0,u=0,E=()=>{var q=[],p={field:(v,A)=>{A=v.tableCode?
a[v.tableCode].value.length>A?a[v.tableCode].value[A].value[v.code]:kb.record.create({fields:{empty:v}}).empty:a[v.code];return kb.extend({type:v.type},A)},record:v=>{t.each(A=>{var O=(B=>{var L=kb.filter.scan(K,v,B.query);if(!L&&"upsert"==r.pattern.value){for(var N in B.rows)0==kb.filter.result[N].value.length&&(v[N].value.push({value:kb.extend({},B.rows[N])}),kb.filter.result[N]={value:[v[N].value.last()]});L=kb.filter.result}return L})((()=>{var B={rows:{},query:[]};u=A;b.each((L,N)=>{L.external.tableCode&&
(L.external.tableCode in B.rows||(B.rows[L.external.tableCode]=kb.record.create(K.fields[L.external.tableCode],!1)),B.rows[L.external.tableCode][L.external.code]=H(L.external,p.field(L.internal,u)),B.query.push(kb.filter.query.create(L.external,L.operator,p.field(L.internal,u))))});f.each((L,N)=>{L.field.tableCode&&B.query.push(L.field.code+" "+L.operator+" "+L.value)});B.query=B.query.join(" and ");return B})());O&&e.each((B,L)=>{B.external.tableCode?B.external.tableCode in h?(v[B.external.tableCode]=
{value:h[B.external.tableCode]},h[B.external.tableCode].each((N,R)=>{N.value[B.external.code]=H(B.external,p.field(B.internal,R));"FILE"==B.external.type&&N.value[B.external.code].value&&Array.prototype.push.apply(q,N.value[B.external.code].value)})):O[B.external.tableCode].value.each((N,R)=>{N.value[B.external.code]=H(B.external,p.field(B.internal,u));"FILE"==B.external.type&&N.value[B.external.code].value&&Array.prototype.push.apply(q,N.value[B.external.code].value)}):(v[B.external.code]=H(B.external,
p.field(B.internal,w)),"FILE"==B.external.type&&v[B.external.code].value&&Array.prototype.push.apply(q,v[B.external.code].value))})});return v}},H=(v,A)=>{switch(v.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":Array.isArray(A.value)||(A.value=[A.value])}A.type=v.type;return v.lookup?kb.extend({lookup:!0},A):A},x=v=>{v.each((A,O)=>{r.formula.value.each((B,L)=>{B.value.field.value in d.external&&(N=>{N.tableCode?A[N.tableCode].value.each((R,
S)=>{R.value[N.code].value=kb.formula.calculate(B.value,R.value,A,A,d.external);N.lookup&&(R.value[N.code].lookup=!0)}):(A[N.code].value=kb.formula.calculate(B.value,A,A,A,d.external),N.lookup&&(A[N.code].lookup=!0))})(d.external[B.value.field.value])})});return v};"insert"==r.pattern.value?(v=>{kb.file.clone(q,!0).then(()=>{kb.record.api.set(r.app.value,{post:v},k).then(A=>{w++;w<n?E():G()}).catch(A=>{kb.alert(kb.error.parse(A));D()})})})(x([p.record(kb.record.create(K))])):kb.record.api.get(r.app.value,
(()=>{var v=[];b.each((A,O)=>{A.external.tableCode||v.push(kb.filter.query.create(A.external,A.operator,p.field(A.internal,w)))});f.each((A,O)=>{A.field.tableCode||v.push(A.field.code+" "+A.operator+" "+A.value)});return v.join(" and ")})()).then(v=>{v=(A=>{var O=[];0!=A.length?O=A.map(B=>p.record(B)):"upsert"==r.pattern.value&&(B=>{O.push(p.record((()=>{var L=kb.record.create(K);B.each((N,R)=>{N.external.tableCode?L[N.external.tableCode]={value:[]}:L[N.external.code]=H(N.external,p.field(N.internal,
w))});return L})()))})(b.filter(B=>!kb.field.reserved.includes(B.external.type)));return x(O)})(v);kb.file.clone(q,!0).then(()=>{kb.record.api.set(r.app.value,{post:v.filter(A=>!A.$id.value),put:v.reduce((A,O)=>{O.$id.value&&A.push(kb.record.api.transform(O));return A},[])},k).then(A=>{w++;w<n?E():G()}).catch(A=>{kb.alert(kb.error.parse(A));D()})})}).catch(v=>{kb.alert(kb.error.parse(v));D()})};r.mapping.value.some(q=>!(q.value.external.value in d.external&&q.value.internal.value in d.internal))?
(kb.alert("No field to transfer was found"),D()):r.criteria.value.some(q=>!(q.value.external.value in d.external&&q.value.internal.value in d.internal))?(kb.alert("No field to transfer was found"),D()):(r.mapping.value.each((q,p)=>{((H,x)=>{H.tableCode?h[H.tableCode]=(v=>{v=v?v.length:1;x.tableCode&&(v=v<a[x.tableCode].value.length?a[x.tableCode].value.length:v);return Array(v).fill().map(()=>({value:kb.record.create(K.fields[H.tableCode],!1)}))})(h[H.tableCode]):x.tableCode&&(n=0==a[x.tableCode].value.length?
0:n<a[x.tableCode].value.length?a[x.tableCode].value.length:n);e.push({external:H,internal:x})})(d.external[q.value.external.value],d.internal[q.value.internal.value])}),r.criteria.value.each((q,p)=>{p=d.external[q.value.external.value];var H=q.value.operator.value;q=d.internal[q.value.internal.value];p.tableCode?(p.tableCode in h&&delete h[p.tableCode],q.tableCode&&(t=t<a[q.tableCode].value.length?a[q.tableCode].value.length:t)):q.tableCode&&(n=0==a[q.tableCode].value.length?0:n<a[q.tableCode].value.length?
a[q.tableCode].value.length:n);b.push({external:p,operator:H,internal:q})}),kb.filter.query.parse.expand({id:r.app.value,fields:y.origin},r.filter.value).each((q,p)=>{f.push({field:d.external[q.field],operator:q.operator,value:q.value})}),0!=n?(u=w=0,E()):G())})({external:y.parallelize,internal:c.fieldInfos.parallelize})}).catch(y=>{kb.alert(kb.error.parse(y));D()}):G()}).catch(l=>{kb.alert(kb.error.parse(l));D()}):G()})(C[J])};k||kb.loadStart();M(0,()=>{k||kb.loadEnd();I()})});kb.field.load(kb.injector.app.id).then(C=>
{c.app={id:kb.injector.app.id,fields:C.origin};c.fieldInfos=C;try{(g=>{0!=g.length?P(g,m.record,!0).then(k=>z(m)).catch(()=>z(m)):z(m)})(kb.plugin.upsert.reduce((g,k)=>{k.event.value.includes(m.pattern)&&g.push(k);return g},[]))}catch(g){kb.alert(kb.error.parse(g)),z(m)}}).catch(C=>z(m))}else z(m)}));
kb.constants=kb.extend({submit:{message:{cancel:{process:{en:"The process action was canceled.",ja:"\u30d7\u30ed\u30bb\u30b9\u30a2\u30af\u30b7\u30e7\u30f3\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u8fdb\u7a0b\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002","zh-TW":"\u7a0b\u5e8f\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002"},submit:{en:"The submit was canceled.",ja:"\u4fdd\u5b58\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u4fdd\u5b58\u5df2\u88ab\u53d6\u6d88\u3002",
"zh-TW":"\u63d0\u4ea4\u5df2\u88ab\u53d6\u6d88\u3002"}},duplicate:{en:"A similar record already exists. Would you like to proceed with the registration anyway?",ja:"\u985e\u4f3c\u30ec\u30b3\u30fc\u30c9\u304c\u65e2\u306b\u767b\u9332\u3055\u308c\u3066\u3044\u307e\u3059\u304c\u3001\u3053\u306e\u307e\u307e\u767b\u9332\u3057\u3066\u3082\u5b9c\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u7ecf\u6709\u7c7b\u4f3c\u7684\u8bb0\u5f55\u5b58\u5728\u4e86\uff0c\u60a8\u8fd8\u8981\u7ee7\u7eed\u6ce8\u518c\u5417\uff1f",
"zh-TW":"\u5df2\u6709\u985e\u4f3c\u7684\u8a18\u9304\u5b58\u5728\uff0c\u60a8\u9084\u8981\u7e7c\u7e8c\u8a3b\u518a\u55ce\uff1f"}}}},kb.constants);
