/*
* FileName "main.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';window.BooooooostEcho=class{constructor(){}build(l,k){try{window.bst.attachment=new BooooooostAttachment,window.bst.field=new BooooooostField,window.bst.filter=new BooooooostFilter,window.bst.formula=new BooooooostFormula,window.bst.record=new BooooooostRecord,window.bst.table=new BooooooostTable,window.bst.view=new BooooooostView,window.kb.attachment=window.bst.attachment,window.kb.field=window.bst.field,window.kb.filter=window.bst.filter,window.kb.formula=window.bst.formula,window.kb.record=window.bst.record,
window.kb.table=window.bst.table,window.kb.view=window.bst.view,bst.field.load(l).then(h=>{this.app={id:l,fields:((d,b)=>{var a={},c;for(c in d){var f=d[c];f.tableCode?f.tableCode in a||(a[f.tableCode]=b[f.tableCode]):a[c]=f}return a})(h.parallelize,h.tables),view:{edit:k.injector.edit,fields:k.view.fields}};this.controller={access:new BooooooostEchoAccessController(k.access,h.origin),injector:(d=>{d.contents.addClass("kb-echo-popup");return d})(new BooooooostPopupwindow(bst.create("iframe").addClass("kb-echo-popup-contents"),
"full","full",[]))};this.view={build:()=>{(d=>{bst.elm("body").append((b=>{this.setting.ui.container=b;return b.on("scroll",a=>d())})(bst.create("div").addClass("kb-echo")).append((b=>{switch(this.setting.view.type){case "CALENDAR":b.addClass("kb-echo-main-calendar");break;case "LIST":b.addClass("kb-echo-main-list")}return b})(bst.create("div").addClass("kb-echo-main")).append((b=>{this.setting.ui.header.info=b;return b.on("show",a=>d())})(bst.create("header").addClass("kb-echo-header")).append(bst.create("div").addClass("kb-echo-header-info").append(bst.create("div").addClass("kb-echo-header-title").html(this.setting.title)).append(bst.create("div").addClass("kb-echo-header-description").html(this.setting.description?
this.setting.description.replace(/\n/g,"<br>"):"")))).append((b=>{this.setting.ui.header.action=b;return b.on("show",a=>d())})(bst.create("header").addClass("kb-echo-header")).append(bst.create("div").addClass("kb-echo-header-action").append((b=>{b.append(bst.create("button").addClass("kb-icon kb-icon-filter").on("click",a=>{bst.filter.build(this.setting.filter.app,this.setting.filter.query,c=>{this.setting.filter.query=c;this.setting.filter.offset=0;this.view.load().then(()=>{}).catch(()=>{})})}));
switch(this.setting.view.type){case "CALENDAR":b.append((()=>{this.setting.filter.prev=bst.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-left").on("click",a=>{this.setting.filter.monitor.html((new Date(this.setting.filter.monitor.text()+"-01")).calc("-1 month").format("Y-m"));this.view.load().then(()=>{}).catch(()=>{})});return this.setting.filter.prev})()).append((()=>{this.setting.filter.next=bst.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-right").on("click",
a=>{this.setting.filter.monitor.html((new Date(this.setting.filter.monitor.text()+"-01")).calc("1 month").format("Y-m"));this.view.load().then(()=>{}).catch(()=>{})});return this.setting.filter.next})()).append((()=>{this.setting.filter.monitor=bst.create("span").addClass("kb-echo-header-filter-monitor").html((new Date).format("Y-m"));return this.setting.filter.monitor})()).append(bst.create("button").addClass("kb-icon kb-icon-date").on("click",a=>{bst.pickupDate(this.setting.filter.monitor.text()+
"-01",c=>{this.setting.filter.monitor.html((new Date(c)).format("Y-m"));this.view.load().then(()=>{}).catch(()=>{})})}));break;case "LIST":b.append((()=>{this.setting.filter.prev=bst.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-left").on("click",a=>{this.setting.filter.offset-=this.setting.filter.limit;this.view.load().then(()=>{}).catch(()=>{})});return this.setting.filter.prev})()).append((()=>{this.setting.filter.next=bst.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-right").on("click",
a=>{this.setting.filter.offset+=this.setting.filter.limit;this.view.load().then(()=>{}).catch(()=>{})});return this.setting.filter.next})()).append((()=>{this.setting.filter.monitor=bst.create("span").addClass("kb-echo-header-filter-monitor");return this.setting.filter.monitor})()).append(bst.create("div").addClass("kb-echo-header-filter-cases kb-dropdown").append(bst.create("select").assignOption([{code:25,label:"/25 rec"},{code:50,label:"/50 rec"},{code:100,label:"/100 rec"}],"label","code").val(this.setting.filter.limit).on("change",
a=>{this.setting.filter.offset=0;this.setting.filter.limit=parseInt(a.currentTarget.val());this.view.load().then(()=>{}).catch(()=>{})}))),this.setting.injector.add&&b.append(bst.create("button").addClass("kb-icon kb-icon-add").on("click",a=>bst.event.call("bst.create.call",{})))}return b})(bst.create("div").addClass("kb-echo-header-filter"))).append(bst.create("div").addClass("kb-echo-header-space")))).append(((b,a)=>{var c=(f,e)=>{var g=document.createElementNS("http://www.w3.org/2000/svg","svg"),
m=document.createElementNS("http://www.w3.org/2000/svg","path");g.setAttribute("class",f);g.setAttribute("viewBox","0 0 27 27");g.setAttribute("height","27");g.setAttribute("width","27");m.setAttribute("d",e);g.appendChild(m);return g};this.setting.ui.body=bst.create("div").addClass("kb-echo-body-main");this.setting.ui.mask.left=a.clone(!0).addClass("kb-echo-mask-left").append(c("kb-echo-mask-corner kb-echo-mask-corner-top","M27,0H0v27C0,12.088,12.089,0,27,0z")).append(c("kb-echo-mask-corner kb-echo-mask-corner-bottom",
"M27,27H0V0C0,14.912,12.089,27,27,27z"));this.setting.ui.mask.right=a.clone(!0).addClass("kb-echo-mask-right").append(c("kb-echo-mask-corner kb-echo-mask-corner-top","M0,0h27v27C27,12.088,14.911,0,0,0z")).append(c("kb-echo-mask-corner kb-echo-mask-corner-bottom","M27,0v27H0C14.912,27,27,14.911,27,0z"));switch(this.setting.view.type){case "LIST":this.setting.ui.body.addClass("kb-view-container")}return b.append(this.setting.ui.body).append(this.setting.ui.mask.left).append(this.setting.ui.mask.right)})(bst.create("main").addClass("kb-echo-body"),
bst.create("div").addClass("kb-echo-mask").append(bst.create("div").addClass("kb-echo-mask-border"))))));window.on("resize",b=>d())})(()=>{if(this.setting.ui.container.visible())switch((d=>{this.setting.ui.header.action.css({width:d.toString()+"px"});this.setting.ui.header.info.css({width:d.toString()+"px"});this.setting.ui.mask.left.css({left:this.setting.ui.container.scrollLeft.toString()+"px"});this.setting.ui.mask.right.css({left:(d-this.setting.ui.mask.right.innerWidth()+this.setting.ui.container.scrollLeft).toString()+
"px"})})(this.setting.ui.container.innerWidth()),this.setting.view.type){case "CALENDAR":this.setting.ui.body.elm(".kb-calendar")&&this.setting.ui.body.elm(".kb-calendar").elm("thead").css({top:this.setting.ui.header.action.outerHeight().toString()+"px"});break;case "LIST":this.setting.ui.body.elm(".kb-view")&&this.setting.ui.body.elm(".kb-view").elm("thead").css({top:this.setting.ui.header.action.outerHeight().toString()+"px"})}});switch(this.setting.view.type){case "CALENDAR":this.setting.ui.calendar=
new BooooooostCalendar(!0);this.setting.ui.body.append(this.setting.ui.calendar.calendar.addClass("kb-calendar"));break;case "LIST":this.setting.ui.list=bst.view.create(this.setting.ui.body,this.app,this.setting.view.id).elm(".kb-view")}this.view.load().then(()=>{}).catch(()=>{})},load:()=>new Promise((d,b)=>{bst.loadStart();bst.api(bst.api.url("/api/records"),"GET",{app:this.app.id,query:(()=>{var a=[];this.setting.view.filterCond&&a.push("("+this.setting.view.filterCond+")");this.setting.filter.query&&
a.push("("+bst.filter.query.parse.expand(this.app,this.setting.filter.query).map(c=>c.field+" "+c.operator+" "+c.value).join(" and ")+")");switch(this.setting.view.type){case "CALENDAR":a.push((c=>{var f=[],e=(g,m)=>{switch(this.app.fields[this.setting.view.date].type){case "DATE":g="prev"==m?g.calc("-1 day").format("Y-m-d"):g.calc("1 month").format("Y-m-d");break;default:g="prev"==m?g.calc("-1 second").calc(bst.timezoneOffset()+" hour").format("ISO"):g.calc("1 month").calc(bst.timezoneOffset()+" hour").format("ISO")}return g};
f.push(this.setting.view.date+'!=""');f.push(this.setting.view.date+'>"'+e(c,"prev")+'"');f.push(this.setting.view.date+'<"'+e(c,"next")+'"');return"("+f.join(" and ")+")"})(new Date(this.setting.filter.monitor.text()+"-01")))}a=a.join(" and ");this.setting.view.sort&&(a+=" order by "+this.setting.view.sort);return a+=" limit "+this.setting.filter.limit+" offset "+this.setting.filter.offset})()}).then(a=>{switch(this.setting.view.type){case "CALENDAR":bst.event.call("bst.view.load",{container:this.setting.ui.calendar.calendar,
records:a.records,totalCount:Number(a.totalCount)}).then(c=>{if(c.error)bst.loadEnd(),b();else{var f=(e,g)=>{0!=c.records.length?bst.event.call("bst.style.call",{container:this.setting.ui.body,record:c.records[e],pattern:"detail"}).then(m=>{e++;e<c.records.length?f(e,g):g()}).catch(m=>{e++;e<c.records.length?f(e,g):g()}):g()};f(0,()=>{this.setting.ui.calendar.show(new Date(this.setting.filter.monitor.text()+"-01"),null,{create:(e,g,m)=>{e.append((n=>{n.append(bst.create("span").addClass("kb-calendar-cell-guide").css(m).html(g.getDate().toString()));
this.setting.view.title in this.app.fields&&((p,u)=>{p.noLabel=!0;u.each((t,v)=>{(q=>{n.append((r=>{r.append(bst.field.activate(bst.field.create(p).addClass("kb-picker kb-readonly").css({width:"100%"}),q));if(this.setting.injector.edit)r.on("click",w=>bst.event.call("bst.edit.call",{recordId:t.$id.value}));bst.record.set(r,q,t);return r})(bst.create("div").addClass("kb-scope kb-calendar-cell-item")))})({id:this.app.id,fields:(()=>{var q={};q[p.code]=p;return q})()})})})(bst.extend({},this.app.fields[this.setting.view.title]),
c.records.filter(p=>(new Date(p[this.setting.view.date].value)).getDate()==g.getDate()));this.setting.injector.add&&n.append(bst.create("button").addClass("kb-icon kb-icon-add kb-calendar-cell-button").on("click",p=>bst.event.call("bst.create.call",{date:g.format("Y-m-d")})));return n})(bst.create("div").addClass("kb-calendar-cell")))}});bst.loadEnd();this.setting.ui.container.show();bst.event.call("bst.view.load.complete",{container:c.container});d()})}});break;case "LIST":bst.event.call("bst.view.load",
{container:this.setting.ui.list,records:a.records,totalCount:Number(a.totalCount)}).then(c=>{if(c.error)bst.loadEnd(),b();else{var f=()=>{var e=this.setting.filter,g=e.monitor,m=g.html;var n=(e.offset+1).comma()+"&nbsp;-&nbsp;"+(e.offset+c.records.length).comma()+"&nbsp;of&nbsp;"+c.totalCount.comma();m.call(g,n);0<e.offset?e.prev.removeAttr("disabled"):e.prev.attr("disabled","disabled");e.offset+(e.limit==c.records.length?e.limit:c.records.length)<c.totalCount?e.next.removeAttr("disabled"):e.next.attr("disabled",
"disabled");bst.loadEnd();this.setting.ui.container.show();bst.event.call("bst.view.load.complete",{container:c.container});d()};this.setting.ui.list.clearRows();0!=c.totalCount?c.records.each((e,g)=>{(m=>{bst.event.call("bst.style.call",{container:m.elm("[form-id=form_"+this.app.id+"]"),record:e,pattern:"detail"}).then(n=>{bst.record.set(m.elm("[form-id=form_"+this.app.id+"]"),this.app,n.record).then(()=>{g==a.records.length-1&&f()})}).catch(()=>{})})(this.setting.ui.list.addRow())}):f()}})}}).catch(a=>
{bst.alert(bst.error.parse(a));b()})})};this.setting=bst.extend({filter:{app:{id:l,fields:((d,b)=>{var a={};switch(k.view.type){case "CALENDAR":a[k.view.title]=d[k.view.title];break;case "LIST":for(var c in d)if(k.view.fields.includes(c))switch(d[c].type){case "SUBTABLE":var f=void 0,e=b[c];for(f in e.fields)a[f]=e.fields[f];break;default:a[c]=d[c]}}return a})(h.origin,h.tables)},query:"",offset:0,limit:100,monitor:null,prev:null,next:null},ui:{container:null,header:{action:null,info:null},body:null,
mask:{left:null,right:null},calendar:null,list:null}},k);bst.event.on("bst.create.call",d=>{bst.api(bst.api.url("/api/access"),"GET",{}).then(b=>{(a=>{switch(k.view.type){case "CALENDAR":a[k.view.date]={value:d.date}}(c=>{var f=[];f.push("pre="+encodeURIComponent(c));f.push("sender="+encodeURIComponent(window.location.origin));this.controller.injector.contents.elm("iframe").hide().attr("src",this.setting.injector.add+"?"+f.join("&")).off("load").on("load",e=>e.currentTarget.show());this.controller.injector.show()})(btoa((new TextEncoder).encode(JSON.stringify(a)).reduce((c,
f)=>c+String.fromCharCode(f),"")))})(JSON.parse(atob(b.fields)))}).catch(b=>bst.alert(bst.error.parse(b)));return d});bst.event.on("bst.edit.call",d=>{var b=[];b.push("id="+d.recordId);b.push("pattern="+this.setting.injector.pattern);b.push("sender="+encodeURIComponent(window.location.origin));this.controller.injector.contents.elm("iframe").hide().attr("src",this.setting.injector.edit+"?"+b.join("&")).off("load").on("load",a=>a.currentTarget.show());this.controller.injector.show();return d});window.addEventListener("message",
d=>{"https://injector.kintone-booster.com"==event.origin&&"Done"==event.data&&this.view.load().then(()=>{this.controller.injector.hide()}).catch(()=>{})});0!=Object.keys(this.controller.access.app.fields).length?this.controller.access.show(()=>this.view.build()):this.view.build()})}catch(h){bst.alert(bst.error.parse(h))}}};
window.BooooooostEchoAccessController=class extends BooooooostDialog{constructor(l,k){super(999996,!1,!1);this.app={id:"access",fields:(()=>{var h=l.fields.reduce((d,b)=>{var a=k[b];switch(a.type){case "LINK":d[b]={code:b,type:"LINK",label:bst.constants.echo.caption.access.field[bst.operator.language].replace(/\*\*\*/g,a.label),required:!1,noLabel:!1,placeholder:"",protocol:a.protocol};break;case "NUMBER":d[b]={code:b,type:"NUMBER",label:bst.constants.echo.caption.access.field[bst.operator.language].replace(/\*\*\*/g,
a.label),required:!1,noLabel:!1,digit:a.digit};break;default:d[b]={code:b,type:"SINGLE_LINE_TEXT",label:bst.constants.echo.caption.access.field[bst.operator.language].replace(/\*\*\*/g,a.label),required:!1,noLabel:!1,placeholder:"",format:"text"}}return d},{});l.pass&&(h.$pass={code:"$pass",type:"SINGLE_LINE_TEXT",label:bst.constants.echo.caption.access.pass[bst.operator.language],required:!0,noLabel:!1,placeholder:"",format:"password"});return h})()};this.handler=null;this.header.css({paddingLeft:"0.25em",
textAlign:"left"}).html("Access Controller");this.container.css({height:"auto",width:"35em"});this.contents.css({padding:"0"}).append((h=>{for(var d in this.app.fields)h.append(bst.field.activate(bst.field.create(this.app.fields[d]).css({width:"100%"}),this.app));h.elms("input,select,textarea").each((b,a)=>b.initialize());return h})(bst.create("div").addClass("kb-scope").attr("form-id","form_"+this.app.id)));window.on("resize",h=>{this.contents.css({height:"auto"}).css({height:this.container.innerHeight().toString()+
"px"})})}get(){return new Promise((l,k)=>{var h=bst.record.get(this.contents,this.app);h.error?l(h):bst.confirm(bst.constants.common.message.confirm.submit[bst.operator.language],()=>{bst.api(bst.api.url("/api/access"),"POST",(d=>{var b={};"$pass"in d&&(b.$pass=d.$pass.value,delete d.$pass);b.fields=(a=>{for(var c in a)a[c].type=this.app.fields[c].type;return a})(d);return b})(h.record)).then(d=>{"ok"!=d.result&&(h.error=!0);l(h)}).catch(d=>{bst.alert(bst.error.parse(d));l({error:!0})})})})}set(){return new Promise((l,
k)=>{bst.api(bst.api.url("/api/access"),"GET",{}).then(h=>{bst.record.set(this.contents,this.app,(d=>{"$pass"in this.app.fields&&(d.$pass={value:""});return d})(JSON.parse(atob(h.fields))));l(!1)}).catch(h=>{bst.alert(bst.error.parse(h));l(!0)})})}show(l){this.handler&&(this.ok.off("click",this.handler),this.cancel.off("click"));this.handler=k=>{this.get().then(h=>{h.error||(l(),this.hide())})};this.ok.attr("tabstop","tabstop").on("click",this.handler);this.cancel.on("click",k=>this.hide());this.set().then(k=>
{k||(this.contents.css({height:"auto"}).css({height:this.container.innerHeight().toString()+"px"}),super.show(),this.contents.elm("input,select,textarea").focus())})}};window.bst.echo||(window.bst.echo=new BooooooostEcho);
bst.constants=bst.extend({echo:{caption:{access:{field:{en:"Please enter ***.",ja:"***\u3092\u5165\u529b\u3057\u3066\u4e0b\u3055\u3044\u3002",zh:"\u8bf7\u8f93\u5165 ***\u3002","zh-TW":"\u8acb\u8f38\u5165 ***\u3002"},pass:{en:"Please enter your password.",ja:"\u30d1\u30b9\u30ef\u30fc\u30c9\u3092\u5165\u529b\u3057\u3066\u4e0b\u3055\u3044\u3002",zh:"\u8bf7\u8f93\u5165\u60a8\u7684\u5bc6\u7801\u3002","zh-TW":"\u8acb\u8f38\u5165\u60a8\u7684\u5bc6\u78bc\u3002"}}},description:{},message:{confirm:{},invalid:{}}}},
bst.constants);window.kb.echo||(window.kb.echo=window.bst.echo);
