/*
* FileName "plugin.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';kb.event.on("kb.style.call",f=>new Promise((p,z)=>{if(f.container.attr("form-id")!="form_access"&&kb.plugin.style.length!=0){var d={},y=(l,g,h)=>new Promise((w,x)=>{var q={},t=(k,m)=>{(n=>{var c=kb.filter.scan(d.app,g,n.condition.value);c?kb.filter.auth(n.user.value,n.organization.value,n.group.value).then(r=>{r&&(n.color.value.map(b=>b.value).each((b,u)=>{b.field.value in d.fieldInfos.parallelize&&(a=>{a.tableCode?a.tableCode in c&&c[a.tableCode].value.each((e,v)=>{a.code in e.value&&
(e.value[a.code].backcolor=b.backcolor.value,e.value[a.code].forecolor=b.forecolor.value)}):a.code in c&&(c[a.code].backcolor=b.backcolor.value,c[a.code].forecolor=b.forecolor.value)})(d.fieldInfos.parallelize[b.field.value])}),n.editable.value.map(b=>b.value).each((b,u)=>{b.field.value in d.fieldInfos.parallelize&&(a=>{d.fieldInfos.disables.includes(a.code)||(a.tableCode?a.tableCode in c&&(c[a.tableCode].value.each((e,v)=>{a.code in e.value&&(e.value[a.code].disabled=b.state.value=="disable")}),
q[a.code]=g[a.tableCode].value.map(e=>e.value[a.code].disabled?"disabled":"")):a.code in c&&(c[a.code].disabled=b.state.value=="disable",q[a.code]=g[a.code].disabled?"disabled":""))})(d.fieldInfos.parallelize[b.field.value])}),n.display.value.map(b=>b.value).each((b,u)=>{b.field.value in d.fieldInfos.groups?d.fieldInfos.groups[b.field.value].fields.map(a=>a.code).each((a,e)=>{a in d.fieldInfos.parallelize&&a in c&&(c[a].hidden=b.state.value=="hide")}):b.field.value in d.fieldInfos.tables?b.field.value in
c&&(c[b.field.value].hidden=b.state.value=="hide"):(a=>{a.tableCode?a.tableCode in c&&c[a.tableCode].value.each((e,v)=>{a.code in e.value&&(e.value[a.code].hidden=b.state.value=="hide")}):a.code in c&&(c[a.code].hidden=b.state.value=="hide")})(d.fieldInfos.parallelize[b.field.value])}));k++;k<l.length?t(k,m):m()}).catch(r=>{kb.alert(kb.error.parse(r));x()}):(k++,k<l.length?t(k,m):m())})(l[k])};t(0,()=>{h.latest?h.latest.style||(h.latest.style="{}"):h.latest={style:"{}"};var k=JSON.stringify(q),m=
k!="{}"?h.latest.style!=k:!1;m&&(h.latest.style=k);w({performed:m})})});kb.field.load(kb.echo.app.id).then(l=>{d.app={id:kb.echo.app.id,fields:l.origin};d.fieldInfos=l;try{(g=>{g.length!=0?y(g,f.record,f.container).then(h=>{f.performed=h.performed;p(f)}).catch(()=>p(f)):p(f)})(kb.plugin.style.reduce((g,h)=>{h.page.value.includes(f.pattern)&&g.push(h);return g},[]))}catch(g){kb.alert(kb.error.parse(g)),p(f)}}).catch(l=>p(f))}else p(f)}));